# Generated by Django 5.2.10 on 2026-05-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0048_force_rls_on_all_enabled_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, db_index=True, help_text='Tenant schema (django-tenants) for fan-out workers.', max_length=63)),
                ('label', models.CharField(blank=True, help_text="Human-readable label for the operator (e.g. 'Sept 2026 cutover').", max_length=200)),
                ('intake_method', models.CharField(choices=[('file_upload', 'Direct file upload'), ('archive', 'Compressed archive (zip / tar / gz / 7z)'), ('url', 'Remote URL / signed link'), ('sftp', 'SFTP path'), ('s3', 'S3 prefix'), ('sql_dump', 'SQL dump file'), ('database', 'Live database connection'), ('oauth_folder', 'Google Drive / OneDrive / Dropbox folder (OAuth)'), ('email', 'Email with attachments'), ('api_pull', 'Vendor API accelerator (Phase U9)')], db_index=True, default='file_upload', max_length=32)),
                ('intake_source_uri', models.TextField(blank=True, help_text='Where it came from (path / URL / OAuth handle / API endpoint).')),
                ('source_hint', models.CharField(blank=True, help_text="Optional operator hint (e.g. 'PowerSchool export'). The classifier still runs; this is a tie-breaker, not a hard decision.", max_length=200)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Stable across re-runs of the same bundle; replays produce zero duplicates.', max_length=128, unique=True)),
                ('sla_tier', models.CharField(choices=[('small', 'Small school (≤ 1k students, ≤ 1h)'), ('mid', 'Mid school (1k–10k students, ≤ 4h)'), ('large', 'Large district (10k–50k students, ≤ 12h)'), ('state', 'Multi-district / state (concierge required)')], db_index=True, default='small', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending intake'), ('INGESTING', 'Ingesting artifacts'), ('PROFILED', 'Artifacts profiled'), ('CLASSIFIED', 'Source + domains classified'), ('MAPPED', 'Fields mapped to canonical ontology'), ('READY', 'Ready to apply'), ('APPLYING', 'Applying to tenant'), ('APPLIED', 'Applied; reconciliation pending'), ('RECONCILED', 'Reconciliation closed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted by operator')], db_index=True, default='PENDING', max_length=20)),
                ('size_summary', models.JSONField(blank=True, default=dict, help_text='Bundle-wide totals: artifact_count, total_bytes, total_rows.')),
                ('discovery_summary', models.JSONField(blank=True, default=dict, help_text='Phase U3 output: ranked source candidates + per-artifact domain guesses.')),
                ('mapping_summary', models.JSONField(blank=True, default=dict, help_text='Phase U4 output: per-artifact column → canonical field mappings + confidences.')),
                ('reconciliation_summary', models.JSONField(blank=True, default=dict, help_text='Phase U8 output: per-domain parity counts, sampling, scorecards.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, help_text='Target tenant. Null for pre-tenant bundles staged during signup.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_bundles', to='schools.school')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_bundles_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration bundle',
                'verbose_name_plural': 'Migration bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_within_bundle', models.TextField(help_text='Path of this artifact relative to bundle root (preserves subfolder shape).')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('detected_format', models.CharField(choices=[('csv', 'CSV'), ('tsv', 'TSV'), ('xlsx', 'XLSX'), ('xls', 'XLS (legacy)'), ('json', 'JSON'), ('jsonl', 'JSON Lines'), ('xml', 'XML'), ('sql', 'SQL dump'), ('sqlite', 'SQLite database'), ('parquet', 'Parquet'), ('pdf', 'PDF (OCR — Phase U7)'), ('image', 'Image (OCR — Phase U7)'), ('archive', 'Archive (zip / tar / gz / 7z) — expanded'), ('unknown', 'Unknown / extension-only')], db_index=True, default='unknown', max_length=16)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('encoding', models.CharField(blank=True, help_text='Detected text encoding (utf-8, cp1252, etc.); blank for binary.', max_length=32)),
                ('row_count', models.BigIntegerField(blank=True, help_text='For tabular formats only; null for archives / binaries / pre-profile.', null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('locale_hints', models.JSONField(blank=True, default=dict, help_text='Date format, decimal separator, name order, etc. (Phase U2 fills this).')),
                ('profile', models.JSONField(blank=True, default=dict, help_text='Full artifact profile (Phase U2): per-column types, samples, PII flags.')),
                ('inferred_source', models.CharField(blank=True, db_index=True, help_text="Top source-system guess from Phase U3 classifier (e.g. 'powerschool', 'unknown_custom').", max_length=64)),
                ('inferred_domain', models.JSONField(blank=True, default=list, help_text="Phase U3 ranked domain candidates: [{'domain': 'students', 'confidence': 0.93}, ...].")),
                ('quarantined', models.BooleanField(db_index=True, default=False)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_archive', models.ForeignKey(blank=True, help_text='Set when this artifact was unpacked from a parent archive.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='migration_cloud.migrationartifact')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='migration_cloud.migrationbundle')),
            ],
            options={
                'verbose_name': 'Migration artifact',
                'verbose_name_plural': 'Migration artifacts',
                'ordering': ['bundle_id', 'path_within_bundle'],
            },
        ),
        migrations.AddIndex(
            model_name='migrationbundle',
            index=models.Index(fields=['school', '-created_at'], name='migration_c_school__8d2fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationbundle',
            index=models.Index(fields=['status', '-created_at'], name='migration_c_status_6e3c32_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationbundle',
            index=models.Index(fields=['intake_method', '-created_at'], name='migration_c_intake__f3c742_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationartifact',
            index=models.Index(fields=['bundle', 'detected_format'], name='migration_c_bundle__ebf6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationartifact',
            index=models.Index(fields=['sha256'], name='migration_c_sha256_59b0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationartifact',
            index=models.Index(fields=['quarantined', 'bundle'], name='migration_c_quarant_c0f7fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='migrationartifact',
            constraint=models.UniqueConstraint(fields=('bundle', 'sha256', 'path_within_bundle'), name='uniq_artifact_per_bundle_path'),
        ),
    ]
