# Generated by Django 5.2.10 on 2026-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationbundle',
            name='intake_method',
            field=models.CharField(choices=[('file_upload', 'Direct file upload'), ('archive', 'Compressed archive (zip / tar / gz / 7z)'), ('url', 'Remote URL / signed link'), ('sftp', 'SFTP path'), ('s3', 'S3 prefix'), ('sql_dump', 'SQL dump file'), ('database', 'Live database connection'), ('oauth_folder', 'Google Drive / OneDrive / Dropbox folder (OAuth)'), ('email', 'Email with attachments'), ('api_pull', 'Vendor API accelerator (Phase U9)'), ('pdf', 'PDF transcript stack (text + OCR fallback)'), ('access_db', 'Microsoft Access database (.mdb / .accdb)')], db_index=True, default='file_upload', max_length=32),
        ),
    ]
