# Generated by Django 5.2.10 on 2026-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0003_tier1_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='migrationasset',
            new_name='migration_c_bundle__99d7cf_idx',
            old_name='mc_asset_bundle_status_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationasset',
            new_name='migration_c_entity__7b8243_idx',
            old_name='mc_asset_entity_lid_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationasset',
            new_name='migration_c_sha256_4f40be_idx',
            old_name='mc_asset_sha256_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationconflict',
            new_name='migration_c_bundle__0bcc6c_idx',
            old_name='mc_conf_bundle_res_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationconflict',
            new_name='migration_c_canonic_743247_idx',
            old_name='mc_conf_model_pk_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationidmapping',
            new_name='migration_c_legacy__49ea0b_idx',
            old_name='mc_idmap_ns_lid_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationidmapping',
            new_name='migration_c_canonic_f4d3c1_idx',
            old_name='mc_idmap_model_pk_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationidmapping',
            new_name='migration_c_bundle__975b5a_idx',
            old_name='mc_idmap_bundle_dom_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationprogressevent',
            new_name='migration_c_bundle__a00a43_idx',
            old_name='mc_evt_bundle_at_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationprogressevent',
            new_name='migration_c_bundle__b3f66f_idx',
            old_name='mc_evt_bundle_stage_idx',
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='asset_kind',
            field=models.CharField(db_index=True, help_text="Discriminator (e.g. 'photo', 'immunization', 'report_card', 'transcript').", max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='entity_kind',
            field=models.CharField(db_index=True, help_text="Canonical entity the asset belongs to (e.g. 'student', 'guardian', 'invoice').", max_length=64),
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='legacy_id',
            field=models.CharField(db_index=True, help_text='external_id of the row this asset belongs to.', max_length=128),
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='source_uri',
            field=models.TextField(blank=True, help_text='Where the asset was fetched from (http(s):// / s3:// / file:// / data:base64).'),
        ),
        migrations.AlterField(
            model_name='migrationasset',
            name='stored_path',
            field=models.TextField(blank=True, help_text='MEDIA_ROOT-relative path of the stored asset.'),
        ),
        migrations.AlterField(
            model_name='migrationconflict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationidmapping',
            name='canonical_model',
            field=models.CharField(db_index=True, help_text="Dotted path of the canonical model the row landed in (e.g. 'apps.people.StudentProfile').", max_length=128),
        ),
        migrations.AlterField(
            model_name='migrationidmapping',
            name='canonical_pk',
            field=models.CharField(db_index=True, help_text='Primary key of the canonical row (stringified for cross-type tolerance).', max_length=64),
        ),
        migrations.AlterField(
            model_name='migrationidmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationidmapping',
            name='legacy_id',
            field=models.CharField(db_index=True, help_text='The original external_id / source-system row identifier.', max_length=128),
        ),
        migrations.AlterField(
            model_name='migrationidmapping',
            name='legacy_namespace',
            field=models.CharField(db_index=True, help_text="Source-system namespace (e.g. 'powerschool', 'blackbaud', 'unknown_custom').", max_length=64),
        ),
        migrations.AlterField(
            model_name='migrationprogressevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
