# Generated by Django 5.2.10 on 2026-05-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0005_api_tokens_and_webhooks'),
        ('schools', '0051_add_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text="List of scope strings, e.g. ['bundles:read', 'bundles:write']."),
        ),
        migrations.AlterField(
            model_name='migrationcloudapitoken',
            name='token_hash',
            field=models.CharField(db_index=True, help_text='sha256 hex digest of the opaque token; plaintext returned ONCE at mint.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='migrationcloudwebhookdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationcloudwebhooksubscription',
            name='event_types',
            field=models.JSONField(blank=True, default=list, help_text="List of event-type strings, e.g. ['bundle.advanced']."),
        ),
        migrations.AlterField(
            model_name='migrationcloudwebhooksubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationcloudwebhooksubscription',
            name='secret_ciphertext',
            field=models.BinaryField(blank=True, help_text="Raw HMAC secret material used to sign outbound deliveries. TODO: wrap with django-cryptography encrypt() once Agent 5's auth/crypto layer merges.", null=True),
        ),
        migrations.AlterField(
            model_name='migrationcloudwebhooksubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_cloud_webhook_subscriptions', to='schools.school'),
        ),
        migrations.CreateModel(
            name='CompanionCiphertextBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_file', models.FileField(help_text='Encrypted bundle bytes; layout: companion_uploads/<tenant_id>/<uuid>.bin', upload_to='companion_uploads/')),
                ('ciphertext_sha256', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decrypted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_ciphertext_blobs', to='schools.school')),
            ],
            options={
                'verbose_name': 'Companion ciphertext blob',
                'verbose_name_plural': 'Companion ciphertext blobs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationAuthorizationAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_role', models.CharField(help_text="Operator-supplied role (e.g. 'Head of School', 'IT Director').", max_length=128)),
                ('vendor_source', models.CharField(db_index=True, help_text="Source-vendor id (matches Companion canonical-bundle 'source' field).", max_length=64)),
                ('vendor_account_holder_name', models.CharField(help_text='Human with legal authority over the source data at the vendor.', max_length=256)),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_version', models.CharField(default='v1.0', max_length=32)),
                ('signature_text', models.TextField(help_text='Verbatim text the operator agreed to; rendered at sign time.')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('signed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migration_authorization_agreements_signed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant the agreement covers. Matches CompanionUploadReceipt.tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='migration_authorization_agreements', to='schools.school')),
            ],
            options={
                'verbose_name': 'Migration authorization agreement',
                'verbose_name_plural': 'Migration authorization agreements',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionUploadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_idempotency_key', models.CharField(max_length=128, unique=True)),
                ('ciphertext_sha256', models.CharField(db_index=True, max_length=64)),
                ('plaintext_byte_size', models.PositiveIntegerField(default=0, help_text='Client-reported plaintext size (post-decrypt, pre-compression).')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encryption_scheme', models.CharField(default='libsodium-secretbox-x25519-sealed', help_text='Encryption scheme tag; matches companion-extension/src/lib/crypto.ts.', max_length=32)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_receipts', to='migration_cloud.migrationbundle')),
                ('ciphertext_blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='migration_cloud.companionciphertextblob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_upload_receipts', to='schools.school')),
                ('maa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companion_receipts', to='migration_cloud.migrationauthorizationagreement')),
            ],
            options={
                'verbose_name': 'Companion upload receipt',
                'verbose_name_plural': 'Companion upload receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companionciphertextblob',
            index=models.Index(fields=['tenant', '-received_at'], name='migration_c_tenant__5a5e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='companionciphertextblob',
            index=models.Index(fields=['ciphertext_sha256'], name='migration_c_ciphert_4659e4_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationauthorizationagreement',
            index=models.Index(fields=['tenant', '-signed_at'], name='migration_c_tenant__5b294f_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationauthorizationagreement',
            index=models.Index(fields=['tenant', 'vendor_source'], name='migration_c_tenant__318809_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationauthorizationagreement',
            index=models.Index(fields=['vendor_source', '-signed_at'], name='migration_c_vendor__1d87ef_idx'),
        ),
        migrations.AddIndex(
            model_name='companionuploadreceipt',
            index=models.Index(fields=['tenant', '-received_at'], name='migration_c_tenant__a67902_idx'),
        ),
        migrations.AddIndex(
            model_name='companionuploadreceipt',
            index=models.Index(fields=['bundle'], name='migration_c_bundle__5e1f26_idx'),
        ),
        migrations.AddIndex(
            model_name='companionuploadreceipt',
            index=models.Index(fields=['received_at'], name='migration_c_receive_2592ff_idx'),
        ),
    ]
