# Generated by Django 5.2.10 on 2026-05-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0009_merge_v3_32_parallel_branches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='migrationcloudcompanionkeypair',
            new_name='migration_c_is_acti_c68d15_idx',
            old_name='migration_c_is_acti_a8f3b1_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationcloudcompanionkeypair',
            new_name='migration_c_key_ver_fd08d1_idx',
            old_name='migration_c_key_ver_2c9b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationcloudcompanionkeypair',
            new_name='migration_c_created_97d2b5_idx',
            old_name='migration_c_created_5e1f72_idx',
        ),
    ]
