# Generated by Django 5.2.10 on 2026-05-19 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0018_merge_0016_0017'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='migrationcloudcounselattestation',
            new_name='migration_c_attesta_90ef4b_idx',
            old_name='migration_c_attesta_3c0a44_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationcloudmaacampaignnotification',
            new_name='migration_c_campaig_ca2248_idx',
            old_name='migration_c_campaig_8d5b22_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationcloudmaacampaignnotification',
            new_name='migration_c_dispatc_f764c9_idx',
            old_name='migration_c_dispatc_e7f199_idx',
        ),
        migrations.AlterField(
            model_name='migrationcloudcounselattestation',
            name='attestation_text',
            field=models.TextField(help_text="Operator-supplied narrative describing the attestation (e.g. 'Received signed PDF from counsel Jane Q. Doe, Esq. on 2026-06-01; filed at docs/legal/maa_v2_signoff.pdf')."),
        ),
        migrations.AlterField(
            model_name='migrationcloudcounselattestation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationcloudcounselattestation',
            name='related_artifact_path',
            field=models.CharField(blank=True, default='', help_text="Optional repo-relative path of the supporting artifact (e.g. 'docs/legal/maa_v2_signoff.pdf'). Free-text; the audit row is the SOT, not the file.", max_length=512),
        ),
        migrations.AlterField(
            model_name='migrationcloudmaacampaignnotification',
            name='agreement',
            field=models.ForeignKey(help_text='The v1.0-era MAA row that triggered the notification. On agreement deletion the notification rows cascade out (they are derived audit; the SOT is the agreement).', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='migration_cloud.migrationauthorizationagreement'),
        ),
        migrations.AlterField(
            model_name='migrationcloudmaacampaignnotification',
            name='campaign_version',
            field=models.CharField(db_index=True, help_text="Campaign identifier, e.g. 'maa_v2_resign_2026Q3'. Allows future v3.x re-sign campaigns to coexist (each campaign is independently idempotent).", max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationcloudmaacampaignnotification',
            name='dispatch_mode',
            field=models.CharField(db_index=True, default='dry_run', help_text="Either 'dry_run' (recorded but not enqueued) or 'queued' (enqueued via send_mail and recorded). 'queued' rows are the only ones operators expect a real email send for.", max_length=16),
        ),
        migrations.AlterField(
            model_name='migrationcloudmaacampaignnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationcloudmaacampaignnotification',
            name='recipient_email',
            field=models.EmailField(help_text="Email address that received (or was queued to receive) the campaign email. Operator-attached not at scrape time but resolved from the signing operator's User row.", max_length=254),
        ),
    ]
