# Generated by Django 5.2.10 on 2026-05-19 08:04

import apps.platform_runtime.append_only
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0019_rename_counsel_maa_indexes_and_field_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCloudAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUIDv4 primary key. Random so event IDs don't leak ordering or per-tenant volume.", primary_key=True, serialize=False)),
                ('tenant_id_hash', models.CharField(db_index=True, help_text='First 12 hex chars of sha256(tenant_slug). Auditors export by this prefix; operators correlate to the tenant via a separately-maintained map (see docs/MIGRATION_CLOUD_AUDIT_LOG.md).', max_length=12)),
                ('event_type', models.CharField(choices=[('companion.upload', 'Companion upload accepted'), ('maa.sign', 'MAA signed'), ('maa.sign_attempt_draft', 'Attempt to sign a DRAFT MAA refused'), ('key.rotate', 'Companion server-keypair rotated'), ('webhook.subscription.created', 'Webhook subscription created'), ('webhook.subscription.deleted', 'Webhook subscription deleted (deactivated)'), ('webhook.delivery.replay', 'Webhook delivery manually replayed'), ('token.mint', 'Scoped API token minted'), ('token.revoke', 'Scoped API token revoked'), ('legacy_hash.decrypt', 'Legacy SIS-hash field decrypted'), ('audit.retention_purge_applied', 'Audit retention purge applied (counsel-approved)')], db_index=True, help_text='One of the registered audit event types.', max_length=64)),
                ('actor_id', models.CharField(blank=True, help_text='sha256(user.email)[:64] when authenticated. NULL for system events (Celery beat). NEVER the raw email.', max_length=64, null=True)),
                ('event_subject_hash', models.CharField(blank=True, help_text='sha256(subject_id_or_slug)[:64] of the entity the event acts on (webhook sub UUID, token id, MAA id, ...). NULL when no concrete subject.', max_length=64, null=True)),
                ('payload_summary', models.JSONField(default=dict, help_text='Small structured summary (counts, booleans, hex prefixes). NEVER PII; NEVER signature/key/password material — enforced by _sanitize_payload at write time.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at_iso', models.CharField(blank=True, default='', help_text='ISO-8601 UTC representation of created_at, populated in save() so the value is present even on raw-SQL exports.', max_length=32)),
                ('integrity_hash', models.CharField(editable=False, help_text='SHA-256 of canonical_json({id, tenant_id_hash, event_type, actor_id, event_subject_hash, payload_summary, created_at_iso, prev_event_hash}). Chains per-tenant.', max_length=64)),
                ('prev_event_hash', models.CharField(editable=False, help_text="Previous event's integrity_hash for the same tenant_id_hash, or 'genesis' for the first event per tenant.", max_length=64)),
            ],
            options={
                'verbose_name': 'Migration Cloud audit event',
                'verbose_name_plural': 'Migration Cloud audit events',
                'indexes': [models.Index(fields=['tenant_id_hash', 'created_at'], name='migration_c_tenant__8a5038_idx'), models.Index(fields=['event_type', 'created_at'], name='migration_c_event_t_71d1d9_idx')],
            },
            bases=(apps.platform_runtime.append_only.AppendOnlyModelMixin, models.Model),
        ),
    ]
