# Generated by Django 5.2.10 on 2026-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0023_guardian_consent_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guardianconsenttoken',
            new_name='migration_c_intake__02f9fe_idx',
            old_name='migration_c_intake__a01b23_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianconsenttoken',
            new_name='migration_c_token_s_78b7d9_idx',
            old_name='migration_c_token_s_b12c34_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianconsenttoken',
            new_name='migration_c_tenant__a2576c_idx',
            old_name='migration_c_tenant__c23d45_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianconsenttoken',
            new_name='migration_c_expires_00a5ee_idx',
            old_name='migration_c_expires_d34e56_idx',
        ),
        migrations.AlterField(
            model_name='migrationcloudauditevent',
            name='event_type',
            field=models.CharField(choices=[('companion.upload', 'Companion upload accepted'), ('maa.sign', 'MAA signed'), ('maa.sign_attempt_draft', 'Attempt to sign a DRAFT MAA refused'), ('key.rotate', 'Companion server-keypair rotated'), ('webhook.subscription.created', 'Webhook subscription created'), ('webhook.subscription.deleted', 'Webhook subscription deleted (deactivated)'), ('webhook.delivery.replay', 'Webhook delivery manually replayed'), ('token.mint', 'Scoped API token minted'), ('token.revoke', 'Scoped API token revoked'), ('legacy_hash.decrypt', 'Legacy SIS-hash field decrypted'), ('audit.retention_purge_applied', 'Audit retention purge applied (counsel-approved)'), ('migration.intake.state_advanced', 'Migration intake state advanced'), ('migration.guardian_consent.campaign_started', 'Guardian consent campaign started'), ('migration.guardian_consent.minted', 'Guardian consent token minted'), ('migration.guardian_consent.first_seen', 'Guardian opened the consent page for the first time'), ('migration.guardian_consent.consented', 'Guardian consented to migration'), ('migration.guardian_consent.declined', 'Guardian declined consent'), ('migration.guardian_consent.revoked', 'Guardian revoked previously-granted consent'), ('migration.guardian_consent.expired', 'Guardian consent token expired before decision'), ('migration.guardian_consent.resent', 'Guardian consent email resent'), ('audit.rate_limit_triggered', 'Audit event volume rate-limit triggered for a tenant')], db_index=True, help_text='One of the registered audit event types.', max_length=64),
        ),
    ]
