# Generated by Django 5.2.10 on 2026-05-19 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0024_rename_migration_c_intake__a01b23_idx_migration_c_intake__02f9fe_idx_and_more'),
        ('schools', '0051_add_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationConnectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('supported_methods', models.JSONField(blank=True, default=list)),
                ('supports_api', models.BooleanField(default=False)),
                ('supports_export', models.BooleanField(default=True)),
                ('supports_browser_export', models.BooleanField(default=False)),
                ('certification_status', models.CharField(choices=[('planned', 'Planned'), ('experimental', 'Experimental'), ('verified_test', 'Verified in test'), ('pilot_ready', 'Pilot ready'), ('production_ready', 'Production ready')], db_index=True, default='planned', max_length=32)),
                ('supported_entities', models.JSONField(blank=True, default=list)),
                ('known_limitations', models.TextField(blank=True)),
                ('rate_limit_notes', models.TextField(blank=True)),
                ('auth_notes', models.TextField(blank=True)),
                ('mapping_template', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Migration connector profile',
                'verbose_name_plural': 'Migration connector profiles',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='MigrationSourceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_platform_type', models.CharField(db_index=True, max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('connection_method', models.CharField(choices=[('api_token', 'API token'), ('oauth', 'OAuth'), ('username_password', 'Username and password'), ('file_export', 'Uploaded export file'), ('manual_template', 'Manual template')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=16)),
                ('credential_reference', models.CharField(blank=True, help_text='Opaque handle — never the secret itself.', max_length=128)),
                ('credential_storage_mode', models.CharField(choices=[('memory_only', 'In-memory only (one-time)'), ('encrypted_vault', 'Encrypted at rest'), ('external_secret_manager', 'External secret manager')], default='memory_only', max_length=32)),
                ('credential_ciphertext', models.BinaryField(blank=True, help_text='Fernet-wrapped credential blob when storage_mode=encrypted_vault.', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_confirmed', models.BooleanField(default=False)),
                ('authorization_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('terms_acknowledged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_source_authorizations', to=settings.AUTH_USER_MODEL)),
                ('connector_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_connections', to='migration_cloud.migrationconnectorprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_source_connections_created', to=settings.AUTH_USER_MODEL)),
                ('linked_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_connections', to='migration_cloud.migrationbundle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_source_connections', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MigrationFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_entity', models.CharField(db_index=True, max_length=64)),
                ('source_field', models.CharField(max_length=128)),
                ('destination_model', models.CharField(blank=True, max_length=128)),
                ('destination_field', models.CharField(blank=True, max_length=128)),
                ('transform_rule', models.CharField(blank=True, max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('needs_review', 'Needs review')], db_index=True, default='suggested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_field_mappings', to='schools.school')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='migration_cloud.migrationsourceconnection')),
            ],
            options={
                'ordering': ('source_entity', 'source_field'),
            },
        ),
        migrations.CreateModel(
            name='MigrationDiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_entities', models.JSONField(blank=True, default=list)),
                ('counts_by_entity', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('external_blockers', models.JSONField(blank=True, default=list)),
                ('audit_summary', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_discovery_runs', to='schools.school')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_discovery_runs_started', to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='migration_cloud.migrationsourceconnection')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='MigrationStagingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('staged', 'Staged'), ('validated', 'Validated'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('staged_payload_reference', models.CharField(blank=True, max_length=256)),
                ('mapping_version', models.CharField(blank=True, default='v1', max_length=32)),
                ('data_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_batches', to='migration_cloud.migrationdiscoveryrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_staging_batches', to='schools.school')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_batches', to='migration_cloud.migrationsourceconnection')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MigrationQuarantineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('source_identifier', models.CharField(blank=True, max_length=256)),
                ('issue_code', models.CharField(db_index=True, max_length=64)),
                ('issue_message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('suggested_fix', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored'), ('blocked', 'Blocked')], db_index=True, default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_quarantine_resolutions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_quarantine_items', to='schools.school')),
                ('staging_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_items', to='migration_cloud.migrationstagingbatch')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MigrationImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back'), ('partial', 'Partial')], db_index=True, default='preview', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_counts', models.JSONField(blank=True, default=dict)),
                ('updated_counts', models.JSONField(blank=True, default=dict)),
                ('skipped_counts', models.JSONField(blank=True, default=dict)),
                ('error_counts', models.JSONField(blank=True, default=dict)),
                ('rollback_snapshot_reference', models.CharField(blank=True, max_length=256)),
                ('audit_summary', models.JSONField(blank=True, default=dict)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_import_runs', to='migration_cloud.migrationbundle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_import_runs', to='schools.school')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_import_runs_started', to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='migration_cloud.migrationsourceconnection')),
                ('staging_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='migration_cloud.migrationstagingbatch')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='MigrationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_audit_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_audit_events', to='schools.school')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='migration_cloud.migrationdiscoveryrun')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='migration_cloud.migrationimportrun')),
                ('source_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='migration_cloud.migrationsourceconnection')),
                ('staging_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='migration_cloud.migrationstagingbatch')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='migrationsourceconnection',
            index=models.Index(fields=['school', 'status'], name='migration_c_school__2f3d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationsourceconnection',
            index=models.Index(fields=['school', 'source_platform_type'], name='migration_c_school__360b41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='migrationfieldmapping',
            unique_together={('source_connection', 'source_entity', 'source_field')},
        ),
        migrations.AddIndex(
            model_name='migrationdiscoveryrun',
            index=models.Index(fields=['school', 'status'], name='migration_c_school__89bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationstagingbatch',
            index=models.Index(fields=['school', 'entity_type', 'status'], name='migration_c_school__5acded_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationquarantineitem',
            index=models.Index(fields=['school', 'status', 'issue_code'], name='migration_c_school__1723fb_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationimportrun',
            index=models.Index(fields=['school', 'status'], name='migration_c_school__b07583_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationauditevent',
            index=models.Index(fields=['school', 'event_type', 'created_at'], name='migration_c_school__b4b612_idx'),
        ),
    ]
