# Generated by Django 5.2.10 on 2026-05-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0025_migration_cloud_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationstagingbatch',
            name='staged_rows',
            field=models.JSONField(blank=True, default=list, help_text='Normalized row dicts staged for bundle ingest (never credentials).'),
        ),
    ]
