# Generated by Django 5.2.10 on 2026-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0033_migration_artifact_blob'),
        ('schools', '0077_schoolmembership_suspended_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='migrationidmapping',
            name='uniq_id_mapping_per_school_namespace',
        ),
        migrations.AddConstraint(
            model_name='migrationidmapping',
            constraint=models.UniqueConstraint(fields=('legacy_namespace', 'legacy_id', 'canonical_model', 'school', 'domain'), name='uniq_id_mapping_per_school_namespace'),
        ),
    ]
