# Generated by Django 5.2.10 on 2026-07-24 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_cloud', '0041_cutover_runbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationintakerequest',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='The MigrationBundle this intake drives (self-serve apply). Null until the school uploads data; the bundle owns the real data lifecycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='migration_cloud.migrationbundle'),
        ),
    ]
