# Generated by Django 5.2.10 on 2026-07-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRegionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_key', models.CharField(max_length=32)),
                ('draft_fingerprint', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_region_approvals', to='schools.school')),
            ],
            options={
                'verbose_name': 'Experience region approval',
                'verbose_name_plural': 'Experience region approvals',
                'indexes': [models.Index(fields=['school', 'region_key'], name='idx_exp_region_appr_school_key')],
                'constraints': [models.UniqueConstraint(fields=('school', 'region_key'), name='uniq_experience_region_approval_per_school_region')],
            },
        ),
    ]
