# Generated by Django 5.2.10 on 2026-03-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_webhook_subscription_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Next time this delivery is eligible for processing.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "scheduled_for"], name="events_wh_status_sched"
            ),
        ),
    ]
