# Generated by Django 5.2.10 on 2026-05-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_webhook_delivery_remediation_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventsystemremediationaudit',
            new_name='events_even_school__fae22a_idx',
            old_name='events_remed_school_created_idx',
        ),
        migrations.RenameIndex(
            model_name='eventsystemremediationaudit',
            new_name='events_even_deliver_dfc557_idx',
            old_name='events_remed_src_pk_idx',
        ),
    ]
