# Generated by Django; seed pipeline stages in RunPython

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_stages(apps, schema_editor):
    PipelineStage = apps.get_model("sales", "PipelineStage")
    for key, label, so in [
        ("lead", "Lead", 1),
        ("contacted", "Contacted", 2),
        ("demo", "Demo", 3),
        ("pilot", "Pilot", 4),
        ("onboarded", "Onboarded", 5),
    ]:
        PipelineStage.objects.get_or_create(
            key=key, defaults={"label": label, "sort_order": so}
        )


def unseed(apps, schema_editor):
    PipelineStage = apps.get_model("sales", "PipelineStage")
    PipelineStage.objects.filter(
        key__in=("lead", "contacted", "demo", "pilot", "onboarded")
    ).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=64)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional one-line summary; use Activity for dated entries.",
                    ),
                ),
                ("next_follow_up", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="sales.pipelinestage",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sales.lead",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RunPython(seed_stages, unseed),
    ]
