from django.urls import path

from apps.platform_runtime.views_administration import (
    blueprint_apply_view,
    blueprint_detail,
    blueprint_impact_view,
    blueprint_installation_detail,
    blueprint_installations,
    blueprint_marketplace,
    blueprint_preview_view,
    blueprint_rollback_view,
    change_request_apply,
    change_request_approve,
    change_request_cancel,
    change_request_detail,
    change_request_reject,
    change_request_schedule,
    change_requests,
    configuration_center,
    configuration_module_detail,
    pack_apply_view,
    pack_detail,
    pack_impact_view,
    pack_installation_detail,
    pack_installations,
    pack_marketplace,
    pack_preview_view,
    pack_rollback_view,
    pack_simulation_view,
    registry_health_view,
)

app_name = "configuration"

urlpatterns = [
    path("", configuration_center, name="center"),
    path("change-requests/", change_requests, name="change_requests"),
    path("change-requests/<int:request_id>/", change_request_detail, name="change_request_detail"),
    path("change-requests/<int:request_id>/approve/", change_request_approve, name="change_request_approve"),
    path("change-requests/<int:request_id>/reject/", change_request_reject, name="change_request_reject"),
    path("change-requests/<int:request_id>/schedule/", change_request_schedule, name="change_request_schedule"),
    path("change-requests/<int:request_id>/cancel/", change_request_cancel, name="change_request_cancel"),
    path("change-requests/<int:request_id>/apply/", change_request_apply, name="change_request_apply"),
    path("registries/health/", registry_health_view, name="registry_health"),
    path("blueprints/", blueprint_marketplace, name="blueprint_marketplace"),
    path("blueprints/installations/", blueprint_installations, name="blueprint_installations"),
    path(
        "blueprints/installations/<int:installation_id>/",
        blueprint_installation_detail,
        name="blueprint_installation_detail",
    ),
    path(
        "blueprints/installations/<int:installation_id>/rollback/",
        blueprint_rollback_view,
        name="blueprint_rollback",
    ),
    path("blueprints/<slug:key>/", blueprint_detail, name="blueprint_detail"),
    path("blueprints/<slug:key>/preview/", blueprint_preview_view, name="blueprint_preview"),
    path("blueprints/<slug:key>/impact/", blueprint_impact_view, name="blueprint_impact"),
    path("blueprints/<slug:key>/apply/", blueprint_apply_view, name="blueprint_apply"),
    path("pack-installations/", pack_installations, name="pack_installations"),
    path(
        "pack-installations/<int:installation_id>/",
        pack_installation_detail,
        name="pack_installation_detail",
    ),
    path(
        "pack-installations/<int:installation_id>/rollback/",
        pack_rollback_view,
        name="pack_rollback",
    ),
    path("workflow-packs/", pack_marketplace, {"pack_route": "workflow-packs"}, name="workflow_packs"),
    path("workflow-packs/<slug:key>/", pack_detail, {"pack_route": "workflow-packs"}, name="workflow_pack_detail"),
    path("workflow-packs/<slug:key>/preview/", pack_preview_view, {"pack_route": "workflow-packs"}, name="workflow_pack_preview"),
    path("workflow-packs/<slug:key>/simulate/", pack_simulation_view, {"pack_route": "workflow-packs"}, name="workflow_pack_simulation"),
    path("workflow-packs/<slug:key>/impact/", pack_impact_view, {"pack_route": "workflow-packs"}, name="workflow_pack_impact"),
    path("workflow-packs/<slug:key>/apply/", pack_apply_view, {"pack_route": "workflow-packs"}, name="workflow_pack_apply"),
    path("dashboard-packs/", pack_marketplace, {"pack_route": "dashboard-packs"}, name="dashboard_packs"),
    path("dashboard-packs/<slug:key>/", pack_detail, {"pack_route": "dashboard-packs"}, name="dashboard_pack_detail"),
    path("dashboard-packs/<slug:key>/preview/", pack_preview_view, {"pack_route": "dashboard-packs"}, name="dashboard_pack_preview"),
    path("dashboard-packs/<slug:key>/simulate/", pack_simulation_view, {"pack_route": "dashboard-packs"}, name="dashboard_pack_simulation"),
    path("dashboard-packs/<slug:key>/impact/", pack_impact_view, {"pack_route": "dashboard-packs"}, name="dashboard_pack_impact"),
    path("dashboard-packs/<slug:key>/apply/", pack_apply_view, {"pack_route": "dashboard-packs"}, name="dashboard_pack_apply"),
    path("policy-bundles/", pack_marketplace, {"pack_route": "policy-bundles"}, name="policy_bundles"),
    path("policy-bundles/<slug:key>/", pack_detail, {"pack_route": "policy-bundles"}, name="policy_bundle_detail"),
    path("policy-bundles/<slug:key>/preview/", pack_preview_view, {"pack_route": "policy-bundles"}, name="policy_bundle_preview"),
    path("policy-bundles/<slug:key>/simulate/", pack_simulation_view, {"pack_route": "policy-bundles"}, name="policy_bundle_simulation"),
    path("policy-bundles/<slug:key>/impact/", pack_impact_view, {"pack_route": "policy-bundles"}, name="policy_bundle_impact"),
    path("policy-bundles/<slug:key>/apply/", pack_apply_view, {"pack_route": "policy-bundles"}, name="policy_bundle_apply"),
    path("experience-templates/", pack_marketplace, {"pack_route": "experience-templates"}, name="experience_template_marketplace"),
    path("experience-templates/<slug:key>/", pack_detail, {"pack_route": "experience-templates"}, name="experience_template_detail"),
    path("experience-templates/<slug:key>/preview/", pack_preview_view, {"pack_route": "experience-templates"}, name="experience_template_preview"),
    path("experience-templates/<slug:key>/simulate/", pack_simulation_view, {"pack_route": "experience-templates"}, name="experience_template_simulation"),
    path("experience-templates/<slug:key>/impact/", pack_impact_view, {"pack_route": "experience-templates"}, name="experience_template_impact"),
    path("experience-templates/<slug:key>/apply/", pack_apply_view, {"pack_route": "experience-templates"}, name="experience_template_apply"),
    path("<slug:module_key>/", configuration_module_detail, name="module_detail"),
]
