# Generated by Django 5.2.10 on 2026-05-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersuccess', '0001_section_11_benchmark_customer_success'),
        ('schools', '0057_school_primary_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpcenterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FILE', 'File upload'), ('URL', 'Web URL')], db_index=True, max_length=8)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('registered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpcenter_sources_registered', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpcenter_sources', to='schools.school')),
            ],
            options={
                'verbose_name': 'Helpcenter source',
                'verbose_name_plural': 'Helpcenter sources',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['school', 'kind'], name='customersuc_school__6e721f_idx'), models.Index(fields=['school', '-registered_at'], name='customersuc_school__89cf93_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'URL')), fields=('school', 'url'), name='uniq_helpcenter_source_per_school_url'), models.UniqueConstraint(condition=models.Q(('kind', 'FILE')), fields=('school', 'file_name'), name='uniq_helpcenter_source_per_school_file')],
            },
        ),
    ]
