# Generated by Django 5.2.10 on 2026-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersuccess', '0002_helpcentersource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoticketrule',
            name='trigger',
            field=models.CharField(choices=[('workflow_failure', 'Workflow failure'), ('health_below', 'Health score below threshold'), ('inactivity_days', 'Admin inactivity (days)'), ('risk_alert_red', 'Red risk alert'), ('feedback_critical', 'Critical/high feedback submission')], db_index=True, max_length=40),
        ),
    ]
