# Generated by Django 5.2.10 on 2026-06-18 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersuccess', '0003_alter_autoticketrule_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkCohortMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, help_text='e.g. maturity:overall, health:overall, maturity:finance', max_length=80)),
                ('member_count', models.PositiveIntegerField(default=0, help_text='Schools contributing a value (>= k-anonymity floor).')),
                ('p25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('p50', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('p75', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Benchmark cohort metric',
                'verbose_name_plural': 'Benchmark cohort metrics',
                'ordering': ['cohort_id', 'metric_key'],
            },
        ),
        migrations.AddField(
            model_name='benchmarkcohort',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='True when produced by recompute_benchmark_cohorts (vs hand-curated).'),
        ),
        migrations.AddField(
            model_name='benchmarkcohort',
            name='last_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmarkcohort',
            name='member_count',
            field=models.PositiveIntegerField(default=0, help_text='Schools matching this cohort at last recompute (k-anonymity gate).'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkcohort',
            constraint=models.UniqueConstraint(condition=models.Q(('is_auto', True)), fields=('country_code', 'size_band', 'institution_type'), name='uniq_auto_cohort_bucket'),
        ),
        migrations.AddField(
            model_name='benchmarkcohortmetric',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='customersuccess.benchmarkcohort'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkcohortmetric',
            constraint=models.UniqueConstraint(fields=('cohort', 'metric_key'), name='uniq_cohort_metric_key'),
        ),
    ]
