# Generated by Django 5.2.10 on 2026-01-24 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0011_remove_scheduleentry_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-3 country code', max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('ministry_name', models.CharField(help_text='Name of education ministry', max_length=200)),
                ('emis_version', models.CharField(help_text='EMIS format version/standard', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('requirements_url', models.URLField(blank=True, help_text='URL to official EMIS requirements')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EMIS Compliance',
                'verbose_name_plural': 'EMIS Compliances',
            },
        ),
        migrations.CreateModel(
            name='EMISExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('students', 'Student Data'), ('teachers', 'Teacher Data'), ('subjects', 'Subject Data'), ('enrollment', 'Enrollment Data'), ('performance', 'Academic Performance'), ('infrastructure', 'School Infrastructure'), ('full', 'Complete EMIS Dataset')], default='full', max_length=20)),
                ('export_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='emis_exports/%Y/%m/')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('country_code', models.CharField(default='CMR', help_text='ISO 3166-1 alpha-3 country code', max_length=3)),
                ('ministry_format', models.CharField(blank=True, help_text='Specific ministry format requirements', max_length=50)),
                ('academic_year', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='emis_exports', to='academics.academicyear')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis_exports', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emis_exports', to='academics.term')),
            ],
            options={
                'verbose_name': 'EMIS Export',
                'verbose_name_plural': 'EMIS Exports',
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='EMISFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-3 country code', max_length=3)),
                ('export_type', models.CharField(choices=[('students', 'Student Data'), ('teachers', 'Teacher Data'), ('subjects', 'Subject Data'), ('enrollment', 'Enrollment Data'), ('performance', 'Academic Performance'), ('infrastructure', 'School Infrastructure'), ('full', 'Complete EMIS Dataset')], max_length=20)),
                ('field_name', models.CharField(help_text='Internal field name', max_length=100)),
                ('mapped_name', models.CharField(help_text='EMIS export field name', max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'EMIS Field Mapping',
                'verbose_name_plural': 'EMIS Field Mappings',
                'unique_together': {('country_code', 'export_type', 'field_name')},
            },
        ),
    ]
