# Generated by Django 5.2.10 on 2026-03-06 17:32

import emis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisexport',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=emis.models._emis_export_upload_to),
        ),
    ]
