"""
Management command to seed admin dashboard color palettes.
Creates preset ThemePacks with admin_dashboard palette from Unfold design system.
Run: python manage.py seed_admin_dashboard_palettes [--reset]
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.brand_experience.platform_global_branding import PlatformGlobalBranding
from apps.platform_runtime.helpers import get_platform_site_settings_record
from apps.siteconfig.models import ThemePack

CURATED_CATALOG_SLUGS = (
    "admin-academic-slate",
    "admin-academic-authority",
    "admin-campus-blue",
    "admin-ocean-blue",
    "admin-indigo-lecture",
    "admin-digital-lavender",
    "admin-runmycampus-warm-pink",
    "admin-sunset-study",
    "admin-sunset-warm",
    "admin-forest-academy",
    "admin-modern-sage",
    "admin-verdant-growth",
    "admin-tech-pioneer",
    "admin-cyber-lab",
    "admin-glassmorphism",
    "admin-high-contrast-accessible",
    "admin-conservatory",
    "admin-midnight-scholar",
    # Ultra High-End (super ultra high-end theme packs for tenants)
    "admin-ultra-gallery",
    "admin-ultra-noir",
    "admin-ultra-platinum",
    "portal-ultra-gallery",
    "portal-ultra-noir",
    "portal-ultra-platinum",
    "portal-active-learner",
    "portal-creative-spark",
    "portal-sunset-scholar",
    "portal-grounded-mentor",
    "portal-playroom",
    "portal-orchard",
)


def build_admin_dashboard_palette(
    primary,
    accent,
    accent_light,
    dashboard_bg,
    surface,
    border,
    border_strong,
    text,
    muted,
    subtle,
    role_admin,
    role_student,
    role_teacher,
    success="#10b981",
    warning="#f59e0b",
    danger="#ef4444",
    info="#3b82f6",
    shadow="0 1px 2px rgba(15,23,42,0.05)",
    shadow_hover="0 4px 12px rgba(15,23,42,0.1)",
    border_hover=None,
    weather_bg=None,
):
    border_hover = border_hover or border_strong
    if weather_bg is None and primary.startswith("#") and len(primary) >= 7:
        try:
            r = int(primary[1:3], 16)
            g = int(primary[3:5], 16)
            b = int(primary[5:7], 16)
            weather_bg = f"rgba({r},{g},{b},0.08)"
        except (ValueError, IndexError):
            weather_bg = "rgba(255,106,136,0.08)"
    if weather_bg is None:
        weather_bg = "rgba(255,106,136,0.08)"
    return {
        "admin_dashboard": {
            "primary": primary,
            "accent": accent,
            "accent_light": accent_light,
            "dashboard_bg": dashboard_bg,
            "surface": surface,
            "border": border,
            "border_strong": border_strong,
            "text": text,
            "muted": muted,
            "subtle": subtle,
            "role_admin": role_admin,
            "role_student": role_student,
            "role_teacher": role_teacher,
            "success": success,
            "warning": warning,
            "danger": danger,
            "info": info,
            "shadow": shadow,
            "shadow_hover": shadow_hover,
            "border_hover": border_hover or border_strong,
            "weather_bg": weather_bg,
        }
    }


class Command(BaseCommand):
    help = "Seed preset admin dashboard color palettes (Unfold design system)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing admin dashboard palettes before creating",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        reset = options.get("reset", False)

        self.stdout.write(
            self.style.SUCCESS("Creating admin dashboard color palettes...\n")
        )

        # School-focused palettes: professional, readable, all theme modes supported
        palettes = [
            # 1. Academic Slate (Default) - neutral, professional, K-12
            {
                "slug": "admin-academic-slate",
                "name": "Academic Slate (Default)",
                "description": "Neutral slate grey. Professional, low-distraction, ideal for schools.",
                "applies_to_admin": True,
                "is_default": True,
                "is_active": True,
                "primary_color": "#475569",
                "accent_color": "#0ea5e9",
                "palette": build_admin_dashboard_palette(
                    primary="#475569",
                    accent="#0ea5e9",
                    accent_light="#38bdf8",
                    dashboard_bg="#f8fafc",
                    surface="#ffffff",
                    border="rgba(15,23,42,0.08)",
                    border_strong="rgba(15,23,42,0.12)",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#6366f1",
                    role_student="#0ea5e9",
                    role_teacher="#10b981",
                    weather_bg="rgba(14,165,233,0.08)",
                ),
            },
            # 2. Campus Blue - trust, calm, institutional
            {
                "slug": "admin-campus-blue",
                "name": "Campus Blue",
                "description": "Trust and calm. Institutional blue, ideal for academies.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#2563eb",
                "accent_color": "#38bdf8",
                "palette": build_admin_dashboard_palette(
                    primary="#2563eb",
                    accent="#38bdf8",
                    accent_light="#7dd3fc",
                    dashboard_bg="#eff6ff",
                    surface="#ffffff",
                    border="rgba(37,99,235,0.12)",
                    border_strong="rgba(37,99,235,0.2)",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#6366f1",
                    role_student="#2563eb",
                    role_teacher="#10b981",
                    weather_bg="rgba(37,99,235,0.08)",
                ),
            },
            # 3. Forest Academy - nature, growth, learning
            {
                "slug": "admin-forest-academy",
                "name": "Forest Academy",
                "description": "Natural green. Calming, growth-oriented, ideal for learning.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#059669",
                "accent_color": "#34d399",
                "palette": build_admin_dashboard_palette(
                    primary="#059669",
                    accent="#34d399",
                    accent_light="#6ee7b7",
                    dashboard_bg="#f0fdf4",
                    surface="#ffffff",
                    border="rgba(5,150,105,0.15)",
                    border_strong="rgba(5,150,105,0.25)",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#059669",
                    role_student="#0ea5e9",
                    role_teacher="#34d399",
                    weather_bg="rgba(5,150,105,0.08)",
                ),
            },
            # 4. RunMyCampus Warm Pink - brand accent
            {
                "slug": "admin-runmycampus-warm-pink",
                "name": "RunMyCampus Warm Pink",
                "description": "Warm pink with purple. Friendly, creative, brand accent.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#ff6a88",
                "accent_color": "#9b6bff",
                "palette": build_admin_dashboard_palette(
                    primary="#ff6a88",
                    accent="#9b6bff",
                    accent_light="#c4a5ff",
                    dashboard_bg="#f8fafc",
                    surface="#ffffff",
                    border="rgba(15,23,42,0.08)",
                    border_strong="rgba(15,23,42,0.12)",
                    text="#0f172a",
                    muted="#6b7280",
                    subtle="#22314e",
                    role_admin="#9b6bff",
                    role_student="#ff6a88",
                    role_teacher="#2dd4bf",
                    weather_bg="rgba(255,106,136,0.08)",
                ),
            },
            # 5. Midnight Scholar - Unfold dark primary
            {
                "slug": "admin-midnight-scholar",
                "name": "Midnight Scholar",
                "description": "Dark, focused. Ideal for data-heavy and analytics views.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#3b82f6",
                "accent_color": "#818cf8",
                "palette": build_admin_dashboard_palette(
                    primary="#3b82f6",
                    accent="#818cf8",
                    accent_light="#a5b4fc",
                    dashboard_bg="#0f172a",
                    surface="#1e293b",
                    border="rgba(148,163,184,0.25)",
                    border_strong="rgba(148,163,184,0.35)",
                    text="#f1f5f9",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#818cf8",
                    role_student="#60a5fa",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.3)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.4)",
                    weather_bg="rgba(59,130,246,0.15)",
                ),
            },
            # 6. Indigo Lecture - modern, tech-forward
            {
                "slug": "admin-indigo-lecture",
                "name": "Indigo Lecture",
                "description": "Modern indigo/purple. Tech-forward, ideal for STEM.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#4f46e5",
                "accent_color": "#818cf8",
                "palette": build_admin_dashboard_palette(
                    primary="#4f46e5",
                    accent="#818cf8",
                    accent_light="#a5b4fc",
                    dashboard_bg="#0f172a",
                    surface="#1e293b",
                    border="rgba(148,163,184,0.25)",
                    border_strong="rgba(148,163,184,0.35)",
                    text="#f1f5f9",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#818cf8",
                    role_student="#60a5fa",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.3)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.4)",
                    weather_bg="rgba(79,70,229,0.15)",
                ),
            },
            # 7. Sunset Study - warm dark, energetic
            {
                "slug": "admin-sunset-study",
                "name": "Sunset Study",
                "description": "Warm orange/amber dark. Energetic, creative, low glare.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#f59e0b",
                "accent_color": "#fbbf24",
                "palette": build_admin_dashboard_palette(
                    primary="#f59e0b",
                    accent="#fbbf24",
                    accent_light="#fde68a",
                    dashboard_bg="#1c1917",
                    surface="#292524",
                    border="rgba(251,191,36,0.2)",
                    border_strong="rgba(251,191,36,0.35)",
                    text="#fef3c7",
                    muted="#d6d3d1",
                    subtle="#e7e5e4",
                    role_admin="#fbbf24",
                    role_student="#f59e0b",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.3)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.4)",
                    weather_bg="rgba(245,158,11,0.15)",
                ),
            },
            # 8. RunMyCampus Dark Neutral - neutral dark
            {
                "slug": "admin-runmycampus-dark-neutral",
                "name": "RunMyCampus Dark Neutral",
                "description": "Unfold dark grays: neutral dark admin.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#94a3b8",
                "accent_color": "#cbd5e1",
                "palette": build_admin_dashboard_palette(
                    primary="#94a3b8",
                    accent="#cbd5e1",
                    accent_light="#e2e8f0",
                    dashboard_bg="#0f172a",
                    surface="#1e293b",
                    border="rgba(148,163,184,0.25)",
                    border_strong="rgba(148,163,184,0.35)",
                    text="#f1f5f9",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#818cf8",
                    role_student="#60a5fa",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.3)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.4)",
                    weather_bg="rgba(148,163,184,0.12)",
                ),
            },
            # 9. Sky Blue (Professional)
            {
                "slug": "admin-sky-blue",
                "name": "Sky Blue",
                "description": "Professional sky blue; clean and modern.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0ea5e9",
                "accent_color": "#38bdf8",
                "palette": build_admin_dashboard_palette(
                    primary="#0ea5e9",
                    accent="#38bdf8",
                    accent_light="#7dd3fc",
                    dashboard_bg="#f8fafc",
                    surface="#ffffff",
                    border="#e2e8f0",
                    border_strong="#cbd5e1",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#6366f1",
                    role_student="#0ea5e9",
                    role_teacher="#10b981",
                    weather_bg="rgba(14,165,233,0.08)",
                ),
            },
            # 10. Forest Green
            {
                "slug": "admin-forest-green",
                "name": "Forest Green",
                "description": "Natural green; calming and professional.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#10b981",
                "accent_color": "#34d399",
                "palette": build_admin_dashboard_palette(
                    primary="#10b981",
                    accent="#34d399",
                    accent_light="#6ee7b7",
                    dashboard_bg="#f0fdf4",
                    surface="#ffffff",
                    border="#d1fae5",
                    border_strong="#a7f3d0",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#059669",
                    role_student="#10b981",
                    role_teacher="#34d399",
                    weather_bg="rgba(16,185,129,0.08)",
                ),
            },
            # 11. Sunset Warm
            {
                "slug": "admin-sunset-warm",
                "name": "Sunset Warm",
                "description": "Warm orange/amber; friendly and energetic.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#f59e0b",
                "accent_color": "#fbbf24",
                "palette": build_admin_dashboard_palette(
                    primary="#f59e0b",
                    accent="#fbbf24",
                    accent_light="#fde68a",
                    dashboard_bg="#fffbeb",
                    surface="#ffffff",
                    border="#fde68a",
                    border_strong="#fcd34d",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#d97706",
                    role_student="#f59e0b",
                    role_teacher="#10b981",
                    weather_bg="rgba(245,158,11,0.08)",
                ),
            },
            # 12. Ocean Blue
            {
                "slug": "admin-ocean-blue",
                "name": "Ocean Blue",
                "description": "Deep blue; trustworthy and corporate.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#3b82f6",
                "accent_color": "#60a5fa",
                "palette": build_admin_dashboard_palette(
                    primary="#3b82f6",
                    accent="#60a5fa",
                    accent_light="#93c5fd",
                    dashboard_bg="#eff6ff",
                    surface="#ffffff",
                    border="#bfdbfe",
                    border_strong="#93c5fd",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#6366f1",
                    role_student="#3b82f6",
                    role_teacher="#10b981",
                    weather_bg="rgba(59,130,246,0.08)",
                ),
            },
            # 13. High Contrast Light (WCAG AAA)
            {
                "slug": "admin-high-contrast-light",
                "name": "High Contrast Light",
                "description": "Maximum accessibility; light background, strong contrast.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#000000",
                "accent_color": "#0066cc",
                "palette": build_admin_dashboard_palette(
                    primary="#000000",
                    accent="#0066cc",
                    accent_light="#3385ff",
                    dashboard_bg="#ffffff",
                    surface="#ffffff",
                    border="#000000",
                    border_strong="#000000",
                    text="#000000",
                    muted="#333333",
                    subtle="#666666",
                    role_admin="#000080",
                    role_student="#0066cc",
                    role_teacher="#008000",
                    shadow="0 2px 4px rgba(0,0,0,0.2)",
                    shadow_hover="0 4px 8px rgba(0,0,0,0.3)",
                    weather_bg="rgba(0,102,204,0.1)",
                ),
            },
            # 14. High Contrast Dark
            {
                "slug": "admin-high-contrast-dark",
                "name": "High Contrast Dark",
                "description": "Maximum accessibility; dark background, strong contrast.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#60a5fa",
                "accent_color": "#93c5fd",
                "palette": build_admin_dashboard_palette(
                    primary="#60a5fa",
                    accent="#93c5fd",
                    accent_light="#bfdbfe",
                    dashboard_bg="#0c0c0c",
                    surface="#171717",
                    border="#404040",
                    border_strong="#525252",
                    text="#fafafa",
                    muted="#a3a3a3",
                    subtle="#d4d4d4",
                    role_admin="#818cf8",
                    role_student="#60a5fa",
                    role_teacher="#34d399",
                    shadow="0 2px 4px rgba(0,0,0,0.5)",
                    shadow_hover="0 6px 12px rgba(0,0,0,0.6)",
                    weather_bg="rgba(96,165,250,0.2)",
                ),
            },
            # 15. Slate Gray
            {
                "slug": "admin-slate-gray",
                "name": "Slate Gray",
                "description": "Muted slate; minimal and focused.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#475569",
                "accent_color": "#64748b",
                "palette": build_admin_dashboard_palette(
                    primary="#475569",
                    accent="#64748b",
                    accent_light="#94a3b8",
                    dashboard_bg="#f1f5f9",
                    surface="#ffffff",
                    border="#e2e8f0",
                    border_strong="#cbd5e1",
                    text="#0f172a",
                    muted="#64748b",
                    subtle="#475569",
                    role_admin="#4f46e5",
                    role_student="#0369a1",
                    role_teacher="#047857",
                    weather_bg="rgba(71,85,105,0.08)",
                ),
            },
            # 16. Deep Space / Midnight Blue
            {
                "slug": "admin-deep-space-midnight",
                "name": "Deep Space / Midnight Blue",
                "description": "Midnight base (#101010–#222222), Neon Blue/Teal (#3B86D1) for data, soft white text (#F8F9FA).",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#3B86D1",
                "accent_color": "#5ba3e8",
                "palette": build_admin_dashboard_palette(
                    primary="#3B86D1",
                    accent="#5ba3e8",
                    accent_light="#7eb8ed",
                    dashboard_bg="#101010",
                    surface="#222222",
                    border="rgba(248,249,250,0.12)",
                    border_strong="rgba(248,249,250,0.2)",
                    text="#F8F9FA",
                    muted="#b8bcc4",
                    subtle="#e2e4e8",
                    role_admin="#5ba3e8",
                    role_student="#3B86D1",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.4)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.5)",
                    border_hover="rgba(248,249,250,0.25)",
                    weather_bg="rgba(59,134,209,0.15)",
                ),
            },
            # === School-themed (15 core + niche + contemporary) ===
            # 17. Academic Authority (admin/finance)
            {
                "slug": "admin-academic-authority",
                "name": "Academic Authority",
                "description": "Trustworthy. Navy and Trust Blue, Cloud Dancer background. Best for admins and finance.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0D173B",
                "accent_color": "#007BFF",
                "palette": build_admin_dashboard_palette(
                    primary="#0D173B",
                    accent="#007BFF",
                    accent_light="#E7EAF3",
                    dashboard_bg="#F0F3F5",
                    surface="#F8F9FA",
                    border="rgba(26,28,30,0.08)",
                    border_strong="rgba(26,28,30,0.12)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#0D173B",
                    role_student="#007BFF",
                    role_teacher="#1B4332",
                    success="#1B4332",
                    weather_bg="rgba(0,123,255,0.08)",
                ),
            },
            # 18. Executive Ivy (private schools)
            {
                "slug": "admin-executive-ivy",
                "name": "Executive Ivy",
                "description": "Elite, traditional. Forest green, warm cream, gold accents.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#1B4332",
                "accent_color": "#D4AF37",
                "palette": build_admin_dashboard_palette(
                    primary="#1B4332",
                    accent="#D4AF37",
                    accent_light="rgba(212,175,55,0.2)",
                    dashboard_bg="#F5F5DC",
                    surface="#ffffff",
                    border="rgba(27,67,50,0.12)",
                    border_strong="rgba(27,67,50,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#1B4332",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    success="#1B4332",
                    weather_bg="rgba(27,67,50,0.08)",
                ),
            },
            # 19. Modern Chancellor (multi-school / SaaS)
            {
                "slug": "admin-modern-chancellor",
                "name": "Modern Chancellor",
                "description": "Clean, corporate SaaS. Charcoal and slate blue, crisp white.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#333333",
                "accent_color": "#708090",
                "palette": build_admin_dashboard_palette(
                    primary="#333333",
                    accent="#708090",
                    accent_light="#94a3b8",
                    dashboard_bg="#ffffff",
                    surface="#f8fafc",
                    border="rgba(51,51,51,0.1)",
                    border_strong="rgba(51,51,51,0.18)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#333333",
                    role_student="#1982C4",
                    role_teacher="#10b981",
                    weather_bg="rgba(112,128,144,0.08)",
                ),
            },
            # 20. Sophisticated Slate (dark mode 2.0)
            {
                "slug": "admin-sophisticated-slate",
                "name": "Sophisticated Slate",
                "description": "Sleek dark. Silhouette charcoal, soft grays. High-end admin.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#9B51E0",
                "accent_color": "#669BBC",
                "palette": build_admin_dashboard_palette(
                    primary="#9B51E0",
                    accent="#669BBC",
                    accent_light="#a78bfa",
                    dashboard_bg="#1A1A1A",
                    surface="#2C2C2E",
                    border="rgba(255,255,255,0.1)",
                    border_strong="rgba(255,255,255,0.18)",
                    text="#F0F3F5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#9B51E0",
                    role_student="#669BBC",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.4)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.5)",
                    weather_bg="rgba(155,81,224,0.15)",
                ),
            },
            # 21. Digital Lavender (student wellness / admin)
            {
                "slug": "admin-digital-lavender",
                "name": "Digital Lavender",
                "description": "Calming. Lavender and soft mint. Student wellness and counseling.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#7C7CE4",
                "accent_color": "#A78BFA",
                "palette": build_admin_dashboard_palette(
                    primary="#7C7CE4",
                    accent="#A78BFA",
                    accent_light="rgba(167,139,250,0.25)",
                    dashboard_bg="#F3F4F6",
                    surface="#ffffff",
                    border="rgba(124,124,228,0.15)",
                    border_strong="rgba(124,124,228,0.25)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#7C7CE4",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    warning="#EC5800",
                    info="#1982C4",
                    weather_bg="rgba(124,124,228,0.1)",
                ),
            },
            # 22. Modern Sage (teacher / grading)
            {
                "slug": "admin-modern-sage",
                "name": "Modern Sage",
                "description": "Teacher and grading. Sage green, warm surface, growth indicators.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#2D4739",
                "accent_color": "#5F7A61",
                "palette": build_admin_dashboard_palette(
                    primary="#2D4739",
                    accent="#5F7A61",
                    accent_light="#76A665",
                    dashboard_bg="#FDFCF0",
                    surface="#ffffff",
                    border="rgba(45,71,57,0.12)",
                    border_strong="rgba(45,71,57,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#2D4739",
                    role_student="#1982C4",
                    role_teacher="#D58D8D",
                    success="#76A665",
                    weather_bg="rgba(95,122,97,0.08)",
                ),
            },
            # 23. Focused Classroom (LMS / teachers)
            {
                "slug": "admin-focused-classroom",
                "name": "Focused Classroom",
                "description": "Balanced. Muted rose, slate, sage. Minimize cognitive load.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#708090",
                "accent_color": "#BFD3C1",
                "palette": build_admin_dashboard_palette(
                    primary="#708090",
                    accent="#BFD3C1",
                    accent_light="#D58D8D",
                    dashboard_bg="#FDFCF0",
                    surface="#ffffff",
                    border="rgba(112,128,144,0.12)",
                    border_strong="rgba(112,128,144,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#708090",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    success="#76A665",
                    weather_bg="rgba(191,211,193,0.15)",
                ),
            },
            # 24. The Tech Pioneer (STEM / robotics)
            {
                "slug": "admin-tech-pioneer",
                "name": "The Tech Pioneer",
                "description": "Sci-fi. Neon cyan and violet on charcoal. STEM and coding.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#00F5FF",
                "accent_color": "#6366f1",
                "palette": build_admin_dashboard_palette(
                    primary="#00F5FF",
                    accent="#6366f1",
                    accent_light="#a78bfa",
                    dashboard_bg="#121212",
                    surface="#1e1e2e",
                    border="rgba(0,245,255,0.15)",
                    border_strong="rgba(0,245,255,0.25)",
                    text="#F0F3F5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#6366f1",
                    role_student="#00F5FF",
                    role_teacher="#00FF41",
                    success="#00FF41",
                    shadow="0 1px 2px rgba(0,0,0,0.4)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.5)",
                    weather_bg="rgba(0,245,255,0.12)",
                ),
            },
            # 25. Verdant Growth (progress tracking)
            {
                "slug": "admin-verdant-growth",
                "name": "Verdant Growth",
                "description": "Success-driven. Emerald and gold. Progress and development.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#064e3b",
                "accent_color": "#D4AF37",
                "palette": build_admin_dashboard_palette(
                    primary="#064e3b",
                    accent="#D4AF37",
                    accent_light="#76A665",
                    dashboard_bg="#f0fdf4",
                    surface="#ffffff",
                    border="rgba(6,78,59,0.12)",
                    border_strong="rgba(6,78,59,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#064e3b",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    success="#22C55E",
                    weather_bg="rgba(6,78,59,0.08)",
                ),
            },
            # 26. The Sensory Room (special education)
            {
                "slug": "admin-sensory-room",
                "name": "The Sensory Room",
                "description": "Inclusive. Soft peach, dusty teal, mauve. Low saturation.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#4E89AE",
                "accent_color": "#B298DC",
                "palette": build_admin_dashboard_palette(
                    primary="#4E89AE",
                    accent="#B298DC",
                    accent_light="#FFDAB9",
                    dashboard_bg="#FFFAF5",
                    surface="#ffffff",
                    border="rgba(78,137,174,0.12)",
                    border_strong="rgba(78,137,174,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#4E89AE",
                    role_student="#B298DC",
                    role_teacher="#76A665",
                    weather_bg="rgba(78,137,174,0.08)",
                ),
            },
            # 27. The Cyber Lab (STEM / coding)
            {
                "slug": "admin-cyber-lab",
                "name": "The Cyber Lab",
                "description": "Futuristic. Dark slate, electric cyan, matrix green.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#00F5FF",
                "accent_color": "#00FF41",
                "palette": build_admin_dashboard_palette(
                    primary="#00F5FF",
                    accent="#00FF41",
                    accent_light="rgba(0,255,65,0.3)",
                    dashboard_bg="#121212",
                    surface="#1a1a1a",
                    border="rgba(0,245,255,0.15)",
                    border_strong="rgba(0,245,255,0.25)",
                    text="#F0F3F5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#00F5FF",
                    role_student="#00FF41",
                    role_teacher="#34d399",
                    success="#00FF41",
                    shadow="0 1px 2px rgba(0,0,0,0.4)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.5)",
                    weather_bg="rgba(0,245,255,0.12)",
                ),
            },
            # 28. The Blueprint (engineering)
            {
                "slug": "admin-blueprint",
                "name": "The Blueprint",
                "description": "Drafting blue, engineering gray, safety orange. Architecture/engineering.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#003366",
                "accent_color": "#FF6600",
                "palette": build_admin_dashboard_palette(
                    primary="#003366",
                    accent="#FF6600",
                    accent_light="#8E8E8E",
                    dashboard_bg="#f0f4f8",
                    surface="#ffffff",
                    border="rgba(0,51,102,0.12)",
                    border_strong="rgba(0,51,102,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#003366",
                    role_student="#1982C4",
                    role_teacher="#FF6600",
                    warning="#FF6600",
                    weather_bg="rgba(0,51,102,0.08)",
                ),
            },
            # 29. High-Contrast Accessible
            {
                "slug": "admin-high-contrast-accessible",
                "name": "High-Contrast Accessible",
                "description": "Pure charcoal, high-vis yellow, white. Visual impairment support.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#222222",
                "accent_color": "#FFF200",
                "palette": build_admin_dashboard_palette(
                    primary="#222222",
                    accent="#FFF200",
                    accent_light="rgba(255,242,0,0.25)",
                    dashboard_bg="#222222",
                    surface="#333333",
                    border="rgba(255,255,255,0.2)",
                    border_strong="rgba(255,255,255,0.35)",
                    text="#ffffff",
                    muted="#FFF200",
                    subtle="#e2e8f0",
                    role_admin="#FFF200",
                    role_student="#FFF200",
                    role_teacher="#34d399",
                    success="#22C55E",
                    shadow="0 1px 2px rgba(0,0,0,0.5)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.6)",
                    weather_bg="rgba(255,242,0,0.15)",
                ),
            },
            # 30. The Focus Mode (exams / low distraction)
            {
                "slug": "admin-focus-mode",
                "name": "The Focus Mode",
                "description": "Deep ink, silver, teal. Cool dark for exams.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#45A29E",
                "accent_color": "#C5C6C7",
                "palette": build_admin_dashboard_palette(
                    primary="#45A29E",
                    accent="#C5C6C7",
                    accent_light="#e2e4e8",
                    dashboard_bg="#0B0C10",
                    surface="#1a1b1e",
                    border="rgba(197,198,199,0.2)",
                    border_strong="rgba(197,198,199,0.35)",
                    text="#F0F3F5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#45A29E",
                    role_student="#C5C6C7",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.5)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.6)",
                    weather_bg="rgba(69,162,158,0.15)",
                ),
            },
            # 31. The Conservatory (elite / arts)
            {
                "slug": "admin-conservatory",
                "name": "The Conservatory",
                "description": "Velvet maroon, parchment, antique brass. Premium, historic.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#800000",
                "accent_color": "#B08D57",
                "palette": build_admin_dashboard_palette(
                    primary="#800000",
                    accent="#B08D57",
                    accent_light="rgba(176,141,87,0.25)",
                    dashboard_bg="#FCF5E5",
                    surface="#ffffff",
                    border="rgba(128,0,0,0.15)",
                    border_strong="rgba(128,0,0,0.25)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#800000",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    weather_bg="rgba(128,0,0,0.08)",
                ),
            },
            # 32. The Modern Gallery (arts / design)
            {
                "slug": "admin-modern-gallery",
                "name": "The Modern Gallery",
                "description": "Stark white, pitch black, pop hot pink. Arts and design.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#000000",
                "accent_color": "#FF007F",
                "palette": build_admin_dashboard_palette(
                    primary="#000000",
                    accent="#FF007F",
                    accent_light="rgba(255,0,127,0.2)",
                    dashboard_bg="#ffffff",
                    surface="#f8fafc",
                    border="rgba(0,0,0,0.12)",
                    border_strong="rgba(0,0,0,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#000000",
                    role_student="#FF007F",
                    role_teacher="#10b981",
                    weather_bg="rgba(255,0,127,0.08)",
                ),
            },
            # 33. The Midnight Scholar (premium dark library)
            {
                "slug": "admin-the-midnight-scholar",
                "name": "The Midnight Scholar",
                "description": "Deepest navy, pale gold, ivory. Premium private library.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#020D19",
                "accent_color": "#E3C567",
                "palette": build_admin_dashboard_palette(
                    primary="#E3C567",
                    accent="#E3C567",
                    accent_light="rgba(227,197,103,0.25)",
                    dashboard_bg="#020D19",
                    surface="#0a1628",
                    border="rgba(227,197,103,0.2)",
                    border_strong="rgba(227,197,103,0.35)",
                    text="#FCF5E5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#E3C567",
                    role_student="#E3C567",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.5)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.6)",
                    weather_bg="rgba(227,197,103,0.12)",
                ),
            },
            # 34. Glassmorphism (contemporary)
            {
                "slug": "admin-glassmorphism",
                "name": "Glassmorphism",
                "description": "Translucent, electric indigo, soft cyan. Contemporary SaaS.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#6366F1",
                "accent_color": "#22d3ee",
                "palette": build_admin_dashboard_palette(
                    primary="#6366F1",
                    accent="#22d3ee",
                    accent_light="rgba(99,102,241,0.2)",
                    dashboard_bg="#f0f4ff",
                    surface="#ffffff",
                    border="rgba(99,102,241,0.15)",
                    border_strong="rgba(99,102,241,0.25)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#6366F1",
                    role_student="#22d3ee",
                    role_teacher="#10b981",
                    weather_bg="rgba(99,102,241,0.08)",
                ),
            },
            # 35. Neo-Brutalist (contemporary)
            {
                "slug": "admin-neo-brutalist",
                "name": "Neo-Brutalist",
                "description": "Stark yellow, black, persimmon. High-contrast, Gen-Z.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#FACC15",
                "accent_color": "#EC5800",
                "palette": build_admin_dashboard_palette(
                    primary="#000000",
                    accent="#EC5800",
                    accent_light="#FACC15",
                    dashboard_bg="#FACC15",
                    surface="#ffffff",
                    border="rgba(0,0,0,0.25)",
                    border_strong="rgba(0,0,0,0.4)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#000000",
                    role_student="#EC5800",
                    role_teacher="#10b981",
                    warning="#EC5800",
                    weather_bg="rgba(236,88,0,0.15)",
                ),
            },
            # 36. Eco-Digital (contemporary)
            {
                "slug": "admin-eco-digital",
                "name": "Eco-Digital",
                "description": "Deep forest, sage, stone. Biophilic, sustainability.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#064E3B",
                "accent_color": "#A3B18A",
                "palette": build_admin_dashboard_palette(
                    primary="#064E3B",
                    accent="#A3B18A",
                    accent_light="#BFD3C1",
                    dashboard_bg="#f0fdf4",
                    surface="#ffffff",
                    border="rgba(6,78,59,0.12)",
                    border_strong="rgba(6,78,59,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#064E3B",
                    role_student="#1982C4",
                    role_teacher="#76A665",
                    success="#22C55E",
                    weather_bg="rgba(163,177,138,0.15)",
                ),
            },
            # 37. Monochrome Pro (contemporary)
            {
                "slug": "admin-monochrome-pro",
                "name": "Monochrome Pro",
                "description": "Black, white, digital lavender accent. Minimalist, law/grad.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#000000",
                "accent_color": "#A78BFA",
                "palette": build_admin_dashboard_palette(
                    primary="#000000",
                    accent="#A78BFA",
                    accent_light="rgba(167,139,250,0.2)",
                    dashboard_bg="#ffffff",
                    surface="#f8fafc",
                    border="rgba(0,0,0,0.12)",
                    border_strong="rgba(0,0,0,0.2)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#000000",
                    role_student="#A78BFA",
                    role_teacher="#10b981",
                    weather_bg="rgba(167,139,250,0.08)",
                ),
            },
            # 38. Retro-Future (contemporary)
            {
                "slug": "admin-retro-future",
                "name": "Retro-Future",
                "description": "Cyber teal, sunset pink, midnight purple. Vaporwave, gamified.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#2DD4BF",
                "accent_color": "#F472B6",
                "palette": build_admin_dashboard_palette(
                    primary="#2DD4BF",
                    accent="#F472B6",
                    accent_light="rgba(244,114,182,0.25)",
                    dashboard_bg="#1E1B4B",
                    surface="#312e81",
                    border="rgba(45,212,191,0.2)",
                    border_strong="rgba(45,212,191,0.35)",
                    text="#F0F3F5",
                    muted="#94a3b8",
                    subtle="#cbd5e1",
                    role_admin="#2DD4BF",
                    role_student="#F472B6",
                    role_teacher="#34d399",
                    shadow="0 1px 2px rgba(0,0,0,0.4)",
                    shadow_hover="0 6px 16px rgba(0,0,0,0.5)",
                    weather_bg="rgba(45,212,191,0.15)",
                ),
            },
            # 39. Bento-Box (contemporary, parent dashboard)
            {
                "slug": "admin-bento-box",
                "name": "Bento-Box",
                "description": "Slate blue, off-white, emerald. Modular, structured.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#1E293B",
                "accent_color": "#10b981",
                "palette": build_admin_dashboard_palette(
                    primary="#1E293B",
                    accent="#10b981",
                    accent_light="#34d399",
                    dashboard_bg="#F8FAFC",
                    surface="#ffffff",
                    border="rgba(30,41,59,0.1)",
                    border_strong="rgba(30,41,59,0.18)",
                    text="#1A1C1E",
                    muted="#4A4A4A",
                    subtle="#64748b",
                    role_admin="#1E293B",
                    role_student="#1982C4",
                    role_teacher="#10b981",
                    success="#10b981",
                    weather_bg="rgba(16,185,129,0.08)",
                ),
            },
            # === Ultra High-End (super ultra high-end – luxury palette for tenants) ===
            {
                "slug": "admin-ultra-gallery",
                "name": "Ultra Gallery (Light)",
                "description": "Super ultra high-end. Gallery White, Rich Black typography, gold accent. Statement header, 600ms motion, hairline borders.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0A0A0A",
                "accent_color": "#B8860B",
                "background_color": "#FDFDFD",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#FDFDFD;--statement-header-fg:#0A0A0A;}.card,.cp-panel{border-radius:2px;border:1px solid rgba(10,10,10,0.08);}",
                "palette": build_admin_dashboard_palette(
                    primary="#0A0A0A",
                    accent="#B8860B",
                    accent_light="rgba(184,134,11,0.2)",
                    dashboard_bg="#FDFDFD",
                    surface="#FFFFFF",
                    border="rgba(10,10,10,0.08)",
                    border_strong="rgba(10,10,10,0.14)",
                    text="#1A1A1A",
                    muted="#525252",
                    subtle="#737373",
                    role_admin="#0A0A0A",
                    role_student="#0F172A",
                    role_teacher="#B8860B",
                    success="#0F172A",
                    weather_bg="rgba(184,134,11,0.08)",
                ),
            },
            {
                "slug": "admin-ultra-noir",
                "name": "Ultra Noir (Dark)",
                "description": "Super ultra high-end dark. Rich Black background, Platinum text, gold accent. Premium staff experience.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "backend_console_theme": "dark",
                "primary_color": "#FDFDFD",
                "accent_color": "#B8860B",
                "background_color": "#0A0A0A",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#0A0A0A;--statement-header-fg:#FDFDFD;}",
                "palette": build_admin_dashboard_palette(
                    primary="#FDFDFD",
                    accent="#B8860B",
                    accent_light="rgba(184,134,11,0.25)",
                    dashboard_bg="#0A0A0A",
                    surface="#171717",
                    border="rgba(255,255,255,0.1)",
                    border_strong="rgba(255,255,255,0.18)",
                    text="#F5F5F5",
                    muted="#A3A3A3",
                    subtle="#E5E5E5",
                    role_admin="#B8860B",
                    role_student="#60a5fa",
                    role_teacher="#34d399",
                    shadow="0 2px 12px rgba(0,0,0,0.3)",
                    shadow_hover="0 8px 24px rgba(0,0,0,0.4)",
                    weather_bg="rgba(184,134,11,0.15)",
                ),
            },
            {
                "slug": "admin-ultra-platinum",
                "name": "Ultra Platinum",
                "description": "Super ultra high-end neutral. Platinum surfaces, navy primary, gold accent. Magazine-style authority.",
                "applies_to_admin": True,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0F172A",
                "accent_color": "#B8860B",
                "background_color": "#FAFAFA",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#FAFAFA;--statement-header-fg:#0F172A;}",
                "palette": build_admin_dashboard_palette(
                    primary="#0F172A",
                    accent="#B8860B",
                    accent_light="rgba(184,134,11,0.2)",
                    dashboard_bg="#FAFAFA",
                    surface="#FFFFFF",
                    border="rgba(15,23,42,0.08)",
                    border_strong="rgba(15,23,42,0.14)",
                    text="#1A1A1A",
                    muted="#525252",
                    subtle="#737373",
                    role_admin="#0F172A",
                    role_student="#0ea5e9",
                    role_teacher="#10b981",
                    success="#10b981",
                    weather_bg="rgba(184,134,11,0.08)",
                ),
            },
            # Portal-only Ultra High-End
            {
                "slug": "portal-ultra-gallery",
                "name": "Ultra Gallery (Portal)",
                "description": "Super ultra high-end portal. Gallery White, Rich Black, gold accent. Mature statement branding.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0A0A0A",
                "accent_color": "#B8860B",
                "background_color": "#FDFDFD",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#FDFDFD;--statement-header-fg:#0A0A0A;}",
                "palette": {"gradient": ["#0A0A0A", "#1A1A1A"], "card": "#FFFFFF"},
            },
            {
                "slug": "portal-ultra-noir",
                "name": "Ultra Noir (Portal)",
                "description": "Super ultra high-end dark portal. Rich Black, Platinum text, gold accent.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#FDFDFD",
                "accent_color": "#B8860B",
                "background_color": "#0A0A0A",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#0A0A0A;--statement-header-fg:#FDFDFD;}",
                "palette": {"gradient": ["#0A0A0A", "#171717"], "card": "#171717"},
            },
            {
                "slug": "portal-ultra-platinum",
                "name": "Ultra Platinum (Portal)",
                "description": "Super ultra high-end neutral portal. Platinum surfaces, navy and gold. Premium tenant experience.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#0F172A",
                "accent_color": "#B8860B",
                "background_color": "#FAFAFA",
                "font_family": "Inter, system-ui, -apple-system, sans-serif",
                "layout": "STANDARD",
                "custom_css": ":root{--luxury-rich-black:#0A0A0A;--luxury-gallery-white:#FDFDFD;--luxury-platinum:#E5E5E5;--luxury-accent:#B8860B;--statement-header-bg:#FAFAFA;--statement-header-fg:#0F172A;}",
                "palette": {"gradient": ["#0F172A", "#1e293b"], "card": "#FFFFFF"},
            },
            # === Portal-only (no admin_dashboard palette) ===
            {
                "slug": "portal-active-learner",
                "name": "Active Learner",
                "description": "Energetic. Academic violet, fresh blue, persimmon. Student portals.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#6A4C93",
                "accent_color": "#1982C4",
                "background_color": "#F3F4F6",
                "palette": {},
            },
            {
                "slug": "portal-creative-spark",
                "name": "Creative Spark",
                "description": "Playful. Electric wasabi and banana yellow. Coding/arts.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#9ACD32",
                "accent_color": "#FFDE22",
                "background_color": "#1a1a1a",
                "palette": {},
            },
            {
                "slug": "portal-sunset-scholar",
                "name": "Sunset Scholar",
                "description": "Motivational. Sunset orange, midnight blue. Gamified learning.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#EC5800",
                "accent_color": "#1e3a5f",
                "background_color": "#fef3c7",
                "palette": {},
            },
            {
                "slug": "portal-grounded-mentor",
                "name": "Grounded Mentor",
                "description": "Approachable. Terracotta, warm khaki. Parent portals.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#E2725B",
                "accent_color": "#C4B896",
                "background_color": "#F5F5DC",
                "palette": {},
            },
            {
                "slug": "portal-playroom",
                "name": "The Playroom",
                "description": "Primary red, sunshine yellow, sky blue. Elementary K-5.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#E63946",
                "accent_color": "#FFB703",
                "background_color": "#A8DADC",
                "palette": {},
            },
            {
                "slug": "portal-orchard",
                "name": "The Orchard",
                "description": "Apple red, leaf green, pale wood. Nature-inspired primary.",
                "applies_to_admin": False,
                "is_default": False,
                "is_active": True,
                "primary_color": "#BC4749",
                "accent_color": "#A7C957",
                "background_color": "#F2E8CF",
                "palette": {},
            },
        ]

        all_defined_slugs = [p["slug"] for p in palettes]
        by_slug = {p["slug"]: p for p in palettes}
        palettes = [by_slug[slug] for slug in CURATED_CATALOG_SLUGS if slug in by_slug]
        missing_slugs = [slug for slug in CURATED_CATALOG_SLUGS if slug not in by_slug]
        if missing_slugs:
            self.stdout.write(
                self.style.WARNING(
                    f"Skipped missing curated slugs: {', '.join(missing_slugs)}"
                )
            )

        slugs = [p["slug"] for p in palettes]
        if reset:
            self.stdout.write("Deleting existing admin dashboard palettes...")
            ThemePack.objects.filter(slug__in=slugs).delete()
            ThemePack.objects.filter(slug__in=all_defined_slugs).exclude(
                slug__in=slugs
            ).delete()
            self.stdout.write(self.style.SUCCESS("  Deleted.\n"))

        created_count = 0
        updated_count = 0
        for definition in palettes:
            slug = definition.pop("slug")
            palette_json = definition.pop("palette")
            pack, created = ThemePack.objects.update_or_create(
                slug=slug,
                defaults={**definition, "palette": palette_json},
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"  + Created: {pack.name}"))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f"  ~ Updated: {pack.name}"))

        get_platform_site_settings_record(create=True)
        pgb, _ = PlatformGlobalBranding.objects.get_or_create(pk=1)
        if not pgb.admin_theme_pack_id:
            default_pack = ThemePack.objects.filter(slug="admin-academic-slate").first()
            if default_pack:
                pgb.admin_theme_pack = default_pack
                pgb.save()
                self.stdout.write(
                    self.style.SUCCESS(
                        f"\n  + Set default admin theme: {default_pack.name}"
                    )
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone: {created_count + updated_count} palettes ({created_count} created, {updated_count} updated)"
            )
        )
