# Generated by Django 5.2.10 on 2026-05-29 16:06

import apps.governance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_employment_school_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolassignment',
            name='role',
            field=models.CharField(choices=apps.governance.models._get_school_membership_role_choices, default='TEACHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='schoolcontextprofile',
            name='role',
            field=models.CharField(choices=apps.governance.models._get_school_membership_role_choices, default='ADMIN', max_length=20),
        ),
    ]
