# Generated by Django 5.2.10 on 2026-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_expand_role_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("LEADERSHIP", "Leadership"),
                    ("PRINCIPAL", "Principal"),
                    ("VICE_PRINCIPAL", "Vice Principal"),
                    ("DEAN", "Dean"),
                    ("CENSOR", "Censor"),
                    ("BURSAR", "Bursar"),
                    ("HOD", "Head of Department"),
                    ("TEACHER", "Teacher"),
                    ("IT_ADMIN", "IT Administrator"),
                    ("BOARDING_MANAGER", "Boarding Manager"),
                    ("PARENT", "Parent"),
                    ("STUDENT", "Student"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
