# Generated by Django 5.2.10 on 2026-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Administrator"),
                    ("ADMIN", "Administrator"),
                    ("LEADERSHIP", "Leadership"),
                    ("PRINCIPAL", "Principal"),
                    ("VICE_PRINCIPAL", "Vice Principal"),
                    ("DEAN", "Dean"),
                    ("CENSOR", "Censor"),
                    ("BURSAR", "Bursar"),
                    ("HOD", "Head of Department"),
                    ("DEPT_LEAD", "Department Lead"),
                    ("FINANCE_STAFF", "Finance Staff"),
                    ("ACADEMICS_STAFF", "Academics Staff"),
                    ("COMMS_STAFF", "Communications Staff"),
                    ("SECRETARY", "Secretary"),
                    ("EXECUTIVE_ASSISTANT", "Executive Assistant"),
                    ("VIRTUAL_ASSISTANT", "Virtual Assistant"),
                    ("TEACHER", "Teacher"),
                    ("IT_ADMIN", "IT Administrator"),
                    ("BOARDING_MANAGER", "Boarding Manager"),
                    ("PARENT", "Parent"),
                    ("STUDENT", "Student"),
                ],
                default="PARENT",
                max_length=20,
            ),
        ),
    ]
