# Generated by Django 5.2.10 on 2026-02-09 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_temporary_role_grant"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the delegation becomes active."
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="When the delegation is scheduled to end."
                    ),
                ),
                (
                    "extended_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, effective end is this date instead of end_date.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="When False, delegation is no longer in effect (e.g. revoked or returned early).",
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Which workflows this applies to: list of keys e.g. ["syllabus_approval", "grade_approval"] or empty for "all".',
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional: e.g. Annual leave, Training.",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this (delegator or admin for emergency override).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        help_text="User who will act on their behalf (e.g. Vice-Principal).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        help_text="User who is away (Principal, Dean, Teacher, etc.).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DelegationActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        help_text="e.g. syllabus_approved, grade_approved.",
                        max_length=100,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="Short description of the object (e.g. Physics Form 3).",
                        max_length=255,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acting_for",
                    models.ForeignKey(
                        help_text="The delegator on whose behalf the action was taken.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The delegate who performed the action.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: link to the affected object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="accounts.delegation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="delegation",
            index=models.Index(
                fields=["delegator", "is_active"], name="accounts_de_delegat_4263ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delegation",
            index=models.Index(
                fields=["delegate", "is_active"], name="accounts_de_delegat_5edc91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delegation",
            index=models.Index(
                fields=["end_date", "extended_end_date"],
                name="accounts_de_end_dat_929d86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="delegationactionlog",
            index=models.Index(
                fields=["acting_for", "created_at"],
                name="accounts_de_acting__790ab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="delegationactionlog",
            index=models.Index(
                fields=["delegation", "created_at"],
                name="accounts_de_delegat_4c0f97_idx",
            ),
        ),
    ]
