# Generated by Django 5.2.10 on 2026-03-18 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_add_logout_event_type"),
        ("siteconfig", "0159_add_workflow_dashboard_recommended_sectors"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederationSsoHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_summary",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federation_sso_health",
                        to="siteconfig.serviceintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federation SSO health",
                "verbose_name_plural": "Federation SSO health",
            },
        ),
    ]
