# Generated by Django 5.2.10 on 2026-05-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_resync_accessrole_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='', help_text="Per-user language preference. When set, overrides Accept-Language and the tenant default at login. Values mirror settings.LANGUAGES codes (e.g. 'en', 'es', 'pt-br', 'zh-hans'). Empty string = inherit.", max_length=16),
        ),
    ]
