# Generated by Django 5.2.10 on 2026-05-23 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_encrypt_legacy_hash_fields'),
        ('schools', '0057_school_primary_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('public_key_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('permission_bitmap', models.JSONField(blank=True, default=list)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_device_registration',
            },
        ),
        migrations.CreateModel(
            name='OfflineCapabilityToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('permission_bitmap', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_tokens', to='accounts.deviceregistration')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_capability_tokens', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_capability_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_offline_capability_token',
            },
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['school', 'revoked_at'], name='accounts_de_school__677d31_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.UniqueConstraint(fields=('school', 'user', 'device_id'), name='uniq_device_per_user_school'),
        ),
        migrations.AddIndex(
            model_name='offlinecapabilitytoken',
            index=models.Index(fields=['school', 'expires_at'], name='accounts_of_school__aa32b8_idx'),
        ),
    ]
