# Generated by Django 5.2.10 on 2026-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_security_posture_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_security_posture_review_at',
            field=models.DateTimeField(blank=True, help_text='Last quarterly security posture review completed by the user.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful password change.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_strength_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='zxcvbn score 0–4 when password was last set.', null=True),
        ),
    ]
