# Generated by Django 5.2.10 on 2026-05-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_rebac_tuples_offline_iam'),
        ('schools', '0062_school_institution_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('oidc', 'OIDC'), ('saml', 'SAML'), ('manual', 'Manual')], max_length=16)),
                ('provider', models.CharField(blank=True, default='', help_text="Slug of the upstream IdP (e.g. 'azure', 'google', 'okta').", max_length=64)),
                ('subject', models.CharField(blank=True, default='', help_text='Verified subject claim (OIDC `sub`, SAML NameID).', max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenant_bindings', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_binding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User tenant binding',
                'verbose_name_plural': 'User tenant bindings',
                'indexes': [models.Index(fields=['school', 'source'], name='accounts_us_school__8ce2a3_idx'), models.Index(fields=['provider', 'subject'], name='accounts_us_provide_f1593e_idx')],
            },
        ),
    ]
