# Generated by Django 5.2.10 on 2026-06-03 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_user_tenant_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownLoginContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_hash', models.CharField(db_index=True, help_text="sha256(ip + '|' + user_agent)[:16] — the dedupe key.", max_length=16)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='sha256(ip)[:12] — never the raw IP.', max_length=12)),
                ('ua_hash', models.CharField(blank=True, default='', help_text='sha256(user_agent)[:12] — never the raw UA string.', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_login_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Known login context',
                'verbose_name_plural': 'Known login contexts',
                'db_table': 'accounts_known_login_context',
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_kn_user_id_e3f11f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'context_hash'), name='accounts_known_login_ctx_uniq')],
            },
        ),
    ]
