# Generated by Django 5.2.10 on 2026-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_role_dpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed'), ('MFA_CHANGE', 'MFA changed'), ('PWD_RESET', 'Password reset'), ('DATA_EXPORT', 'Data export'), ('LOCKDOWN_TRIGGERED', 'Emergency lockdown'), ('SESSION_REVOKED', 'Sessions revoked'), ('OWNERSHIP_CHANGED', 'School ownership changed'), ('IMPOSSIBLE_TRAVEL', 'Impossible travel (login from distant location)')], max_length=40),
        ),
    ]
