# Generated by Django 5.2.10 on 2026-07-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_rls_policy_default_deny'),
        ('schools', '0076_alter_school_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantbinding',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='When a user is bound to multiple schools, which binding wins for automatic tenant selection at login. Exactly one per user (partial unique constraint).'),
        ),
        migrations.AlterField(
            model_name='usertenantbinding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_bindings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertenantbinding',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='uniq_tenant_binding_user_school'),
        ),
        migrations.AddConstraint(
            model_name='usertenantbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_tenant_binding_per_user'),
        ),
    ]
