# Generated by Django 5.2.10 on 2026-07-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_multi_tenant_binding'),
        ('schools', '0077_schoolmembership_suspended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='role_groups', to='accounts.accessrole')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_groups', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='uniq_role_group_code_per_school')],
            },
        ),
    ]
