# Generated by Django 5.2.14 on 2026-07-27 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_user_profile_setup_completed'),
        ('schools', '0081_rls_backfill_unenumerated_tenant_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolJoinCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('role', models.CharField(default='PARENT', max_length=32)),
                ('label', models.CharField(blank=True, default='', help_text="Admin note, e.g. 'Grade 7 parents' or 'New teachers 2026'.", max_length=120)),
                ('domain_allowlist', models.CharField(blank=True, default='', help_text="Comma-separated email domains (e.g. 'school.edu, staff.school.edu'). Empty = any email may redeem.", max_length=255)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum redemptions. Blank = unlimited.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blank = never expires.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_codes_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='schools.school')),
            ],
            options={
                'verbose_name': 'School join code',
                'verbose_name_plural': 'School join codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='accounts_jc_school_act_idx')],
            },
        ),
    ]
