# Generated by Django 5.2.14 on 2026-07-27 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_schooljoincode'),
        ('schools', '0081_rls_backfill_unenumerated_tenant_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMagicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login magic link',
                'verbose_name_plural': 'Login magic links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_ml_token_idx'), models.Index(fields=['user', 'created_at'], name='accounts_ml_user_ts_idx')],
            },
        ),
    ]
