# Generated by Django 5.2.10 on 2026-07-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_loginmagiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_setup_deferred_until',
            field=models.DateTimeField(blank=True, help_text="When set to a future time, a required user may defer MFA enrollment until then (a self- or admin-granted 'skip for now' window). Honored by RequireMFAMiddleware / post-login routing UNLESS the principal must always be strict (superuser / platform admin / active school owner). Cleared once MFA is enrolled or reset.", null=True),
        ),
    ]
