# A direct permission grant gets a tenant (2026-08-23).
#
# `User.feature_permissions` is a plain M2M with no school column, and
# `has_feature_permission` short-circuited on it BEFORE the school-scoped role
# and temporary-grant branches ran -- ignoring the `school` argument entirely.
# So a code granted on School A's RBAC console was held at School B by any
# account belonging to both, through the resolver behind every
# `require_permission` gate on the platform.
#
# This table records WHICH school a grant was issued for. Absence of a row means
# the historical platform-wide grant, so no data migration is needed and every
# existing row keeps the meaning it was written with; a tenant surface now writes
# a row naming its own school (`accounts.feature_permission_scope`).
#
# `schools.School` is a SHARED_APP, same as `accounts` -- this FK does not cross
# the tenancy boundary (AccessRole.school is the standing precedent).

# Generated by Django 5.2.14 on 2026-08-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_dpo_drops_bulk_data_export'),
        ('schools', '0084_alter_marketing_funnel_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='accounts.permission')),
                ('school', models.ForeignKey(blank=True, help_text='NULL means the grant applies platform-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permission_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'permission'], name='accounts_fe_user_id_809d27_idx')],
                'unique_together': {('user', 'permission', 'school')},
            },
        ),
    ]
