# Generated by Django 5.2.10 on 2026-03-06 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('community', 'Community'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='community', max_length=24)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('inactive', 'Inactive')], default='lead', max_length=24)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='schools.school')),
            ],
            options={
                'verbose_name': 'Event sponsor',
                'verbose_name_plural': 'Event sponsors',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_venues', to='schools.school')),
            ],
            options={
                'verbose_name': 'Event venue',
                'verbose_name_plural': 'Event venues',
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organizer_name', models.CharField(blank=True, max_length=160)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('ticketing_enabled', models.BooleanField(default=False)),
                ('sponsorship_enabled', models.BooleanField(default=False)),
                ('fundraising_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_events', to='schools.school')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='school_events.eventvenue')),
            ],
            options={
                'verbose_name': 'School event',
                'verbose_name_plural': 'School events',
                'ordering': ['start_at', 'title'],
                'unique_together': {('school', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EventTicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='school_events.schoolevent')),
            ],
            options={
                'verbose_name': 'Event ticket tier',
                'verbose_name_plural': 'Event ticket tiers',
                'ordering': ['price', 'name'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('checked_in', 'Checked in')], default='reserved', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('ticket_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='school_events.eventtickettier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='school_events.schoolevent')),
            ],
            options={
                'verbose_name': 'Event registration',
                'verbose_name_plural': 'Event registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSponsorCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='pledged', max_length=20)),
                ('pledged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='school_events.eventsponsor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_commitments', to='school_events.schoolevent')),
            ],
            options={
                'verbose_name': 'Event sponsor commitment',
                'verbose_name_plural': 'Event sponsor commitments',
                'ordering': ['-pledged_amount', 'sponsor__name'],
                'unique_together': {('event', 'sponsor')},
            },
        ),
    ]
