# Generated by Django 5.2.10 on 2026-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/students/"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/teachers/"
            ),
        ),
    ]
