# Generated by Django 5.2.10 on 2026-01-18 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("people", "0002_studentprofile_profile_photo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="pay_grade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("MTN_MOMO", "MTN Mobile Money"),
                    ("ORANGE_MOMO", "Orange Money"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHECK", "Check"),
                    ("CASH", "Cash"),
                ],
                default="BANK_TRANSFER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="position_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="people.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="salary_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="salary_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PHONE", "Phone Call"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("receives_email", models.BooleanField(default=True)),
                ("receives_sms", models.BooleanField(default=False)),
                ("receives_whatsapp", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
