# Generated by Django 5.2.10 on 2026-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_teacherprofile_department_teacherprofile_pay_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentguardian",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="preferred_contact",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("WHATSAPP", "WhatsApp"),
                    ("PHONE", "Phone Call"),
                ],
                default="EMAIL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="receives_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="receives_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="receives_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ParentProfile",
        ),
    ]
