# Generated by Django 5.2.10 on 2026-01-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentguardian',
            name='people_guard_user_results_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentguardian',
            name='people_guard_user_finance_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='people_student_classroom_year_idx',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this student record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - preserves grade history when student leaves', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this student record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
