# Generated by Django 5.2.10 on 2026-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_add_exam_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
