# Generated by Django 5.2.10 on 2026-01-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_scheduleentry_room_and_more'),
        ('people', '0014_teacherprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.classroom'),
        ),
    ]
