# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0019_merge_people_leaf_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="uses_transport",
            field=models.BooleanField(
                default=False,
                help_text="Student uses school bus/transport; transport fee will be added to fee invoices when the plan includes a Transport fee item.",
            ),
        ),
    ]
