# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0023_add_badge_scan_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
