# Generated by Django 5.2.10 on 2026-02-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_studentprofile_updated_at'),
        ('people', '0026_enable_rls_postgresql'),
    ]

    operations = [
    ]
