# Generated by Django 5.2.10 on 2026-02-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0028_merge_people_conflicting_leaves"),
        ("schools", "0011_school_is_frozen_frozen_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Asthma, Early Bird, Scholarship", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MED", "Medical"),
                            ("FIN", "Financial"),
                            ("ACA", "Academic"),
                            ("GEN", "General"),
                        ],
                        default="GEN",
                        max_length=3,
                    ),
                ),
                ("color_hex", models.CharField(default="#3498db", max_length=7)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Metadata for the AI Nuance Engine"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Only users with Medical or Admin permissions can see this tag on students.",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="When this tag is added to a student, a notification or support workflow can be triggered.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_tags",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Information tag",
                "verbose_name_plural": "Information tags",
                "ordering": ["school", "sort_order", "name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="School-defined information tags for nuance, discounts, and workflows.",
                related_name="students",
                to="people.informationtag",
            ),
        ),
    ]
