# Generated by Django 5.2.10 on 2026-03-04 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0035_employer_profile_transcript_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=128)),
                ("record_id", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "INSERT"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=16,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("request_meta", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log",
                "db_table": "audit_log",
                "ordering": ["-changed_at"],
            },
        ),
    ]
