# Generated by Django 5.2.10 on 2026-03-06 17:19

from django.db import migrations, models
from django.utils import timezone


def _people_tenant_upload_to(subpath):
    """Tenant-prefixed upload_to for models with school_id (Section 25.3).

    Inlined from ``apps.people.models._people_tenant_upload_to`` for migration
    historical-state safety.
    """

    def upload_to(instance, filename):
        school_id = getattr(instance, "school_id", None) or (
            getattr(getattr(instance, "school", None), "pk", None)
            if getattr(instance, "school", None)
            else None
        )
        if school_id is None:
            return f"tenant_uploads/people/{subpath}/{filename}"
        return f"tenants/{school_id}/people/{subpath}/{filename}"

    return upload_to


def _passport_doc_upload_to(instance, filename):
    """Tenant-scoped path for PassportDocument (Section 25.3).

    Inlined from ``apps.people.models._passport_doc_upload_to`` for migration
    historical-state safety.
    """
    school_id = getattr(instance, "verified_by_school_id", None)
    now = timezone.now()
    subpath = f"people/passport_docs/{now:%Y/%m}"
    if school_id is None:
        return f"tenant_uploads/{subpath}/{filename}"
    return f"tenants/{school_id}/{subpath}/{filename}"


def tenant_upload_to_student_profile_photo(instance, filename):
    """Serializable upload_to for StudentProfile.profile_photo (Section 25.3).

    Inlined from ``apps.people.models.tenant_upload_to_student_profile_photo`` for
    migration historical-state safety.
    """
    return _people_tenant_upload_to("profiles/students")(instance, filename)


def tenant_upload_to_teacher_profile_photo(instance, filename):
    """Serializable upload_to for TeacherProfile.profile_photo (Section 25.3).

    Inlined from ``apps.people.models.tenant_upload_to_teacher_profile_photo`` for
    migration historical-state safety.
    """
    return _people_tenant_upload_to("profiles/teachers")(instance, filename)


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0038_rls_policy_default_deny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passportdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=_passport_doc_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=tenant_upload_to_student_profile_photo,
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=tenant_upload_to_teacher_profile_photo,
            ),
        ),
    ]
