# Generated by Django 5.2.10 on 2026-04-27 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_fix_audit_trigger_changed_by_id_column'),
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPassportMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consent_status', models.CharField(choices=[('private', 'Private'), ('shared_with_school', 'Shared with school'), ('revoked', 'Revoked')], db_index=True, default='private', max_length=32)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='people.studentpassport')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_passport_memberships', to='schools.school')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_memberships', to='people.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'student_profile'], name='people_stud_school__5ef624_idx'), models.Index(fields=['passport', 'school'], name='people_stud_passpor_e64cd0_idx')],
                'unique_together': {('passport', 'school', 'student_profile')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptVaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=64)),
                ('artifact_ref', models.CharField(blank=True, help_text='Storage path, external document id, or opaque reference.', max_length=512)),
                ('verification_hash', models.CharField(blank=True, max_length=128)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('access_status', models.CharField(choices=[('private', 'Private'), ('shared_with_school', 'Shared with school'), ('revoked', 'Revoked')], db_index=True, default='private', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuing_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_transcript_vault_items', to='schools.school')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to='people.studentpassport')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_vault_items', to='people.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['passport', 'access_status'], name='people_tran_passpor_ea0ba9_idx'), models.Index(fields=['student_profile', 'issuing_school'], name='people_tran_student_a027f8_idx')],
            },
        ),
    ]
