# Generated by Django 5.2.10 on 2026-05-14 20:16

import apps.people.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_specialeducationplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='specialeducationplan',
            new_name='people_spec_school__c22102_idx',
            old_name='people_sep_school_status_idx',
        ),
        migrations.RenameIndex(
            model_name='specialeducationplan',
            new_name='people_spec_student_5e3675_idx',
            old_name='people_sep_student_eff_idx',
        ),
        migrations.RenameIndex(
            model_name='specialeducationplan',
            new_name='people_spec_next_re_543946_idx',
            old_name='people_sep_next_review_idx',
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='accommodations',
            field=models.JSONField(blank=True, default=list, help_text='Free-text accommodations list (extra time, scribe, etc.).'),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='case_manager',
            field=models.ForeignKey(blank=True, help_text='Special-ed coordinator or counselor owning this plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_education_plans_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='goals',
            field=models.TextField(blank=True, help_text='Measurable annual goals — kept brief; full plan PDF attached separately.'),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='next_review_at',
            field=models.DateField(blank=True, help_text='Statutory review deadline; surfaces in SLA queues.', null=True),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='plan_document',
            field=models.FileField(blank=True, help_text='Signed IEP / 504 PDF (FERPA-sensitive).', null=True, upload_to=apps.people.models.tenant_upload_to_special_education_plan),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='primary_disability',
            field=models.CharField(blank=True, help_text='IDEA primary disability category, where applicable.', max_length=128),
        ),
    ]
