# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_rename_people_sep_school_status_idx_people_spec_school__c22102_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.people.models._passport_doc_upload_to),
        ),
        migrations.AlterField(
            model_name='specialeducationplan',
            name='plan_document',
            field=models.FileField(blank=True, help_text='Signed IEP / 504 PDF (FERPA-sensitive).', null=True, upload_to=apps.people.models.tenant_upload_to_special_education_plan),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.people.models.tenant_upload_to_student_profile_photo),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.people.models.tenant_upload_to_teacher_profile_photo),
        ),
    ]
