# Generated by Django 5.2.10 on 2026-05-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_studentnote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentnote',
            new_name='people_stud_school__dacb55_idx',
            old_name='people_stud_school__8f0a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='studentnote',
            new_name='people_stud_student_f21daa_idx',
            old_name='people_stud_student_4c1e8a_idx',
        ),
    ]
