# Generated by Django 5.2.10 on 2026-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0055_staff_compliance_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
