# Generated by Django 5.2.10 on 2026-07-03 15:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0061_transfercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('RETURNING', 'Returning'), ('PROBATION', 'Probation'), ('ALUMNI', 'Alumni'), ('TRANSFERRED', 'Transferred')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransferConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=256)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('token_sha256', models.CharField(help_text='sha256 of the raw URL-safe token. Raw token NEVER persisted; returned exactly once from mint().', max_length=64, unique=True)),
                ('token_issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('token_first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('consented', 'Consented'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('consent_text_version', models.CharField(max_length=16)),
                ('consent_text_sha256', models.CharField(help_text='sha256 of the rendered consent text — immutable proof of what was agreed.', max_length=64)),
                ('ip_address_decision', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_decision', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='people.transfercase')),
            ],
            options={
                'ordering': ['-token_issued_at'],
                'indexes': [models.Index(fields=['case', 'decision'], name='people_tran_case_id_705e82_idx'), models.Index(fields=['expires_at'], name='people_tran_expires_c673b4_idx')],
            },
        ),
    ]
