# Generated by Django 5.2.10 on 2026-07-03 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_discipline_rls_postgresql'),
        ('people', '0062_alter_studentprofile_status_transferconsent'),
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('student_code', ''), _negated=True), fields=('school', 'student_code'), name='uniq_studentprofile_school_student_code'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('admission_number', ''), _negated=True), fields=('school', 'admission_number'), name='uniq_studentprofile_school_admission_no'),
        ),
    ]
