# Generated by Django 5.2.10 on 2026-07-03 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0063_studentprofile_identifiers_per_school'),
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='people.studentprofile'),
        ),
        migrations.CreateModel(
            name='RecordMergeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('guardian', 'Guardian link')], db_index=True, default='student', max_length=16)),
                ('primary_pk', models.CharField(max_length=64)),
                ('secondary_pk', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('approved', 'Approved'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('preview', models.JSONField(blank=True, default=dict, help_text='Re-point plan: per model.field row counts at preview time.')),
                ('collisions', models.JSONField(blank=True, default=list, help_text='Quarantined unique-constraint hits from apply: rows left on the retired secondary for operator review — never deleted.')),
                ('history', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_operations_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_operations_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_merge_operations', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='people_reco_school__5bc98a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('primary_pk', models.F('secondary_pk')), _negated=True), name='record_merge_primary_neq_secondary')],
            },
        ),
    ]
