# Generated by Django 5.2.10 on 2026-07-03 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0064_recordmergeoperation_and_merged_into'),
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTransferBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('merge', 'School merge (absorb source into target)'), ('split', 'School split (cohort into a new tenant)')], max_length=10)),
                ('consent_mode', models.CharField(choices=[('institutional', 'Institutional authority (dual-approved)'), ('per_guardian', 'Per-guardian consent tokens')], default='institutional', max_length=20)),
                ('consent_basis', models.TextField(blank=True, default='', help_text='Institutional authority for the move (board resolution, ministry order…). Required before approval in institutional mode; journaled onto every case.')),
                ('cohort', models.JSONField(blank=True, default=dict, help_text='Selection filter: {"classroom_ids": […], "student_pks": […]}. Empty = every active student (merge).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('approved', 'Approved (dual)'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_issues', 'Completed with issues'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('ledger', models.JSONField(blank=True, default=dict, help_text='Per-case attempt ledger: {case_id: {attempts, last_error, at}}.')),
                ('history', models.JSONField(blank=True, default=list)),
                ('wind_down', models.JSONField(blank=True, default=dict, help_text='Merge wind-down receipt: {export_zip, deactivated, at, by}.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_batches_approved_primary', to=settings.AUTH_USER_MODEL)),
                ('approved_by_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_batches_approved_secondary', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_batches_created', to=settings.AUTH_USER_MODEL)),
                ('source_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_transfer_batches_out', to='schools.school')),
                ('target_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_transfer_batches_in', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transfercase',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='School merge/split batch that fanned this case out (Wave D).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='people.schooltransferbatch'),
        ),
        migrations.AddIndex(
            model_name='schooltransferbatch',
            index=models.Index(fields=['status', 'kind'], name='people_scho_status_9b7dc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='schooltransferbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source_school', models.F('target_school')), _negated=True), name='school_batch_source_neq_target'),
        ),
    ]
