# Generated by Django 5.2.10 on 2026-07-03 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_schooltransferbatch_and_case_batch_fk'),
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfercase',
            index=models.Index(fields=['batch', 'status'], name='people_tran_batch_i_fff9f3_idx'),
        ),
    ]
