# Generated by Django 5.2.10 on 2026-07-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0067_ensure_school_fk_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_guardian_duplicates', to='people.studentguardian'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_teacher_duplicates', to='people.teacherprofile'),
        ),
    ]
