# Generated by Django 5.2.10 on 2026-07-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0069_alter_specialty_options_alter_room_bookable_resource'),
        ('people', '0068_studentguardian_is_active_and_more'),
        ('schools', '0081_rls_backfill_unenumerated_tenant_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('PROMOTED', 'Promoted'), ('RETAINED', 'Retained (repeating the year)'), ('CONDITIONALLY_PROMOTED', 'Conditionally promoted'), ('TRANSFERRED_OUT', 'Transferred out'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='', help_text='How the year ended. Blank while the year is still running.', max_length=32)),
                ('outcome_reason', models.CharField(blank=True, default='', help_text="Free text for the school's own wording or the condition attached to a conditional promotion. Never parsed.", max_length=255)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('decision_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classroom')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_enrollments', to='people.enrollment')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.specialty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='people.studentprofile')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['school', 'academic_year'], name='people_enro_school__7de9c2_idx'), models.Index(fields=['student', 'academic_year'], name='people_enro_student_59a860_idx'), models.Index(fields=['classroom', 'status'], name='people_enro_classro_4a856d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='people_enrollment_one_active_per_student')],
            },
        ),
    ]
