# Generated by Django 5.2.14 on 2026-08-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0085_classroom_specialty_code_per_school_unique'),
        ('people', '0072_heal_merge_tombstone_columns'),
        ('schools', '0087_alter_school_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_code', models.CharField(max_length=32)),
                ('next_seq', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sequences', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sequences', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'academic_year'], name='people_admi_school__0bdb52_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'node_code'), name='uniq_admission_sequence_per_school_year_node')],
            },
        ),
    ]
