# Generated by Django 5.2.14 on 2026-09-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0087_rls_force_and_null_arm_postgresql'),
        ('people', '0080_enrollment_expelled_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.specialty'),
        ),
    ]
