# Generated by Django 5.2.10 on 2026-02-13 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0002_enable_rls_postgresql"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LMS", "LMS"),
                            ("PAYMENT", "Payment"),
                            ("ATTENDANCE", "Attendance"),
                            ("LIBRARY", "Library"),
                            ("AI", "AI"),
                            ("SIS", "SIS"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Master kill switch: when False, requests to this API are blocked.",
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, default="v1.0", max_length=10),
                ),
                (
                    "allowed_scopes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"read_only": true, "write": false, "pii_access": false}',
                    ),
                ),
                (
                    "rate_limit_per_min",
                    models.PositiveIntegerField(blank=True, default=60),
                ),
                (
                    "ip_whitelist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed client IPs; empty = no restriction.",
                    ),
                ),
                ("secret_key_hash", models.TextField(blank=True)),
                ("last_call_at", models.DateTimeField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                (
                    "pii_masking",
                    models.BooleanField(
                        default=False,
                        help_text="When True, mask student names/IDs in responses for this integration.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_services",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Service",
                "verbose_name_plural": "API Services",
                "ordering": ["category", "service_name"],
            },
        ),
        migrations.CreateModel(
            name="APIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("key_rotated", "Key rotated"),
                            ("limit_changed", "Limit changed"),
                            ("scope_changed", "Scope changed"),
                            ("ip_updated", "IP list updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "api_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="apicenter.apiservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Audit Log",
                "verbose_name_plural": "API Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
