"""
Privacy utilities: PII export and anonymization for right-to-be-forgotten requests.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from django.conf import settings
from django.db import transaction

from apps.accounts.models import User
from apps.compliance.models_audit import (
    AuditLog,
    AccessLog,
    UserActivitySession,
    ComplianceReport,
)


EXPORT_DIR = Path(settings.BASE_DIR) / "logs" / "privacy"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def export_user_data(user: User) -> Path:
    """Export a user's PII-related records to a JSON file and return the path."""
    payload = {
        "user": {
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "role": user.role,
            "is_active": user.is_active,
        },
        "teacher_profile": None,
        "audit_logs": [],
        "access_logs": [],
        "sessions": [],
    }

    teacher = getattr(user, "teacher_profile", None)
    if teacher:
        payload["teacher_profile"] = {
            "staff_id": teacher.staff_id,
            "phone": teacher.phone,
            "department": teacher.department_id,
            "position_title": teacher.position_title,
        }

    payload["audit_logs"] = list(
        AuditLog.objects.filter(user=user)
        .order_by("-timestamp")
        .values(
            "id",
            "action",
            "model_name",
            "object_id",
            "object_repr",
            "timestamp",
            "ip_address",
            "reason",
        )
    )

    payload["access_logs"] = list(
        AccessLog.objects.filter(user=user)
        .order_by("-timestamp")
        .values(
            "id",
            "access_type",
            "resource",
            "status",
            "timestamp",
            "ip_address",
            "request_method",
        )
    )

    payload["sessions"] = list(
        UserActivitySession.objects.filter(user=user)
        .order_by("-login_timestamp")
        .values(
            "id",
            "session_key",
            "login_timestamp",
            "logout_timestamp",
            "ip_address",
            "is_suspicious",
        )
    )

    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    export_path = EXPORT_DIR / f"privacy_export_user_{user.id}_{timestamp}.json"
    export_path.write_text(json.dumps(payload, default=str, indent=2), encoding="utf-8")
    return export_path


@transaction.atomic
def anonymize_user(user: User, delete_sessions: bool = True) -> None:
    """Anonymize PII for a user and related compliance artifacts."""
    anon_suffix = f"anon-{user.id}"

    # User core fields
    user.first_name = ""
    user.last_name = ""
    user.email = "anonymized@example.com"
    user.username = anon_suffix
    user.profile_photo = None
    user.save(
        update_fields=["first_name", "last_name", "email", "username", "profile_photo"]
    )

    # Teacher profile PII
    teacher = getattr(user, "teacher_profile", None)
    if teacher:
        teacher.staff_id = ""
        teacher.phone = ""
        teacher.position_title = ""
        teacher.pay_grade = ""
        teacher.salary_amount = None
        teacher.salary_cap = None
        teacher.paystub_notes = ""
        teacher.profile_photo = None
        teacher.save()

    # Access logs: strip IPs
    AccessLog.objects.filter(user=user).update(ip_address=None)

    # Audit logs: detach user reference and strip metadata
    AuditLog.objects.filter(user=user).update(
        user=None,
        ip_address=None,
        user_agent="",
        object_repr="",
        reason="Anonymized",
    )

    # Sessions: delete or detach
    if delete_sessions:
        UserActivitySession.objects.filter(user=user).delete()
    else:
        UserActivitySession.objects.filter(user=user).update(
            user=None, ip_address=None, notes="Anonymized"
        )

    # Compliance reports metadata (if any generated by user)
    ComplianceReport.objects.filter(generated_by=user).update(generated_by=None)


# Plan IV: Per-region PII masking (GDPR/FERPA/NDPR)
COMPLIANCE_REGIONS = ("GDPR", "FERPA", "NDPR", "")


def mask_pii_for_region(value: str | None, region: str) -> str:
    """
    Mask PII for display/logging according to region. Use for compliance_region-aware masking.
    - GDPR/NDPR: mask email and phone; show last 2 of name.
    - FERPA: mask email; allow last 4 of phone.
    - Empty/unknown: return redacted placeholder.
    """
    if not value or not str(value).strip():
        return ""
    s = str(value).strip()
    region_upper = (region or "").upper()
    if region_upper == "GDPR" or region_upper == "NDPR":
        if "@" in s and "." in s:
            parts = s.split("@")
            return (parts[0][:1] + "***@" + parts[-1]) if len(parts) == 2 else "***"
        if len(s) >= 4 and s.replace("+", "").replace(" ", "").isdigit():
            return "***" + s[-2:]
        if len(s) <= 3:
            return "**"
        return s[:1] + "***" + s[-1:] if len(s) > 2 else "**"
    if region_upper == "FERPA":
        if "@" in s and "." in s:
            parts = s.split("@")
            return (parts[0][:2] + "***@" + parts[-1]) if len(parts) == 2 else "***"
        if len(s) >= 4 and s.replace("+", "").replace(" ", "").isdigit():
            return "****" + s[-4:]
        return s[:2] + "***" if len(s) > 3 else "***"
    return "***"
