# Generated by Django 5.2.10 on 2026-03-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('schools', '0026_rls_policy_default_deny'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMachineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g. admission, invoice, discipline_case.', max_length=80)),
                ('states', models.JSONField(default=list, help_text='List of state codes, e.g. ["draft", "submitted", "closed"].')),
                ('transitions', models.JSONField(default=list, help_text='List of {from_state, to_state, event}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'State Machine Definition',
                'verbose_name_plural': 'State Machine Definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EntityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('current_state', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_states', to='metadata.statemachinedefinition')),
            ],
            options={
                'verbose_name': 'Entity State',
                'verbose_name_plural': 'Entity States',
                'ordering': ['entity_type', 'entity_id'],
                'unique_together': {('definition', 'school', 'entity_type', 'entity_id')},
            },
        ),
    ]
