# Generated by Django 5.2.10 on 2026-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_add_entity_field_catalog_and_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMutationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, help_text='User ID if applicable.', null=True)),
                ('target_type', models.CharField(help_text='Config type (e.g. SiteSettings, RegionConfig, blueprint, policy_bundle).', max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('region', 'Region'), ('blueprint', 'Blueprint'), ('plan', 'Plan'), ('tenant', 'Tenant'), ('sandbox', 'Sandbox')], default='tenant', max_length=20)),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('impact_summary', models.CharField(blank=True, max_length=500)),
                ('rollback_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Config Mutation Audit Log',
                'verbose_name_plural': 'Config Mutation Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessGlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Business/education term (e.g. Report Card, Transcript, Fee).', max_length=160)),
                ('definition', models.TextField(blank=True)),
                ('entity_code', models.CharField(blank=True, db_index=True, help_text='Optional link to EntityCatalogEntry.code.', max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Glossary Entry',
                'verbose_name_plural': 'Business Glossary Entries',
                'ordering': ['term', 'locale'],
                'unique_together': {('term', 'locale')},
            },
        ),
    ]
