# Generated by Django 5.2.10 on 2026-03-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0004_add_glossary_and_config_audit"),
        ("schools", "0034_remove_biometricdevice_school_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. dashboard_principal_home, form_student_edit.",
                        max_length=80,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("region", "Region"),
                            ("blueprint", "Blueprint"),
                            ("plan", "Plan"),
                            ("tenant", "Tenant"),
                            ("sandbox", "Sandbox"),
                        ],
                        db_index=True,
                        default="tenant",
                        max_length=20,
                    ),
                ),
                (
                    "layout_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structure: sections, widget_keys, order, options (metadata-driven UI).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout Definition",
                "verbose_name_plural": "Layout Definitions",
                "ordering": ["code", "scope"],
            },
        ),
    ]
