# Generated by Django 5.2.10 on 2026-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_add_layout_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(help_text='Metadata type (e.g. EntityCatalogEntry, PolicyBundle).', max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('region', 'Region'), ('blueprint', 'Blueprint'), ('plan', 'Plan'), ('tenant', 'Tenant'), ('sandbox', 'Sandbox')], db_index=True, default='tenant', max_length=20)),
                ('old_value_summary', models.JSONField(blank=True, default=dict)),
                ('new_value_summary', models.JSONField(blank=True, default=dict)),
                ('tenants_affected', models.JSONField(blank=True, default=list, help_text='List of tenant/school IDs if scope allows.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metadata Change Log',
                'verbose_name_plural': 'Metadata Change Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
