# Generated by Django 5.2.10 on 2026-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_add_entity_catalog_pack_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfielddefinition',
            name='required',
            field=models.BooleanField(default=False, help_text='When True, runtime may treat the field as mandatory (aligned with siteconfig EAV).'),
        ),
    ]
