# Generated by Django 5.2.10 on 2026-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_dynamicfielddefinition_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmutationauditlog',
            name='target_type',
            field=models.CharField(help_text='Config type (e.g. platform tenant settings row, RegionConfig, blueprint, policy_bundle).', max_length=80),
        ),
    ]
