# Generated by Django 5.2.10 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_configmutationauditlog_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcatalogentry',
            name='compliance_tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags like ['pii','ferpa','gdpr_special'] consumed by DLP rules."),
        ),
        migrations.AddField(
            model_name='fieldcatalogentry',
            name='dlp_redaction_strategy',
            field=models.CharField(default='null', help_text="One of 'null', 'mask', 'hash', 'tokenize'. How to redact when access is denied.", max_length=20),
        ),
        migrations.AddField(
            model_name='fieldcatalogentry',
            name='sensitivity_tier',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential'), ('secret', 'Secret / regulated')], db_index=True, default='internal', help_text='Move 3: drives field-level RLS at query/serializer/export time.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fieldcatalogentry',
            index=models.Index(fields=['sensitivity_tier'], name='md_fc_sens_idx'),
        ),
    ]
