# Generated by Django 5.2.10 on 2026-07-02 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_rls_policy_default_deny'),
        ('schools', '0077_schoolmembership_suspended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedValueLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_model', models.CharField(help_text='Dotted label of the output row, e.g. "reports.ReportCard".', max_length=100)),
                ('output_pk', models.CharField(max_length=64)),
                ('computation', models.CharField(db_index=True, help_text='Stable computation name, e.g. "report_card.term" / "analytics.nightly_risk".', max_length=100)),
                ('computation_version', models.CharField(blank=True, default='', max_length=64)),
                ('granularity', models.CharField(choices=[('row', 'row'), ('scope', 'scope')], default='row', max_length=8)),
                ('inputs', models.JSONField(blank=True, default=list, help_text='row granularity: [{model, pk}, …]; scope granularity: [{model, scope: {…}}, …]. Capped; truncation is flagged.')),
                ('inputs_truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_value_lineage', to='schools.school')),
            ],
            options={
                'verbose_name': 'Derived value lineage',
                'verbose_name_plural': 'Derived value lineage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'output_model', 'output_pk'], name='metadata_de_school__c34903_idx'), models.Index(fields=['computation', 'created_at'], name='metadata_de_computa_7a722f_idx')],
            },
        ),
    ]
