# Generated by Django 5.2.10 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesyncqueue',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Incremented when the client retries a failed sync_batch row.'),
        ),
    ]
