# -*- coding: utf-8 -*-
"""
Additional ``super:admin_bridge`` entries for every model registered on
``platform_admin_site`` that is not covered by the core registry (automation,
billing, brand_experience tables, ``marketplace`` app native admins, observability,
policies, ``registries`` app, ``schools`` fleet tables, ``global_registries`` weather).

Merged into ``super_admin_bridge_registry`` at import time.
"""

from __future__ import annotations

from django.utils.translation import gettext_lazy as _

_DESC = _(
    "Platform backoffice changelist; prefer control plane / super-first flows where available."
)

PLATFORM_ADMIN_SURFACE_BRIDGE_ORDER: list[str] = [
    "accounts_user",
    "automation_automationapprovalqueue",
    "automation_automationexecutionlog",
    "automation_migrationplaybook",
    "automation_migrationprofile",
    "automation_migrationquarantinerecord",
    "billing_billingaccount",
    "billing_billingprocessorsyncevent",
    "billing_platformbillingprocessorconfig",
    "billing_platformledgerentry",
    "billing_quote",
    "billing_revenuesharepayout",
    "billing_tenantsubscription",
    "billing_usagemeter",
    "brand_experience_brandprofile",
    "brand_experience_brandsettings",
    "brand_experience_designtemplate",
    "brand_experience_themepack",
    "global_registries_weatherlocation",
    "marketplace_appauditlog",
    "marketplace_appbillingledger",
    "marketplace_appinstallation",
    "marketplace_appscope",
    "marketplace_appversioncompat",
    "marketplace_capabilityregistry",
    "marketplace_marketplaceapp",
    "marketplace_marketplacelisting",
    "marketplace_marketplacereview",
    "marketplace_publisherorganization",
    "marketplace_scopegrant",
    "observability_anomalydetection",
    "observability_healthcheckalert",
    "observability_performancetrace",
    "observability_systemhealthmetric",
    "policies_blueprintcompatibilityrule",
    "policies_countryprofile",
    "policies_policycompatibilityrule",
    "registries_academicterminologyregistry",
    "registries_calendarsystemregistry",
    "registries_countryregistry",
    "registries_currencyregistry",
    "registries_documenttyperegistry",
    "registries_educationlevelregistry",
    "registries_educationsystemtyperegistry",
    "registries_feecategoryregistry",
    "registries_gradescaleregistry",
    "registries_institutiontyperegistry",
    "registries_localeregistry",
    "registries_subdivisionregistry",
    "registries_timezoneregistry",
    "schools_school",
    "schools_schoolmembership",
    "schools_schoolprovisioningevent",
    "schools_tenantapiusage",
    "schools_tenantquotalimit",
    "metadata_configmutationauditlog",
    "metadata_dynamicfielddefinition",
    "metadata_dynamicfieldvalue",
    "metadata_entitycatalogentry",
    "platform_runtime_platformintegrationwebhookevent",
    "platform_runtime_platformoperatorcommandcenterlink",
    "platform_runtime_platformoperatormigrationcloudlink",
    "platform_runtime_platformoperatororchestrationworkbenchlink",
    "platform_runtime_platformoperatorphaseblink",
    "platform_runtime_platformoperatorplatformhublink",
    "platform_runtime_platformoperatorplaybooklink",
    "platform_runtime_platformoperatorsuperanalyticsoverviewlink",
    "platform_runtime_platformoperatorsuperdashboardlink",
    "platform_runtime_platformoperatorsuperschoolslistlink",
    "platform_runtime_platformoperatorsupportdashboardlink",
    "platform_runtime_platformoperatortenanthealthlink",
    "platform_runtime_platformoperatortruthhublink",
    "platform_runtime_platformoperatorworkflowsimulatorlink",
    "platform_runtime_platformreportplatformskudefault",
    "siteconfig_globalsupportticket",
    "siteconfig_globalsupportticketreply",
    "siteconfig_globalsupportticketwebhookendpoint",
]

PLATFORM_ADMIN_SURFACE_BRIDGES: dict[str, dict[str, object]] = {
    "accounts_user": {
        "admin_url": "admin:accounts_user_changelist",
        "label": _("Users (platform admin)"),
        "description": _(
            "Set Role to Super Administrator (SUPERADMIN) for full manager-host control plane and API Center."
        ),
        "icon": "bi-person-badge",
        "show_in_nav": True,
        "nav_id": "cp_admin_bridge_accounts_users",
        "nav_label": _("Users (admin)"),
        "nav_icon": "bi-person-badge",
    },
    "automation_automationapprovalqueue": {
        "admin_url": "admin:automation_automationapprovalqueue_changelist",
        "label": _("Automation approval queue (platform admin)"),
        "description": _DESC,
        "icon": "bi-cpu",
        "show_in_nav": False,
    },
    "automation_automationexecutionlog": {
        "admin_url": "admin:automation_automationexecutionlog_changelist",
        "label": _("Automation execution log (platform admin)"),
        "description": _DESC,
        "icon": "bi-lightning",
        "show_in_nav": False,
    },
    "automation_migrationplaybook": {
        "admin_url": "admin:automation_migrationplaybook_changelist",
        "label": _("Migration playbook (platform admin)"),
        "description": _DESC,
        "icon": "bi-journal-code",
        "show_in_nav": False,
    },
    "automation_migrationprofile": {
        "admin_url": "admin:automation_migrationprofile_changelist",
        "label": _("Migration profile (platform admin)"),
        "description": _DESC,
        "icon": "bi-hdd-network",
        "show_in_nav": False,
    },
    "automation_migrationquarantinerecord": {
        "admin_url": "admin:automation_migrationquarantinerecord_changelist",
        "label": _("Migration quarantine record (platform admin)"),
        "description": _DESC,
        "icon": "bi-shield-exclamation",
        "show_in_nav": False,
    },
    "billing_billingaccount": {
        "admin_url": "admin:billing_billingaccount_changelist",
        "label": _("Billing account (platform admin)"),
        "description": _DESC,
        "icon": "bi-credit-card",
        "show_in_nav": False,
    },
    "billing_billingprocessorsyncevent": {
        "admin_url": "admin:billing_billingprocessorsyncevent_changelist",
        "label": _("Billing processor sync event (platform admin)"),
        "description": _DESC,
        "icon": "bi-arrow-repeat",
        "show_in_nav": False,
    },
    "billing_platformbillingprocessorconfig": {
        "admin_url": "admin:billing_platformbillingprocessorconfig_changelist",
        "label": _("Platform billing processor config (platform admin)"),
        "description": _DESC,
        "icon": "bi-gear-wide",
        "show_in_nav": False,
    },
    "billing_platformledgerentry": {
        "admin_url": "admin:billing_platformledgerentry_changelist",
        "label": _("Platform ledger entry (platform admin)"),
        "description": _DESC,
        "icon": "bi-cash-stack",
        "show_in_nav": False,
    },
    "billing_quote": {
        "admin_url": "admin:billing_quote_changelist",
        "label": _("Quote (platform admin)"),
        "description": _DESC,
        "icon": "bi-receipt",
        "show_in_nav": False,
    },
    "billing_revenuesharepayout": {
        "admin_url": "admin:billing_revenuesharepayout_changelist",
        "label": _("Revenue share payout (platform admin)"),
        "description": _DESC,
        "icon": "bi-graph-up-arrow",
        "show_in_nav": False,
    },
    "billing_tenantsubscription": {
        "admin_url": "admin:billing_tenantsubscription_changelist",
        "label": _("Tenant subscription (platform admin)"),
        "description": _DESC,
        "icon": "bi-building",
        "show_in_nav": False,
    },
    "billing_usagemeter": {
        "admin_url": "admin:billing_usagemeter_changelist",
        "label": _("Usage meter (platform admin)"),
        "description": _DESC,
        "icon": "bi-speedometer",
        "show_in_nav": False,
    },
    "brand_experience_brandprofile": {
        "admin_url": "admin:brand_experience_brandprofile_changelist",
        "label": _("Brand profile (platform admin)"),
        "description": _DESC,
        "icon": "bi-palette",
        "show_in_nav": False,
    },
    "brand_experience_brandsettings": {
        "admin_url": "admin:brand_experience_brandsettings_changelist",
        "label": _("Brand settings (platform admin)"),
        "description": _DESC,
        "icon": "bi-brush",
        "show_in_nav": False,
    },
    "brand_experience_designtemplate": {
        "admin_url": "admin:brand_experience_designtemplate_changelist",
        "label": _("Design template (platform admin)"),
        "description": _DESC,
        "icon": "bi-file-earmark-image",
        "show_in_nav": False,
    },
    "brand_experience_themepack": {
        "admin_url": "admin:brand_experience_themepack_changelist",
        "label": _("Theme pack (platform admin)"),
        "description": _DESC,
        "icon": "bi-paint-bucket",
        "show_in_nav": False,
    },
    "global_registries_weatherlocation": {
        "admin_url": "admin:global_registries_weatherlocation_changelist",
        "label": _("Weather location (platform admin)"),
        "description": _DESC,
        "icon": "bi-cloud-sun",
        "show_in_nav": False,
    },
    "marketplace_appauditlog": {
        "admin_url": "admin:marketplace_appauditlog_changelist",
        "label": _("Marketplace app audit log (native app)"),
        "description": _DESC,
        "icon": "bi-list-check",
        "show_in_nav": False,
    },
    "marketplace_appbillingledger": {
        "admin_url": "admin:marketplace_appbillingledger_changelist",
        "label": _("Marketplace app billing ledger (native app)"),
        "description": _DESC,
        "icon": "bi-wallet2",
        "show_in_nav": False,
    },
    "marketplace_appinstallation": {
        "admin_url": "admin:marketplace_appinstallation_changelist",
        "label": _("Marketplace app installation (native app)"),
        "description": _DESC,
        "icon": "bi-download",
        "show_in_nav": False,
    },
    "marketplace_appscope": {
        "admin_url": "admin:marketplace_appscope_changelist",
        "label": _("Marketplace app scope (native app)"),
        "description": _DESC,
        "icon": "bi-bounding-box",
        "show_in_nav": False,
    },
    "marketplace_appversioncompat": {
        "admin_url": "admin:marketplace_appversioncompat_changelist",
        "label": _("Marketplace app version compat (native app)"),
        "description": _DESC,
        "icon": "bi-patch-check",
        "show_in_nav": False,
    },
    "marketplace_capabilityregistry": {
        "admin_url": "admin:marketplace_capabilityregistry_changelist",
        "label": _("Marketplace capability registry (native app)"),
        "description": _DESC,
        "icon": "bi-grid-3x3",
        "show_in_nav": False,
    },
    "marketplace_marketplaceapp": {
        "admin_url": "admin:marketplace_marketplaceapp_changelist",
        "label": _("Marketplace app (native app)"),
        "description": _DESC,
        "icon": "bi-shop-window",
        "show_in_nav": False,
    },
    "marketplace_marketplacelisting": {
        "admin_url": "admin:marketplace_marketplacelisting_changelist",
        "label": _("Marketplace listing (native app)"),
        "description": _DESC,
        "icon": "bi-card-list",
        "show_in_nav": False,
    },
    "marketplace_marketplacereview": {
        "admin_url": "admin:marketplace_marketplacereview_changelist",
        "label": _("Marketplace review (native app)"),
        "description": _DESC,
        "icon": "bi-star",
        "show_in_nav": False,
    },
    "marketplace_publisherorganization": {
        "admin_url": "admin:marketplace_publisherorganization_changelist",
        "label": _("Publisher organization (native app)"),
        "description": _DESC,
        "icon": "bi-building-add",
        "show_in_nav": False,
    },
    "marketplace_scopegrant": {
        "admin_url": "admin:marketplace_scopegrant_changelist",
        "label": _("Scope grant (native app)"),
        "description": _DESC,
        "icon": "bi-key",
        "show_in_nav": False,
    },
    "observability_anomalydetection": {
        "admin_url": "admin:observability_anomalydetection_changelist",
        "label": _("Anomaly detection (platform admin)"),
        "description": _DESC,
        "icon": "bi-activity",
        "show_in_nav": False,
    },
    "observability_healthcheckalert": {
        "admin_url": "admin:observability_healthcheckalert_changelist",
        "label": _("Health check alert (platform admin)"),
        "description": _DESC,
        "icon": "bi-heart-pulse",
        "show_in_nav": False,
    },
    "observability_performancetrace": {
        "admin_url": "admin:observability_performancetrace_changelist",
        "label": _("Performance trace (platform admin)"),
        "description": _DESC,
        "icon": "bi-graph-down",
        "show_in_nav": False,
    },
    "observability_systemhealthmetric": {
        "admin_url": "admin:observability_systemhealthmetric_changelist",
        "label": _("System health metric (platform admin)"),
        "description": _DESC,
        "icon": "bi-speedometer2",
        "show_in_nav": False,
    },
    "policies_blueprintcompatibilityrule": {
        "admin_url": "admin:policies_blueprintcompatibilityrule_changelist",
        "label": _("Policies blueprint compatibility rule (platform admin)"),
        "description": _DESC,
        "icon": "bi-diagram-2",
        "show_in_nav": False,
    },
    "policies_countryprofile": {
        "admin_url": "admin:policies_countryprofile_changelist",
        "label": _("Country profile (platform admin)"),
        "description": _DESC,
        "icon": "bi-globe",
        "show_in_nav": False,
    },
    "policies_policycompatibilityrule": {
        "admin_url": "admin:policies_policycompatibilityrule_changelist",
        "label": _("Policy compatibility rule (platform admin)"),
        "description": _DESC,
        "icon": "bi-sliders2",
        "show_in_nav": False,
    },
    "registries_academicterminologyregistry": {
        "admin_url": "admin:registries_academicterminologyregistry_changelist",
        "label": _("Academic terminology registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-book",
        "show_in_nav": False,
    },
    "registries_calendarsystemregistry": {
        "admin_url": "admin:registries_calendarsystemregistry_changelist",
        "label": _("Calendar system registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-calendar3",
        "show_in_nav": False,
    },
    "registries_countryregistry": {
        "admin_url": "admin:registries_countryregistry_changelist",
        "label": _("Country registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-flag",
        "show_in_nav": False,
    },
    "registries_currencyregistry": {
        "admin_url": "admin:registries_currencyregistry_changelist",
        "label": _("Currency registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-currency-exchange",
        "show_in_nav": False,
    },
    "registries_documenttyperegistry": {
        "admin_url": "admin:registries_documenttyperegistry_changelist",
        "label": _("Document type registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-file-earmark-text",
        "show_in_nav": False,
    },
    "registries_educationlevelregistry": {
        "admin_url": "admin:registries_educationlevelregistry_changelist",
        "label": _("Education level registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-mortarboard",
        "show_in_nav": False,
    },
    "registries_educationsystemtyperegistry": {
        "admin_url": "admin:registries_educationsystemtyperegistry_changelist",
        "label": _("Education system type registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-layers",
        "show_in_nav": False,
    },
    "registries_feecategoryregistry": {
        "admin_url": "admin:registries_feecategoryregistry_changelist",
        "label": _("Fee category registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-tag",
        "show_in_nav": False,
    },
    "registries_gradescaleregistry": {
        "admin_url": "admin:registries_gradescaleregistry_changelist",
        "label": _("Grade scale registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-award",
        "show_in_nav": False,
    },
    "registries_institutiontyperegistry": {
        "admin_url": "admin:registries_institutiontyperegistry_changelist",
        "label": _("Institution type registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-translate",
        "show_in_nav": False,
    },
    "registries_localeregistry": {
        "admin_url": "admin:registries_localeregistry_changelist",
        "label": _("Locale registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-geo-alt",
        "show_in_nav": False,
    },
    "registries_subdivisionregistry": {
        "admin_url": "admin:registries_subdivisionregistry_changelist",
        "label": _("Subdivision registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-signpost",
        "show_in_nav": False,
    },
    "registries_timezoneregistry": {
        "admin_url": "admin:registries_timezoneregistry_changelist",
        "label": _("Timezone registry (platform admin)"),
        "description": _DESC,
        "icon": "bi-clock",
        "show_in_nav": False,
    },
    "schools_school": {
        "admin_url": "admin:schools_school_changelist",
        "label": _("School (platform admin)"),
        "description": _DESC,
        "icon": "bi-building",
        "show_in_nav": False,
    },
    "schools_schoolmembership": {
        "admin_url": "admin:schools_schoolmembership_changelist",
        "label": _("School membership (platform admin)"),
        "description": _DESC,
        "icon": "bi-people",
        "show_in_nav": False,
    },
    "schools_schoolprovisioningevent": {
        "admin_url": "admin:schools_schoolprovisioningevent_changelist",
        "label": _("School provisioning event (platform admin)"),
        "description": _DESC,
        "icon": "bi-lightning-charge",
        "show_in_nav": False,
    },
    "schools_tenantapiusage": {
        "admin_url": "admin:schools_tenantapiusage_changelist",
        "label": _("Tenant API usage (platform admin)"),
        "description": _DESC,
        "icon": "bi-bar-chart",
        "show_in_nav": False,
    },
    "schools_tenantquotalimit": {
        "admin_url": "admin:schools_tenantquotalimit_changelist",
        "label": _("Tenant quota limit (platform admin)"),
        "description": _DESC,
        "icon": "bi-speedometer",
        "show_in_nav": False,
    },
    "metadata_configmutationauditlog": {
        "admin_url": "admin:metadata_configmutationauditlog_changelist",
        "label": _("Config mutation audit log (platform admin)"),
        "description": _DESC,
        "icon": "bi-journal-text",
        "show_in_nav": False,
    },
    "metadata_dynamicfielddefinition": {
        "admin_url": "admin:metadata_dynamicfielddefinition_changelist",
        "label": _("Dynamic field definition (platform admin)"),
        "description": _DESC,
        "icon": "bi-input-cursor-text",
        "show_in_nav": False,
    },
    "metadata_dynamicfieldvalue": {
        "admin_url": "admin:metadata_dynamicfieldvalue_changelist",
        "label": _("Dynamic field value (platform admin)"),
        "description": _DESC,
        "icon": "bi-ui-radios",
        "show_in_nav": False,
    },
    "metadata_entitycatalogentry": {
        "admin_url": "admin:metadata_entitycatalogentry_changelist",
        "label": _("Entity catalog entry (platform admin)"),
        "description": _DESC,
        "icon": "bi-collection",
        "show_in_nav": False,
    },
    "platform_runtime_platformintegrationwebhookevent": {
        "admin_url": "admin:platform_runtime_platformintegrationwebhookevent_changelist",
        "label": _("Platform integration webhook event (platform admin)"),
        "description": _DESC,
        "icon": "bi-webhook",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorcommandcenterlink": {
        "admin_url": "admin:platform_runtime_platformoperatorcommandcenterlink_changelist",
        "label": _("Platform operator command center link (platform admin)"),
        "description": _DESC,
        "icon": "bi-display",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatormigrationcloudlink": {
        "admin_url": "admin:platform_runtime_platformoperatormigrationcloudlink_changelist",
        "label": _("Platform operator migration cloud link (platform admin)"),
        "description": _DESC,
        "icon": "bi-cloud-arrow-up",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatororchestrationworkbenchlink": {
        "admin_url": "admin:platform_runtime_platformoperatororchestrationworkbenchlink_changelist",
        "label": _("Platform operator orchestration workbench link (platform admin)"),
        "description": _DESC,
        "icon": "bi-diagram-3",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorphaseblink": {
        "admin_url": "admin:platform_runtime_platformoperatorphaseblink_changelist",
        "label": _("Platform operator Phase B link (platform admin)"),
        "description": _DESC,
        "icon": "bi-flag",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorplatformhublink": {
        "admin_url": "admin:platform_runtime_platformoperatorplatformhublink_changelist",
        "label": _("Platform operator platform hub link (platform admin)"),
        "description": _DESC,
        "icon": "bi-columns-gap",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorplaybooklink": {
        "admin_url": "admin:platform_runtime_platformoperatorplaybooklink_changelist",
        "label": _("Platform operator playbook link (platform admin)"),
        "description": _DESC,
        "icon": "bi-book",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorsuperanalyticsoverviewlink": {
        "admin_url": "admin:platform_runtime_platformoperatorsuperanalyticsoverviewlink_changelist",
        "label": _("Platform operator super analytics overview link (platform admin)"),
        "description": _DESC,
        "icon": "bi-graph-up",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorsuperdashboardlink": {
        "admin_url": "admin:platform_runtime_platformoperatorsuperdashboardlink_changelist",
        "label": _("Platform operator super dashboard link (platform admin)"),
        "description": _DESC,
        "icon": "bi-speedometer",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorsuperschoolslistlink": {
        "admin_url": "admin:platform_runtime_platformoperatorsuperschoolslistlink_changelist",
        "label": _("Platform operator super schools list link (platform admin)"),
        "description": _DESC,
        "icon": "bi-building",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorsupportdashboardlink": {
        "admin_url": "admin:platform_runtime_platformoperatorsupportdashboardlink_changelist",
        "label": _("Platform operator support dashboard link (platform admin)"),
        "description": _DESC,
        "icon": "bi-life-preserver",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatortenanthealthlink": {
        "admin_url": "admin:platform_runtime_platformoperatortenanthealthlink_changelist",
        "label": _("Platform operator tenant health link (platform admin)"),
        "description": _DESC,
        "icon": "bi-heart-pulse",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatortruthhublink": {
        "admin_url": "admin:platform_runtime_platformoperatortruthhublink_changelist",
        "label": _("Platform operator truth hub link (platform admin)"),
        "description": _DESC,
        "icon": "bi-bullseye",
        "show_in_nav": False,
    },
    "platform_runtime_platformoperatorworkflowsimulatorlink": {
        "admin_url": "admin:platform_runtime_platformoperatorworkflowsimulatorlink_changelist",
        "label": _("Platform operator workflow simulator link (platform admin)"),
        "description": _DESC,
        "icon": "bi-bezier2",
        "show_in_nav": False,
    },
    "platform_runtime_platformreportplatformskudefault": {
        "admin_url": "admin:platform_runtime_platformreportplatformskudefault_changelist",
        "label": _("Platform report platform SKU default (platform admin)"),
        "description": _DESC,
        "icon": "bi-box",
        "show_in_nav": False,
    },
    "siteconfig_globalsupportticket": {
        "admin_url": "admin:siteconfig_globalsupportticket_changelist",
        "label": _("Global support ticket (platform admin)"),
        "description": _DESC,
        "icon": "bi-ticket-perforated",
        "show_in_nav": False,
    },
    "siteconfig_globalsupportticketreply": {
        "admin_url": "admin:siteconfig_globalsupportticketreply_changelist",
        "label": _("Global support ticket reply (platform admin)"),
        "description": _DESC,
        "icon": "bi-reply",
        "show_in_nav": False,
    },
    "siteconfig_globalsupportticketwebhookendpoint": {
        "admin_url": "admin:siteconfig_globalsupportticketwebhookendpoint_changelist",
        "label": _("Global support ticket webhook endpoint (platform admin)"),
        "description": _DESC,
        "icon": "bi-link-45deg",
        "show_in_nav": False,
    },
}
