from functools import partial

from django.urls import include, path
from django.views.generic import RedirectView
from apps.marketplace import views as marketplace_views
from apps.marketplace.publisher_access import require_verified_publisher_with_host
from apps.marketplace.views_publisher import (
    publisher_app_detail as marketplace_publisher_app_detail,
    publisher_dashboard as marketplace_publisher_dashboard,
    publisher_submit_for_review as marketplace_publisher_submit_for_review,
)
from apps.marketplace import views_developer_platform as marketplace_dev_views
from apps.customersuccess import views_super as cs_views
from apps.orchestration import views as orchestration_views
from . import super_views
from apps.portal.views_ai_mode import ai_mode_view as _ai_mode_view
from . import super_views_subscription_manage
from . import super_views_support_live
from . import super_views_beyond_reach
from . import views_mat_group_hub
from .control_plane import require_super_access_with_host
from . import super_views_config
from . import super_views_config_crud
from . import super_views_enterprise_security
from . import super_views_security_surface
from . import super_views_mfa_policy
from . import super_views_owner_email
from . import super_views_operator_team
from . import super_views_superadmin
from .super_views_founder_dashboard import super_founder_dashboard
from .super_views_catalog import (
    super_blueprints_catalog,
    super_dashboard_packs_catalog,
    super_metadata_catalog,
    super_metadata_catalog_field_impact,
    super_policies_catalog,
    super_registries_overview,
    super_workflow_packs_catalog,
)
from apps.portal.views_multicampus_academics import multicampus_academics
from apps.portal.views_multicampus_billing import multicampus_billing
from apps.billing.views_holding_rollup import holding_currency_rollup_dashboard
from apps.portal.views_multicampus_extension import multicampus_extension
from .super_views_wedge import (
    super_advancement_hub,
    super_advancement_phase2_placeholder,
    super_curriculum_packs,
    super_district_enterprise,
    super_education_systems,
    super_geography,
    super_group_campuses,
    super_he_pack,
    super_learning_delivery_packs,
    super_learning_institution_catalog_json,
    super_ministry_report_stubs,
    super_ministry_stub_pdf,
    super_native_roster_connectors,
    super_one_sis_any_lms,
    super_wedge_index,
    super_wedge_operator_detail,
)
from .super_views_migration import (
    sync_repair,
    super_migration_cloud,
    super_migration_exception_ack,
    super_migration_profile_registry,
    super_migration_quarantine_waive,
    super_migration_rollback,
)
from .super_views_provisioning import api_create_school
from .super_views_remote_support import (
    super_remote_support_accept,
    super_remote_support_console,
    super_remote_support_end,
    super_remote_support_sessions,
)
from apps.lifecycle.views import LifecycleTimelineView
from apps.lifecycle.views_bulk import BulkSchoolCreateView
from apps.lifecycle.views_clone import CloneSchoolView
from apps.lifecycle.views_jobs import ProvisioningJobsDashboardView
from apps.lifecycle.views_migration_intent import SchoolMigrationIntentView
from apps.lifecycle.views_rapid_create import RapidCreateView
from apps.schoolops.views_analytics import MealPlanAnalyticsView
from apps.schoolops.views_email_admin import EmailDeliveryConfigView
from apps.schoolops.views_email_health import (
    EmailHealthDashboardView,
    EmailHealthStreamView,
    SmtpProbeJsonView,
)
from apps.siteconfig.views_globe_api import GlobeStreamView, globe_live_api, globe_markers_api
from apps.siteconfig.views_operator_fleet_api import (
    OperatorFleetStreamView,
    operator_fleet_context_api,
    operator_fleet_globe_presence_api,
    operator_fleet_snapshot_api,
    operator_fleet_tour_narrator_api,
)
from apps.siteconfig.views_cockpit_live import cockpit_live_json
from apps.schools.views_fleet_live import FleetStreamView, fleet_live_json
from apps.schoolops.views_email_webhook import EmailProviderWebhookView
from .views_signup_diagnostics import SignupDiagnosticsView
from .super_views_signup_verifications import (
    SignupVerificationActionView,
    SignupVerificationConsoleView,
)
from .super_views_sidebar_badges import operator_sidebar_badges
from .super_views_invite_school import InviteSchoolConsoleView

app_name = "super"

urlpatterns = [
    # Wave P-A (v3.95.1): MAT Group Hub operator dashboard.
    path(
        "mat-hub/",
        views_mat_group_hub.mat_group_hub_dashboard,
        name="mat_group_hub_dashboard",
    ),
    # Wave Q5 (v3.95.2): MAT Group Hub registry-editor form.
    path(
        "mat-hub/edit/",
        views_mat_group_hub.mat_group_hub_edit,
        name="mat_group_hub_create",
    ),
    path(
        "mat-hub/<str:group_id>/edit/",
        views_mat_group_hub.mat_group_hub_edit,
        name="mat_group_hub_edit",
    ),
    path(
        "mat-hub/<str:group_id>/",
        views_mat_group_hub.mat_group_hub_detail,
        name="mat_group_hub_detail",
    ),
    path(
        "mat-hub/<str:group_id>/api/",
        views_mat_group_hub.mat_group_hub_api,
        name="mat_group_hub_api",
    ),
    path(
        "",
        require_super_access_with_host(super_views.super_dashboard_v2),
        name="dashboard",
    ),
    path(
        "schools/",
        require_super_access_with_host(super_views.super_schools_list),
        name="schools_list",
    ),
    path(
        "export/schools.csv",
        require_super_access_with_host(super_views.export_schools_csv),
        name="export_schools_csv",
    ),
    path(
        "export/revenue.csv",
        require_super_access_with_host(super_views.export_revenue_csv),
        name="export_revenue_csv",
    ),
    path(
        "export/summary.pdf",
        require_super_access_with_host(super_views.export_super_dashboard_pdf),
        name="export_super_dashboard_pdf",
    ),
    path(
        "export/fleet-status.odt",
        require_super_access_with_host(super_views.export_fleet_status_odt),
        name="export_fleet_status_odt",
    ),
    path(
        "api/dashboard-layout/",
        require_super_access_with_host(super_views.api_super_dashboard_layout),
        name="api_super_dashboard_layout",
    ),
    path(
        "command-center/",
        require_super_access_with_host(super_views.super_command_center_v2),
        name="command_center",
    ),
    path(
        "founder/",
        require_super_access_with_host(super_founder_dashboard),
        name="founder_dashboard",
    ),
    path(
        "create/",
        require_super_access_with_host(super_views.create_school_wizard),
        name="create_school_wizard",
    ),
    path(
        "curriculum-packs/",
        require_super_access_with_host(super_curriculum_packs),
        name="curriculum_packs",
    ),
    path(
        "learning-delivery-packs/",
        require_super_access_with_host(super_learning_delivery_packs),
        name="learning_delivery_packs",
    ),
    path(
        "learning-institution-catalog.json",
        require_super_access_with_host(super_learning_institution_catalog_json),
        name="learning_institution_catalog_json",
    ),
    path(
        "ministry-report-stubs/",
        require_super_access_with_host(super_ministry_report_stubs),
        name="ministry_report_stubs",
    ),
    path(
        "ministry-stub-pdf/",
        require_super_access_with_host(super_ministry_stub_pdf),
        name="ministry_stub_pdf",
    ),
    path(
        "district-enterprise/",
        require_super_access_with_host(super_district_enterprise),
        name="district_enterprise",
    ),
    path(
        "geography/", require_super_access_with_host(super_geography), name="geography"
    ),
    path(
        "wedge/",
        require_super_access_with_host(super_wedge_index),
        name="wedge_index",
    ),
    path(
        "wedge/<int:wedge_id>/",
        require_super_access_with_host(super_wedge_operator_detail),
        name="wedge_operator_detail",
    ),
    path(
        "wedges/multicampus-billing/",
        require_super_access_with_host(multicampus_billing),
        name="wedge_surface_multicampus_billing",
    ),
    path(
        "wedges/multicampus-academics/",
        require_super_access_with_host(multicampus_academics),
        name="wedge_surface_multicampus_academics",
    ),
    path(
        "wedges/multicampus-extension/",
        require_super_access_with_host(multicampus_extension),
        name="wedge_surface_multicampus_extension",
    ),
    path(
        "native-roster-connectors/",
        require_super_access_with_host(super_native_roster_connectors),
        name="native_roster_connectors",
    ),
    path(
        "education-systems/",
        require_super_access_with_host(super_education_systems),
        name="education_systems",
    ),
    path(
        "group-campuses/",
        require_super_access_with_host(super_group_campuses),
        name="group_campuses",
    ),
    path(
        "one-sis-any-lms/",
        require_super_access_with_host(super_one_sis_any_lms),
        name="one_sis_any_lms",
    ),
    path(
        "advancement/",
        require_super_access_with_host(super_advancement_hub),
        name="advancement_hub",
    ),
    path(
        "advancement/phase2/",
        require_super_access_with_host(super_advancement_phase2_placeholder),
        name="advancement_phase2_placeholder",
    ),
    path("he-pack/", require_super_access_with_host(super_he_pack), name="he_pack"),
    path(
        "api/create-school/",
        require_super_access_with_host(api_create_school),
        name="api_create_school",
    ),
    path(
        "api/schools/<uuid:school_id>/lens/",
        require_super_access_with_host(super_views.api_school_lens_snapshot),
        name="api_school_lens_snapshot",
    ),
    path(
        "security/schools/<uuid:school_id>/mfa-policy/",
        require_super_access_with_host(super_views_mfa_policy.tenant_mfa_policy),
        name="tenant_mfa_policy",
    ),
    path(
        "schools/<uuid:school_id>/resend-owner-setup-email/",
        require_super_access_with_host(
            super_views_owner_email.resend_owner_setup_email_view
        ),
        name="resend_owner_setup_email",
    ),
    path(
        "schools/<uuid:school_id>/reveal-owner-setup-link/",
        require_super_access_with_host(
            super_views_owner_email.reveal_owner_setup_link_view
        ),
        name="reveal_owner_setup_link",
    ),
    path(
        "api/schools/<uuid:school_id>/requeue-provision/",
        require_super_access_with_host(super_views.api_school_requeue_provision),
        name="api_school_requeue_provision",
    ),
    path(
        "api/schools/<uuid:school_id>/timeline/",
        require_super_access_with_host(super_views.api_school_timeline),
        name="api_school_timeline",
    ),
    path(
        "api/schools/<uuid:school_id>/approve/",
        require_super_access_with_host(super_views.api_approve_school),
        name="api_approve_school",
    ),
    path(
        "api/schools/<uuid:school_id>/lifecycle/",
        require_super_access_with_host(super_views.school_lifecycle_action),
        name="api_school_lifecycle",
    ),
    path(
        "api/bulk/schools/",
        require_super_access_with_host(super_views.api_bulk_schools),
        name="api_bulk_schools",
    ),
    path(
        "api/bulk/operators/",
        require_super_access_with_host(super_views.api_bulk_operators),
        name="api_bulk_operators",
    ),
    path(
        "api/schools/<uuid:school_id>/policy-bundles/",
        require_super_access_with_host(super_views.api_school_policy_bundles),
        name="api_school_policy_bundles",
    ),
    path(
        "api/schools/<uuid:school_id>/policy-bundles/<int:bundle_id>/activate/",
        require_super_access_with_host(super_views.api_school_policy_bundle_activate),
        name="api_school_policy_bundle_activate",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/",
        require_super_access_with_host(super_views.api_school_offboarding),
        name="api_school_offboarding",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/export/",
        require_super_access_with_host(super_views.api_school_offboarding_export),
        name="api_school_offboarding_export",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/deactivate/",
        require_super_access_with_host(super_views.api_school_offboarding_deactivate),
        name="api_school_offboarding_deactivate",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/hold/",
        require_super_access_with_host(super_views.api_school_offboarding_hold),
        name="api_school_offboarding_hold",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/purge/",
        require_super_access_with_host(super_views.api_school_offboarding_purge),
        name="api_school_offboarding_purge",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/dual-approve/",
        require_super_access_with_host(super_views.api_school_offboarding_dual_approve),
        name="api_school_offboarding_dual_approve",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/approve-request/",
        require_super_access_with_host(super_views.api_school_offboarding_approve_request),
        name="api_school_offboarding_approve_request",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/reject-request/",
        require_super_access_with_host(super_views.api_school_offboarding_reject_request),
        name="api_school_offboarding_reject_request",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/purge-certificate/",
        require_super_access_with_host(super_views.api_purge_certificate_download),
        name="api_school_offboarding_purge_certificate",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/schedule/",
        require_super_access_with_host(super_views.api_school_offboarding_schedule),
        name="api_school_offboarding_schedule",
    ),
    path(
        "api/schools/<uuid:school_id>/offboarding/export/download/",
        require_super_access_with_host(super_views.api_school_offboarding_export_download),
        name="api_school_offboarding_export_download",
    ),
    path(
        "offboarding/",
        require_super_access_with_host(super_views.super_offboarding_queue),
        name="offboarding_queue",
    ),
    # Operator remote-support actions (same-host on /super/; closes the
    # cross-host gap). Per-tenant scope enforced in-view by operator_can_remote_support.
    # Console PAGE (table hydrates from sessions.json via JS). Mounted before the
    # other remote-support routes; the exact "remote-support/" path is distinct
    # from "remote-support/sessions.json" and "remote-support/<uuid>/...", so all
    # resolve independently.
    path(
        "remote-support/",
        require_super_access_with_host(super_remote_support_console),
        name="remote_support_console",
    ),
    path(
        "remote-support/sessions.json",
        require_super_access_with_host(super_remote_support_sessions),
        name="remote_support_sessions",
    ),
    path(
        "remote-support/<uuid:session_id>/accept/",
        require_super_access_with_host(super_remote_support_accept),
        name="remote_support_accept",
    ),
    path(
        "remote-support/<uuid:session_id>/end/",
        require_super_access_with_host(super_remote_support_end),
        name="remote_support_end",
    ),
    path(
        "api/offboarding/run-scheduled/",
        require_super_access_with_host(super_views.api_super_run_scheduled_purges),
        name="api_run_scheduled_purges",
    ),
    path(
        "api/geo/cities/",
        require_super_access_with_host(super_views.api_geo_cities),
        name="api_geo_cities",
    ),
    path(
        "api/geo/timezones/",
        require_super_access_with_host(super_views.api_geo_timezones),
        name="api_geo_timezones",
    ),
    path(
        "api/provinces/",
        require_super_access_with_host(super_views.api_provinces),
        name="api_provinces",
    ),
    path(
        "api/education-profiles/",
        require_super_access_with_host(super_views.api_education_profiles),
        name="api_education_profiles",
    ),
    path(
        "api/system-blueprint/",
        require_super_access_with_host(super_views.api_system_blueprint),
        name="api_system_blueprint",
    ),
    path(
        "api/plans-configurator/",
        require_super_access_with_host(super_views.api_plans_configurator),
        name="api_plans_configurator",
    ),
    path(
        "usage/", require_super_access_with_host(super_views.super_usage), name="usage"
    ),
    path(
        "migration/",
        require_super_access_with_host(super_migration_cloud),
        name="migration_cloud",
    ),
    path(
        "migration/registry/",
        require_super_access_with_host(super_migration_profile_registry),
        name="migration_profile_registry",
    ),
    path(
        "migration/rollback/<int:run_id>/",
        require_super_access_with_host(super_migration_rollback),
        name="migration_rollback",
    ),
    path(
        "migration/exception-ack/<int:run_id>/",
        require_super_access_with_host(super_migration_exception_ack),
        name="migration_exception_ack",
    ),
    path(
        "migration/quarantine-waive/<int:record_id>/",
        require_super_access_with_host(super_migration_quarantine_waive),
        name="migration_quarantine_waive",
    ),
    path(
        "ai-center/",
        include("apps.apicenter.ai_center_urls"),
    ),
    path(
        "pulse/", require_super_access_with_host(super_views.super_pulse), name="pulse"
    ),
    path(
        "tenant-health/",
        require_super_access_with_host(super_views.super_tenant_health),
        name="tenant_health",
    ),
    path(
        "fleet-wall/",
        require_super_access_with_host(super_views.super_fleet_wall),
        name="fleet_wall",
    ),
    path(
        "provision-queue/",
        require_super_access_with_host(super_views.super_provision_queue),
        name="provision_queue",
    ),
    path(
        "tenants/<uuid:school_id>/360/",
        require_super_access_with_host(super_views.super_tenant_360),
        name="tenant_360",
    ),
    path(
        "lifecycle/<uuid:school_id>/",
        require_super_access_with_host(LifecycleTimelineView.as_view()),
        name="lifecycle_timeline",
    ),
    path(
        "schools/bulk-create/",
        require_super_access_with_host(BulkSchoolCreateView.as_view()),
        name="schools_bulk_create",
    ),
    path(
        "schools/<uuid:source_id>/clone/",
        require_super_access_with_host(CloneSchoolView.as_view()),
        name="schools_clone",
    ),
    path(
        "schools/<uuid:school_id>/migration-intent/",
        require_super_access_with_host(SchoolMigrationIntentView.as_view()),
        name="schools_migration_intent",
    ),
    path(
        "schools/rapid/",
        require_super_access_with_host(RapidCreateView.as_view()),
        name="schools_rapid_create",
    ),
    path(
        "provisioning/jobs/",
        require_super_access_with_host(ProvisioningJobsDashboardView.as_view()),
        name="provisioning_jobs",
    ),
    path(
        "health/",
        require_super_access_with_host(super_views.super_control_health_dashboard),
        name="control_health",
    ),
    path(
        "registries/",
        require_super_access_with_host(super_registries_overview),
        name="registries_overview",
    ),
    path(
        "metadata-catalog/",
        require_super_access_with_host(super_metadata_catalog),
        name="metadata_catalog",
    ),
    path(
        "metadata-catalog/impact/<str:entity_code>/<str:field_name>/",
        require_super_access_with_host(super_metadata_catalog_field_impact),
        name="metadata_catalog_field_impact",
    ),
    path(
        "blueprints/",
        require_super_access_with_host(super_blueprints_catalog),
        name="blueprints_catalog",
    ),
    path(
        "policies/",
        require_super_access_with_host(super_policies_catalog),
        name="policies_catalog",
    ),
    path(
        "workflow-packs/",
        require_super_access_with_host(super_workflow_packs_catalog),
        name="workflow_packs_catalog",
    ),
    path(
        "dashboard-packs/",
        require_super_access_with_host(super_dashboard_packs_catalog),
        name="dashboard_packs_catalog",
    ),
    # Section 11: Benchmark intelligence (11.3) & Customer success (11.4)
    path(
        "customer-success/",
        require_super_access_with_host(cs_views.customer_success_dashboard),
        name="customer_success_dashboard",
    ),
    path(
        "customer-success/api/benchmark/cohorts/",
        require_super_access_with_host(cs_views.api_benchmark_cohorts),
        name="cs_api_benchmark_cohorts",
    ),
    path(
        "customer-success/api/benchmark/peer-metrics/",
        require_super_access_with_host(cs_views.api_benchmark_peer_metrics),
        name="cs_api_benchmark_peer_metrics",
    ),
    path(
        "customer-success/api/maturity-scores/",
        require_super_access_with_host(cs_views.api_maturity_scores),
        name="cs_api_maturity_scores",
    ),
    path(
        "customer-success/api/risk-alerts/",
        require_super_access_with_host(cs_views.api_risk_alerts),
        name="cs_api_risk_alerts",
    ),
    path(
        "customer-success/api/intervention-suggestions/",
        require_super_access_with_host(cs_views.api_intervention_suggestions),
        name="cs_api_intervention_suggestions",
    ),
    path(
        "customer-success/api/tenant-health/",
        require_super_access_with_host(cs_views.api_tenant_health),
        name="cs_api_tenant_health",
    ),
    path(
        "customer-success/api/workflow-failures/",
        require_super_access_with_host(cs_views.api_workflow_failures),
        name="cs_api_workflow_failures",
    ),
    path(
        "customer-success/api/admin-inactivity-alerts/",
        require_super_access_with_host(cs_views.api_admin_inactivity_alerts),
        name="cs_api_admin_inactivity_alerts",
    ),
    path(
        "billing/",
        require_super_access_with_host(super_views.billing_dashboard),
        name="billing_dashboard",
    ),
    path(
        "billing/holding-currency-rollups/",
        require_super_access_with_host(holding_currency_rollup_dashboard),
        name="holding_currency_rollup_dashboard",
    ),
    path(
        "billing/subscription/<str:school_id>/",
        super_views_subscription_manage.tenant_subscription_manage,
        name="tenant_subscription_manage",
    ),
    path(
        "security/surface/",
        require_super_access_with_host(
            super_views_security_surface.super_security_surface_dashboard
        ),
        name="security_surface_dashboard",
    ),
    path(
        "security/",
        require_super_access_with_host(
            super_views_enterprise_security.super_security_hub
        ),
        name="security_hub",
    ),
    path(
        "superadmin/",
        super_views_superadmin.super_superadmin_console,
        name="superadmin_console",
    ),
    path(
        "team/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_roster
        ),
        name="operator_team_roster",
    ),
    path(
        "team/invite/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_invite
        ),
        name="operator_team_invite",
    ),
    path(
        "team/promote/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_promote
        ),
        name="operator_team_promote",
    ),
    path(
        "team/promote/<int:promo_id>/decide/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_promotion_decide
        ),
        name="operator_team_promotion_decide",
    ),
    path(
        "team/<int:user_id>/lens/",
        require_super_access_with_host(
            super_views_operator_team.api_operator_lens_snapshot
        ),
        name="api_operator_lens_snapshot",
    ),
    path(
        "team/<int:user_id>/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_detail
        ),
        name="operator_team_detail",
    ),
    path(
        "team/<int:user_id>/offboard/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_offboard
        ),
        name="operator_team_offboard",
    ),
    path(
        "team/<int:user_id>/revoke-sessions/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_revoke_sessions
        ),
        name="operator_team_revoke_sessions",
    ),
    path(
        "team/<int:user_id>/suspend/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_suspend
        ),
        name="operator_team_suspend",
    ),
    path(
        "team/<int:user_id>/reactivate/",
        require_super_access_with_host(
            super_views_operator_team.super_operator_team_reactivate
        ),
        name="operator_team_reactivate",
    ),
    path(
        "security/command-center/",
        require_super_access_with_host(
            super_views_enterprise_security.super_security_hub
        ),
        name="security_command_center",
    ),
    path(
        "enterprise-security-command-center/",
        require_super_access_with_host(
            super_views_enterprise_security.super_security_hub
        ),
        name="enterprise_security_command_center",
    ),
    path(
        "marketplace/",
        require_super_access_with_host(marketplace_views.governance_console),
        name="marketplace_governance",
    ),
    path(
        "marketplace-governance/",
        RedirectView.as_view(pattern_name="super:marketplace_governance", permanent=False),
        name="marketplace_governance_alias",
    ),
    path(
        "marketplace/reviews/<int:review_id>/action/",
        require_super_access_with_host(marketplace_views.marketplace_review_action),
        name="marketplace_review_action",
    ),
    path(
        "marketplace/blueprints/",
        require_super_access_with_host(marketplace_views.blueprint_marketplace),
        name="blueprint_marketplace",
    ),
    path(
        "marketplace/apps/",
        require_super_access_with_host(marketplace_views.app_catalog),
        name="app_catalog",
    ),
    path(
        "marketplace/apps/install-impact-preview/",
        require_super_access_with_host(marketplace_views.super_install_impact_preview),
        name="marketplace_install_impact_preview",
    ),
    path(
        "marketplace/compatibility/",
        require_super_access_with_host(marketplace_views.compatibility_matrix),
        name="marketplace_compatibility",
    ),
    path(
        "marketplace/sandbox/",
        require_super_access_with_host(marketplace_views.sandbox_inspector),
        name="marketplace_sandbox_inspector",
    ),
    path(
        "marketplace/health/",
        require_super_access_with_host(marketplace_views.installation_health),
        name="marketplace_installation_health",
    ),
    path(
        "marketplace/incidents/",
        require_super_access_with_host(
            marketplace_views.marketplace_incident_dashboard
        ),
        name="marketplace_incident_dashboard",
    ),
    # Move 1 — developer-platform operator surfaces.
    path(
        "marketplace/signups/",
        require_super_access_with_host(marketplace_dev_views.signup_review_queue),
        name="marketplace_signup_review_queue",
    ),
    path(
        "marketplace/signups/<int:signup_id>/decide/",
        require_super_access_with_host(marketplace_dev_views.signup_decide),
        name="marketplace_signup_decide",
    ),
    path(
        "marketplace/publisher/metrics.json",
        require_verified_publisher_with_host(
            marketplace_dev_views.partner_dashboard_metrics
        ),
        name="marketplace_publisher_metrics",
    ),
    path(
        "marketplace/publisher/webhooks/",
        require_verified_publisher_with_host(marketplace_dev_views.publisher_webhook_log),
        name="marketplace_publisher_webhook_log",
    ),
    path(
        "marketplace/publisher/apps/<slug:app_slug>/webhooks/",
        require_verified_publisher_with_host(marketplace_dev_views.webhook_endpoints_view),
        name="marketplace_webhook_endpoints",
    ),
    path(
        "marketplace/publisher/apps/<slug:app_slug>/webhooks/<int:endpoint_id>/edit/",
        require_verified_publisher_with_host(
            marketplace_dev_views.webhook_endpoint_edit_view
        ),
        name="marketplace_webhook_endpoint_edit",
    ),
    path(
        "marketplace/publisher/apps/<slug:app_slug>/versions/",
        require_verified_publisher_with_host(marketplace_dev_views.app_versions_view),
        name="marketplace_app_versions",
    ),
    path(
        "marketplace/ratings/<int:rating_id>/reply/",
        require_super_access_with_host(marketplace_dev_views.publisher_reply_view),
        name="marketplace_publisher_reply",
    ),
    path(
        "marketplace/activate-sandbox/",
        require_super_access_with_host(marketplace_views.super_activate_sandbox),
        name="marketplace_activate_sandbox",
    ),
    path(
        "marketplace/refresh-installation/",
        require_super_access_with_host(marketplace_views.super_refresh_installation),
        name="marketplace_refresh_installation",
    ),
    path(
        "marketplace/package-rollout/",
        require_super_access_with_host(marketplace_views.package_rollout),
        name="package_rollout",
    ),
    path(
        "marketplace/package-promote/",
        require_super_access_with_host(marketplace_views.package_promote),
        name="package_promote",
    ),
    path(
        "marketplace/publisher/",
        marketplace_publisher_dashboard,
        name="marketplace_publisher_dashboard",
    ),
    path(
        "marketplace/publisher/<slug:slug>/submit/",
        marketplace_publisher_submit_for_review,
        name="marketplace_publisher_submit_for_review",
    ),
    path(
        "marketplace/publisher/<slug:slug>/",
        marketplace_publisher_app_detail,
        name="marketplace_publisher_app_detail",
    ),
    path(
        "phase-b-snapshot-diff/",
        require_super_access_with_host(super_views.super_phase_b_snapshot_diff),
        name="phase_b_snapshot_diff",
    ),
    path(
        "policy-diff/",
        require_super_access_with_host(super_views.super_policy_diff),
        name="policy_diff",
    ),
    path(
        "policy-diff/apply-to-sandbox/",
        require_super_access_with_host(
            super_views.super_apply_policy_bundle_to_sandbox
        ),
        name="policy_apply_to_sandbox",
    ),
    path(
        "trust/",
        require_super_access_with_host(super_views.super_trust_center),
        name="trust_center",
    ),
    path(
        "trust/platform-events/",
        require_super_access_with_host(super_views.super_platform_events),
        name="platform_events",
    ),
    path(
        "trust/export/",
        require_super_access_with_host(super_views.super_audit_export),
        name="audit_export",
    ),
    path(
        "migration/csv-diff/",
        require_super_access_with_host(
            super_views_beyond_reach.super_migration_csv_diff
        ),
        name="migration_csv_diff",
    ),
    path(
        "tools/legacy-csv-preview/",
        require_super_access_with_host(
            super_views_beyond_reach.super_legacy_sis_csv_preview
        ),
        name="legacy_csv_preview",
    ),
    path(
        "tools/governed-query/",
        require_super_access_with_host(
            super_views_beyond_reach.super_governed_data_query
        ),
        name="governed_data_query",
    ),
    path(
        "compliance/",
        require_super_access_with_host(super_views.super_compliance_overview),
        name="compliance_overview",
    ),
    path(
        "analytics/",
        require_super_access_with_host(super_views.super_analytics_overview),
        name="analytics_overview",
    ),
    path(
        "funding/",
        require_super_access_with_host(super_views.super_funding_overview),
        name="funding_overview",
    ),
    path(
        "ai/mode/",
        require_super_access_with_host(_ai_mode_view),
        name="ai_mode",
    ),
    path(
        "support/",
        require_super_access_with_host(super_views.super_support_dashboard),
        name="support_dashboard",
    ),
    path(
        "support/live/",
        require_super_access_with_host(
            super_views_support_live.super_support_live_console
        ),
        name="support_live_console",
    ),
    path(
        "support/export.csv",
        require_super_access_with_host(super_views.super_support_tickets_export_csv),
        name="support_tickets_export_csv",
    ),
    path(
        "support/csat/",
        require_super_access_with_host(super_views.super_support_csat_dashboard),
        name="support_csat_dashboard",
    ),
    path(
        "support/queue/",
        require_super_access_with_host(super_views.support_queue_fragment),
        name="support_queue_fragment",
    ),
    path(
        "support/assign/",
        require_super_access_with_host(super_views.support_assign_ticket),
        name="support_assign_ticket",
    ),
    path(
        "support/bulk/",
        require_super_access_with_host(super_views.support_bulk_action),
        name="support_bulk_action",
    ),
    path(
        "support/auto-rules/",
        require_super_access_with_host(super_views.support_auto_rules_dashboard),
        name="support_auto_rules_dashboard",
    ),
    path(
        "support/auto-rules/save/",
        require_super_access_with_host(super_views.support_auto_rules_save),
        name="support_auto_rules_save",
    ),
    path(
        "support/on-call/",
        require_super_access_with_host(super_views.support_on_call_dashboard),
        name="support_on_call_dashboard",
    ),
    path(
        "support/on-call/save/",
        require_super_access_with_host(super_views.support_on_call_save),
        name="support_on_call_save",
    ),
    path(
        "support/on-call/generate/",
        require_super_access_with_host(super_views.support_on_call_generate),
        name="support_on_call_generate",
    ),
    path(
        "support/ticket/<uuid:ticket_id>/",
        require_super_access_with_host(super_views.super_support_ticket_detail),
        name="support_ticket_detail",
    ),
    path(
        "switch-to-tenant/",
        require_super_access_with_host(super_views.switch_to_tenant),
        name="switch_to_tenant",
    ),
    path(
        "sync-repair/<uuid:school_id>/",
        require_super_access_with_host(sync_repair),
        name="sync_repair",
    ),
    path(
        "ai-model-hub/",
        require_super_access_with_host(super_views.ai_model_hub),
        name="ai_model_hub",
    ),
    path(
        "ai-gateway-console/",
        require_super_access_with_host(super_views.super_ai_gateway_console),
        name="ai_gateway_console",
    ),
    path(
        "global-ai-version/",
        require_super_access_with_host(super_views.global_ai_version),
        name="global_ai_version",
    ),
    path(
        "global-ai-version/progress/<str:run_id>/",
        require_super_access_with_host(super_views.global_ai_version_progress),
        name="global_ai_version_progress",
    ),
    path(
        "runtime-inspector/",
        require_super_access_with_host(super_views.super_runtime_inspector),
        name="runtime_inspector",
    ),
    path(
        "runtime-truth-hub/",
        require_super_access_with_host(super_views.super_runtime_truth_hub),
        name="runtime_truth_hub",
    ),
    path(
        "workflow-simulator/",
        require_super_access_with_host(super_views.super_workflow_simulator),
        name="workflow_simulator",
    ),
    path(
        "playbook-operator-hub/",
        require_super_access_with_host(super_views.super_playbook_operator_hub),
        name="playbook_operator_hub",
    ),
    path(
        "orchestration/",
        require_super_access_with_host(orchestration_views.operator_workbench),
        name="orchestration_workbench",
    ),
    path(
        "orchestration/runs/<int:run_id>/retry/",
        require_super_access_with_host(orchestration_views.retry_run),
        name="orchestration_retry_run",
    ),
    path(
        "orchestration/definitions/<slug:code>/start/",
        require_super_access_with_host(orchestration_views.start_run),
        name="orchestration_start_run",
    ),
    path(
        "orchestration/runs/<int:run_id>/",
        require_super_access_with_host(orchestration_views.run_detail_page),
        name="orchestration_run_detail",
    ),
    path(
        "platform-operator-hub/",
        require_super_access_with_host(
            super_views_config.super_platform_operator_hub
        ),
        name="platform_operator_hub",
    ),
    path(
        "operator-policy/",
        require_super_access_with_host(super_views_config.super_operator_policy),
        name="operator_policy",
    ),
    path(
        "backlog-unlock-center/",
        require_super_access_with_host(
            super_views_config.super_backlog_unlock_center
        ),
        name="backlog_unlock_center",
    ),
    path(
        "fleet-governed-changes/",
        require_super_access_with_host(
            super_views_config.super_fleet_governed_changes
        ),
        name="fleet_governed_changes",
    ),
    # Legacy pretty paths only (no URL names). 301 → canonical slug; bookmarks keep working.
    path(
        "admin-bridge/integrations-marketplace/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="integrations",
            )
        ),
    ),
    path(
        "admin-bridge/marketplace-apps/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="marketplace_apps",
            )
        ),
    ),
    path(
        "admin-bridge/packages/installed/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="packages_installed",
            )
        ),
    ),
    path(
        "admin-bridge/packages/experience-packs/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="experience_packs",
            )
        ),
    ),
    path(
        "admin-bridge/runtime-defaults/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="runtime_defaults",
            )
        ),
    ),
    path(
        "admin-bridge/fleet-governed-changes/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="fleet_governed_changes",
            )
        ),
    ),
    path(
        "admin-bridge/ai-model-registry/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="ai_model_registry",
            )
        ),
    ),
    path(
        "admin-bridge/global-brand-registry/",
        require_super_access_with_host(
            partial(
                super_views_config.super_admin_bridge_legacy_path_redirect,
                bridge_key="global_brand_registry",
            )
        ),
    ),
    path(
        "admin-bridge/<slug:bridge_key>/",
        require_super_access_with_host(super_views_config.super_admin_bridge),
        name="admin_bridge",
    ),
    # Legacy path: /super/config/ redirects to Configuration Control Center (siteconfig:console_domains_hub). Single config surface.
    path(
        "config/",
        require_super_access_with_host(super_views.super_config_hub_redirect),
        name="config_hub",
    ),
    path(
        "config/site-settings/",
        require_super_access_with_host(super_views_config.super_site_settings_list),
        name="site_settings_list",
    ),
    path(
        "config/site-settings/<int:pk>/",
        require_super_access_with_host(super_views_config.super_site_settings_edit),
        name="site_settings_edit",
    ),
    path(
        "config/regions/",
        require_super_access_with_host(super_views_config.super_regions_list),
        name="regions_list",
    ),
    path(
        "config/regions/add/",
        require_super_access_with_host(super_views_config_crud.super_region_add),
        name="region_add",
    ),
    path(
        "config/regions/<str:code>/edit/",
        require_super_access_with_host(super_views_config_crud.super_region_edit),
        name="region_edit",
    ),
    path(
        "config/regions/<str:code>/delete/",
        require_super_access_with_host(super_views_config_crud.super_region_delete),
        name="region_delete",
    ),
    path(
        "config/grading/",
        require_super_access_with_host(super_views_config.super_grading_list),
        name="grading_list",
    ),
    path(
        "config/grading/add/",
        require_super_access_with_host(super_views_config_crud.super_grading_add),
        name="grading_add",
    ),
    path(
        "config/grading/<int:pk>/edit/",
        require_super_access_with_host(super_views_config_crud.super_grading_edit),
        name="grading_edit",
    ),
    path(
        "config/grading/<int:pk>/delete/",
        require_super_access_with_host(super_views_config_crud.super_grading_delete),
        name="grading_delete",
    ),
    path(
        "config/plans/",
        require_super_access_with_host(super_views_config.super_plans_list),
        name="plans_list",
    ),
    path(
        "config/plans/add/",
        require_super_access_with_host(super_views_config_crud.super_plan_add),
        name="plan_add",
    ),
    path(
        "config/plans/<int:pk>/edit/",
        require_super_access_with_host(super_views_config_crud.super_plan_edit),
        name="plan_edit",
    ),
    path(
        "config/plans/<int:pk>/delete/",
        require_super_access_with_host(super_views_config_crud.super_plan_delete),
        name="plan_delete",
    ),
    path(
        "config/plan-addons/add/",
        require_super_access_with_host(super_views_config_crud.super_plan_addon_add),
        name="plan_addon_add",
    ),
    path(
        "config/plan-addons/<int:pk>/edit/",
        require_super_access_with_host(super_views_config_crud.super_plan_addon_edit),
        name="plan_addon_edit",
    ),
    path(
        "config/plan-addons/<int:pk>/delete/",
        require_super_access_with_host(super_views_config_crud.super_plan_addon_delete),
        name="plan_addon_delete",
    ),
    path(
        "config/feature-toggles/",
        require_super_access_with_host(super_views_config.super_feature_toggles_list),
        name="feature_toggles_list",
    ),
    path(
        "config/feature-toggles/add/",
        require_super_access_with_host(
            super_views_config_crud.super_feature_toggle_add
        ),
        name="feature_toggle_add",
    ),
    path(
        "config/feature-toggles/<int:pk>/edit/",
        require_super_access_with_host(
            super_views_config_crud.super_feature_toggle_edit
        ),
        name="feature_toggle_edit",
    ),
    path(
        "config/feature-toggles/<int:pk>/delete/",
        require_super_access_with_host(
            super_views_config_crud.super_feature_toggle_delete
        ),
        name="feature_toggle_delete",
    ),
    path(
        "config/country-multipliers/",
        require_super_access_with_host(
            super_views_config.super_country_multipliers_list
        ),
        name="country_multipliers_list",
    ),
    path(
        "config/country-multipliers/add/",
        require_super_access_with_host(
            super_views_config_crud.super_country_multiplier_add
        ),
        name="country_multiplier_add",
    ),
    path(
        "config/country-multipliers/<int:pk>/edit/",
        require_super_access_with_host(
            super_views_config_crud.super_country_multiplier_edit
        ),
        name="country_multiplier_edit",
    ),
    path(
        "config/country-multipliers/<int:pk>/delete/",
        require_super_access_with_host(
            super_views_config_crud.super_country_multiplier_delete
        ),
        name="country_multiplier_delete",
    ),
    path(
        "incidents/",
        require_super_access_with_host(super_views_config.super_incidents_list),
        name="incidents_list",
    ),
    path(
        "billing-accounts/",
        require_super_access_with_host(super_views_config.super_billing_accounts_list),
        name="billing_accounts_list",
    ),
    path(
        "migration-runs/",
        require_super_access_with_host(super_views_config.super_migration_runs_list),
        name="migration_runs_list",
    ),
    # v3.33.0 — schoolops meal-plan low-balance analytics dashboard.
    path(
        "schoolops/meal-plan-analytics/",
        MealPlanAnalyticsView.as_view(),
        name="schoolops_meal_plan_analytics",
    ),  # rbac-allow: staff-only-meal-plan-analytics-dashboard
    # v3.57.x Wave 8 Agent C — email delivery health + config endpoints.
    # 2026-06-06 — operator signup email-verification console (resend/regenerate).
    path(
        "signup-verifications/",
        SignupVerificationConsoleView.as_view(),
        name="signup_verifications",
    ),  # rbac-allow: super-staff-signup-verification-console
    path(
        "signup-verifications/<int:pk>/action/",
        SignupVerificationActionView.as_view(),
        name="signup_verification_action",
    ),  # rbac-allow: super-staff-signup-verification-action
    path(
        "sidebar/badges/",
        require_super_access_with_host(operator_sidebar_badges),
        name="sidebar_badges",
    ),  # rbac-allow: super-staff-operator-sidebar-badge-counts
    # 2026-06-06 — invite a whole school onto the platform (vs self-signup).
    path(
        "invite-school/",
        InviteSchoolConsoleView.as_view(),
        name="invite_school",
    ),  # rbac-allow: super-staff-invite-school-console
    path(
        "email/health/",
        EmailHealthDashboardView.as_view(),
        name="email_health",
    ),  # rbac-allow: super-staff-email-health-dashboard
    path(
        "email/health/probe/",
        SmtpProbeJsonView.as_view(),
        name="email_health_probe",
    ),  # rbac-allow: super-staff-email-health-dashboard
    path(
        "email/configure/",
        EmailDeliveryConfigView.as_view(),
        name="email_configure",
    ),  # rbac-allow: super-staff-email-configure
    # v3.58.x Wave 9 Agent K — signup-flow diagnostics dashboard.
    path(
        "signup/diagnostics/",
        SignupDiagnosticsView.as_view(),
        name="signup_diagnostics",
    ),  # rbac-allow: super-staff-signup-flow-diagnostics
    # v3.58.x Wave 9 Agent M — email reliability completion track.
    path(
        "api/cockpit/live.json",
        require_super_access_with_host(cockpit_live_json),
        name="api_cockpit_live",
    ),  # rbac-allow: super-staff-cockpit-live-json
    path(
        "api/fleet/live.json",
        require_super_access_with_host(fleet_live_json),
        name="api_fleet_live",
    ),  # rbac-allow: super-staff-fleet-live-json
    path(
        "api/fleet/stream/",
        require_super_access_with_host(FleetStreamView.as_view()),
        name="api_fleet_stream",
    ),  # rbac-allow: super-staff-fleet-live-stream
    path(
        "api/globe/markers/",
        globe_markers_api,
        name="api_globe_markers",
    ),  # rbac-allow: super-staff-globe-markers-api
    path(
        "api/globe/live/",
        globe_live_api,
        name="api_globe_live",
    ),  # rbac-allow: super-staff-globe-live-api
    path(
        "api/globe/stream/",
        GlobeStreamView.as_view(),
        name="api_globe_stream",
    ),  # rbac-allow: super-staff-globe-live-stream
    path(
        "api/operator/fleet/snapshot/",
        require_super_access_with_host(operator_fleet_snapshot_api),
        name="api_operator_fleet_snapshot",
    ),  # rbac-allow: super-staff-operator-fleet-snapshot
    path(
        "api/operator/fleet/context/",
        require_super_access_with_host(operator_fleet_context_api),
        name="api_operator_fleet_context",
    ),  # rbac-allow: super-staff-operator-fleet-context
    path(
        "api/operator/fleet/stream/",
        require_super_access_with_host(OperatorFleetStreamView.as_view()),
        name="api_operator_fleet_stream",
    ),  # rbac-allow: super-staff-operator-fleet-stream
    path(
        "api/operator/fleet/globe-presence/",
        require_super_access_with_host(operator_fleet_globe_presence_api),
        name="api_operator_fleet_globe_presence",
    ),  # rbac-allow: super-staff-operator-fleet-globe-presence
    path(
        "api/operator/fleet/tour-narrator/",
        require_super_access_with_host(operator_fleet_tour_narrator_api),
        name="api_operator_fleet_tour_narrator",
    ),  # rbac-allow: super-staff-operator-fleet-tour-narrator
    path(
        "email/health/stream/",
        EmailHealthStreamView.as_view(),
        name="email_health_stream",
    ),  # rbac-allow: super-staff-email-health-dashboard
    path(
        "email/webhook/<str:provider>/",
        EmailProviderWebhookView.as_view(),
        name="email_provider_webhook",
    ),  # rbac-allow: anonymous-signature-verified-bounce-webhook-receiver
]
