# Generated by Django 5.2.10 on 2026-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_stripeplanprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplanprice',
            name='plan_code',
            field=models.SlugField(
                db_index=True,
                help_text="Matches siteconfig.Plan.slug",
                max_length=80,
            ),
        ),
    ]
