# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_entitlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='currency_code',
            field=models.CharField(default=apps.billing.models._platform_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='currency_code',
            field=models.CharField(default=apps.billing.models._platform_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency_code',
            field=models.CharField(default=apps.billing.models._platform_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='revenuesharepayout',
            name='currency_code',
            field=models.CharField(default=apps.billing.models._platform_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='stripeplanprice',
            name='currency',
            field=models.CharField(default=apps.billing.models._platform_default_currency, max_length=3),
        ),
    ]
