# Generated by Django 5.2.10 on 2026-06-27 03:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import connection, migrations, models

from apps.schools.rls import should_apply_rls


SUBSCRIPTION_GRANT_TABLE = "billing_subscriptiongrant"
SUBSCRIPTION_GRANT_POLICY = "billing_tenant_subscriptiongrant"
USING_CLAUSE = """(
    current_setting('app.rls_bypass', true) = 'on'
    OR (
        current_setting('app.current_school_id', true) IS NOT NULL
        AND school_id::text = current_setting('app.current_school_id', true)
    )
)"""


def apply_subscription_grant_rls(apps, schema_editor):
    if not should_apply_rls(connection):
        return
    with connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {SUBSCRIPTION_GRANT_TABLE} ENABLE ROW LEVEL SECURITY;")
        cursor.execute(f"DROP POLICY IF EXISTS {SUBSCRIPTION_GRANT_POLICY} ON {SUBSCRIPTION_GRANT_TABLE};")
        cursor.execute(
            f"""
            CREATE POLICY {SUBSCRIPTION_GRANT_POLICY} ON {SUBSCRIPTION_GRANT_TABLE}
            FOR ALL
            USING {USING_CLAUSE}
            WITH CHECK {USING_CLAUSE};
            """
        )


def reverse_subscription_grant_rls(apps, schema_editor):
    if not should_apply_rls(connection):
        return
    with connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS {SUBSCRIPTION_GRANT_POLICY} ON {SUBSCRIPTION_GRANT_TABLE};")
        cursor.execute(f"ALTER TABLE {SUBSCRIPTION_GRANT_TABLE} DISABLE ROW LEVEL SECURITY;")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_rls_policy_default_deny'),
        ('schools', '0076_alter_school_currency'),
        ('siteconfig', '0203_seed_country_multipliers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=12)),
                ('percent_off', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('REGION', 'Region'), ('PLAN', 'Plan'), ('TENANT', 'Tenant'), ('PARTNER', 'Partner')], default='GLOBAL', max_length=16)),
                ('country_codes', models.JSONField(blank=True, default=list, help_text='Optional ISO country codes this promotion applies to.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_promotions', to='siteconfig.plan')),
            ],
            options={
                'verbose_name': 'Billing promotion',
                'verbose_name_plural': 'Billing promotions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('DISCOUNT', 'Manual discount'), ('WAIVER', 'Subscription waiver'), ('CREDIT', 'Account credit'), ('SPONSORSHIP', 'Sponsorship'), ('INTERNAL', 'Internal/demo')], default='DISCOUNT', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=12)),
                ('percent_off', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('include_addons', models.BooleanField(default=True)),
                ('cycle_limit', models.PositiveIntegerField(blank=True, help_text='Optional maximum number of billing renewals this grant can affect.', null=True)),
                ('cycles_applied', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subscription_grants', to=settings.AUTH_USER_MODEL)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_grants', to='billing.billingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_grants', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grants', to='billing.billingpromotion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_grants', to='schools.school')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_grants', to='billing.tenantsubscription')),
            ],
            options={
                'verbose_name': 'Subscription grant',
                'verbose_name_plural': 'Subscription grants',
                'ordering': ['-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['school', 'status', 'starts_at', 'ends_at'], name='bill_grant_school_status_idx'), models.Index(fields=['subscription', 'status'], name='billing_grant_sub_status_idx')],
            },
        ),
        migrations.RunPython(
            apply_subscription_grant_rls,
            reverse_subscription_grant_rls,
        ),
    ]
