# Generated by Django 5.2.10 on 2026-06-27 04:01

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_billingpromotion_subscriptiongrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text='Canonical ISO 3166-1 alpha-2 country code where possible.', max_length=3, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=120)),
                ('currency_code', models.CharField(default=apps.billing.models._platform_default_currency, max_length=3)),
                ('market_tier', models.CharField(choices=[('A', 'Tier A'), ('B', 'Tier B'), ('C', 'Tier C')], default='B', max_length=1)),
                ('price_zone', models.CharField(blank=True, help_text='Usually mirrors CountryMultiplier.zone; kept editable for commercial policy.', max_length=1)),
                ('public_price_mode', models.CharField(choices=[('PUBLISHED', 'Published'), ('LOCALIZED', 'Localized'), ('QUOTE', 'Quote'), ('CUSTOM_CONTRACT', 'Custom contract')], default='LOCALIZED', max_length=20)),
                ('default_billing_cycles', models.JSONField(blank=True, default=list, help_text='Market-default cycles such as monthly, annual, school_year, custom_contract.')),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='Market-default payment rails such as card, bank, mobile_money, invoice, purchase_order.')),
                ('tax_behavior', models.CharField(choices=[('EXCLUSIVE', 'Tax exclusive'), ('INCLUSIVE', 'Tax inclusive'), ('REVERSE_CHARGE', 'Reverse charge'), ('MANUAL', 'Manual review')], default='EXCLUSIVE', max_length=20)),
                ('invoice_locale', models.CharField(blank=True, max_length=16)),
                ('checkout_copy', models.JSONField(blank=True, default=dict, help_text='Tenant-facing wording for checkout, procurement, mobile money, tax, or invoice caveats.')),
                ('procurement_policy', models.JSONField(blank=True, default=dict, help_text='PO, wire, government, NGO, offline, and contract approval rules for this country.')),
                ('promotion_policy', models.JSONField(blank=True, default=dict, help_text='Market promotion knobs such as annual discount, launch offers, sponsorship defaults.')),
                ('addon_policy', models.JSONField(blank=True, default=dict, help_text='Market add-on rules such as usage bundles, hidden add-ons, and required approvals.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country billing profile',
                'verbose_name_plural': 'Country billing profiles',
                'ordering': ['country_code'],
            },
        ),
    ]
