# Generated by Django 5.2.14 on 2026-06-27 19:06

import apps.billing.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_stripeplanprice_billing_cycle'),
        ('schools', '0076_alter_school_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('reference_stem', models.CharField(db_index=True, max_length=120, unique=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('currency_code', models.CharField(default=apps.billing.models._platform_default_currency, max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='ISSUED', max_length=12)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingaccount')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='schools.school')),
            ],
            options={
                'verbose_name': 'Platform invoice',
                'verbose_name_plural': 'Platform invoices',
                'ordering': ['-sequence'],
            },
        ),
    ]
