# Generated by Django 5.2.10 on 2026-07-18 14:19

import apps.billing.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_platforminvoice'),
        ('schools', '0077_schoolmembership_suspended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorRevenueShareAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ref', models.CharField(blank=True, help_text='Stable school slug/id snapshot, retained for reconciliation if the School row is later deleted (school FK is SET_NULL).', max_length=64)),
                ('source_payment_id', models.BigIntegerField(db_index=True, help_text='finance.Payment pk. Not an FK: finance is a tenant app, billing is shared. Unique only in combination with school (pk collides across tenants).')),
                ('processor_code', models.CharField(blank=True, db_index=True, help_text='Gateway/PSP the payment routed through (e.g. flutterwave, mtn_momo, stripe) — the counterparty that owes the referral rebate.', max_length=40)),
                ('method_code', models.CharField(blank=True, help_text='finance PaymentMethodCode rail for finer attribution.', max_length=32)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net money received (Payment.amount - refunded_amount) = attributed GMV.', max_digits=14)),
                ('currency_code', models.CharField(default=apps.billing.models._platform_default_currency, max_length=3)),
                ('rev_share_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Referral rate applied at accrual time (snapshotted).', max_digits=6)),
                ('rebate_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='gross_amount * rev_share_percent / 100 — what the processor owes the platform.', max_digits=14)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('INVOICED', 'Invoiced to processor'), ('RECONCILED', 'Reconciled / settled'), ('VOIDED', 'Voided')], db_index=True, default='ACCRUED', max_length=12)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the underlying payment settled (Payment.paid_at).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_revshare_accruals', to='schools.school')),
            ],
            options={
                'verbose_name': 'Processor revenue-share accrual',
                'verbose_name_plural': 'Processor revenue-share accruals',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['processor_code', 'status', 'occurred_at'], name='bill_revshare_proc_status_idx'), models.Index(fields=['school', 'occurred_at'], name='bill_revshare_school_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'source_payment_id'), name='billing_processor_revshare_uniq_school_payment')],
            },
        ),
    ]
