"""Latin America + Caribbean Tier 1 extension - 31 hand-researched countries.

Appended into COUNTRY_LOCALIZATION at import time by _seed_country_localization.py.

Coverage:
  Latin America (17): AR, BO, CL, CO, CR, CU, DO, EC, SV, GT, HN, NI, PA, PY,
                     PE, UY, VE
  Caribbean (14):    AG, BS, BB, BZ, DM, GD, GY, HT, JM, KN, LC, VC, TT, SR

Skipped (already in Tier 1 base seed): MX (Preescolar/Primaria/Secundaria/Prepa
+ 5-bimestre), BR (Bimestre + Educacao Infantil/Fundamental/Medio).

Calendar convention:
  - LATAM Spanish countries default to week_start=1 (Monday)
  - Southern Hemisphere (AR/CL/UY/PY): Mar-Dec academic year
  - Caribbean / Central America / Northern S.A.: Aug-Jul or Sept-Jul
  - Anglophone Caribbean follows British 3-term Sept-July pattern
"""

LATAM_CARIBBEAN_EXTENSION = {
    # ============================================================
    # LATIN AMERICA - SPANISH SPEAKING (17 countries, MX/BR excluded)
    # ============================================================
    "AR": {  # Argentina
        "calendar_system": {
            "code": "ar-2-cuatrimestre",
            "label": "2 Cuatrimestres",
            "term_count": 2,
            "term_names": ["Primer Cuatrimestre", "Segundo Cuatrimestre"],
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "inicial",    "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",   "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria", "label": "Educacion Secundaria",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-17"},
            {"code": "terciario",  "label": "Terciario / Universidad",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ar-i1", "label": "Sala de 3",      "order": 0},
            {"code": "ar-i2", "label": "Sala de 4",      "order": 1},
            {"code": "ar-i3", "label": "Sala de 5",      "order": 2},
            {"code": "ar-p1", "label": "1° Primaria", "order": 3},
            {"code": "ar-p6", "label": "6° Primaria", "order": 8},
            {"code": "ar-s1", "label": "1° Secundaria", "order": 9},
            {"code": "ar-s5", "label": "5° Secundaria", "order": 13},
        ],
        "terminology": {
            "teacher": "Docente / Maestro/a",
            "principal": "Director/a",
            "term": "Cuatrimestre",
            "report_card": "Boletin",
            "grade_level": "Año",
        },
    },
    "BO": {  # Bolivia
        "calendar_system": {
            "code": "bo-4-bimestre",
            "label": "4 Bimestres",
            "term_count": 4,
            "term_names": ["Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Cuarto Bimestre"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial en Familia Comunitaria", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-5"},
            {"code": "primaria",     "label": "Educacion Primaria Comunitaria Vocacional", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Educacion Secundaria Comunitaria Productiva", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-17"},
            {"code": "universidad",  "label": "Educacion Superior",                       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bo-i1", "label": "Inicial 1",     "order": 0},
            {"code": "bo-i2", "label": "Inicial 2",     "order": 1},
            {"code": "bo-p1", "label": "1° Primaria", "order": 2},
            {"code": "bo-p6", "label": "6° Primaria", "order": 7},
            {"code": "bo-s1", "label": "1° Secundaria", "order": 8},
            {"code": "bo-s6", "label": "6° Secundaria", "order": 13},
        ],
        "terminology": {
            "teacher": "Maestro/a",
            "principal": "Director/a",
            "term": "Bimestre",
            "report_card": "Boletin",
            "grade_level": "Curso",
        },
    },
    "CL": {  # Chile
        "calendar_system": {
            "code": "cl-2-semestre",
            "label": "2 Semestres",
            "term_count": 2,
            "term_names": ["Primer Semestre", "Segundo Semestre"],
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "parvularia",   "label": "Educacion Parvularia",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "basica",       "label": "Educacion Basica",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "media",        "label": "Educacion Media",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-17"},
            {"code": "tecnico",      "label": "Tecnico Profesional",      "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "14-18"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cl-pk", "label": "Pre-Kinder",       "order": 0},
            {"code": "cl-k",  "label": "Kinder",           "order": 1},
            {"code": "cl-b1", "label": "1° Basico",   "order": 2},
            {"code": "cl-b8", "label": "8° Basico",   "order": 9},
            {"code": "cl-m1", "label": "1° Medio",    "order": 10},
            {"code": "cl-m4", "label": "4° Medio",    "order": 13},
        ],
        "terminology": {
            "teacher": "Profesor/a",
            "principal": "Director/a",
            "term": "Semestre",
            "report_card": "Informe de Notas",
            "grade_level": "Curso",
        },
    },
    "CO": {  # Colombia
        "calendar_system": {
            "code": "co-4-periodo",
            "label": "4 Periodos Academicos",
            "term_count": 4,
            "term_names": ["Primer Periodo", "Segundo Periodo", "Tercer Periodo", "Cuarto Periodo"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preescolar",   "label": "Preescolar",               "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",     "label": "Basica Primaria",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "secundaria",   "label": "Basica Secundaria",        "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "media",        "label": "Educacion Media",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-16"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "co-pj", "label": "Pre-jardin",       "order": 0},
            {"code": "co-j",  "label": "Jardin",           "order": 1},
            {"code": "co-tr", "label": "Transicion",       "order": 2},
            {"code": "co-p1", "label": "Primero",          "order": 3},
            {"code": "co-p5", "label": "Quinto",           "order": 7},
            {"code": "co-s6", "label": "Sexto",            "order": 8},
            {"code": "co-s9", "label": "Noveno",           "order": 11},
            {"code": "co-m10","label": "Decimo",           "order": 12},
            {"code": "co-m11","label": "Once",             "order": 13},
        ],
        "terminology": {
            "teacher": "Profesor/a / Docente",
            "principal": "Rector/a",
            "term": "Periodo",
            "report_card": "Boletin",
            "grade_level": "Grado",
        },
    },
    "CR": {  # Costa Rica
        "calendar_system": {
            "code": "cr-3-trimestre",
            "label": "3 Trimestres",
            "term_count": 3,
            "term_names": ["Primer Trimestre", "Segundo Trimestre", "Tercer Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "maternal",     "label": "Educacion Preescolar (Maternal)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-5"},
            {"code": "primaria",     "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Educacion Secundaria",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "cr-mi", "label": "Materno Infantil", "order": 0},
            {"code": "cr-tr", "label": "Transicion",       "order": 1},
            {"code": "cr-p1", "label": "Primer Grado",     "order": 2},
            {"code": "cr-p6", "label": "Sexto Grado",      "order": 7},
            {"code": "cr-s7", "label": "Setimo",           "order": 8},
            {"code": "cr-s11","label": "Undecimo",         "order": 12},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Trimestre",
            "report_card": "Boleta de Calificaciones",
            "grade_level": "Grado / Año",
        },
    },
    "CU": {  # Cuba
        "calendar_system": {
            "code": "cu-2-semestre",
            "label": "2 Semestres",
            "term_count": 2,
            "term_names": ["Primer Semestre", "Segundo Semestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "circulo",      "label": "Circulo Infantil",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-5"},
            {"code": "primaria",     "label": "Escuela Primaria",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Secundaria Basica",        "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-14"},
            {"code": "preuniv",      "label": "Preuniversitario",         "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cu-pi", "label": "Preescolar",       "order": 0},
            {"code": "cu-p1", "label": "1er Grado",        "order": 1},
            {"code": "cu-p6", "label": "6to Grado",        "order": 6},
            {"code": "cu-s7", "label": "7mo Grado",        "order": 7},
            {"code": "cu-s9", "label": "9no Grado",        "order": 9},
            {"code": "cu-u10","label": "10mo Grado",       "order": 10},
            {"code": "cu-u12","label": "12mo Grado",       "order": 12},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Semestre",
            "report_card": "Boleta de Notas",
            "grade_level": "Grado",
        },
    },
    "DO": {  # Dominican Republic
        "calendar_system": {
            "code": "do-4-periodo",
            "label": "4 Periodos",
            "term_count": 4,
            "term_names": ["Primer Periodo", "Segundo Periodo", "Tercer Periodo", "Cuarto Periodo"],
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "inicial",      "label": "Nivel Inicial",            "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",     "label": "Nivel Primario",           "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Nivel Secundario",         "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "do-i1", "label": "Pre-Primario",     "order": 0},
            {"code": "do-p1", "label": "1ro Primaria",     "order": 1},
            {"code": "do-p6", "label": "6to Primaria",     "order": 6},
            {"code": "do-s1", "label": "1ro Secundaria",   "order": 7},
            {"code": "do-s6", "label": "6to Secundaria",   "order": 12},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Periodo",
            "report_card": "Boletin de Calificaciones",
            "grade_level": "Grado",
        },
    },
    "EC": {  # Ecuador
        "calendar_system": {
            "code": "ec-3-quimestre",
            "label": "2 Quimestres",
            "term_count": 2,
            "term_names": ["Primer Quimestre", "Segundo Quimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "egb",          "label": "Educacion General Basica", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-14"},
            {"code": "bachillerato", "label": "Bachillerato General Unificado", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "15-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ec-i1", "label": "Inicial 1",       "order": 0},
            {"code": "ec-i2", "label": "Inicial 2",       "order": 1},
            {"code": "ec-b1", "label": "1° EGB",     "order": 2},
            {"code": "ec-b7", "label": "7° EGB",     "order": 8},
            {"code": "ec-b10","label": "10° EGB",    "order": 11},
            {"code": "ec-bg1","label": "1° BGU",     "order": 12},
            {"code": "ec-bg3","label": "3° BGU",     "order": 14},
        ],
        "terminology": {
            "teacher": "Docente / Profesor/a",
            "principal": "Rector/a",
            "term": "Quimestre",
            "report_card": "Reporte de Notas",
            "grade_level": "Año",
        },
    },
    "SV": {  # El Salvador
        "calendar_system": {
            "code": "sv-4-periodo",
            "label": "4 Periodos",
            "term_count": 4,
            "term_names": ["Primer Periodo", "Segundo Periodo", "Tercer Periodo", "Cuarto Periodo"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "parvularia",   "label": "Educacion Parvularia",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "basica",       "label": "Educacion Basica",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-15"},
            {"code": "media",        "label": "Educacion Media (Bachillerato)", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "16-18"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "sv-pv", "label": "Parvularia 4-6",  "order": 0},
            {"code": "sv-b1", "label": "1° Grado",   "order": 1},
            {"code": "sv-b9", "label": "9° Grado",   "order": 9},
            {"code": "sv-m1", "label": "1° Bachillerato", "order": 10},
            {"code": "sv-m2", "label": "2° Bachillerato", "order": 11},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Periodo",
            "report_card": "Boleta de Notas",
            "grade_level": "Grado",
        },
    },
    "GT": {  # Guatemala
        "calendar_system": {
            "code": "gt-4-bimestre",
            "label": "4 Bimestres",
            "term_count": 4,
            "term_names": ["Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Cuarto Bimestre"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preprimaria",  "label": "Preprimaria",              "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "primaria",     "label": "Primaria",                 "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-12"},
            {"code": "basicos",      "label": "Ciclo Basico",             "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "13-15"},
            {"code": "diversificado","label": "Diversificado",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "gt-pp", "label": "Parvulos",         "order": 0},
            {"code": "gt-p1", "label": "1° Primaria", "order": 1},
            {"code": "gt-p6", "label": "6° Primaria", "order": 6},
            {"code": "gt-b1", "label": "1° Basico",   "order": 7},
            {"code": "gt-b3", "label": "3° Basico",   "order": 9},
            {"code": "gt-d4", "label": "4° Diversificado", "order": 10},
            {"code": "gt-d6", "label": "6° Diversificado", "order": 12},
        ],
        "terminology": {
            "teacher": "Maestro/a / Catedratico/a",
            "principal": "Director/a",
            "term": "Bimestre",
            "report_card": "Boleta de Calificaciones",
            "grade_level": "Grado",
        },
    },
    "HN": {  # Honduras
        "calendar_system": {
            "code": "hn-3-trimestre",
            "label": "3 Trimestres",
            "term_count": 3,
            "term_names": ["Primer Trimestre", "Segundo Trimestre", "Tercer Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "prebasica",    "label": "Educacion Prebasica",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "basica",       "label": "Educacion Basica",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "media",        "label": "Educacion Media",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "hn-pb", "label": "Prebasica",        "order": 0},
            {"code": "hn-b1", "label": "1° Basica",   "order": 1},
            {"code": "hn-b9", "label": "9° Basica",   "order": 9},
            {"code": "hn-m1", "label": "1° Media",    "order": 10},
            {"code": "hn-m3", "label": "3° Media",    "order": 12},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Trimestre",
            "report_card": "Boleta de Calificaciones",
            "grade_level": "Grado",
        },
    },
    "NI": {  # Nicaragua
        "calendar_system": {
            "code": "ni-4-bimestre",
            "label": "4 Bimestres",
            "term_count": 4,
            "term_names": ["Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Cuarto Bimestre"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "preescolar",   "label": "Educacion Preescolar",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",     "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Educacion Secundaria",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "ni-pe", "label": "Preescolar",       "order": 0},
            {"code": "ni-p1", "label": "1° Primaria", "order": 1},
            {"code": "ni-p6", "label": "6° Primaria", "order": 6},
            {"code": "ni-s1", "label": "1° Secundaria", "order": 7},
            {"code": "ni-s5", "label": "5° Secundaria", "order": 11},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Bimestre",
            "report_card": "Boletin de Calificaciones",
            "grade_level": "Grado",
        },
    },
    "PA": {  # Panama
        "calendar_system": {
            "code": "pa-3-trimestre",
            "label": "3 Trimestres",
            "term_count": 3,
            "term_names": ["Primer Trimestre", "Segundo Trimestre", "Tercer Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "preescolar",   "label": "Educacion Preescolar",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-5"},
            {"code": "primaria",     "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "premedia",     "label": "Premedia",                 "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-14"},
            {"code": "media",        "label": "Media (Bachillerato)",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "pa-pe", "label": "Pre-escolar",      "order": 0},
            {"code": "pa-p1", "label": "1° Primaria", "order": 1},
            {"code": "pa-p6", "label": "6° Primaria", "order": 6},
            {"code": "pa-pm7","label": "7° Premedia", "order": 7},
            {"code": "pa-pm9","label": "9° Premedia", "order": 9},
            {"code": "pa-m10","label": "10° Media",   "order": 10},
            {"code": "pa-m12","label": "12° Media",   "order": 12},
        ],
        "terminology": {
            "teacher": "Educador/a / Profesor/a",
            "principal": "Director/a",
            "term": "Trimestre",
            "report_card": "Boletin",
            "grade_level": "Grado",
        },
    },
    "PY": {  # Paraguay
        "calendar_system": {
            "code": "py-4-periodo",
            "label": "4 Periodos",
            "term_count": 4,
            "term_names": ["Primer Periodo", "Segundo Periodo", "Tercer Periodo", "Cuarto Periodo"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "eeb",          "label": "Educacion Escolar Basica", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "media",        "label": "Educacion Media",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "py-i1", "label": "Maternal",         "order": 0},
            {"code": "py-i2", "label": "Pre-jardin",       "order": 1},
            {"code": "py-i3", "label": "Jardin",           "order": 2},
            {"code": "py-i4", "label": "Preescolar",       "order": 3},
            {"code": "py-e1", "label": "1° EEB",      "order": 4},
            {"code": "py-e9", "label": "9° EEB",      "order": 12},
            {"code": "py-m1", "label": "1° Media",    "order": 13},
            {"code": "py-m3", "label": "3° Media",    "order": 15},
        ],
        "terminology": {
            "teacher": "Docente / Maestro/a",
            "principal": "Director/a",
            "term": "Periodo",
            "report_card": "Libreta de Calificaciones",
            "grade_level": "Grado / Año",
        },
    },
    "PE": {  # Peru
        "calendar_system": {
            "code": "pe-4-bimestre",
            "label": "4 Bimestres",
            "term_count": 4,
            "term_names": ["Primer Bimestre", "Segundo Bimestre", "Tercer Bimestre", "Cuarto Bimestre"],
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",     "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secundaria",   "label": "Educacion Secundaria",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "pe-i3", "label": "Inicial 3 años", "order": 0},
            {"code": "pe-i4", "label": "Inicial 4 años", "order": 1},
            {"code": "pe-i5", "label": "Inicial 5 años", "order": 2},
            {"code": "pe-p1", "label": "1° Primaria", "order": 3},
            {"code": "pe-p6", "label": "6° Primaria", "order": 8},
            {"code": "pe-s1", "label": "1° Secundaria", "order": 9},
            {"code": "pe-s5", "label": "5° Secundaria", "order": 13},
        ],
        "terminology": {
            "teacher": "Profesor/a / Docente",
            "principal": "Director/a",
            "term": "Bimestre",
            "report_card": "Libreta de Notas",
            "grade_level": "Grado / Año",
        },
    },
    "UY": {  # Uruguay
        "calendar_system": {
            "code": "uy-2-semestre",
            "label": "2 Semestres",
            "term_count": 2,
            "term_names": ["Primer Semestre", "Segundo Semestre"],
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaria",     "label": "Educacion Primaria",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "ciclo-basico", "label": "Ciclo Basico (Secundaria)","glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-14"},
            {"code": "bachillerato", "label": "Bachillerato Diversificado","glyph": "\U0001F393", "primary_sector": "secondary",      "typical_ages": "15-17"},
            {"code": "terciaria",    "label": "Educacion Terciaria",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "uy-i3", "label": "Inicial 3",       "order": 0},
            {"code": "uy-i5", "label": "Inicial 5",       "order": 2},
            {"code": "uy-p1", "label": "1° Primaria", "order": 3},
            {"code": "uy-p6", "label": "6° Primaria", "order": 8},
            {"code": "uy-cb1","label": "1° CB",      "order": 9},
            {"code": "uy-cb3","label": "3° CB",      "order": 11},
            {"code": "uy-b4", "label": "4° Bachillerato", "order": 12},
            {"code": "uy-b6", "label": "6° Bachillerato", "order": 14},
        ],
        "terminology": {
            "teacher": "Maestro/a / Profesor/a",
            "principal": "Director/a",
            "term": "Semestre",
            "report_card": "Carne de Calificaciones",
            "grade_level": "Año",
        },
    },
    "VE": {  # Venezuela
        "calendar_system": {
            "code": "ve-3-lapso",
            "label": "3 Lapsos",
            "term_count": 3,
            "term_names": ["Primer Lapso", "Segundo Lapso", "Tercer Lapso"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "inicial",      "label": "Educacion Inicial",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "basica",       "label": "Educacion Primaria (Basica)", "glyph": "\U0001F3EB", "primary_sector": "primary",      "typical_ages": "6-11"},
            {"code": "media",        "label": "Educacion Media General",  "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "universidad",  "label": "Universidad",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "ve-im", "label": "Maternal",         "order": 0},
            {"code": "ve-ip", "label": "Preescolar",       "order": 1},
            {"code": "ve-b1", "label": "1er Grado",        "order": 2},
            {"code": "ve-b6", "label": "6to Grado",        "order": 7},
            {"code": "ve-m1", "label": "1er Año",     "order": 8},
            {"code": "ve-m5", "label": "5to Año",     "order": 12},
        ],
        "terminology": {
            "teacher": "Docente / Profesor/a",
            "principal": "Director/a",
            "term": "Lapso",
            "report_card": "Boletin de Notas",
            "grade_level": "Grado / Año",
        },
    },
    # ============================================================
    # CARIBBEAN - ANGLOPHONE (12 countries, British-influenced)
    # ============================================================
    "AG": {  # Antigua and Barbuda
        "calendar_system": {
            "code": "ag-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["Michaelmas Term", "Lent Term", "Trinity Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form / A-Levels",     "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University / College",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ag-k",  "label": "Kindergarten",     "order": 0},
            {"code": "ag-p1", "label": "Grade 1",          "order": 1},
            {"code": "ag-p6", "label": "Grade 6",          "order": 6},
            {"code": "ag-f1", "label": "Form 1",           "order": 7},
            {"code": "ag-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "ag-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "ag-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Class",
        },
    },
    "BS": {  # Bahamas
        "calendar_system": {
            "code": "bs-3-term",
            "label": "3 Terms (Sept-June)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "junior-high", "label": "Junior High School",        "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-14"},
            {"code": "senior-high", "label": "Senior High School",        "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "college",     "label": "College / University",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bs-k",  "label": "Kindergarten",     "order": 0},
            {"code": "bs-p1", "label": "Grade 1",          "order": 1},
            {"code": "bs-p6", "label": "Grade 6",          "order": 6},
            {"code": "bs-j7", "label": "Grade 7",          "order": 7},
            {"code": "bs-j9", "label": "Grade 9",          "order": 9},
            {"code": "bs-s10","label": "Grade 10",         "order": 10},
            {"code": "bs-s12","label": "Grade 12 (BGCSE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "BB": {  # Barbados
        "calendar_system": {
            "code": "bb-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["Michaelmas Term", "Lent Term", "Trinity Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery",     "label": "Nursery School",            "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-10"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "11-16"},
            {"code": "sixth-form",  "label": "Sixth Form",                "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University / Polytechnic",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bb-r",  "label": "Reception",        "order": 0},
            {"code": "bb-i1", "label": "Infants 1",        "order": 1},
            {"code": "bb-i2", "label": "Infants 2",        "order": 2},
            {"code": "bb-c1", "label": "Class 1",          "order": 3},
            {"code": "bb-c4", "label": "Class 4",          "order": 6},
            {"code": "bb-f1", "label": "Form 1",           "order": 7},
            {"code": "bb-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "bb-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "bb-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Class",
        },
    },
    "BZ": {  # Belize
        "calendar_system": {
            "code": "bz-3-term",
            "label": "3 Terms (Sept-June)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "secondary",   "label": "Secondary School / High School", "glyph": "\U0001F393", "primary_sector": "secondary",   "typical_ages": "14-17"},
            {"code": "sixth-form",  "label": "Sixth Form / Junior College","glyph": "\U0001F4DA", "primary_sector": "post_secondary",  "typical_ages": "17-19"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bz-i1", "label": "Infant 1",         "order": 0},
            {"code": "bz-i2", "label": "Infant 2",         "order": 1},
            {"code": "bz-s1", "label": "Standard 1",       "order": 2},
            {"code": "bz-s6", "label": "Standard 6 (PSE)", "order": 7},
            {"code": "bz-f1", "label": "Form 1",           "order": 8},
            {"code": "bz-f4", "label": "Form 4 (CSEC)",    "order": 11},
            {"code": "bz-jc1","label": "Junior College Yr 1", "order": 12},
            {"code": "bz-jc2","label": "Junior College Yr 2", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Standard / Form",
        },
    },
    "DM": {  # Dominica
        "calendar_system": {
            "code": "dm-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["Michaelmas Term", "Lent Term", "Trinity Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form College",        "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "Community College / University","glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "dm-k",  "label": "Kindergarten",     "order": 0},
            {"code": "dm-p1", "label": "Grade 1",          "order": 1},
            {"code": "dm-p6", "label": "Grade 6 (CEE)",    "order": 6},
            {"code": "dm-f1", "label": "Form 1",           "order": 7},
            {"code": "dm-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "dm-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "dm-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Grade",
        },
    },
    "GD": {  # Grenada
        "calendar_system": {
            "code": "gd-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Advanced Level / Sixth Form","glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gd-k",  "label": "Kindergarten",     "order": 0},
            {"code": "gd-p1", "label": "Grade 1",          "order": 1},
            {"code": "gd-p6", "label": "Grade 6",          "order": 6},
            {"code": "gd-f1", "label": "Form 1",           "order": 7},
            {"code": "gd-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "gd-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "gd-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Grade",
        },
    },
    "GY": {  # Guyana
        "calendar_system": {
            "code": "gy-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery",     "label": "Nursery School",            "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form",                "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gy-n1", "label": "Nursery 1",        "order": 0},
            {"code": "gy-n2", "label": "Nursery 2",        "order": 1},
            {"code": "gy-p1", "label": "Grade 1",          "order": 2},
            {"code": "gy-p6", "label": "Grade 6 (NGSA)",   "order": 7},
            {"code": "gy-f1", "label": "Form 1",           "order": 8},
            {"code": "gy-f5", "label": "Form 5 (CSEC)",    "order": 12},
            {"code": "gy-f6l","label": "Lower Sixth",      "order": 13},
            {"code": "gy-f6u","label": "Upper Sixth (CAPE)","order": 14},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Headteacher / Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Grade",
        },
    },
    "JM": {  # Jamaica
        "calendar_system": {
            "code": "jm-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["Christmas Term", "Easter Term", "Summer Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "basic",       "label": "Basic / Infant School",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "secondary",   "label": "Secondary / High School",   "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form",                "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University / College",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "jm-k",  "label": "Kindergarten",     "order": 0},
            {"code": "jm-g1", "label": "Grade 1",          "order": 1},
            {"code": "jm-g6", "label": "Grade 6 (PEP)",    "order": 6},
            {"code": "jm-g7", "label": "Grade 7",          "order": 7},
            {"code": "jm-g11","label": "Grade 11 (CSEC)",  "order": 11},
            {"code": "jm-g12","label": "Grade 12 / Lower Sixth","order": 12},
            {"code": "jm-g13","label": "Grade 13 / Upper Sixth (CAPE)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Grade",
        },
    },
    "KN": {  # Saint Kitts and Nevis
        "calendar_system": {
            "code": "kn-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form College",        "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "kn-k",  "label": "Kindergarten",     "order": 0},
            {"code": "kn-g1", "label": "Grade 1",          "order": 1},
            {"code": "kn-g6", "label": "Grade 6",          "order": 6},
            {"code": "kn-f1", "label": "Form 1",           "order": 7},
            {"code": "kn-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "kn-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "kn-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Grade",
        },
    },
    "LC": {  # Saint Lucia
        "calendar_system": {
            "code": "lc-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sir Arthur Lewis Community College / Sixth Form","glyph": "\U0001F393", "primary_sector": "post_secondary", "typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "lc-k",  "label": "Kindergarten",     "order": 0},
            {"code": "lc-i1", "label": "Infants 1",        "order": 1},
            {"code": "lc-i2", "label": "Infants 2",        "order": 2},
            {"code": "lc-s1", "label": "Standard 1",       "order": 3},
            {"code": "lc-s5", "label": "Standard 5 (CEE)", "order": 7},
            {"code": "lc-f1", "label": "Form 1",           "order": 8},
            {"code": "lc-f5", "label": "Form 5 (CSEC)",    "order": 12},
            {"code": "lc-f6l","label": "Lower Sixth",      "order": 13},
            {"code": "lc-f6u","label": "Upper Sixth (CAPE)","order": 14},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Standard",
        },
    },
    "VC": {  # Saint Vincent and the Grenadines
        "calendar_system": {
            "code": "vc-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-school",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "community-coll","label": "Community College / Sixth Form","glyph": "\U0001F393", "primary_sector": "post_secondary","typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "vc-k",  "label": "Kindergarten",     "order": 0},
            {"code": "vc-p1", "label": "Grade 1",          "order": 1},
            {"code": "vc-p6", "label": "Grade 6 (CPEA)",   "order": 6},
            {"code": "vc-f1", "label": "Form 1",           "order": 7},
            {"code": "vc-f5", "label": "Form 5 (CSEC)",    "order": 11},
            {"code": "vc-f6l","label": "Lower Sixth",      "order": 12},
            {"code": "vc-f6u","label": "Upper Sixth (CAPE)","order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Grade",
        },
    },
    "TT": {  # Trinidad and Tobago
        "calendar_system": {
            "code": "tt-3-term",
            "label": "3 Terms (Sept-July)",
            "term_count": 3,
            "term_names": ["Michaelmas Term", "Hilary Term", "Trinity Term"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "ecce",        "label": "Early Childhood Care & Education", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-4"},
            {"code": "primary",     "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",          "glyph": "\U0001F4DA", "primary_sector": "secondary",       "typical_ages": "12-16"},
            {"code": "sixth-form",  "label": "Sixth Form",                "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "17-18"},
            {"code": "university",  "label": "University",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "tt-ec", "label": "ECCE",             "order": 0},
            {"code": "tt-i1", "label": "Infants 1",        "order": 1},
            {"code": "tt-i2", "label": "Infants 2",        "order": 2},
            {"code": "tt-s1", "label": "Standard 1",       "order": 3},
            {"code": "tt-s5", "label": "Standard 5 (SEA)", "order": 7},
            {"code": "tt-f1", "label": "Form 1",           "order": 8},
            {"code": "tt-f5", "label": "Form 5 (CSEC)",    "order": 12},
            {"code": "tt-f6l","label": "Lower Sixth",      "order": 13},
            {"code": "tt-f6u","label": "Upper Sixth (CAPE)","order": 14},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Form / Standard",
        },
    },
    # ============================================================
    # CARIBBEAN - NON-ANGLOPHONE (2 countries)
    # ============================================================
    "HT": {  # Haiti (Franco-Creole bilingual)
        "calendar_system": {
            "code": "ht-3-trimestre",
            "label": "3 Trimestres (Sept-Juin)",
            "term_count": 3,
            "term_names": ["Premier Trimestre", "Deuxieme Trimestre", "Troisieme Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kindergarten", "label": "Jaden Timoun / Kindergarten / Maternelle", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primaire",     "label": "Ekol Primer / Enseignement Primaire (Fondamental I-II)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "secondaire",   "label": "Ekol Segonde / Enseignement Secondaire (Fondamental III + Secondaire)", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "12-18"},
            {"code": "professionnel","label": "Inivesite Pwofesyonel / Formation Professionnelle", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "15+"},
            {"code": "universite",   "label": "Inivesite / Universite",   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "ht-m1", "label": "Maternelle / Jaden 1", "order": 0},
            {"code": "ht-m3", "label": "Maternelle 3 / Preparatoire", "order": 2},
            {"code": "ht-af1","label": "1ere Annee Fondamentale", "order": 3},
            {"code": "ht-af6","label": "6eme Annee Fondamentale", "order": 8},
            {"code": "ht-af9","label": "9eme Annee Fondamentale", "order": 11},
            {"code": "ht-s1", "label": "Seconde",         "order": 12},
            {"code": "ht-s2", "label": "Rheto (1ere)",    "order": 13},
            {"code": "ht-s3", "label": "Philo (Terminale - Bac)", "order": 14},
        ],
        "terminology": {
            "teacher": "Pwofese / Professeur (Met)",
            "principal": "Direkte / Directeur",
            "term": "Trimes / Trimestre",
            "report_card": "Kane / Bulletin",
            "grade_level": "Klas / Classe",
        },
    },
    "SR": {  # Suriname (Dutch system)
        "calendar_system": {
            "code": "sr-3-trimester",
            "label": "3 Trimesters (Okt-Aug)",
            "term_count": 3,
            "term_names": ["Eerste Trimester", "Tweede Trimester", "Derde Trimester"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "kleuter",      "label": "Kleuteronderwijs",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-5"},
            {"code": "basis",        "label": "Basisonderwijs (GLO)",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "voj",          "label": "Voortgezet Onderwijs Junioren (VOJ)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "vos",          "label": "Voortgezet Onderwijs Senioren (VOS)", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "16-18"},
            {"code": "beroep",       "label": "Beroepsonderwijs",         "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15+"},
            {"code": "universiteit", "label": "Universiteit (Anton de Kom)","glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sr-k1", "label": "Kleuter 1",       "order": 0},
            {"code": "sr-k2", "label": "Kleuter 2",       "order": 1},
            {"code": "sr-g1", "label": "GLO Klas 1",      "order": 2},
            {"code": "sr-g6", "label": "GLO Klas 6 (GLO-toets)", "order": 7},
            {"code": "sr-vj1","label": "VOJ Klas 1",      "order": 8},
            {"code": "sr-vj4","label": "VOJ Klas 4 (Mulo)", "order": 11},
            {"code": "sr-vs1","label": "VOS Klas 1",      "order": 12},
            {"code": "sr-vs4","label": "VOS Klas 4 (VWO-eindexamen)", "order": 15},
        ],
        "terminology": {
            "teacher": "Leerkracht / Leraar",
            "principal": "Directeur / Schoolhoofd",
            "term": "Trimester",
            "report_card": "Rapport",
            "grade_level": "Klas",
        },
    },
}
