"""Africa Tier 1 extension - 45 hand-researched countries.

Appended into COUNTRY_LOCALIZATION at import time by _seed_country_localization.py.
Each country gets full detail (calendar + school_types + education_levels + terminology)
with country-LOCAL labels (not generic Anglo defaults).

Authoring notes:
- Francophone Africa: "Maternelle / Primaire / College / Lycee / Universite"
  + "Enseignant / Directeur / Trimestre / Bulletin / Niveau", 3-trimester usually Sept/Oct start.
- Anglophone Africa: "Nursery / Primary / JSS / SSS" or "Junior/Senior High" variants.
- Lusophone Africa: "Pre-Escolar / Primario / Secundario / Superior"
  + "Professor / Diretor / Trimestre / Boletim / Ano".
- Arabic-North Africa: bilingual Arabic + French labels where French is taught.
- All emoji as unicode escapes to avoid encoding issues on Windows codepages.
"""

AFRICA_EXTENSION = {
    "DZ": {  # Algeria
        "calendar_system": {
            "code": "dz-3-trimester",
            "label": "3 Trimestres (Algerian)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 0,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "creche",     "label": "Creche / حضانة",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "ibtidaiya",  "label": "Primaire / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "mutawasita", "label": "College (CEM) / متوسط",    "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "11-15"},
            {"code": "thanawiya",  "label": "Lycee / ثانوي",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universite", "label": "Universite / جامعة",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "dz-1ap", "label": "1ere AP",     "order": 1},
            {"code": "dz-5ap", "label": "5eme AP",     "order": 5},
            {"code": "dz-1am", "label": "1ere AM",     "order": 6},
            {"code": "dz-4am", "label": "4eme AM (BEM)", "order": 9},
            {"code": "dz-1sec","label": "1ere Sec",    "order": 10},
            {"code": "dz-3sec","label": "3eme Sec (BAC)", "order": 12},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre / فصل",
            "report_card": "Bulletin / كشف نقاط",
            "grade_level": "Niveau / مستوى",
        },
    },
    "AO": {  # Angola
        "calendar_system": {
            "code": "ao-3-trimester",
            "label": "3 Trimestres (Angolano)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "pre-escolar",   "label": "Ensino Pre-Escolar",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primario",      "label": "Ensino Primario",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "i-ciclo-sec",   "label": "I Ciclo do Secundario",   "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "ii-ciclo-sec",  "label": "II Ciclo do Secundario",  "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "superior",      "label": "Ensino Superior",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ao-1cl", "label": "1ª Classe", "order": 1},
            {"code": "ao-6cl", "label": "6ª Classe", "order": 6},
            {"code": "ao-9cl", "label": "9ª Classe", "order": 9},
            {"code": "ao-12cl","label": "12ª Classe", "order": 12},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Trimestre",
            "report_card": "Boletim",
            "grade_level": "Classe",
        },
    },
    "BJ": {  # Benin
        "calendar_system": {
            "code": "bj-3-trimester",
            "label": "3 Trimestres (Beninois)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",    "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College (CEG)",  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "bj-ci",   "label": "CI",      "order": 1},
            {"code": "bj-cm2",  "label": "CM2",     "order": 6},
            {"code": "bj-6e",   "label": "6eme",    "order": 7},
            {"code": "bj-3e",   "label": "3eme (BEPC)", "order": 10},
            {"code": "bj-2nd",  "label": "Seconde", "order": 11},
            {"code": "bj-tle",  "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "BW": {  # Botswana
        "calendar_system": {
            "code": "bw-3-term",
            "label": "3 Terms (Botswana)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-primary", "label": "Pre-Primary",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "junior-sec",  "label": "Junior Secondary",   "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "senior-sec",  "label": "Senior Secondary",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "university",  "label": "University",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bw-std1", "label": "Standard 1",  "order": 1},
            {"code": "bw-std7", "label": "Standard 7 (PSLE)", "order": 7},
            {"code": "bw-form1","label": "Form 1",      "order": 8},
            {"code": "bw-form3","label": "Form 3 (JCE)","order": 10},
            {"code": "bw-form5","label": "Form 5 (BGCSE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Morutabana",
            "principal": "Headteacher / Mogokgo",
            "term": "Term / Kgwedi",
            "report_card": "Report Card",
            "grade_level": "Standard / Form",
        },
    },
    "BF": {  # Burkina Faso
        "calendar_system": {
            "code": "bf-3-trimester",
            "label": "3 Trimestres (Burkinabe)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",    "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College (CEG)",  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "bf-cp1",  "label": "CP1",          "order": 1},
            {"code": "bf-cm2",  "label": "CM2 (CEP)",    "order": 6},
            {"code": "bf-6e",   "label": "6eme",         "order": 7},
            {"code": "bf-3e",   "label": "3eme (BEPC)",  "order": 10},
            {"code": "bf-tle",  "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "BI": {  # Burundi
        "calendar_system": {
            "code": "bi-3-trimester",
            "label": "3 Trimestres (Burundais)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle",     "label": "Ecole Maternelle",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "fondamentale",   "label": "Ecole Fondamentale", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "post-fondamentale", "label": "Post-Fondamentale", "glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "15-19"},
            {"code": "universite",     "label": "Universite",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "bi-1f",  "label": "1ere Fondamentale", "order": 1},
            {"code": "bi-9f",  "label": "9eme Fondamentale", "order": 9},
            {"code": "bi-1pf", "label": "1ere Post-Fondamentale", "order": 10},
            {"code": "bi-4pf", "label": "4eme Post-Fondamentale (Etat)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / Umwarimu",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "CV": {  # Cabo Verde
        "calendar_system": {
            "code": "cv-3-trimester",
            "label": "3 Trimestres (Cabo-verdiano)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "pre-escolar", "label": "Pre-Escolar",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "basico",      "label": "Ensino Basico",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "secundario",  "label": "Ensino Secundario",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "superior",    "label": "Ensino Superior",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cv-1ano",  "label": "1º Ano",  "order": 1},
            {"code": "cv-8ano",  "label": "8º Ano",  "order": 8},
            {"code": "cv-9ano",  "label": "9º Ano",  "order": 9},
            {"code": "cv-12ano", "label": "12º Ano", "order": 12},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Trimestre",
            "report_card": "Boletim",
            "grade_level": "Ano",
        },
    },
    "CM": {  # Cameroon (bilingual FR/EN)
        "calendar_system": {
            "code": "cm-3-trimester",
            "label": "3 Trimestres / 3 Terms (Cameroon)",
            "term_count": 3,
            "term_names": ["Trimestre 1 / Term 1", "Trimestre 2 / Term 2", "Trimestre 3 / Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / Nursery",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire / Primary",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College / Secondary (1st cycle)", "glyph": "\U0001F3EB", "primary_sector": "middle",      "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee / High School",         "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite / University",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "cm-sil",  "label": "SIL / Class 1",   "order": 1},
            {"code": "cm-cm2",  "label": "CM2 / Class 6 (CEP/FSLC)", "order": 6},
            {"code": "cm-6e",   "label": "6eme / Form 1",   "order": 7},
            {"code": "cm-3e",   "label": "3eme / Form 4 (BEPC/GCE-OL)", "order": 10},
            {"code": "cm-tle",  "label": "Terminale / Upper Sixth (BAC/GCE-AL)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / Teacher",
            "principal": "Directeur / Principal",
            "term": "Trimestre / Term",
            "report_card": "Bulletin / Report Card",
            "grade_level": "Niveau / Class",
        },
    },
    "CF": {  # Central African Republic
        "calendar_system": {
            "code": "cf-3-trimester",
            "label": "3 Trimestres (Centrafricain)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",    "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College",        "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "cf-cp1", "label": "CP1",         "order": 1},
            {"code": "cf-cm2", "label": "CM2 (CEPE)",  "order": 6},
            {"code": "cf-6e",  "label": "6eme",        "order": 7},
            {"code": "cf-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "cf-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "TD": {  # Chad
        "calendar_system": {
            "code": "td-3-trimester",
            "label": "3 Trimestres (Tchadien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / حضانة",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "college",    "label": "College / إعدادي", "glyph": "\U0001F3EB", "primary_sector": "middle",     "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee / ثانوي",        "glyph": "\U0001F393", "primary_sector": "secondary",  "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite / جامعة",   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",  "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "td-cp1", "label": "CP1",        "order": 1},
            {"code": "td-cm2", "label": "CM2 (CEPE)", "order": 6},
            {"code": "td-6e",  "label": "6eme",       "order": 7},
            {"code": "td-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "td-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre / فصل",
            "report_card": "Bulletin / كشف نقاط",
            "grade_level": "Niveau / مستوى",
        },
    },
    "KM": {  # Comoros
        "calendar_system": {
            "code": "km-3-trimester",
            "label": "3 Trimestres (Comorien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College",          "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "km-cp1", "label": "CP1",         "order": 1},
            {"code": "km-cm2", "label": "CM2 (CEPE)",  "order": 6},
            {"code": "km-6e",  "label": "6eme",        "order": 7},
            {"code": "km-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "km-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "CG": {  # Republic of Congo (Brazzaville)
        "calendar_system": {
            "code": "cg-3-trimester",
            "label": "3 Trimestres (Congolais)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",    "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College (CEG)",  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "cg-cp1", "label": "CP1",         "order": 1},
            {"code": "cg-cm2", "label": "CM2 (CEPE)",  "order": 6},
            {"code": "cg-6e",  "label": "6eme",        "order": 7},
            {"code": "cg-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "cg-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "CD": {  # DR Congo (Kinshasa)
        "calendar_system": {
            "code": "cd-3-trimester",
            "label": "3 Trimestres (Congolais RDC)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle",      "label": "Maternelle",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",        "label": "Primaire",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secondaire",      "label": "Humanites (Secondaire)", "glyph": "\U0001F393", "primary_sector": "secondary",   "typical_ages": "12-18"},
            {"code": "universite",      "label": "Universite",          "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cd-1p", "label": "1ere Primaire",         "order": 1},
            {"code": "cd-6p", "label": "6eme Primaire (TENAFEP)", "order": 6},
            {"code": "cd-1s", "label": "1ere Humanites",        "order": 7},
            {"code": "cd-6s", "label": "6eme Humanites (Exetat)", "order": 12},
        ],
        "terminology": {
            "teacher": "Enseignant / Mwalimu",
            "principal": "Prefet / Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "CI": {  # Cote d'Ivoire
        "calendar_system": {
            "code": "ci-3-trimester",
            "label": "3 Trimestres (Ivoirien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College",          "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "ci-cp1", "label": "CP1",         "order": 1},
            {"code": "ci-cm2", "label": "CM2 (CEPE)",  "order": 6},
            {"code": "ci-6e",  "label": "6eme",        "order": 7},
            {"code": "ci-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "ci-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "DJ": {  # Djibouti
        "calendar_system": {
            "code": "dj-3-trimester",
            "label": "3 Trimestres (Djiboutien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 0,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / حضانة", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "college",    "label": "College / إعدادي", "glyph": "\U0001F3EB", "primary_sector": "middle", "typical_ages": "11-15"},
            {"code": "lycee",      "label": "Lycee / ثانوي",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universite", "label": "Universite / جامعة", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",   "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "dj-cp1", "label": "CP1",         "order": 1},
            {"code": "dj-cm2", "label": "CM2",         "order": 6},
            {"code": "dj-6e",  "label": "6eme",        "order": 7},
            {"code": "dj-3e",  "label": "3eme (BEF)",  "order": 10},
            {"code": "dj-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre / فصل",
            "report_card": "Bulletin / كشف نقاط",
            "grade_level": "Niveau / مستوى",
        },
    },
    "GQ": {  # Equatorial Guinea (Spanish + French)
        "calendar_system": {
            "code": "gq-3-trimester",
            "label": "3 Trimestres (Ecuatoguineano)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preescolar", "label": "Educacion Preescolar",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaria",   "label": "Educacion Primaria",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secundaria", "label": "Educacion Secundaria (ESBA)", "glyph": "\U0001F3EB", "primary_sector": "middle",         "typical_ages": "12-16"},
            {"code": "bachiller",  "label": "Bachillerato",                "glyph": "\U0001F393", "primary_sector": "secondary",      "typical_ages": "16-18"},
            {"code": "universidad", "label": "Universidad",                "glyph": "\U0001F3DB", "primary_sector": "higher_ed",      "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gq-1p",  "label": "1º de Primaria", "order": 1},
            {"code": "gq-6p",  "label": "6º de Primaria", "order": 6},
            {"code": "gq-1eso","label": "1º ESBA",        "order": 7},
            {"code": "gq-4eso","label": "4º ESBA",        "order": 10},
            {"code": "gq-2bac","label": "2º Bachillerato", "order": 12},
        ],
        "terminology": {
            "teacher": "Profesor",
            "principal": "Director",
            "term": "Trimestre",
            "report_card": "Boletin de Notas",
            "grade_level": "Curso",
        },
    },
    "ER": {  # Eritrea
        "calendar_system": {
            "code": "er-2-semester",
            "label": "2 Semesters (Eritrean)",
            "term_count": 2,
            "term_names": ["Semester 1", "Semester 2"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kindergarten", "label": "Kindergarten",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "5-7"},
            {"code": "elementary",   "label": "Elementary School",    "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-12"},
            {"code": "middle",       "label": "Middle School",        "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "secondary",    "label": "Secondary School",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "university",   "label": "University / College",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "er-g1",  "label": "Grade 1",  "order": 1},
            {"code": "er-g5",  "label": "Grade 5",  "order": 5},
            {"code": "er-g8",  "label": "Grade 8",  "order": 8},
            {"code": "er-g12", "label": "Grade 12 (ESECE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Director",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "SZ": {  # Eswatini (formerly Swaziland)
        "calendar_system": {
            "code": "sz-3-term",
            "label": "3 Terms (Eswatini)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-primary", "label": "Pre-Primary",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",      "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "junior-sec",  "label": "Junior Secondary",    "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "senior-sec",  "label": "Senior Secondary",    "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "university",  "label": "University",          "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sz-g1",   "label": "Grade 1",    "order": 1},
            {"code": "sz-g7",   "label": "Grade 7 (EPC)", "order": 7},
            {"code": "sz-form1","label": "Form 1",     "order": 8},
            {"code": "sz-form3","label": "Form 3 (JC)", "order": 10},
            {"code": "sz-form5","label": "Form 5 (SGCSE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Thishela",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Grade / Form",
        },
    },
    "GA": {  # Gabon
        "calendar_system": {
            "code": "ga-3-trimester",
            "label": "3 Trimestres (Gabonais)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College",          "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "ga-cp1", "label": "CP1",         "order": 1},
            {"code": "ga-cm2", "label": "CM2 (CEP)",   "order": 6},
            {"code": "ga-6e",  "label": "6eme",        "order": 7},
            {"code": "ga-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "ga-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "GM": {  # Gambia
        "calendar_system": {
            "code": "gm-3-term",
            "label": "3 Terms (Gambian)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery",     "label": "Nursery School",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "lower-basic", "label": "Lower Basic School",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-13"},
            {"code": "upper-basic", "label": "Upper Basic School",     "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "senior-sec",  "label": "Senior Secondary",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "university",  "label": "University",             "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "gm-g1",  "label": "Grade 1",  "order": 1},
            {"code": "gm-g6",  "label": "Grade 6",  "order": 6},
            {"code": "gm-g9",  "label": "Grade 9 (GABECE)", "order": 9},
            {"code": "gm-g12", "label": "Grade 12 (WASSCE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "GN": {  # Guinea (Conakry)
        "calendar_system": {
            "code": "gn-3-trimester",
            "label": "3 Trimestres (Guineen)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "primaire",   "label": "Primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-13"},
            {"code": "college",    "label": "College",          "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-17"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "17-20"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "20+"},
        ],
        "education_levels": [
            {"code": "gn-cp1", "label": "CP1",         "order": 1},
            {"code": "gn-cm2", "label": "CM2 (CEPE)",  "order": 6},
            {"code": "gn-7e",  "label": "7eme",        "order": 7},
            {"code": "gn-10e", "label": "10eme (BEPC)", "order": 10},
            {"code": "gn-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "GW": {  # Guinea-Bissau
        "calendar_system": {
            "code": "gw-3-trimester",
            "label": "3 Trimestres (Guineense)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "pre-escolar", "label": "Ensino Pre-Escolar",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "basico",      "label": "Ensino Basico",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-13"},
            {"code": "secundario",  "label": "Ensino Secundario",      "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "superior",    "label": "Ensino Superior",        "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gw-1ano",  "label": "1º Ano",  "order": 1},
            {"code": "gw-6ano",  "label": "6º Ano",  "order": 6},
            {"code": "gw-9ano",  "label": "9º Ano",  "order": 9},
            {"code": "gw-11ano", "label": "11º Ano", "order": 11},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Trimestre",
            "report_card": "Boletim",
            "grade_level": "Ano",
        },
    },
    "LS": {  # Lesotho
        "calendar_system": {
            "code": "ls-3-term",
            "label": "3 Terms (Lesotho)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "ecd",         "label": "Early Childhood (ECCD)",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "junior-sec",  "label": "Junior Secondary",        "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "senior-sec",  "label": "Senior Secondary (High)", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "university",  "label": "University",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ls-std1",  "label": "Standard 1",  "order": 1},
            {"code": "ls-std7",  "label": "Standard 7 (PSLE)", "order": 7},
            {"code": "ls-form1", "label": "Form A",      "order": 8},
            {"code": "ls-form3", "label": "Form C (JC)", "order": 10},
            {"code": "ls-form5", "label": "Form E (LGCSE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Mosuoe",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Standard / Form",
        },
    },
    "LR": {  # Liberia
        "calendar_system": {
            "code": "lr-2-semester",
            "label": "2 Semesters (Liberian)",
            "term_count": 2,
            "term_names": ["First Semester", "Second Semester"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-School / Kindergarten", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "elementary",  "label": "Elementary School",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "junior-high", "label": "Junior High School",        "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "senior-high", "label": "Senior High School",        "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "university",  "label": "University / College",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "lr-g1",  "label": "Grade 1",  "order": 1},
            {"code": "lr-g6",  "label": "Grade 6",  "order": 6},
            {"code": "lr-g9",  "label": "Grade 9 (WAEC JSCE)", "order": 9},
            {"code": "lr-g12", "label": "Grade 12 (WASSCE)",   "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "LY": {  # Libya
        "calendar_system": {
            "code": "ly-3-trimester",
            "label": "3 Trimestres (Libyan)",
            "term_count": 3,
            "term_names": ["الفصل 1 / Term 1", "الفصل 2 / Term 2", "الفصل 3 / Term 3"],
            "week_start": 0,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "rawda",     "label": "Rawda (Kindergarten) / روضة", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "ibtidaiya", "label": "Primary / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "iadadiya",  "label": "Preparatory / إعدادي", "glyph": "\U0001F3EB", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "thanawiya", "label": "Secondary / ثانوي",  "glyph": "\U0001F393", "primary_sector": "secondary",   "typical_ages": "15-18"},
            {"code": "jamia",     "label": "University / جامعة",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",   "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ly-g1",  "label": "Grade 1 / الصف 1",  "order": 1},
            {"code": "ly-g6",  "label": "Grade 6 / الصف 6",  "order": 6},
            {"code": "ly-g9",  "label": "Grade 9 (BEC) / الصف 9",  "order": 9},
            {"code": "ly-g12", "label": "Grade 12 (Thanawiya) / الصف 12", "order": 12},
        ],
        "terminology": {
            "teacher": "معلم / Teacher",
            "principal": "مدير / Headmaster",
            "term": "فصل / Term",
            "report_card": "كشف نقاط / Report Card",
            "grade_level": "صف / Grade",
        },
    },
    "MG": {  # Madagascar
        "calendar_system": {
            "code": "mg-3-trimester",
            "label": "3 Trimestres (Malgache)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire (EPP)",   "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "college",    "label": "College (CEG)",    "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "11-15"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mg-cp1", "label": "CP1 (T1)",    "order": 1},
            {"code": "mg-cm2", "label": "CM2 (CEPE)",  "order": 5},
            {"code": "mg-6e",  "label": "6eme",        "order": 6},
            {"code": "mg-3e",  "label": "3eme (BEPC)", "order": 9},
            {"code": "mg-tle", "label": "Terminale (BAC)", "order": 12},
        ],
        "terminology": {
            "teacher": "Enseignant / Mpampianatra",
            "principal": "Directeur / Talen-tsekoly",
            "term": "Trimestre",
            "report_card": "Bulletin / Bokim-pankavanana",
            "grade_level": "Niveau / Kilasy",
        },
    },
    "MW": {  # Malawi
        "calendar_system": {
            "code": "mw-3-term",
            "label": "3 Terms (Malawi)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "ecd",         "label": "Early Childhood Development", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",              "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "secondary",   "label": "Secondary School",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "university",  "label": "University / College",        "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mw-std1",  "label": "Standard 1",  "order": 1},
            {"code": "mw-std8",  "label": "Standard 8 (PSLCE)", "order": 8},
            {"code": "mw-form1", "label": "Form 1",      "order": 9},
            {"code": "mw-form2", "label": "Form 2 (JCE)", "order": 10},
            {"code": "mw-form4", "label": "Form 4 (MSCE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Mphunzitsi",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Standard / Form",
        },
    },
    "ML": {  # Mali
        "calendar_system": {
            "code": "ml-3-trimester",
            "label": "3 Trimestres (Malien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle",   "label": "Jardin d'enfants",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "fondamentale-1", "label": "Fondamental 1er Cycle",  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-13"},
            {"code": "fondamentale-2", "label": "Fondamental 2nd Cycle",  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "lycee",        "label": "Lycee / Secondaire",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite",   "label": "Universite",               "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "ml-1af", "label": "1ere AF",        "order": 1},
            {"code": "ml-6af", "label": "6eme AF (CEP)",  "order": 6},
            {"code": "ml-7af", "label": "7eme AF",        "order": 7},
            {"code": "ml-9af", "label": "9eme AF (DEF)",  "order": 9},
            {"code": "ml-tle", "label": "Terminale (BAC)", "order": 12},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "MR": {  # Mauritania (Arabic + French)
        "calendar_system": {
            "code": "mr-3-trimester",
            "label": "3 Trimestres (Mauritanien)",
            "term_count": 3,
            "term_names": ["Trimestre 1 / الفصل 1", "Trimestre 2 / الفصل 2", "Trimestre 3 / الفصل 3"],
            "week_start": 0,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / حضانة",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "ibtidaiya",  "label": "Primaire / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "iadadiya",   "label": "College / إعدادي", "glyph": "\U0001F3EB", "primary_sector": "middle",     "typical_ages": "12-15"},
            {"code": "thanawiya",  "label": "Lycee / ثانوي",      "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universite", "label": "Universite / جامعة", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mr-1p", "label": "1ere Annee Primaire", "order": 1},
            {"code": "mr-6p", "label": "6eme (CEP)",          "order": 6},
            {"code": "mr-1s", "label": "1ere AS",             "order": 7},
            {"code": "mr-3s", "label": "3eme AS (BEPC)",      "order": 9},
            {"code": "mr-tle","label": "Terminale (BAC)",     "order": 12},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre / فصل",
            "report_card": "Bulletin / كشف نقاط",
            "grade_level": "Niveau / مستوى",
        },
    },
    "MU": {  # Mauritius
        "calendar_system": {
            "code": "mu-3-term",
            "label": "3 Terms (Mauritian / Cambridge)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-primary", "label": "Pre-Primary",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",     "label": "Primary School",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",      "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "11-18"},
            {"code": "tertiary",    "label": "Tertiary / University",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mu-std1", "label": "Standard 1",  "order": 1},
            {"code": "mu-std6", "label": "Standard 6 (PSAC)", "order": 6},
            {"code": "mu-g7",   "label": "Grade 7",     "order": 7},
            {"code": "mu-g9",   "label": "Grade 9 (NCE)", "order": 9},
            {"code": "mu-g11",  "label": "Grade 11 (SC)",  "order": 11},
            {"code": "mu-g13",  "label": "Grade 13 (HSC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Profeser",
            "principal": "Rector / Head Master",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Standard / Grade",
        },
    },
    "MZ": {  # Mozambique
        "calendar_system": {
            "code": "mz-3-trimester",
            "label": "3 Trimestres (Mocambicano)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-escolar",      "label": "Educacao Pre-Escolar",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primario",         "label": "Ensino Primario",             "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "secundario-geral", "label": "Ensino Secundario Geral",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "superior",         "label": "Ensino Superior",             "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mz-1cl",  "label": "1ª Classe", "order": 1},
            {"code": "mz-7cl",  "label": "7ª Classe", "order": 7},
            {"code": "mz-10cl", "label": "10ª Classe", "order": 10},
            {"code": "mz-12cl", "label": "12ª Classe", "order": 12},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Trimestre",
            "report_card": "Boletim",
            "grade_level": "Classe",
        },
    },
    "NA": {  # Namibia
        "calendar_system": {
            "code": "na-3-term",
            "label": "3 Terms (Namibian)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-primary", "label": "Pre-Primary",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "junior-sec",  "label": "Junior Secondary",     "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-16"},
            {"code": "senior-sec",  "label": "Senior Secondary",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "university",  "label": "University",           "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "na-g1",  "label": "Grade 1",  "order": 1},
            {"code": "na-g7",  "label": "Grade 7",  "order": 7},
            {"code": "na-g9",  "label": "Grade 9 (JSC)", "order": 9},
            {"code": "na-g11", "label": "Grade 11 (NSSCO)", "order": 11},
            {"code": "na-g12", "label": "Grade 12 (NSSCAS)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "NE": {  # Niger
        "calendar_system": {
            "code": "ne-3-trimester",
            "label": "3 Trimestres (Nigerien)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "primaire",   "label": "Primaire",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-13"},
            {"code": "college",    "label": "College (CEG)",     "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-17"},
            {"code": "lycee",      "label": "Lycee",             "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "17-20"},
            {"code": "universite", "label": "Universite",        "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "20+"},
        ],
        "education_levels": [
            {"code": "ne-cp1", "label": "CP1",        "order": 1},
            {"code": "ne-cm2", "label": "CM2 (CFEPD)", "order": 6},
            {"code": "ne-6e",  "label": "6eme",       "order": 7},
            {"code": "ne-3e",  "label": "3eme (BEPC)", "order": 10},
            {"code": "ne-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "RW": {  # Rwanda (English-medium since 2008)
        "calendar_system": {
            "code": "rw-3-term",
            "label": "3 Terms (Rwandan)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "pre-primary",  "label": "Pre-Primary / Mato",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",      "label": "Primary School",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "lower-sec",    "label": "Lower Secondary (O-Level)", "glyph": "\U0001F3EB", "primary_sector": "middle",        "typical_ages": "12-15"},
            {"code": "upper-sec",    "label": "Upper Secondary (A-Level)", "glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "15-18"},
            {"code": "university",   "label": "University",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "rw-p1",  "label": "P1",         "order": 1},
            {"code": "rw-p6",  "label": "P6 (PLE)",   "order": 6},
            {"code": "rw-s1",  "label": "S1",         "order": 7},
            {"code": "rw-s3",  "label": "S3 (O-Level)", "order": 9},
            {"code": "rw-s6",  "label": "S6 (A-Level)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Mwarimu",
            "principal": "Head Teacher / Umuyobozi",
            "term": "Term / Igihembwe",
            "report_card": "Report Card",
            "grade_level": "Class / P / S",
        },
    },
    "ST": {  # Sao Tome and Principe
        "calendar_system": {
            "code": "st-3-trimester",
            "label": "3 Trimestres (Santomense)",
            "term_count": 3,
            "term_names": ["1º Trimestre", "2º Trimestre", "3º Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "pre-escolar", "label": "Educacao Pre-Escolar",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "basico",      "label": "Ensino Basico",           "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secundario",  "label": "Ensino Secundario",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-18"},
            {"code": "superior",    "label": "Ensino Superior",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "st-1ano",  "label": "1º Ano",  "order": 1},
            {"code": "st-6ano",  "label": "6º Ano",  "order": 6},
            {"code": "st-9ano",  "label": "9º Ano",  "order": 9},
            {"code": "st-12ano", "label": "12º Ano", "order": 12},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Trimestre",
            "report_card": "Boletim",
            "grade_level": "Ano",
        },
    },
    "SN": {  # Senegal
        "calendar_system": {
            "code": "sn-3-trimester",
            "label": "3 Trimestres (Senegalais)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "elementaire", "label": "Elementaire",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College (Moyen)",  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee (Secondaire)", "glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "sn-ci",   "label": "CI",         "order": 1},
            {"code": "sn-cm2",  "label": "CM2 (CFEE)", "order": 6},
            {"code": "sn-6e",   "label": "6eme",       "order": 7},
            {"code": "sn-3e",   "label": "3eme (BFEM)", "order": 10},
            {"code": "sn-tle",  "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / Jangalekat",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "SC": {  # Seychelles
        "calendar_system": {
            "code": "sc-3-term",
            "label": "3 Terms (Seychellois)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "creche",     "label": "Creche",            "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",    "label": "Primary School",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secondary",  "label": "Secondary School",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "12-18"},
            {"code": "post-sec",   "label": "Post-Secondary / University", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sc-p1",  "label": "P1",         "order": 1},
            {"code": "sc-p6",  "label": "P6",         "order": 6},
            {"code": "sc-s1",  "label": "S1",         "order": 7},
            {"code": "sc-s5",  "label": "S5 (IGCSE)", "order": 11},
            {"code": "sc-s7",  "label": "S7 (A-Level)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Profeser",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Primary / Secondary",
        },
    },
    "SL": {  # Sierra Leone
        "calendar_system": {
            "code": "sl-3-term",
            "label": "3 Terms (Sierra Leonean)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool",   "label": "Pre-School",            "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "jss",         "label": "Junior Secondary (JSS)", "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "sss",         "label": "Senior Secondary (SSS)", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "university",  "label": "University / College",   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sl-p1",   "label": "Primary 1",         "order": 1},
            {"code": "sl-p6",   "label": "Primary 6 (NPSE)",  "order": 6},
            {"code": "sl-jss1", "label": "JSS 1",             "order": 7},
            {"code": "sl-jss3", "label": "JSS 3 (BECE)",      "order": 9},
            {"code": "sl-sss3", "label": "SSS 3 (WASSCE)",    "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Class",
        },
    },
    "SO": {  # Somalia (Somali + Arabic)
        "calendar_system": {
            "code": "so-2-semester",
            "label": "2 Semesters (Somali)",
            "term_count": 2,
            "term_names": ["Semester 1 / الفصل 1", "Semester 2 / الفصل 2"],
            "week_start": 6,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kinder",     "label": "Xanaano (Kindergarten)",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "dugsi-hoose", "label": "Dugsi Hoose (Primary) / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-14"},
            {"code": "dugsi-sare",  "label": "Dugsi Sare (Secondary) / ثانوي", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "14-18"},
            {"code": "jaamacad",    "label": "Jaamacad (University) / جامعة", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "so-f1", "label": "Fasalka 1aad (Grade 1)",  "order": 1},
            {"code": "so-f8", "label": "Fasalka 8aad (Grade 8)",  "order": 8},
            {"code": "so-f9", "label": "Fasalka 9aad (Form 1)",  "order": 9},
            {"code": "so-f12","label": "Fasalka 12aad (SSCE)",    "order": 12},
        ],
        "terminology": {
            "teacher": "Macallin / معلم",
            "principal": "Maamule / مدير",
            "term": "Semester / فصل",
            "report_card": "Warbixin Natiijada / كشف نقاط",
            "grade_level": "Fasalka / Grade",
        },
    },
    "SS": {  # South Sudan
        "calendar_system": {
            "code": "ss-3-term",
            "label": "3 Terms (South Sudanese)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "pre-primary", "label": "Pre-Primary",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "secondary",   "label": "Secondary School",      "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "university",  "label": "University",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ss-p1", "label": "Primary 1",  "order": 1},
            {"code": "ss-p8", "label": "Primary 8 (CPE)", "order": 8},
            {"code": "ss-s1", "label": "Secondary 1", "order": 9},
            {"code": "ss-s4", "label": "Secondary 4 (CSE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Primary / Secondary",
        },
    },
    "SD": {  # Sudan
        "calendar_system": {
            "code": "sd-3-trimester",
            "label": "3 Terms / ثلاثة فصول (Sudanese)",
            "term_count": 3,
            "term_names": ["الفصل 1 / Term 1", "الفصل 2 / Term 2", "الفصل 3 / Term 3"],
            "week_start": 0,
            "academic_year_starts_month": 7,
        },
        "school_types": [
            {"code": "rawda",     "label": "Rawda / روضة",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "asasiya",   "label": "Basic / أساسي",  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "thanawiya", "label": "Secondary / ثانوي", "glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "14-17"},
            {"code": "jamia",     "label": "University / جامعة", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",   "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "sd-g1",  "label": "Grade 1 / الصف 1",   "order": 1},
            {"code": "sd-g8",  "label": "Grade 8 (Basic Cert) / الصف 8",  "order": 8},
            {"code": "sd-g9",  "label": "Grade 9 / الصف 9",   "order": 9},
            {"code": "sd-g11", "label": "Grade 11 (Sudanese Cert) / الصف 11", "order": 11},
        ],
        "terminology": {
            "teacher": "معلم / Teacher",
            "principal": "مدير المدرسة / Headmaster",
            "term": "فصل / Term",
            "report_card": "كشف الدرجات / Report Card",
            "grade_level": "صف / Grade",
        },
    },
    "TZ": {  # Tanzania (Swahili + English)
        "calendar_system": {
            "code": "tz-2-semester",
            "label": "2 Semesters (Tanzanian)",
            "term_count": 2,
            "term_names": ["Muhula wa 1 / Semester 1", "Muhula wa 2 / Semester 2"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "chekechea", "label": "Chekechea (Pre-Primary)",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "msingi",    "label": "Shule ya Msingi (Primary)",  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-14"},
            {"code": "sekondari", "label": "Sekondari (O-Level)",         "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "14-18"},
            {"code": "kidato-5-6", "label": "Kidato cha 5-6 (A-Level)",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "18-20"},
            {"code": "chuo-kikuu", "label": "Chuo Kikuu (University)",    "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "20+"},
        ],
        "education_levels": [
            {"code": "tz-std1",  "label": "Darasa la 1 (Std 1)",  "order": 1},
            {"code": "tz-std7",  "label": "Darasa la 7 (PSLE)",   "order": 7},
            {"code": "tz-form1", "label": "Kidato cha 1 (Form 1)", "order": 8},
            {"code": "tz-form4", "label": "Kidato cha 4 (CSEE)",  "order": 11},
            {"code": "tz-form6", "label": "Kidato cha 6 (ACSEE)", "order": 13},
        ],
        "terminology": {
            "teacher": "Mwalimu / Teacher",
            "principal": "Mwalimu Mkuu / Head Teacher",
            "term": "Muhula / Term",
            "report_card": "Ripoti ya Matokeo / Report Card",
            "grade_level": "Darasa / Kidato",
        },
    },
    "TG": {  # Togo
        "calendar_system": {
            "code": "tg-3-trimester",
            "label": "3 Trimestres (Togolais)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / Jardin d'enfants", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "Primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "college",    "label": "College (CEG)",    "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "lycee",      "label": "Lycee",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "universite", "label": "Universite",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "tg-cp1", "label": "CP1",          "order": 1},
            {"code": "tg-cm2", "label": "CM2 (CEPD)",   "order": 6},
            {"code": "tg-6e",  "label": "6eme",         "order": 7},
            {"code": "tg-3e",  "label": "3eme (BEPC)",  "order": 10},
            {"code": "tg-tle", "label": "Terminale (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau",
        },
    },
    "TN": {  # Tunisia
        "calendar_system": {
            "code": "tn-3-trimester",
            "label": "3 Trimestres (Tunisien)",
            "term_count": 3,
            "term_names": ["Trimestre 1 / الثلاثي 1", "Trimestre 2 / الثلاثي 2", "Trimestre 3 / الثلاثي 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "rawda",     "label": "Jardin d'enfants / روضة", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "ibtidaiya", "label": "Primaire / ابتدائي", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "iadadiya",  "label": "College / إعدادي", "glyph": "\U0001F3EB", "primary_sector": "middle",     "typical_ages": "12-15"},
            {"code": "thanawiya", "label": "Lycee / ثانوي",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "jamia",     "label": "Universite / جامعة", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "tn-1p",  "label": "1ere AP",        "order": 1},
            {"code": "tn-6p",  "label": "6eme AP",        "order": 6},
            {"code": "tn-7b",  "label": "7eme de base",   "order": 7},
            {"code": "tn-9b",  "label": "9eme de base (Dipl. Enseignement de Base)", "order": 9},
            {"code": "tn-4sec","label": "4eme Sec (BAC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Enseignant / معلم",
            "principal": "Directeur / مدير",
            "term": "Trimestre / ثلاثي",
            "report_card": "Bulletin / بطاقة الأعداد",
            "grade_level": "Niveau / مستوى",
        },
    },
    "UG": {  # Uganda
        "calendar_system": {
            "code": "ug-3-term",
            "label": "3 Terms (Ugandan)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "nursery",     "label": "Nursery / Kindergarten",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",     "label": "Primary School",           "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "o-level",     "label": "O-Level Secondary",        "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "13-17"},
            {"code": "a-level",     "label": "A-Level (HSC)",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "17-19"},
            {"code": "university",  "label": "University",               "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "ug-p1", "label": "P1",         "order": 1},
            {"code": "ug-p7", "label": "P7 (PLE)",   "order": 7},
            {"code": "ug-s1", "label": "S1",         "order": 8},
            {"code": "ug-s4", "label": "S4 (UCE / O-Level)", "order": 11},
            {"code": "ug-s6", "label": "S6 (UACE / A-Level)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Omusomesa",
            "principal": "Head Teacher",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Class / P / S",
        },
    },
}
