"""Europe + Oceania Tier 1 extension — 40 hand-researched countries.

Appended into COUNTRY_LOCALIZATION at import time by _seed_country_localization.py.
"""

EUROPE_OCEANIA_EXTENSION = {
    "AT": {  # Austria
        "calendar_system": {
            "code": "at-2-semester",
            "label": "2 Semester (Österreichisch)",
            "term_count": 2,
            "term_names": ["1. Semester", "2. Semester"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kindergarten", "label": "Kindergarten",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "volksschule",  "label": "Volksschule",                 "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "mittelschule", "label": "Mittelschule",                "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "10-14"},
            {"code": "gymnasium",    "label": "Gymnasium",                   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "10-18"},
            {"code": "universitat",  "label": "Universität / Hochschule",    "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "at-vs1", "label": "Volksschule 1", "order": 1},
            {"code": "at-vs2", "label": "Volksschule 2", "order": 2},
            {"code": "at-vs3", "label": "Volksschule 3", "order": 3},
            {"code": "at-vs4", "label": "Volksschule 4", "order": 4},
            {"code": "at-us1", "label": "Unterstufe 1",  "order": 5},
            {"code": "at-us4", "label": "Unterstufe 4",  "order": 8},
            {"code": "at-os5", "label": "Oberstufe 5",   "order": 9},
            {"code": "at-os8", "label": "Oberstufe 8",   "order": 12},
        ],
        "terminology": {
            "teacher": "Lehrer/in",
            "principal": "Direktor/in",
            "term": "Semester",
            "report_card": "Zeugnis",
            "grade_level": "Schulstufe",
        },
    },
    "CH": {  # Switzerland (multilingual: DE / FR / IT)
        "calendar_system": {
            "code": "ch-2-semester",
            "label": "2 Semester / Semestre / Semestre (DE / FR / IT)",
            "term_count": 2,
            "term_names": ["1. Semester", "2. Semester"],
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "kindergarten", "label": "Kindergarten / École enfantine / Scuola dell'infanzia", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "primarschule", "label": "Primarschule / École primaire / Scuola elementare",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "sekundarstufe","label": "Sekundarstufe I / Secondaire I / Scuola media",         "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "gymnasium",    "label": "Gymnasium / Gymnase / Liceo (Matura)",                  "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "berufslehre",  "label": "Berufslehre / Apprentissage / Apprendistato",           "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "hochschule",   "label": "Hochschule / Université / Università",                  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ch-kg1", "label": "Kindergarten 1",      "order": 0},
            {"code": "ch-kg2", "label": "Kindergarten 2",      "order": 1},
            {"code": "ch-p1",  "label": "Primarstufe 1",       "order": 2},
            {"code": "ch-p6",  "label": "Primarstufe 6",       "order": 7},
            {"code": "ch-s1",  "label": "Sekundarstufe I (1)", "order": 8},
            {"code": "ch-s3",  "label": "Sekundarstufe I (3)", "order": 10},
            {"code": "ch-g1",  "label": "Gymnasium 1",         "order": 11},
            {"code": "ch-g4",  "label": "Gymnasium 4 (Matura)","order": 14},
        ],
        "terminology": {
            "teacher": "Lehrperson / Enseignant·e / Insegnante",
            "principal": "Schulleiter/in / Directeur·rice / Direttore/Direttrice",
            "term": "Semester / Semestre",
            "report_card": "Zeugnis / Bulletin / Pagella",
            "grade_level": "Klasse / Classe / Classe",
        },
    },
    "LU": {  # Luxembourg (trilingual: LU / FR / DE)
        "calendar_system": {
            "code": "lu-3-trimester",
            "label": "3 Trimester (Luxembourg)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "spillschoul",  "label": "Spillschoul / École préscolaire",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "fondamental",  "label": "Enseignement fondamental",              "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secondaire",   "label": "Enseignement secondaire / Lycée",       "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "12-19"},
            {"code": "universite",   "label": "Université du Luxembourg",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "lu-c1", "label": "Cycle 1 (préscolaire)", "order": 1},
            {"code": "lu-c2", "label": "Cycle 2",               "order": 2},
            {"code": "lu-c3", "label": "Cycle 3",               "order": 3},
            {"code": "lu-c4", "label": "Cycle 4",               "order": 4},
            {"code": "lu-s7", "label": "Secondaire 7e",         "order": 5},
            {"code": "lu-s1", "label": "Secondaire 1re",        "order": 11},
        ],
        "terminology": {
            "teacher": "Enseignant·e / Léierperson",
            "principal": "Directeur·rice",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Cycle / Classe",
        },
    },
    "LI": {  # Liechtenstein
        "calendar_system": {
            "code": "li-2-semester",
            "label": "2 Semester (Liechtenstein)",
            "term_count": 2,
            "term_names": ["1. Semester", "2. Semester"],
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "kindergarten",  "label": "Kindergarten",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "primarschule",  "label": "Primarschule",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "sekundarstufe", "label": "Sekundarstufe I",    "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-15"},
            {"code": "gymnasium",     "label": "Liechtensteinisches Gymnasium", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "11-19"},
            {"code": "berufslehre",   "label": "Berufslehre",        "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
        ],
        "education_levels": [
            {"code": "li-kg",  "label": "Kindergarten",  "order": 0},
            {"code": "li-p1",  "label": "Primarstufe 1", "order": 1},
            {"code": "li-p5",  "label": "Primarstufe 5", "order": 5},
            {"code": "li-s1",  "label": "Sekundar 1",    "order": 6},
            {"code": "li-g4",  "label": "Gymnasium 4",   "order": 12},
        ],
        "terminology": {
            "teacher": "Lehrperson",
            "principal": "Schulleiter/in",
            "term": "Semester",
            "report_card": "Zeugnis",
            "grade_level": "Klasse",
        },
    },
    "MC": {  # Monaco (French system aligned)
        "calendar_system": {
            "code": "mc-3-trimester",
            "label": "3 Trimestres (Monaco)",
            "term_count": 3,
            "term_names": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "École maternelle",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaire",   "label": "École primaire",    "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "college",    "label": "Collège",           "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-15"},
            {"code": "lycee",      "label": "Lycée",             "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universite", "label": "Université / IUM",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mc-ps",  "label": "Petite Section",         "order": 0},
            {"code": "mc-gs",  "label": "Grande Section",         "order": 2},
            {"code": "mc-cp",  "label": "CP",                     "order": 3},
            {"code": "mc-cm2", "label": "CM2",                    "order": 7},
            {"code": "mc-6",   "label": "6e (Collège)",           "order": 8},
            {"code": "mc-3",   "label": "3e (Brevet)",            "order": 11},
            {"code": "mc-2nd", "label": "2nde (Lycée)",           "order": 12},
            {"code": "mc-tle", "label": "Terminale (Baccalauréat)", "order": 14},
        ],
        "terminology": {
            "teacher": "Enseignant·e",
            "principal": "Proviseur·e",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Classe",
        },
    },
    "AD": {  # Andorra (Catalan / French / Spanish systems coexist)
        "calendar_system": {
            "code": "ad-3-trimestre",
            "label": "3 Trimestres (Andorra)",
            "term_count": 3,
            "term_names": ["1r Trimestre", "2n Trimestre", "3r Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternal",   "label": "Escola Maternal / Bressol",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-3"},
            {"code": "primera",    "label": "Primera Ensenyança",             "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "segona",     "label": "Segona Ensenyança",              "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-16"},
            {"code": "batxillerat","label": "Batxillerat",                    "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "universitat","label": "Universitat d'Andorra",          "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ad-pe1",  "label": "Primera Ensenyança 1", "order": 1},
            {"code": "ad-pe6",  "label": "Primera Ensenyança 6", "order": 6},
            {"code": "ad-se1",  "label": "Segona Ensenyança 1",  "order": 7},
            {"code": "ad-se4",  "label": "Segona Ensenyança 4",  "order": 10},
            {"code": "ad-bt1",  "label": "Batxillerat 1",        "order": 11},
            {"code": "ad-bt2",  "label": "Batxillerat 2",        "order": 12},
        ],
        "terminology": {
            "teacher": "Professor/a",
            "principal": "Director/a",
            "term": "Trimestre",
            "report_card": "Butlletí de notes",
            "grade_level": "Curs",
        },
    },
    "SM": {  # San Marino (Italian system aligned)
        "calendar_system": {
            "code": "sm-3-trimester",
            "label": "3 Trimestri (Sammarinese)",
            "term_count": 3,
            "term_names": ["I Trimestre", "II Trimestre", "III Trimestre"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "infanzia",    "label": "Scuola dell'infanzia",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "elementare",  "label": "Scuola elementare",      "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "media",       "label": "Scuola media",           "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "superiore",   "label": "Scuola secondaria superiore", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "14-19"},
            {"code": "universita",  "label": "Università di San Marino","glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sm-el1", "label": "Elementare 1", "order": 1},
            {"code": "sm-el5", "label": "Elementare 5", "order": 5},
            {"code": "sm-md1", "label": "Media 1",      "order": 6},
            {"code": "sm-md3", "label": "Media 3",      "order": 8},
            {"code": "sm-sp1", "label": "Superiore 1",  "order": 9},
            {"code": "sm-sp5", "label": "Superiore 5 (Maturità)", "order": 13},
        ],
        "terminology": {
            "teacher": "Insegnante",
            "principal": "Preside",
            "term": "Trimestre",
            "report_card": "Pagella",
            "grade_level": "Classe",
        },
    },
    "VA": {  # Vatican City (Italian + Latin liturgical)
        "calendar_system": {
            "code": "va-2-semester",
            "label": "2 Semestri (Pontificio)",
            "term_count": 2,
            "term_names": ["Semestre I", "Semestre II"],
            "week_start": 1,
            "academic_year_starts_month": 10,
        },
        "school_types": [
            {"code": "seminario",   "label": "Seminario / Schola minor",     "glyph": "\U0001F4DA", "primary_sector": "secondary",  "typical_ages": "14-19"},
            {"code": "pontificia",  "label": "Università Pontificia",        "glyph": "\U0001F3DB", "primary_sector": "higher_ed",  "typical_ages": "18+"},
            {"code": "accademia",   "label": "Pontificia Accademia Ecclesiastica", "glyph": "\U0001F393", "primary_sector": "post_secondary", "typical_ages": "24+"},
        ],
        "education_levels": [
            {"code": "va-bacc",  "label": "Baccalaureatus", "order": 1},
            {"code": "va-licen", "label": "Licentia",       "order": 2},
            {"code": "va-doct",  "label": "Doctoratus",     "order": 3},
        ],
        "terminology": {
            "teacher": "Magister / Docente",
            "principal": "Rector / Rettore",
            "term": "Semestre",
            "report_card": "Diploma",
            "grade_level": "Annus / Anno",
        },
    },
    "MT": {  # Malta (Maltese + English bilingual)
        "calendar_system": {
            "code": "mt-3-term",
            "label": "3 Terms (Maltese / English)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kinder",      "label": "Kindergarten / Skola tat-Tfal",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",     "label": "Primary School",                 "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "secondary",   "label": "Secondary School",               "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "11-16"},
            {"code": "sixth-form",  "label": "Sixth Form / Junior College",    "glyph": "\U0001F393", "primary_sector": "post_secondary",  "typical_ages": "16-18"},
            {"code": "university",  "label": "University of Malta",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mt-k1", "label": "Kinder 1", "order": 0},
            {"code": "mt-y1", "label": "Year 1",   "order": 1},
            {"code": "mt-y6", "label": "Year 6",   "order": 6},
            {"code": "mt-y7", "label": "Year 7 (Form 1)",  "order": 7},
            {"code": "mt-y11","label": "Year 11 (SEC)",    "order": 11},
            {"code": "mt-mat","label": "MATSEC / A-Level", "order": 13},
        ],
        "terminology": {
            "teacher": "Għalliem / Teacher",
            "principal": "Kap / Head of School",
            "term": "Term",
            "report_card": "Karta tar-Riżultati / Report Card",
            "grade_level": "Year / Sena",
        },
    },
    "CY": {  # Cyprus (Greek-majority; Turkish in north)
        "calendar_system": {
            "code": "cy-3-trimino",
            "label": "3 Τρίμηνα (Greek Cypriot)",
            "term_count": 3,
            "term_names": ["Α' Τρίμηνο", "Β' Τρίμηνο", "Γ' Τρίμηνο"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nipiagogeio",  "label": "Νηπιαγωγείο / Kindergarten",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "dimotiko",     "label": "Δημοτικό / Primary",                  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "gymnasio",     "label": "Γυμνάσιο / Lower Secondary",          "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "lykeio",       "label": "Λύκειο / Upper Secondary",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "panepistimio", "label": "Πανεπιστήμιο / University of Cyprus", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cy-d1", "label": "Δημοτικό A'", "order": 1},
            {"code": "cy-d6", "label": "Δημοτικό ΣΤ'", "order": 6},
            {"code": "cy-g1", "label": "Γυμνάσιο A'", "order": 7},
            {"code": "cy-g3", "label": "Γυμνάσιο Γ'", "order": 9},
            {"code": "cy-l1", "label": "Λύκειο A'",   "order": 10},
            {"code": "cy-l3", "label": "Λύκειο Γ' (Απολυτήριο)", "order": 12},
        ],
        "terminology": {
            "teacher": "Δάσκαλος/α / Καθηγητής/τρια",
            "principal": "Διευθυντής/ντρια",
            "term": "Τρίμηνο",
            "report_card": "Έλεγχος / Απολυτήριο",
            "grade_level": "Τάξη",
        },
    },
    "GR": {  # Greece
        "calendar_system": {
            "code": "gr-2-tetrim",
            "label": "2 Τετράμηνα (Ελληνικό σύστημα)",
            "term_count": 2,
            "term_names": ["A' Τετράμηνο", "B' Τετράμηνο"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nipiagogeio",  "label": "Νηπιαγωγείο",                   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "dimotiko",     "label": "Δημοτικό σχολείο",              "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "gymnasio",     "label": "Γυμνάσιο",                      "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "lykeio",       "label": "Λύκειο / ΕΠΑΛ",                 "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "panepistimio", "label": "Πανεπιστήμιο / ΑΕΙ",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gr-d1", "label": "Δημοτικό A'", "order": 1},
            {"code": "gr-d6", "label": "Δημοτικό ΣΤ'", "order": 6},
            {"code": "gr-g1", "label": "Γυμνάσιο A'",  "order": 7},
            {"code": "gr-g3", "label": "Γυμνάσιο Γ'",  "order": 9},
            {"code": "gr-l1", "label": "Λύκειο A'",    "order": 10},
            {"code": "gr-l3", "label": "Λύκειο Γ' (Πανελλαδικές)", "order": 12},
        ],
        "terminology": {
            "teacher": "Εκπαιδευτικός",
            "principal": "Διευθυντής/ντρια",
            "term": "Τετράμηνο",
            "report_card": "Έλεγχος προόδου",
            "grade_level": "Τάξη",
        },
    },
    "BG": {  # Bulgaria
        "calendar_system": {
            "code": "bg-2-srok",
            "label": "2 Срока (Български)",
            "term_count": 2,
            "term_names": ["I Срок", "II Срок"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "detska-gradina","label": "Детска градина",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "nachalno",      "label": "Начално училище",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-11"},
            {"code": "progimnaziya",  "label": "Прогимназия",             "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "gimnaziya",     "label": "Гимназия",                "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-19"},
            {"code": "universitet",   "label": "Университет",             "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bg-n1", "label": "I клас (Начално)",   "order": 1},
            {"code": "bg-n4", "label": "IV клас",            "order": 4},
            {"code": "bg-p5", "label": "V клас (Прогимн.)",  "order": 5},
            {"code": "bg-p7", "label": "VII клас",           "order": 7},
            {"code": "bg-g8", "label": "VIII клас (Гимн.)",  "order": 8},
            {"code": "bg-g12","label": "XII клас (Зрелост)", "order": 12},
        ],
        "terminology": {
            "teacher": "Учител",
            "principal": "Директор",
            "term": "Срок",
            "report_card": "Бележник / Удостоверение",
            "grade_level": "Клас",
        },
    },
    "CZ": {  # Czechia
        "calendar_system": {
            "code": "cz-2-pololeti",
            "label": "2 Pololetí (Český systém)",
            "term_count": 2,
            "term_names": ["1. pololetí", "2. pololetí"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "materska",   "label": "Mateřská škola",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "zakladni",   "label": "Základní škola",   "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "stredni",    "label": "Střední škola / Gymnázium", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "15-19"},
            {"code": "univerzita", "label": "Univerzita / Vysoká škola", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cz-zs1", "label": "ZŠ 1. třída",  "order": 1},
            {"code": "cz-zs5", "label": "ZŠ 5. třída",  "order": 5},
            {"code": "cz-zs9", "label": "ZŠ 9. třída",  "order": 9},
            {"code": "cz-ss1", "label": "SŠ 1. ročník", "order": 10},
            {"code": "cz-ss4", "label": "SŠ 4. ročník (Maturita)", "order": 13},
        ],
        "terminology": {
            "teacher": "Učitel/ka",
            "principal": "Ředitel/ka",
            "term": "Pololetí",
            "report_card": "Vysvědčení",
            "grade_level": "Třída / Ročník",
        },
    },
    "EE": {  # Estonia
        "calendar_system": {
            "code": "ee-4-veerand",
            "label": "4 Veerandit (Eesti süsteem)",
            "term_count": 4,
            "term_names": ["I veerand", "II veerand", "III veerand", "IV veerand"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "lasteaed",   "label": "Lasteaed",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-7"},
            {"code": "pohikool",   "label": "Põhikool",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-16"},
            {"code": "gumnaasium", "label": "Gümnaasium",      "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-19"},
            {"code": "kutsekool",  "label": "Kutsekool",       "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16-19"},
            {"code": "ulikool",    "label": "Ülikool",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ee-pk1",  "label": "Põhikool 1. klass",   "order": 1},
            {"code": "ee-pk6",  "label": "Põhikool 6. klass",   "order": 6},
            {"code": "ee-pk9",  "label": "Põhikool 9. klass",   "order": 9},
            {"code": "ee-gu10", "label": "Gümnaasium 10. klass","order": 10},
            {"code": "ee-gu12", "label": "Gümnaasium 12. klass","order": 12},
        ],
        "terminology": {
            "teacher": "Õpetaja",
            "principal": "Direktor",
            "term": "Veerand",
            "report_card": "Klassitunnistus",
            "grade_level": "Klass",
        },
    },
    "HU": {  # Hungary
        "calendar_system": {
            "code": "hu-2-felev",
            "label": "2 Félév (Magyar)",
            "term_count": 2,
            "term_names": ["I. félév", "II. félév"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "ovoda",      "label": "Óvoda",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "altalanos",  "label": "Általános iskola",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "gimnazium",  "label": "Gimnázium",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "szakkozep",  "label": "Szakgimnázium / Szakközépiskola", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "14-18"},
            {"code": "egyetem",    "label": "Egyetem",              "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "hu-a1",  "label": "Általános 1. osztály",  "order": 1},
            {"code": "hu-a4",  "label": "Általános 4. osztály",  "order": 4},
            {"code": "hu-a8",  "label": "Általános 8. osztály",  "order": 8},
            {"code": "hu-g9",  "label": "Gimnázium 9. osztály",  "order": 9},
            {"code": "hu-g12", "label": "Gimnázium 12. (Érettségi)", "order": 12},
        ],
        "terminology": {
            "teacher": "Tanár / Tanító",
            "principal": "Igazgató",
            "term": "Félév",
            "report_card": "Bizonyítvány",
            "grade_level": "Osztály",
        },
    },
    "LV": {  # Latvia
        "calendar_system": {
            "code": "lv-2-semestri",
            "label": "2 Semestri (Latviešu)",
            "term_count": 2,
            "term_names": ["1. semestris", "2. semestris"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "bernudarzs", "label": "Bērnudārzs",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-7"},
            {"code": "pamatskola", "label": "Pamatskola",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-15"},
            {"code": "vidusskola", "label": "Vidusskola",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "arodskola",  "label": "Arodskola",      "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "augstskola", "label": "Augstskola / Universitāte", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "lv-pa1",  "label": "Pamatskola 1. klase",  "order": 1},
            {"code": "lv-pa6",  "label": "Pamatskola 6. klase",  "order": 6},
            {"code": "lv-pa9",  "label": "Pamatskola 9. klase",  "order": 9},
            {"code": "lv-vi10", "label": "Vidusskola 10. klase", "order": 10},
            {"code": "lv-vi12", "label": "Vidusskola 12. klase (Centralizētie eksāmeni)", "order": 12},
        ],
        "terminology": {
            "teacher": "Skolotājs/a",
            "principal": "Direktors/e",
            "term": "Semestris",
            "report_card": "Liecība",
            "grade_level": "Klase",
        },
    },
    "LT": {  # Lithuania
        "calendar_system": {
            "code": "lt-2-pusmetis",
            "label": "2 Pusmečiai (Lietuvių)",
            "term_count": 2,
            "term_names": ["I pusmetis", "II pusmetis"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "darzelis",   "label": "Darželis",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "pradine",    "label": "Pradinė mokykla",   "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-11"},
            {"code": "pagrindine", "label": "Pagrindinė mokykla","glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-16"},
            {"code": "gimnazija",  "label": "Gimnazija",         "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-18"},
            {"code": "universitetas", "label": "Universitetas",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "lt-pr1",  "label": "Pradinė 1 klasė", "order": 1},
            {"code": "lt-pr4",  "label": "Pradinė 4 klasė", "order": 4},
            {"code": "lt-pg5",  "label": "Pagrindinė 5 klasė", "order": 5},
            {"code": "lt-pg10", "label": "Pagrindinė 10 klasė", "order": 10},
            {"code": "lt-gm11", "label": "Gimnazija 11 klasė", "order": 11},
            {"code": "lt-gm12", "label": "Gimnazija 12 klasė (Brandos egzaminai)", "order": 12},
        ],
        "terminology": {
            "teacher": "Mokytojas/a",
            "principal": "Direktorius/ė",
            "term": "Pusmetis",
            "report_card": "Pažymėjimas",
            "grade_level": "Klasė",
        },
    },
    "RO": {  # Romania
        "calendar_system": {
            "code": "ro-2-semestru",
            "label": "2 Semestre (Românesc)",
            "term_count": 2,
            "term_names": ["Semestrul I", "Semestrul II"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "gradinita",  "label": "Grădiniță",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primara",    "label": "Școală primară",           "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "gimnaziu",   "label": "Gimnaziu",                 "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "10-14"},
            {"code": "liceu",      "label": "Liceu (Bacalaureat)",      "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "universitate","label": "Universitate",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ro-pr1",  "label": "Clasa pregătitoare",    "order": 0},
            {"code": "ro-cl1",  "label": "Clasa I",               "order": 1},
            {"code": "ro-cl4",  "label": "Clasa a IV-a",          "order": 4},
            {"code": "ro-cl5",  "label": "Clasa a V-a (Gimnaziu)","order": 5},
            {"code": "ro-cl8",  "label": "Clasa a VIII-a (Evaluare națională)", "order": 8},
            {"code": "ro-cl9",  "label": "Clasa a IX-a (Liceu)",  "order": 9},
            {"code": "ro-cl12", "label": "Clasa a XII-a (Bacalaureat)", "order": 12},
        ],
        "terminology": {
            "teacher": "Profesor/oară / Învățător/oare",
            "principal": "Director/oare",
            "term": "Semestru",
            "report_card": "Carnet de note / Foaie matricolă",
            "grade_level": "Clasă",
        },
    },
    "SK": {  # Slovakia
        "calendar_system": {
            "code": "sk-2-polrok",
            "label": "2 Polroky (Slovenský)",
            "term_count": 2,
            "term_names": ["1. polrok", "2. polrok"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "materska",  "label": "Materská škola",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "zakladna",  "label": "Základná škola",  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "gymnazium", "label": "Gymnázium",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "stredna",   "label": "Stredná odborná škola", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "15-19"},
            {"code": "univerzita","label": "Univerzita",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sk-zs1", "label": "ZŠ 1. ročník",  "order": 1},
            {"code": "sk-zs5", "label": "ZŠ 5. ročník",  "order": 5},
            {"code": "sk-zs9", "label": "ZŠ 9. ročník",  "order": 9},
            {"code": "sk-gy1", "label": "Gymnázium 1.",  "order": 10},
            {"code": "sk-gy4", "label": "Gymnázium 4. (Maturita)", "order": 13},
        ],
        "terminology": {
            "teacher": "Učiteľ/ka",
            "principal": "Riaditeľ/ka",
            "term": "Polrok",
            "report_card": "Vysvedčenie",
            "grade_level": "Ročník / Trieda",
        },
    },
    "SI": {  # Slovenia
        "calendar_system": {
            "code": "si-2-polletje",
            "label": "2 Polletji (Slovenščina)",
            "term_count": 2,
            "term_names": ["1. polletje", "2. polletje"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "vrtec",      "label": "Vrtec",              "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovna",    "label": "Osnovna šola",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "srednja",    "label": "Srednja šola / Gimnazija", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "15-19"},
            {"code": "poklicna",   "label": "Poklicna šola",      "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "univerza",   "label": "Univerza",           "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "si-os1", "label": "Osnovna šola 1. razred", "order": 1},
            {"code": "si-os6", "label": "Osnovna šola 6. razred", "order": 6},
            {"code": "si-os9", "label": "Osnovna šola 9. razred", "order": 9},
            {"code": "si-sr1", "label": "Srednja šola 1. letnik", "order": 10},
            {"code": "si-sr4", "label": "Srednja šola 4. letnik (Matura)", "order": 13},
        ],
        "terminology": {
            "teacher": "Učitelj/ica",
            "principal": "Ravnatelj/ica",
            "term": "Polletje",
            "report_card": "Spričevalo",
            "grade_level": "Razred / Letnik",
        },
    },
    "HR": {  # Croatia
        "calendar_system": {
            "code": "hr-2-polugodiste",
            "label": "2 Polugodišta (Hrvatski)",
            "term_count": 2,
            "term_names": ["1. polugodište", "2. polugodište"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "vrtic",      "label": "Vrtić / Dječji vrtić",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovna",    "label": "Osnovna škola",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "gimnazija",  "label": "Gimnazija",              "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "strukovna",  "label": "Strukovna škola",        "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "sveuciliste","label": "Sveučilište / Veleučilište", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",    "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "hr-os1", "label": "OŠ 1. razred", "order": 1},
            {"code": "hr-os4", "label": "OŠ 4. razred", "order": 4},
            {"code": "hr-os8", "label": "OŠ 8. razred", "order": 8},
            {"code": "hr-sr1", "label": "Srednja 1. razred", "order": 9},
            {"code": "hr-sr4", "label": "Srednja 4. razred (Matura)", "order": 12},
        ],
        "terminology": {
            "teacher": "Učitelj/ica / Profesor/ica",
            "principal": "Ravnatelj/ica",
            "term": "Polugodište",
            "report_card": "Svjedodžba",
            "grade_level": "Razred",
        },
    },
    "BA": {  # Bosnia and Herzegovina
        "calendar_system": {
            "code": "ba-2-polugodiste",
            "label": "2 Polugodišta (Bosanski / Hrvatski / Srpski)",
            "term_count": 2,
            "term_names": ["I. polugodište", "II. polugodište"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "vrtic",      "label": "Vrtić / Obdanište",     "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovna",    "label": "Osnovna škola",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-14"},
            {"code": "srednja",    "label": "Srednja škola / Gimnazija", "glyph": "\U0001F393", "primary_sector": "secondary",   "typical_ages": "14-18"},
            {"code": "strucna",    "label": "Stručna škola",         "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "14-18"},
            {"code": "univerzitet","label": "Univerzitet / Sveučilište","glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ba-os1", "label": "Osnovna 1. razred", "order": 1},
            {"code": "ba-os5", "label": "Osnovna 5. razred", "order": 5},
            {"code": "ba-os9", "label": "Osnovna 9. razred", "order": 9},
            {"code": "ba-sr1", "label": "Srednja 1. razred", "order": 10},
            {"code": "ba-sr4", "label": "Srednja 4. razred (Matura)", "order": 13},
        ],
        "terminology": {
            "teacher": "Nastavnik/ca / Profesor/ica",
            "principal": "Direktor/ica / Ravnatelj/ica",
            "term": "Polugodište",
            "report_card": "Svjedodžba / Đačka knjižica",
            "grade_level": "Razred",
        },
    },
    "RS": {  # Serbia
        "calendar_system": {
            "code": "rs-2-polugodiste",
            "label": "2 Полугодишта (Srpski)",
            "term_count": 2,
            "term_names": ["I полугодиште", "II полугодиште"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "vrtic",     "label": "Вртић / Предшколска установа", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovna",   "label": "Основна школа",                  "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-15"},
            {"code": "gimnazija", "label": "Гимназија",                       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "strucna",   "label": "Стручна школа",                  "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "univerzitet","label": "Универзитет",                   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "rs-os1", "label": "Основна 1. разред",                "order": 1},
            {"code": "rs-os4", "label": "Основна 4. разред",                "order": 4},
            {"code": "rs-os8", "label": "Основна 8. разред (Завршни)",     "order": 8},
            {"code": "rs-sr1", "label": "Средња 1. разред",                 "order": 9},
            {"code": "rs-sr4", "label": "Средња 4. разред (Матура)",       "order": 12},
        ],
        "terminology": {
            "teacher": "Наставник / Професор",
            "principal": "Директор",
            "term": "Полугодиште",
            "report_card": "Сведочанство / Ђачка књижица",
            "grade_level": "Разред",
        },
    },
    "ME": {  # Montenegro
        "calendar_system": {
            "code": "me-2-polugodiste",
            "label": "2 Polugodišta (Crnogorski)",
            "term_count": 2,
            "term_names": ["I polugodište", "II polugodište"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "vrtic",     "label": "Vrtić / Predškolska ustanova", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovna",   "label": "Osnovna škola",                "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "gimnazija", "label": "Gimnazija",                    "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "strucna",   "label": "Stručna škola",                "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "univerzitet","label": "Univerzitet Crne Gore",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "me-os1", "label": "Osnovna 1. razred", "order": 1},
            {"code": "me-os9", "label": "Osnovna 9. razred", "order": 9},
            {"code": "me-sr1", "label": "Srednja 1. razred", "order": 10},
            {"code": "me-sr4", "label": "Srednja 4. razred (Matura)", "order": 13},
        ],
        "terminology": {
            "teacher": "Nastavnik/ca / Profesor/ica",
            "principal": "Direktor/ica",
            "term": "Polugodište",
            "report_card": "Svjedočanstvo",
            "grade_level": "Razred",
        },
    },
    "MK": {  # North Macedonia
        "calendar_system": {
            "code": "mk-2-polugodie",
            "label": "2 Полугодија (Македонски)",
            "term_count": 2,
            "term_names": ["I полугодие", "II полугодие"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "gradinka",  "label": "Градинка / Детска градинка",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "osnovno",   "label": "Основно училиште",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "gimnazija", "label": "Гимназија / Средно",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-19"},
            {"code": "strucno",   "label": "Стручно училиште",            "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-19"},
            {"code": "univerzitet","label": "Универзитет",                 "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mk-oo1", "label": "Основно 1. одделение", "order": 1},
            {"code": "mk-oo9", "label": "Основно 9. одделение", "order": 9},
            {"code": "mk-sr1", "label": "Средно 1. година",     "order": 10},
            {"code": "mk-sr4", "label": "Средно 4. (Државна матура)", "order": 13},
        ],
        "terminology": {
            "teacher": "Наставник / Професор",
            "principal": "Директор",
            "term": "Полугодие",
            "report_card": "Свидетелство",
            "grade_level": "Одделение / Година",
        },
    },
    "AL": {  # Albania
        "calendar_system": {
            "code": "al-2-semestral",
            "label": "2 Semestra (Shqip)",
            "term_count": 2,
            "term_names": ["Semestri I", "Semestri II"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kopshti",   "label": "Kopshti / Çerdhja",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "fillore",   "label": "Shkolla fillore (9-vjeçar)","glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "e-mesme",   "label": "Shkolla e mesme / Gjimnazi","glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "profesional","label": "Shkolla profesionale",      "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-18"},
            {"code": "universiteti","label": "Universiteti",             "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "al-k1", "label": "Klasa 1 (Fillore)",  "order": 1},
            {"code": "al-k5", "label": "Klasa 5",            "order": 5},
            {"code": "al-k9", "label": "Klasa 9 (Provimi)",  "order": 9},
            {"code": "al-k10","label": "Klasa 10 (E mesme)", "order": 10},
            {"code": "al-k12","label": "Klasa 12 (Matura Shtetërore)", "order": 12},
        ],
        "terminology": {
            "teacher": "Mësues/e",
            "principal": "Drejtor/eshë",
            "term": "Semestër",
            "report_card": "Dëftesa",
            "grade_level": "Klasa",
        },
    },
    "MD": {  # Moldova
        "calendar_system": {
            "code": "md-2-semestru",
            "label": "2 Semestre (Moldovenesc / Românesc)",
            "term_count": 2,
            "term_names": ["Semestrul I", "Semestrul II"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "gradinita",  "label": "Grădiniță",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primara",    "label": "Școală primară",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "7-11"},
            {"code": "gimnaziu",   "label": "Gimnaziu",           "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "11-15"},
            {"code": "liceu",      "label": "Liceu",              "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universitate","label": "Universitate",      "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "md-cl1",  "label": "Clasa I",                          "order": 1},
            {"code": "md-cl4",  "label": "Clasa a IV-a",                     "order": 4},
            {"code": "md-cl9",  "label": "Clasa a IX-a (Gimnaziu - examen)", "order": 9},
            {"code": "md-cl10", "label": "Clasa a X-a (Liceu)",              "order": 10},
            {"code": "md-cl12", "label": "Clasa a XII-a (Bacalaureat)",      "order": 12},
        ],
        "terminology": {
            "teacher": "Profesor / Învățător",
            "principal": "Director",
            "term": "Semestru",
            "report_card": "Carnet de note",
            "grade_level": "Clasă",
        },
    },
    "UA": {  # Ukraine
        "calendar_system": {
            "code": "ua-2-semestr",
            "label": "2 Семестри (Український)",
            "term_count": 2,
            "term_names": ["I семестр", "II семестр"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "dytsadok",  "label": "Дитячий садок",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-6"},
            {"code": "pochatkova","label": "Початкова школа",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "serednia",  "label": "Середня школа",          "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "10-15"},
            {"code": "litsei",    "label": "Ліцей / Гімназія",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universytet","label": "Університет",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ua-kl1",  "label": "1 клас (Початкова)",    "order": 1},
            {"code": "ua-kl4",  "label": "4 клас",                "order": 4},
            {"code": "ua-kl9",  "label": "9 клас (Базова освіта)","order": 9},
            {"code": "ua-kl10", "label": "10 клас (Ліцей)",       "order": 10},
            {"code": "ua-kl12", "label": "12 клас (ЗНО / НМТ)",   "order": 12},
        ],
        "terminology": {
            "teacher": "Вчитель / Викладач",
            "principal": "Директор",
            "term": "Семестр",
            "report_card": "Табель / Свідоцтво",
            "grade_level": "Клас",
        },
    },
    "BY": {  # Belarus
        "calendar_system": {
            "code": "by-2-semestr",
            "label": "2 Семестра (Беларускі / Русский)",
            "term_count": 2,
            "term_names": ["1-ы семестр / 1 семестр", "2-і семестр / 2 семестр"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "sadok",     "label": "Дзіцячы сад / Детский сад",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-6"},
            {"code": "pachatkova","label": "Пачатковая школа / Начальная школа", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-10"},
            {"code": "siarednia", "label": "Сярэдняя школа / Средняя школа","glyph": "\U0001F4DA", "primary_sector": "middle",      "typical_ages": "10-15"},
            {"code": "gimnaziya", "label": "Гімназія / Ліцэй",            "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "10-18"},
            {"code": "universitet","label": "Універсітэт / Университет",   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "by-kl1",  "label": "1 клас (Пачатковая)", "order": 1},
            {"code": "by-kl4",  "label": "4 клас",              "order": 4},
            {"code": "by-kl9",  "label": "9 клас (Базавая)",    "order": 9},
            {"code": "by-kl11", "label": "11 клас (ЦТ)",        "order": 11},
        ],
        "terminology": {
            "teacher": "Настаўнік / Учитель",
            "principal": "Дырэктар / Директор",
            "term": "Семестр",
            "report_card": "Дзённік / Атэстат",
            "grade_level": "Клас / Класс",
        },
    },
    "XK": {  # Kosovo
        "calendar_system": {
            "code": "xk-2-semestral",
            "label": "2 Semestra (Shqip / Srpski)",
            "term_count": 2,
            "term_names": ["Semestri I", "Semestri II"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kopshti",     "label": "Kopshti / Çerdhja",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "fillore",     "label": "Shkolla fillore",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-15"},
            {"code": "e-mesme",     "label": "Shkolla e mesme / Gjimnazi","glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "15-18"},
            {"code": "profesional", "label": "Shkolla profesionale",    "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15-18"},
            {"code": "universiteti","label": "Universiteti i Prishtinës","glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "xk-k1", "label": "Klasa 1 (Fillore)", "order": 1},
            {"code": "xk-k5", "label": "Klasa 5",           "order": 5},
            {"code": "xk-k9", "label": "Klasa 9",           "order": 9},
            {"code": "xk-k10","label": "Klasa 10 (E mesme)","order": 10},
            {"code": "xk-k12","label": "Klasa 12 (Matura Shtetërore)", "order": 12},
        ],
        "terminology": {
            "teacher": "Mësues/e",
            "principal": "Drejtor/eshë",
            "term": "Semestër",
            "report_card": "Dëftesa",
            "grade_level": "Klasa",
        },
    },
    "IS": {  # Iceland
        "calendar_system": {
            "code": "is-2-misseri",
            "label": "2 Misseri (Íslenskt)",
            "term_count": 2,
            "term_names": ["Haustmisseri", "Vormisseri"],
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "leikskoli",      "label": "Leikskóli",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "grunnskoli",     "label": "Grunnskóli",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-16"},
            {"code": "framhaldsskoli", "label": "Framhaldsskóli",     "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "16-20"},
            {"code": "haskoli",        "label": "Háskóli",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "20+"},
        ],
        "education_levels": [
            {"code": "is-g1",  "label": "Grunnskóli 1. bekkur",  "order": 1},
            {"code": "is-g5",  "label": "Grunnskóli 5. bekkur",  "order": 5},
            {"code": "is-g10", "label": "Grunnskóli 10. bekkur (Samræmd próf)", "order": 10},
            {"code": "is-f1",  "label": "Framhaldsskóli 1. ár",  "order": 11},
            {"code": "is-f4",  "label": "Framhaldsskóli 4. ár (Stúdentspróf)", "order": 14},
        ],
        "terminology": {
            "teacher": "Kennari",
            "principal": "Skólastjóri",
            "term": "Misseri / Önn",
            "report_card": "Vitnisburður",
            "grade_level": "Bekkur",
        },
    },
    "AM": {  # Armenia
        "calendar_system": {
            "code": "am-2-kisamyak",
            "label": "2 Կիսամյակ (Հայերեն)",
            "term_count": 2,
            "term_names": ["Առաջին կիսամյակ", "Երկրորդ կիսամյակ"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "mankapartez", "label": "Մանկապարտեզ",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "tarrakan",    "label": "Տարրական դպրոց",             "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "himnakan",    "label": "Հիմնական դպրոց",             "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "10-15"},
            {"code": "avag",        "label": "Ավագ դպրոց / Ավագ",          "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "hamalsaran",  "label": "Համալսարան",                  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "am-t1", "label": "Տարրական 1-ին դասարան", "order": 1},
            {"code": "am-t4", "label": "Տարրական 4-րդ դասարան", "order": 4},
            {"code": "am-h5", "label": "Հիմնական 5-րդ դասարան", "order": 5},
            {"code": "am-h9", "label": "Հիմնական 9-րդ դասարան", "order": 9},
            {"code": "am-a10","label": "Ավագ 10-րդ դասարան",    "order": 10},
            {"code": "am-a12","label": "Ավագ 12-րդ դասարան (Ավարտական)", "order": 12},
        ],
        "terminology": {
            "teacher": "Ուսուցիչ",
            "principal": "Տնօրեն",
            "term": "Կիսամյակ",
            "report_card": "Օրագիր / Ատեստատ",
            "grade_level": "Դասարան",
        },
    },
    "AZ": {  # Azerbaijan
        "calendar_system": {
            "code": "az-2-semestr",
            "label": "2 Semestr (Azərbaycan)",
            "term_count": 2,
            "term_names": ["I yarımil", "II yarımil"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "ushaqbagchasi","label": "Uşaq bağçası",      "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "ibtidai",      "label": "İbtidai məktəb",    "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "umumi-orta",   "label": "Ümumi orta məktəb", "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "10-15"},
            {"code": "tam-orta",     "label": "Tam orta məktəb / Lisey", "glyph": "\U0001F393", "primary_sector": "secondary", "typical_ages": "15-17"},
            {"code": "universitet",  "label": "Universitet",       "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "az-ib1",  "label": "İbtidai 1-ci sinif",    "order": 1},
            {"code": "az-ib4",  "label": "İbtidai 4-cü sinif",    "order": 4},
            {"code": "az-uo5",  "label": "Ümumi orta 5-ci sinif", "order": 5},
            {"code": "az-uo9",  "label": "Ümumi orta 9-cu sinif (buraxılış)", "order": 9},
            {"code": "az-to10", "label": "Tam orta 10-cu sinif",  "order": 10},
            {"code": "az-to11", "label": "Tam orta 11-ci sinif (Attestat)",   "order": 11},
        ],
        "terminology": {
            "teacher": "Müəllim/ə",
            "principal": "Direktor",
            "term": "Yarımil / Semestr",
            "report_card": "Qiymət vərəqi / Attestat",
            "grade_level": "Sinif",
        },
    },
    "GE": {  # Georgia (Caucasus)
        "calendar_system": {
            "code": "ge-2-semestri",
            "label": "2 სემესტრი (ქართული)",
            "term_count": 2,
            "term_names": ["I სემესტრი", "II სემესტრი"],
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "bagi",        "label": "ბაგა-ბაღი",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "datsq",       "label": "დაწყებითი სკოლა",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "dziritadi",   "label": "ძირითადი სკოლა",      "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "sashualo",    "label": "საშუალო სკოლა",       "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universiteti","label": "უნივერსიტეტი",          "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ge-d1",  "label": "დაწყებითი 1 კლასი",      "order": 1},
            {"code": "ge-d6",  "label": "დაწყებითი 6 კლასი",      "order": 6},
            {"code": "ge-dz7", "label": "ძირითადი 7 კლასი",       "order": 7},
            {"code": "ge-dz9", "label": "ძირითადი 9 კლასი",       "order": 9},
            {"code": "ge-s10", "label": "საშუალო 10 კლასი",       "order": 10},
            {"code": "ge-s12", "label": "საშუალო 12 კლასი (ერთიანი ეროვნული გამოცდები)", "order": 12},
        ],
        "terminology": {
            "teacher": "მასწავლებელი",
            "principal": "დირექტორი",
            "term": "სემესტრი",
            "report_card": "ატესტატი / დღიური",
            "grade_level": "კლასი",
        },
    },
    "FJ": {  # Fiji (Southern Hemisphere, British heritage)
        "calendar_system": {
            "code": "fj-3-term",
            "label": "3 Terms (Fijian school year — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "kindy",     "label": "Kindergarten / Early Childhood", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School",                 "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "secondary", "label": "Secondary School",               "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "tvet",      "label": "TVET / Technical College",       "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "usp",       "label": "University (USP / FNU / UniFiji)","glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "fj-y1",  "label": "Year 1",                       "order": 1},
            {"code": "fj-y6",  "label": "Year 6",                       "order": 6},
            {"code": "fj-y8",  "label": "Year 8 (Fiji Eighth Year Exam)","order": 8},
            {"code": "fj-y9",  "label": "Year 9 (Secondary)",           "order": 9},
            {"code": "fj-y12", "label": "Year 12 (FSFE)",               "order": 12},
            {"code": "fj-y13", "label": "Year 13 (FSFE Form 7)",        "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Qasenivuli",
            "principal": "Head Teacher / Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Year / Form",
        },
    },
    "KI": {  # Kiribati
        "calendar_system": {
            "code": "ki-3-term",
            "label": "3 Terms (Kiribati school year — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Kindergarten",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School",             "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "jss",       "label": "Junior Secondary School",    "glyph": "\U0001F4DA", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "sss",       "label": "Senior Secondary School",    "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "kit",       "label": "Kiribati Institute of Technology / USP Tarawa", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ki-cl1",  "label": "Class 1",  "order": 1},
            {"code": "ki-cl6",  "label": "Class 6",  "order": 6},
            {"code": "ki-f1",   "label": "Form 1 (JSS)",  "order": 7},
            {"code": "ki-f3",   "label": "Form 3 (JSS)",  "order": 9},
            {"code": "ki-f4",   "label": "Form 4 (SSS)",  "order": 10},
            {"code": "ki-f6",   "label": "Form 6 (PSSC / SPFSC)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Tia Reirei",
            "principal": "Head Teacher / Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Class / Form",
        },
    },
    "MH": {  # Marshall Islands (US-trust-territory aligned)
        "calendar_system": {
            "code": "mh-2-semester",
            "label": "2 Semesters (Marshall Islands — US-aligned)",
            "term_count": 2,
            "term_names": ["Fall Semester", "Spring Semester"],
            "week_start": 0,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "preschool",  "label": "Preschool / Head Start",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "elementary", "label": "Elementary School",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "secondary",  "label": "Secondary / High School", "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "cmi",        "label": "College of the Marshall Islands", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mh-k",   "label": "Kindergarten", "order": 1},
            {"code": "mh-g1",  "label": "Grade 1",      "order": 2},
            {"code": "mh-g8",  "label": "Grade 8",      "order": 9},
            {"code": "mh-g9",  "label": "Grade 9",      "order": 10},
            {"code": "mh-g12", "label": "Grade 12",     "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Ri-kaki",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "FM": {  # Federated States of Micronesia
        "calendar_system": {
            "code": "fm-2-semester",
            "label": "2 Semesters (FSM — US-aligned)",
            "term_count": 2,
            "term_names": ["Fall Semester", "Spring Semester"],
            "week_start": 0,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "preschool",  "label": "Preschool / Head Start",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "elementary", "label": "Elementary School",              "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "highschool", "label": "High School",                    "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "comfsm",     "label": "College of Micronesia-FSM",     "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "fm-k",   "label": "Kindergarten", "order": 1},
            {"code": "fm-g1",  "label": "Grade 1",      "order": 2},
            {"code": "fm-g8",  "label": "Grade 8",      "order": 9},
            {"code": "fm-g9",  "label": "Grade 9",      "order": 10},
            {"code": "fm-g12", "label": "Grade 12",     "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Sensei",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "NR": {  # Nauru
        "calendar_system": {
            "code": "nr-3-term",
            "label": "3 Terms (Nauruan school year — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool",                   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School",              "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-12"},
            {"code": "secondary", "label": "Secondary School",            "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "12-18"},
            {"code": "tertiary",  "label": "Tertiary / USP Nauru Campus", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "nr-y1",  "label": "Year 1",  "order": 1},
            {"code": "nr-y6",  "label": "Year 6",  "order": 6},
            {"code": "nr-y7",  "label": "Year 7 (Secondary)", "order": 7},
            {"code": "nr-y12", "label": "Year 12 (NSC)",      "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Year",
        },
    },
    "PW": {  # Palau (US-trust-territory aligned)
        "calendar_system": {
            "code": "pw-2-semester",
            "label": "2 Semesters (Palau — US-aligned)",
            "term_count": 2,
            "term_names": ["Fall Semester", "Spring Semester"],
            "week_start": 0,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "headstart", "label": "Head Start / Preschool",   "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "elementary","label": "Elementary School",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "highschool","label": "Palau High School",        "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "pcc",       "label": "Palau Community College", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "pw-k",   "label": "Kindergarten", "order": 1},
            {"code": "pw-g1",  "label": "Grade 1",      "order": 2},
            {"code": "pw-g8",  "label": "Grade 8",      "order": 9},
            {"code": "pw-g9",  "label": "Grade 9",      "order": 10},
            {"code": "pw-g12", "label": "Grade 12",     "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Sensei",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "PG": {  # Papua New Guinea
        "calendar_system": {
            "code": "pg-4-term",
            "label": "4 Terms (PNG school year — Jan-Dec)",
            "term_count": 4,
            "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "elementary",  "label": "Elementary (Prep / E1 / E2)",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "6-9"},
            {"code": "primary",     "label": "Primary School (Grades 3-8)",       "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "9-14"},
            {"code": "secondary",   "label": "Secondary School (Grades 9-12)",    "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "tvet",        "label": "Technical / Business College",      "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "university",  "label": "University (UPNG / UoG / Divine Word)", "glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "pg-prep", "label": "Prep",                       "order": 0},
            {"code": "pg-g3",   "label": "Grade 3 (Primary)",          "order": 3},
            {"code": "pg-g8",   "label": "Grade 8 (Primary exit)",     "order": 8},
            {"code": "pg-g9",   "label": "Grade 9 (Secondary)",        "order": 9},
            {"code": "pg-g10",  "label": "Grade 10 (Lower Secondary Cert)", "order": 10},
            {"code": "pg-g12",  "label": "Grade 12 (Higher School Cert)",   "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Tisa",
            "principal": "Headmaster / Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "WS": {  # Samoa
        "calendar_system": {
            "code": "ws-4-term",
            "label": "4 Terms (Samoan school year — Jan/Feb-Dec)",
            "term_count": 4,
            "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "aoga-amata", "label": "Aoga Amata (ECE)",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",    "label": "Primary School",          "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "college",    "label": "Secondary / College",     "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "nus",        "label": "National University of Samoa / USP Alafua", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ws-y1",  "label": "Year 1",  "order": 1},
            {"code": "ws-y8",  "label": "Year 8 (Samoa Primary School Cert)", "order": 8},
            {"code": "ws-y9",  "label": "Year 9 (Secondary)",                  "order": 9},
            {"code": "ws-y12", "label": "Year 12 (Samoa Secondary Leaving Cert)", "order": 12},
            {"code": "ws-y13", "label": "Year 13 (PSSC / SPFSC)",              "order": 13},
        ],
        "terminology": {
            "teacher": "Faiaoga",
            "principal": "Pule Aoga / Principal",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Year",
        },
    },
    "SB": {  # Solomon Islands
        "calendar_system": {
            "code": "sb-3-term",
            "label": "3 Terms (Solomon Islands — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "ece",       "label": "Early Childhood Education",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School",             "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secondary", "label": "Secondary School",           "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "12-18"},
            {"code": "tvet",      "label": "Technical / Vocational",     "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "sinu",      "label": "Solomon Islands National University", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sb-y1",  "label": "Year 1",  "order": 1},
            {"code": "sb-y6",  "label": "Year 6 (Primary exit)", "order": 6},
            {"code": "sb-f1",  "label": "Form 1 (Secondary)",    "order": 7},
            {"code": "sb-f5",  "label": "Form 5 (SISC)",         "order": 11},
            {"code": "sb-f6",  "label": "Form 6 (SISC3)",        "order": 12},
            {"code": "sb-f7",  "label": "Form 7 (PSSC / SPFSC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal / Headmaster",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Year / Form",
        },
    },
    "TO": {  # Tonga
        "calendar_system": {
            "code": "to-3-term",
            "label": "3 Terms (Tongan school year — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Kindergarten",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School (Ako Si'i)",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "secondary", "label": "Secondary / College (Kolisi)",     "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "tist",      "label": "Tonga Institute of Science & Tech","glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "usp",       "label": "USP Tonga / 'Atenisi University",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "to-cl1",  "label": "Class 1",  "order": 1},
            {"code": "to-cl6",  "label": "Class 6 (Primary exit)", "order": 6},
            {"code": "to-f1",   "label": "Form 1 (Secondary)",     "order": 7},
            {"code": "to-f5",   "label": "Form 5 (TSC)",           "order": 11},
            {"code": "to-f6",   "label": "Form 6 (PSSC)",          "order": 12},
            {"code": "to-f7",   "label": "Form 7 (SPFSC)",         "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Faiako",
            "principal": "Principal / Puleako",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Class / Form",
        },
    },
    "TV": {  # Tuvalu
        "calendar_system": {
            "code": "tv-3-term",
            "label": "3 Terms (Tuvaluan school year — Jan-Dec)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Kindergarten",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School",            "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-13"},
            {"code": "secondary", "label": "Motufoua Secondary / Fetuvalu", "glyph": "\U0001F3EB", "primary_sector": "secondary",   "typical_ages": "13-18"},
            {"code": "tmti",      "label": "Tuvalu Maritime Training Inst / USP Tuvalu", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "tv-y1",  "label": "Year 1",  "order": 1},
            {"code": "tv-y8",  "label": "Year 8 (Primary exit)",  "order": 8},
            {"code": "tv-f1",  "label": "Form 1 (Secondary)",     "order": 9},
            {"code": "tv-f5",  "label": "Form 5",                 "order": 13},
            {"code": "tv-f7",  "label": "Form 7 (PSSC / SPFSC)",  "order": 15},
        ],
        "terminology": {
            "teacher": "Teacher / Faiakoga",
            "principal": "Principal / Pulekifa",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Year / Form",
        },
    },
    "VU": {  # Vanuatu (Anglophone + Francophone bilingual systems)
        "calendar_system": {
            "code": "vu-3-term",
            "label": "3 Terms (Vanuatu — Jan-Dec; Anglophone + Francophone streams)",
            "term_count": 3,
            "term_names": ["Term 1 / Trimestre 1", "Term 2 / Trimestre 2", "Term 3 / Trimestre 3"],
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "kindi",     "label": "Kindi / Pre-school / Maternelle",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary",   "label": "Primary School / École primaire",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secondary", "label": "Secondary / Collège / Lycée",             "glyph": "\U0001F3EB", "primary_sector": "secondary",       "typical_ages": "12-18"},
            {"code": "tvet",      "label": "TVET / Vanuatu Institute of Technology", "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "nuv",       "label": "National University of Vanuatu / USP Emalus", "glyph": "\U0001F3DB", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "vu-y1",  "label": "Year 1 / Année 1",            "order": 1},
            {"code": "vu-y6",  "label": "Year 6 / CM2 (Primary exit)", "order": 6},
            {"code": "vu-y7",  "label": "Year 7 / 6e (Secondary)",     "order": 7},
            {"code": "vu-y10", "label": "Year 10 / 3e (Brevet)",       "order": 10},
            {"code": "vu-y13", "label": "Year 13 / Terminale (Bac / VSSC)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Tija / Enseignant·e",
            "principal": "Principal / Hedmasta / Directeur·rice",
            "term": "Term / Trimestre",
            "report_card": "Report Card / Bulletin",
            "grade_level": "Year / Classe",
        },
    },
}
