"""
Country-localized education-system seed data for the country-adaptive signup form.

Each country entry covers:
  - calendar_system: how the school year is divided (term count + names + week start)
  - school_types: the school tiers a parent would recognize, with local labels
  - education_levels: granular grade tiers (used by per-school education_levels M2M)
  - terminology: a few key term overrides (e.g. "teacher" -> "tuteur" in some FR locales)

Data is "display-only" per user decision: storage stays Gregorian ISO 8601; this
file informs UI labels + suggested defaults only. Non-Gregorian calendars
(Ethiopia, Iran, Saudi/Arab states, Israel) get the locale-native names but
storage remains Gregorian.

Tier 1 (~50 countries) carry full hand-researched detail.
Tier 2 (~145 countries) carry regional defaults (Africa->3-term/Brit-influenced;
Latin-America->2-semester/Iberian; East-Asia->2-semester/Confucian, etc.)
"""

COUNTRY_LOCALIZATION = {
    "US": {
        "calendar_system": {
            "code": "us-2-semester",
            "label": "2 Semesters (Fall / Spring)",
            "term_count": 2,
            "term_names": ["Fall Semester", "Spring Semester"],
            "has_summer_term": True,
            "summer_term_name": "Summer Session",
            "week_start": 0,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Pre-K", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "elementary", "label": "Elementary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "5-11"},
            {"code": "middle", "label": "Middle School", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-14"},
            {"code": "high", "label": "High School", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "14-18"},
            {"code": "college", "label": "College / University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
            {"code": "k12", "label": "K-12 (combined)", "glyph": "\U0001F3EB", "primary_sector": "k12", "typical_ages": "5-18"},
        ],
        "education_levels": [
            {"code": "us-prek", "label": "Pre-K", "order": 0},
            {"code": "us-k", "label": "Kindergarten", "order": 1},
            {"code": "us-g1", "label": "Grade 1", "order": 2},
            {"code": "us-g2", "label": "Grade 2", "order": 3},
            {"code": "us-g3", "label": "Grade 3", "order": 4},
            {"code": "us-g4", "label": "Grade 4", "order": 5},
            {"code": "us-g5", "label": "Grade 5", "order": 6},
            {"code": "us-g6", "label": "Grade 6", "order": 7},
            {"code": "us-g7", "label": "Grade 7", "order": 8},
            {"code": "us-g8", "label": "Grade 8", "order": 9},
            {"code": "us-g9", "label": "Grade 9 (Freshman)", "order": 10},
            {"code": "us-g10", "label": "Grade 10 (Sophomore)", "order": 11},
            {"code": "us-g11", "label": "Grade 11 (Junior)", "order": 12},
            {"code": "us-g12", "label": "Grade 12 (Senior)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "GB": {
        "calendar_system": {
            "code": "uk-3-term",
            "label": "3 Terms (Autumn / Spring / Summer) with half-terms",
            "term_count": 3,
            "term_names": ["Autumn Term", "Spring Term", "Summer Term"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery", "label": "Nursery", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-4"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "4-11"},
            {"code": "secondary", "label": "Secondary School", "glyph": "\U0001F3EB", "primary_sector": "secondary", "typical_ages": "11-16"},
            {"code": "sixth-form", "label": "Sixth Form / College", "glyph": "\U0001F393", "primary_sector": "post_secondary", "typical_ages": "16-18"},
            {"code": "university", "label": "University", "glyph": "\U0001F3DB️", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "uk-rec", "label": "Reception", "order": 0},
            {"code": "uk-y1", "label": "Year 1", "order": 1},
            {"code": "uk-y2", "label": "Year 2", "order": 2},
            {"code": "uk-y3", "label": "Year 3", "order": 3},
            {"code": "uk-y4", "label": "Year 4", "order": 4},
            {"code": "uk-y5", "label": "Year 5", "order": 5},
            {"code": "uk-y6", "label": "Year 6", "order": 6},
            {"code": "uk-y7", "label": "Year 7", "order": 7},
            {"code": "uk-y8", "label": "Year 8", "order": 8},
            {"code": "uk-y9", "label": "Year 9", "order": 9},
            {"code": "uk-y10", "label": "Year 10 (GCSE)", "order": 10},
            {"code": "uk-y11", "label": "Year 11 (GCSE)", "order": 11},
            {"code": "uk-y12", "label": "Year 12 (AS / Lower Sixth)", "order": 12},
            {"code": "uk-y13", "label": "Year 13 (A2 / Upper Sixth)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Headteacher",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Year",
        },
    },
    "CA": {
        "calendar_system": {
            "code": "ca-2-semester",
            "label": "2 Semesters (Fall / Winter)",
            "term_count": 2,
            "term_names": ["Fall Semester", "Winter Semester"],
            "has_summer_term": True,
            "summer_term_name": "Summer School",
            "week_start": 0,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Daycare", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-4"},
            {"code": "elementary", "label": "Elementary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "5-11"},
            {"code": "middle", "label": "Middle School / Junior High", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-14"},
            {"code": "secondary", "label": "Secondary / High School", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "14-18"},
            {"code": "cegep", "label": "CEGEP (QC) / College", "glyph": "\U0001F393", "primary_sector": "post_secondary", "typical_ages": "17-19"},
            {"code": "university", "label": "University", "glyph": "\U0001F3DB️", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ca-jk", "label": "Junior Kindergarten", "order": 0},
            {"code": "ca-sk", "label": "Senior Kindergarten", "order": 1},
            {"code": "ca-g1", "label": "Grade 1", "order": 2},
            {"code": "ca-g2", "label": "Grade 2", "order": 3},
            {"code": "ca-g3", "label": "Grade 3", "order": 4},
            {"code": "ca-g4", "label": "Grade 4", "order": 5},
            {"code": "ca-g5", "label": "Grade 5", "order": 6},
            {"code": "ca-g6", "label": "Grade 6", "order": 7},
            {"code": "ca-g7", "label": "Grade 7", "order": 8},
            {"code": "ca-g8", "label": "Grade 8", "order": 9},
            {"code": "ca-g9", "label": "Grade 9", "order": 10},
            {"code": "ca-g10", "label": "Grade 10", "order": 11},
            {"code": "ca-g11", "label": "Grade 11", "order": 12},
            {"code": "ca-g12", "label": "Grade 12", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Semester",
            "report_card": "Report Card",
            "grade_level": "Grade",
        },
    },
    "IE": {
        "calendar_system": {
            "code": "ie-3-term",
            "label": "3 Terms (Autumn / Spring / Summer)",
            "term_count": 3,
            "term_names": ["Autumn Term", "Spring Term", "Summer Term"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "naionra", "label": "Naíonra / Pre-school", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary", "label": "Primary School (Bunscoil)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "4-12"},
            {"code": "secondary", "label": "Secondary School (Meánscoil)", "glyph": "\U0001F3EB", "primary_sector": "secondary", "typical_ages": "12-18"},
            {"code": "third-level", "label": "Third Level / University", "glyph": "\U0001F3DB️", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ie-jinf", "label": "Junior Infants", "order": 0},
            {"code": "ie-sinf", "label": "Senior Infants", "order": 1},
            {"code": "ie-1c", "label": "1st Class", "order": 2},
            {"code": "ie-2c", "label": "2nd Class", "order": 3},
            {"code": "ie-3c", "label": "3rd Class", "order": 4},
            {"code": "ie-4c", "label": "4th Class", "order": 5},
            {"code": "ie-5c", "label": "5th Class", "order": 6},
            {"code": "ie-6c", "label": "6th Class", "order": 7},
            {"code": "ie-1y", "label": "1st Year", "order": 8},
            {"code": "ie-2y", "label": "2nd Year", "order": 9},
            {"code": "ie-3y", "label": "3rd Year (Junior Cert)", "order": 10},
            {"code": "ie-ty", "label": "Transition Year", "order": 11},
            {"code": "ie-5y", "label": "5th Year", "order": 12},
            {"code": "ie-6y", "label": "6th Year (Leaving Cert)", "order": 13},
        ],
        "terminology": {
            "teacher": "Múinteoir",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Class / Year",
        },
    },
    "AU": {
        "calendar_system": {
            "code": "au-4-term",
            "label": "4 Terms (Australian school year)",
            "term_count": 4,
            "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "has_summer_term": False,
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "kindy", "label": "Kindy / Pre-school", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "5-12"},
            {"code": "secondary", "label": "Secondary / High School", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "12-18"},
            {"code": "tafe", "label": "TAFE / Vocational", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "16+"},
            {"code": "university", "label": "University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "au-prep", "label": "Prep / Foundation", "order": 0},
            {"code": "au-y1", "label": "Year 1", "order": 1},
            {"code": "au-y2", "label": "Year 2", "order": 2},
            {"code": "au-y3", "label": "Year 3", "order": 3},
            {"code": "au-y4", "label": "Year 4", "order": 4},
            {"code": "au-y5", "label": "Year 5", "order": 5},
            {"code": "au-y6", "label": "Year 6", "order": 6},
            {"code": "au-y7", "label": "Year 7", "order": 7},
            {"code": "au-y8", "label": "Year 8", "order": 8},
            {"code": "au-y9", "label": "Year 9", "order": 9},
            {"code": "au-y10", "label": "Year 10", "order": 10},
            {"code": "au-y11", "label": "Year 11", "order": 11},
            {"code": "au-y12", "label": "Year 12 (HSC/VCE/QCE)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Year",
        },
    },
    "NZ": {
        "calendar_system": {
            "code": "nz-4-term",
            "label": "4 Terms (NZ school year)",
            "term_count": 4,
            "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "has_summer_term": False,
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "ece", "label": "Early Childhood / Kōhanga Reo", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "5-11"},
            {"code": "intermediate", "label": "Intermediate", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-13"},
            {"code": "secondary", "label": "Secondary / College", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "13-18"},
            {"code": "university", "label": "University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "nz-y1", "label": "Year 1", "order": 0},
            {"code": "nz-y2", "label": "Year 2", "order": 1},
            {"code": "nz-y3", "label": "Year 3", "order": 2},
            {"code": "nz-y4", "label": "Year 4", "order": 3},
            {"code": "nz-y5", "label": "Year 5", "order": 4},
            {"code": "nz-y6", "label": "Year 6", "order": 5},
            {"code": "nz-y7", "label": "Year 7", "order": 6},
            {"code": "nz-y8", "label": "Year 8", "order": 7},
            {"code": "nz-y9", "label": "Year 9", "order": 8},
            {"code": "nz-y10", "label": "Year 10", "order": 9},
            {"code": "nz-y11", "label": "Year 11 (NCEA 1)", "order": 10},
            {"code": "nz-y12", "label": "Year 12 (NCEA 2)", "order": 11},
            {"code": "nz-y13", "label": "Year 13 (NCEA 3)", "order": 12},
        ],
        "terminology": {
            "teacher": "Kaiako / Teacher",
            "principal": "Tumuaki / Principal",
            "term": "Term",
            "report_card": "Report",
            "grade_level": "Year",
        },
    },
    "FR": {
        "calendar_system": {
            "code": "fr-3-trimester",
            "label": "3 Trimestres",
            "term_count": 3,
            "term_names": ["Premier Trimestre", "Deuxième Trimestre", "Troisième Trimestre"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "École Maternelle", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "elementaire", "label": "École Élémentaire", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "college", "label": "Collège", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-15"},
            {"code": "lycee", "label": "Lycée", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "universite", "label": "Université / Grande École", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "fr-ps", "label": "Petite Section", "order": 0},
            {"code": "fr-ms", "label": "Moyenne Section", "order": 1},
            {"code": "fr-gs", "label": "Grande Section", "order": 2},
            {"code": "fr-cp", "label": "CP", "order": 3},
            {"code": "fr-ce1", "label": "CE1", "order": 4},
            {"code": "fr-ce2", "label": "CE2", "order": 5},
            {"code": "fr-cm1", "label": "CM1", "order": 6},
            {"code": "fr-cm2", "label": "CM2", "order": 7},
            {"code": "fr-6e", "label": "6ème", "order": 8},
            {"code": "fr-5e", "label": "5ème", "order": 9},
            {"code": "fr-4e", "label": "4ème", "order": 10},
            {"code": "fr-3e", "label": "3ème (Brevet)", "order": 11},
            {"code": "fr-2nd", "label": "Seconde", "order": 12},
            {"code": "fr-1e", "label": "Première", "order": 13},
            {"code": "fr-term", "label": "Terminale (Bac)", "order": 14},
        ],
        "terminology": {
            "teacher": "Enseignant",
            "principal": "Directeur / Proviseur",
            "term": "Trimestre",
            "report_card": "Bulletin",
            "grade_level": "Niveau / Classe",
        },
    },
    "DE": {
        "calendar_system": {
            "code": "de-2-halbjahr",
            "label": "2 Halbjahre",
            "term_count": 2,
            "term_names": ["1. Halbjahr", "2. Halbjahr"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "kita", "label": "Kindertagesstätte (Kita)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-6"},
            {"code": "grundschule", "label": "Grundschule", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-10"},
            {"code": "hauptschule", "label": "Hauptschule / Realschule", "glyph": "\U0001F4DA", "primary_sector": "secondary", "typical_ages": "10-16"},
            {"code": "gymnasium", "label": "Gymnasium", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "10-18"},
            {"code": "berufsschule", "label": "Berufsschule", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "15+"},
            {"code": "universitaet", "label": "Universität / Hochschule", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "de-k1", "label": "1. Klasse", "order": 0},
            {"code": "de-k2", "label": "2. Klasse", "order": 1},
            {"code": "de-k3", "label": "3. Klasse", "order": 2},
            {"code": "de-k4", "label": "4. Klasse", "order": 3},
            {"code": "de-k5", "label": "5. Klasse", "order": 4},
            {"code": "de-k6", "label": "6. Klasse", "order": 5},
            {"code": "de-k7", "label": "7. Klasse", "order": 6},
            {"code": "de-k8", "label": "8. Klasse", "order": 7},
            {"code": "de-k9", "label": "9. Klasse", "order": 8},
            {"code": "de-k10", "label": "10. Klasse", "order": 9},
            {"code": "de-k11", "label": "11. Klasse", "order": 10},
            {"code": "de-k12", "label": "12. Klasse (Abitur)", "order": 11},
            {"code": "de-k13", "label": "13. Klasse (Abitur)", "order": 12},
        ],
        "terminology": {
            "teacher": "Lehrer",
            "principal": "Schulleiter",
            "term": "Halbjahr",
            "report_card": "Zeugnis",
            "grade_level": "Klasse",
        },
    },
    "ES": {
        "calendar_system": {
            "code": "es-3-trimester",
            "label": "3 Trimestres",
            "term_count": 3,
            "term_names": ["Primer Trimestre", "Segundo Trimestre", "Tercer Trimestre"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "infantil", "label": "Educación Infantil", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-6"},
            {"code": "primaria", "label": "Educación Primaria", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "eso", "label": "Educación Secundaria (ESO)", "glyph": "\U0001F4DA", "primary_sector": "secondary", "typical_ages": "12-16"},
            {"code": "bachillerato", "label": "Bachillerato", "glyph": "\U0001F3DB️", "primary_sector": "post_secondary", "typical_ages": "16-18"},
            {"code": "fp", "label": "Formación Profesional", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "16+"},
            {"code": "universidad", "label": "Universidad", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "es-inf1", "label": "Infantil 3 años", "order": 0},
            {"code": "es-inf2", "label": "Infantil 4 años", "order": 1},
            {"code": "es-inf3", "label": "Infantil 5 años", "order": 2},
            {"code": "es-p1", "label": "1º Primaria", "order": 3},
            {"code": "es-p2", "label": "2º Primaria", "order": 4},
            {"code": "es-p3", "label": "3º Primaria", "order": 5},
            {"code": "es-p4", "label": "4º Primaria", "order": 6},
            {"code": "es-p5", "label": "5º Primaria", "order": 7},
            {"code": "es-p6", "label": "6º Primaria", "order": 8},
            {"code": "es-eso1", "label": "1º ESO", "order": 9},
            {"code": "es-eso2", "label": "2º ESO", "order": 10},
            {"code": "es-eso3", "label": "3º ESO", "order": 11},
            {"code": "es-eso4", "label": "4º ESO", "order": 12},
            {"code": "es-bach1", "label": "1º Bachillerato", "order": 13},
            {"code": "es-bach2", "label": "2º Bachillerato", "order": 14},
        ],
        "terminology": {
            "teacher": "Profesor",
            "principal": "Director",
            "term": "Trimestre",
            "report_card": "Boletín de Notas",
            "grade_level": "Curso",
        },
    },
    "IT": {
        "calendar_system": {
            "code": "it-2-quadrimester",
            "label": "2 Quadrimestri",
            "term_count": 2,
            "term_names": ["Primo Quadrimestre", "Secondo Quadrimestre"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "infanzia", "label": "Scuola dell'Infanzia", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaria", "label": "Scuola Primaria", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "media", "label": "Scuola Secondaria di I Grado", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-14"},
            {"code": "superiori", "label": "Scuola Secondaria di II Grado", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "14-19"},
            {"code": "universita", "label": "Università", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "it-p1", "label": "1ª Primaria", "order": 0},
            {"code": "it-p2", "label": "2ª Primaria", "order": 1},
            {"code": "it-p3", "label": "3ª Primaria", "order": 2},
            {"code": "it-p4", "label": "4ª Primaria", "order": 3},
            {"code": "it-p5", "label": "5ª Primaria", "order": 4},
            {"code": "it-m1", "label": "1ª Media", "order": 5},
            {"code": "it-m2", "label": "2ª Media", "order": 6},
            {"code": "it-m3", "label": "3ª Media", "order": 7},
            {"code": "it-s1", "label": "1ª Superiore", "order": 8},
            {"code": "it-s2", "label": "2ª Superiore", "order": 9},
            {"code": "it-s3", "label": "3ª Superiore", "order": 10},
            {"code": "it-s4", "label": "4ª Superiore", "order": 11},
            {"code": "it-s5", "label": "5ª Superiore (Maturità)", "order": 12},
        ],
        "terminology": {
            "teacher": "Insegnante",
            "principal": "Preside / Dirigente Scolastico",
            "term": "Quadrimestre",
            "report_card": "Pagella",
            "grade_level": "Classe",
        },
    },
    "NL": {
        "calendar_system": {
            "code": "nl-2-semester",
            "label": "2 Semesters",
            "term_count": 2,
            "term_names": ["Eerste Semester", "Tweede Semester"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "peuterspeelzaal", "label": "Peuterspeelzaal", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-4"},
            {"code": "basisschool", "label": "Basisschool", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "4-12"},
            {"code": "vmbo", "label": "VMBO", "glyph": "\U0001F527", "primary_sector": "secondary", "typical_ages": "12-16"},
            {"code": "havo", "label": "HAVO", "glyph": "\U0001F4DA", "primary_sector": "secondary", "typical_ages": "12-17"},
            {"code": "vwo", "label": "VWO / Gymnasium", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "12-18"},
            {"code": "universiteit", "label": "Universiteit / HBO", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "nl-g1", "label": "Groep 1", "order": 0},
            {"code": "nl-g2", "label": "Groep 2", "order": 1},
            {"code": "nl-g3", "label": "Groep 3", "order": 2},
            {"code": "nl-g4", "label": "Groep 4", "order": 3},
            {"code": "nl-g5", "label": "Groep 5", "order": 4},
            {"code": "nl-g6", "label": "Groep 6", "order": 5},
            {"code": "nl-g7", "label": "Groep 7", "order": 6},
            {"code": "nl-g8", "label": "Groep 8", "order": 7},
            {"code": "nl-bk1", "label": "Brugklas (Klas 1)", "order": 8},
            {"code": "nl-k2", "label": "Klas 2", "order": 9},
            {"code": "nl-k3", "label": "Klas 3", "order": 10},
            {"code": "nl-k4", "label": "Klas 4", "order": 11},
            {"code": "nl-k5", "label": "Klas 5", "order": 12},
            {"code": "nl-k6", "label": "Klas 6 (VWO)", "order": 13},
        ],
        "terminology": {
            "teacher": "Leraar / Docent",
            "principal": "Schoolleider / Directeur",
            "term": "Semester",
            "report_card": "Rapport",
            "grade_level": "Groep / Klas",
        },
    },
    "BE": {
        "calendar_system": {
            "code": "be-3-trimester",
            "label": "3 Trimestres / Trimesters",
            "term_count": 3,
            "term_names": ["Premier Trimestre", "Deuxième Trimestre", "Troisième Trimestre"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "maternelle", "label": "Maternelle / Kleuterschool", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-6"},
            {"code": "primaire", "label": "École Primaire / Lagere School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "secondaire", "label": "École Secondaire / Middelbare", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "12-18"},
            {"code": "universite", "label": "Université / Universiteit", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "be-m1", "label": "Maternelle 1", "order": 0},
            {"code": "be-m2", "label": "Maternelle 2", "order": 1},
            {"code": "be-m3", "label": "Maternelle 3", "order": 2},
            {"code": "be-p1", "label": "Primaire 1", "order": 3},
            {"code": "be-p2", "label": "Primaire 2", "order": 4},
            {"code": "be-p3", "label": "Primaire 3", "order": 5},
            {"code": "be-p4", "label": "Primaire 4", "order": 6},
            {"code": "be-p5", "label": "Primaire 5", "order": 7},
            {"code": "be-p6", "label": "Primaire 6", "order": 8},
            {"code": "be-s1", "label": "Secondaire 1", "order": 9},
            {"code": "be-s2", "label": "Secondaire 2", "order": 10},
            {"code": "be-s3", "label": "Secondaire 3", "order": 11},
            {"code": "be-s4", "label": "Secondaire 4", "order": 12},
            {"code": "be-s5", "label": "Secondaire 5", "order": 13},
            {"code": "be-s6", "label": "Secondaire 6", "order": 14},
        ],
        "terminology": {
            "teacher": "Enseignant / Leerkracht",
            "principal": "Directeur",
            "term": "Trimestre",
            "report_card": "Bulletin / Rapport",
            "grade_level": "Année",
        },
    },
    "PT": {
        "calendar_system": {
            "code": "pt-3-period",
            "label": "3 Períodos",
            "term_count": 3,
            "term_names": ["1º Período", "2º Período", "3º Período"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "pre-escolar", "label": "Educação Pré-Escolar", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "basico", "label": "Ensino Básico", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-15"},
            {"code": "secundario", "label": "Ensino Secundário", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "superior", "label": "Ensino Superior", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "pt-1a", "label": "1º Ano", "order": 0},
            {"code": "pt-2a", "label": "2º Ano", "order": 1},
            {"code": "pt-3a", "label": "3º Ano", "order": 2},
            {"code": "pt-4a", "label": "4º Ano", "order": 3},
            {"code": "pt-5a", "label": "5º Ano", "order": 4},
            {"code": "pt-6a", "label": "6º Ano", "order": 5},
            {"code": "pt-7a", "label": "7º Ano", "order": 6},
            {"code": "pt-8a", "label": "8º Ano", "order": 7},
            {"code": "pt-9a", "label": "9º Ano", "order": 8},
            {"code": "pt-10a", "label": "10º Ano", "order": 9},
            {"code": "pt-11a", "label": "11º Ano", "order": 10},
            {"code": "pt-12a", "label": "12º Ano", "order": 11},
        ],
        "terminology": {
            "teacher": "Professor",
            "principal": "Diretor",
            "term": "Período",
            "report_card": "Caderneta / Avaliação",
            "grade_level": "Ano",
        },
    },
    "SE": {
        "calendar_system": {
            "code": "se-2-termin",
            "label": "2 Terminer (Höst / Vår)",
            "term_count": 2,
            "term_names": ["Hösttermin", "Vårtermin"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "forskola", "label": "Förskola", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "1-6"},
            {"code": "grundskola", "label": "Grundskola", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-16"},
            {"code": "gymnasium", "label": "Gymnasium", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "16-19"},
            {"code": "hogskola", "label": "Högskola / Universitet", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "se-forsk", "label": "Förskoleklass", "order": 0},
            {"code": "se-a1", "label": "Årskurs 1", "order": 1},
            {"code": "se-a2", "label": "Årskurs 2", "order": 2},
            {"code": "se-a3", "label": "Årskurs 3", "order": 3},
            {"code": "se-a4", "label": "Årskurs 4", "order": 4},
            {"code": "se-a5", "label": "Årskurs 5", "order": 5},
            {"code": "se-a6", "label": "Årskurs 6", "order": 6},
            {"code": "se-a7", "label": "Årskurs 7", "order": 7},
            {"code": "se-a8", "label": "Årskurs 8", "order": 8},
            {"code": "se-a9", "label": "Årskurs 9", "order": 9},
            {"code": "se-g1", "label": "Gymnasium År 1", "order": 10},
            {"code": "se-g2", "label": "Gymnasium År 2", "order": 11},
            {"code": "se-g3", "label": "Gymnasium År 3", "order": 12},
        ],
        "terminology": {
            "teacher": "Lärare",
            "principal": "Rektor",
            "term": "Termin",
            "report_card": "Betyg",
            "grade_level": "Årskurs",
        },
    },
    "NO": {
        "calendar_system": {
            "code": "no-2-termin",
            "label": "2 Terminer (Høst / Vår)",
            "term_count": 2,
            "term_names": ["Høstsemester", "Vårsemester"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "barnehage", "label": "Barnehage", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-6"},
            {"code": "barneskole", "label": "Barneskole", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-13"},
            {"code": "ungdomsskole", "label": "Ungdomsskole", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "13-16"},
            {"code": "vgs", "label": "Videregående Skole", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "16-19"},
            {"code": "universitet", "label": "Universitet / Høgskole", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "no-t1", "label": "1. Trinn", "order": 0},
            {"code": "no-t2", "label": "2. Trinn", "order": 1},
            {"code": "no-t3", "label": "3. Trinn", "order": 2},
            {"code": "no-t4", "label": "4. Trinn", "order": 3},
            {"code": "no-t5", "label": "5. Trinn", "order": 4},
            {"code": "no-t6", "label": "6. Trinn", "order": 5},
            {"code": "no-t7", "label": "7. Trinn", "order": 6},
            {"code": "no-t8", "label": "8. Trinn", "order": 7},
            {"code": "no-t9", "label": "9. Trinn", "order": 8},
            {"code": "no-t10", "label": "10. Trinn", "order": 9},
            {"code": "no-vg1", "label": "VG1", "order": 10},
            {"code": "no-vg2", "label": "VG2", "order": 11},
            {"code": "no-vg3", "label": "VG3", "order": 12},
        ],
        "terminology": {
            "teacher": "Lærer",
            "principal": "Rektor",
            "term": "Semester",
            "report_card": "Vitnemål",
            "grade_level": "Trinn",
        },
    },
    "DK": {
        "calendar_system": {
            "code": "dk-2-semester",
            "label": "2 Semestre",
            "term_count": 2,
            "term_names": ["Efterårssemester", "Forårssemester"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "bornehave", "label": "Børnehave", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "folkeskole", "label": "Folkeskole", "glyph": "\U0001F3EB", "primary_sector": "k12", "typical_ages": "6-16"},
            {"code": "gymnasium", "label": "Gymnasium / STX", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "16-19"},
            {"code": "universitet", "label": "Universitet", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "dk-0", "label": "0. Klasse", "order": 0},
            {"code": "dk-1", "label": "1. Klasse", "order": 1},
            {"code": "dk-2", "label": "2. Klasse", "order": 2},
            {"code": "dk-3", "label": "3. Klasse", "order": 3},
            {"code": "dk-4", "label": "4. Klasse", "order": 4},
            {"code": "dk-5", "label": "5. Klasse", "order": 5},
            {"code": "dk-6", "label": "6. Klasse", "order": 6},
            {"code": "dk-7", "label": "7. Klasse", "order": 7},
            {"code": "dk-8", "label": "8. Klasse", "order": 8},
            {"code": "dk-9", "label": "9. Klasse", "order": 9},
            {"code": "dk-10", "label": "10. Klasse", "order": 10},
            {"code": "dk-g1", "label": "1. G (Gymnasium)", "order": 11},
            {"code": "dk-g2", "label": "2. G", "order": 12},
            {"code": "dk-g3", "label": "3. G", "order": 13},
        ],
        "terminology": {
            "teacher": "Lærer",
            "principal": "Skoleleder",
            "term": "Semester",
            "report_card": "Karakterbog",
            "grade_level": "Klasse",
        },
    },
    "FI": {
        "calendar_system": {
            "code": "fi-2-semester",
            "label": "2 Lukukautta (Syys / Kevät)",
            "term_count": 2,
            "term_names": ["Syyslukukausi", "Kevätlukukausi"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "paivakoti", "label": "Päiväkoti", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-6"},
            {"code": "esikoulu", "label": "Esikoulu", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "6-7"},
            {"code": "peruskoulu", "label": "Peruskoulu", "glyph": "\U0001F3EB", "primary_sector": "k12", "typical_ages": "7-16"},
            {"code": "lukio", "label": "Lukio", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "16-19"},
            {"code": "ammattikoulu", "label": "Ammattikoulu", "glyph": "\U0001F527", "primary_sector": "vocational", "typical_ages": "16+"},
            {"code": "yliopisto", "label": "Yliopisto / AMK", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "fi-esi", "label": "Esikoulu", "order": 0},
            {"code": "fi-l1", "label": "1. Luokka", "order": 1},
            {"code": "fi-l2", "label": "2. Luokka", "order": 2},
            {"code": "fi-l3", "label": "3. Luokka", "order": 3},
            {"code": "fi-l4", "label": "4. Luokka", "order": 4},
            {"code": "fi-l5", "label": "5. Luokka", "order": 5},
            {"code": "fi-l6", "label": "6. Luokka", "order": 6},
            {"code": "fi-l7", "label": "7. Luokka", "order": 7},
            {"code": "fi-l8", "label": "8. Luokka", "order": 8},
            {"code": "fi-l9", "label": "9. Luokka", "order": 9},
            {"code": "fi-lukio1", "label": "Lukio 1", "order": 10},
            {"code": "fi-lukio2", "label": "Lukio 2", "order": 11},
            {"code": "fi-lukio3", "label": "Lukio 3 (Ylioppilas)", "order": 12},
        ],
        "terminology": {
            "teacher": "Opettaja",
            "principal": "Rehtori",
            "term": "Lukukausi",
            "report_card": "Todistus",
            "grade_level": "Luokka",
        },
    },
    "PL": {
        "calendar_system": {
            "code": "pl-2-semester",
            "label": "2 Semestry",
            "term_count": 2,
            "term_names": ["Pierwszy Semestr", "Drugi Semestr"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "przedszkole", "label": "Przedszkole", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "podstawowa", "label": "Szkoła Podstawowa", "glyph": "\U0001F3EB", "primary_sector": "k12", "typical_ages": "6-15"},
            {"code": "liceum", "label": "Liceum / Technikum", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-19"},
            {"code": "uczelnia", "label": "Uczelnia / Uniwersytet", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "pl-k1", "label": "Klasa 1", "order": 0},
            {"code": "pl-k2", "label": "Klasa 2", "order": 1},
            {"code": "pl-k3", "label": "Klasa 3", "order": 2},
            {"code": "pl-k4", "label": "Klasa 4", "order": 3},
            {"code": "pl-k5", "label": "Klasa 5", "order": 4},
            {"code": "pl-k6", "label": "Klasa 6", "order": 5},
            {"code": "pl-k7", "label": "Klasa 7", "order": 6},
            {"code": "pl-k8", "label": "Klasa 8", "order": 7},
            {"code": "pl-l1", "label": "Liceum 1", "order": 8},
            {"code": "pl-l2", "label": "Liceum 2", "order": 9},
            {"code": "pl-l3", "label": "Liceum 3", "order": 10},
            {"code": "pl-l4", "label": "Liceum 4 (Matura)", "order": 11},
        ],
        "terminology": {
            "teacher": "Nauczyciel",
            "principal": "Dyrektor",
            "term": "Semestr",
            "report_card": "Świadectwo",
            "grade_level": "Klasa",
        },
    },
    "RU": {
        "calendar_system": {
            "code": "ru-4-quarter",
            "label": "4 Четверти",
            "term_count": 4,
            "term_names": ["Первая Четверть", "Вторая Четверть", "Третья Четверть", "Четвёртая Четверть"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "detsad", "label": "Детский сад", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-7"},
            {"code": "nachalnaya", "label": "Начальная школа", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "7-11"},
            {"code": "osnovnaya", "label": "Основная школа", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-15"},
            {"code": "srednaya", "label": "Средняя школа (10-11)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-17"},
            {"code": "vuz", "label": "ВУЗ / Университет", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "17+"},
        ],
        "education_levels": [
            {"code": "ru-k1", "label": "1 класс", "order": 0},
            {"code": "ru-k2", "label": "2 класс", "order": 1},
            {"code": "ru-k3", "label": "3 класс", "order": 2},
            {"code": "ru-k4", "label": "4 класс", "order": 3},
            {"code": "ru-k5", "label": "5 класс", "order": 4},
            {"code": "ru-k6", "label": "6 класс", "order": 5},
            {"code": "ru-k7", "label": "7 класс", "order": 6},
            {"code": "ru-k8", "label": "8 класс", "order": 7},
            {"code": "ru-k9", "label": "9 класс (ОГЭ)", "order": 8},
            {"code": "ru-k10", "label": "10 класс", "order": 9},
            {"code": "ru-k11", "label": "11 класс (ЕГЭ)", "order": 10},
        ],
        "terminology": {
            "teacher": "Учитель",
            "principal": "Директор",
            "term": "Четверть",
            "report_card": "Дневник / Табель",
            "grade_level": "Класс",
        },
    },
    "TR": {
        "calendar_system": {
            "code": "tr-2-donem",
            "label": "2 Dönem",
            "term_count": 2,
            "term_names": ["1. Dönem", "2. Dönem"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "anaokulu", "label": "Anaokulu", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "ilkokul", "label": "İlkokul", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-10"},
            {"code": "ortaokul", "label": "Ortaokul", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "10-14"},
            {"code": "lise", "label": "Lise", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "14-18"},
            {"code": "universite", "label": "Üniversite", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "tr-s1", "label": "1. Sınıf", "order": 0},
            {"code": "tr-s2", "label": "2. Sınıf", "order": 1},
            {"code": "tr-s3", "label": "3. Sınıf", "order": 2},
            {"code": "tr-s4", "label": "4. Sınıf", "order": 3},
            {"code": "tr-s5", "label": "5. Sınıf", "order": 4},
            {"code": "tr-s6", "label": "6. Sınıf", "order": 5},
            {"code": "tr-s7", "label": "7. Sınıf", "order": 6},
            {"code": "tr-s8", "label": "8. Sınıf (LGS)", "order": 7},
            {"code": "tr-s9", "label": "9. Sınıf", "order": 8},
            {"code": "tr-s10", "label": "10. Sınıf", "order": 9},
            {"code": "tr-s11", "label": "11. Sınıf", "order": 10},
            {"code": "tr-s12", "label": "12. Sınıf (YKS)", "order": 11},
        ],
        "terminology": {
            "teacher": "Öğretmen",
            "principal": "Müdür",
            "term": "Dönem",
            "report_card": "Karne",
            "grade_level": "Sınıf",
        },
    },
    "JP": {
        "calendar_system": {
            "code": "jp-3-term",
            "label": "3学期制 (Sangakki-sei)",
            "term_count": 3,
            "term_names": ["1学期 (Ichigakki)", "2学期 (Nigakki)", "3学期 (Sangakki)"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 4,
        },
        "school_types": [
            {"code": "youchien", "label": "幼稚園 (Yōchien)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "shogakko", "label": "小学校 (Shōgakkō)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "chugakko", "label": "中学校 (Chūgakkō)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "kotogakko", "label": "高等学校 (Kōtō Gakkō)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "daigaku", "label": "大学 (Daigaku)", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "jp-s1", "label": "小学1年", "order": 0},
            {"code": "jp-s2", "label": "小学2年", "order": 1},
            {"code": "jp-s3", "label": "小学3年", "order": 2},
            {"code": "jp-s4", "label": "小学4年", "order": 3},
            {"code": "jp-s5", "label": "小学5年", "order": 4},
            {"code": "jp-s6", "label": "小学6年", "order": 5},
            {"code": "jp-c1", "label": "中学1年", "order": 6},
            {"code": "jp-c2", "label": "中学2年", "order": 7},
            {"code": "jp-c3", "label": "中学3年", "order": 8},
            {"code": "jp-h1", "label": "高校1年", "order": 9},
            {"code": "jp-h2", "label": "高校2年", "order": 10},
            {"code": "jp-h3", "label": "高校3年", "order": 11},
        ],
        "terminology": {
            "teacher": "先生 (Sensei)",
            "principal": "校長 (Kōchō)",
            "term": "学期 (Gakki)",
            "report_card": "通知表 (Tsūchihyō)",
            "grade_level": "年 (Nen)",
        },
    },
    "KR": {
        "calendar_system": {
            "code": "kr-2-semester",
            "label": "2학기제",
            "term_count": 2,
            "term_names": ["1학기 (1-hakgi)", "2학기 (2-hakgi)"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 3,
        },
        "school_types": [
            {"code": "yuchiwon", "label": "유치원 (Yuchiwon)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "chodeunghakgyo", "label": "초등학교 (Chodeung-hakgyo)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "junghakgyo", "label": "중학교 (Junghakgyo)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "godeunghakgyo", "label": "고등학교 (Godeunghakgyo)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "daehakgyo", "label": "대학교 (Daehakgyo)", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "kr-c1", "label": "초1", "order": 0},
            {"code": "kr-c2", "label": "초2", "order": 1},
            {"code": "kr-c3", "label": "초3", "order": 2},
            {"code": "kr-c4", "label": "초4", "order": 3},
            {"code": "kr-c5", "label": "초5", "order": 4},
            {"code": "kr-c6", "label": "초6", "order": 5},
            {"code": "kr-j1", "label": "중1", "order": 6},
            {"code": "kr-j2", "label": "중2", "order": 7},
            {"code": "kr-j3", "label": "중3", "order": 8},
            {"code": "kr-g1", "label": "고1", "order": 9},
            {"code": "kr-g2", "label": "고2", "order": 10},
            {"code": "kr-g3", "label": "고3 (수능)", "order": 11},
        ],
        "terminology": {
            "teacher": "선생님 (Seonsaengnim)",
            "principal": "교장 (Gyojang)",
            "term": "학기 (Hakgi)",
            "report_card": "성적표 (Seongjeokpyo)",
            "grade_level": "학년 (Hakyeon)",
        },
    },
    "CN": {
        "calendar_system": {
            "code": "cn-2-semester",
            "label": "两学期制 (Liǎng Xuéqī Zhì)",
            "term_count": 2,
            "term_names": ["秋季学期 (Qiūjì Xuéqī)", "春季学期 (Chūnjì Xuéqī)"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "youeryuan", "label": "幼儿园 (Yòu'éryuán)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "xiaoxue", "label": "小学 (Xiǎoxué)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "chuzhong", "label": "初中 (Chūzhōng)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "gaozhong", "label": "高中 (Gāozhōng — Gaokao prep)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "daxue", "label": "大学 (Dàxué)", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "cn-x1", "label": "小学一年级", "order": 0},
            {"code": "cn-x2", "label": "小学二年级", "order": 1},
            {"code": "cn-x3", "label": "小学三年级", "order": 2},
            {"code": "cn-x4", "label": "小学四年级", "order": 3},
            {"code": "cn-x5", "label": "小学五年级", "order": 4},
            {"code": "cn-x6", "label": "小学六年级", "order": 5},
            {"code": "cn-c1", "label": "初一", "order": 6},
            {"code": "cn-c2", "label": "初二", "order": 7},
            {"code": "cn-c3", "label": "初三 (中考)", "order": 8},
            {"code": "cn-g1", "label": "高一", "order": 9},
            {"code": "cn-g2", "label": "高二", "order": 10},
            {"code": "cn-g3", "label": "高三 (高考)", "order": 11},
        ],
        "terminology": {
            "teacher": "老师 (Lǎoshī)",
            "principal": "校长 (Xiàozhǎng)",
            "term": "学期 (Xuéqī)",
            "report_card": "成绩单 (Chéngjì Dān)",
            "grade_level": "年级 (Niánjí)",
        },
    },
    "IN": {
        "calendar_system": {
            "code": "in-3-term",
            "label": "3 Terms (CBSE umbrella)",
            "term_count": 3,
            "term_names": ["Term 1", "Term 2", "Term 3"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 4,
        },
        "school_types": [
            {"code": "preschool", "label": "Pre-school / Playgroup", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-4"},
            {"code": "kg", "label": "Kindergarten (Nursery / LKG / UKG)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-10"},
            {"code": "middle", "label": "Middle School", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "10-14"},
            {"code": "secondary", "label": "Secondary School (Class 9-10)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "14-16"},
            {"code": "higher-secondary", "label": "Higher Secondary (11-12)", "glyph": "\U0001F3DB️", "primary_sector": "post_secondary", "typical_ages": "16-18"},
            {"code": "university", "label": "College / University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "in-nur", "label": "Nursery", "order": 0},
            {"code": "in-lkg", "label": "LKG", "order": 1},
            {"code": "in-ukg", "label": "UKG", "order": 2},
            {"code": "in-c1", "label": "Class 1", "order": 3},
            {"code": "in-c2", "label": "Class 2", "order": 4},
            {"code": "in-c3", "label": "Class 3", "order": 5},
            {"code": "in-c4", "label": "Class 4", "order": 6},
            {"code": "in-c5", "label": "Class 5", "order": 7},
            {"code": "in-c6", "label": "Class 6", "order": 8},
            {"code": "in-c7", "label": "Class 7", "order": 9},
            {"code": "in-c8", "label": "Class 8", "order": 10},
            {"code": "in-c9", "label": "Class 9", "order": 11},
            {"code": "in-c10", "label": "Class 10 (Board Exam)", "order": 12},
            {"code": "in-c11", "label": "Class 11", "order": 13},
            {"code": "in-c12", "label": "Class 12 (Board Exam)", "order": 14},
        ],
        "terminology": {
            "teacher": "Teacher / Shikshak",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Card / Marksheet",
            "grade_level": "Class / Standard",
        },
    },
    "PK": {
        "calendar_system": {
            "code": "pk-3-term",
            "label": "3 Terms",
            "term_count": 3,
            "term_names": ["First Term", "Second Term", "Third Term"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 4,
        },
        "school_types": [
            {"code": "playgroup", "label": "Playgroup", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "2-4"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "5-10"},
            {"code": "middle", "label": "Middle School", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "10-13"},
            {"code": "secondary", "label": "Matric / Secondary", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "13-16"},
            {"code": "intermediate", "label": "Intermediate / FSc / FA", "glyph": "\U0001F3DB️", "primary_sector": "post_secondary", "typical_ages": "16-18"},
            {"code": "university", "label": "University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "pk-nur", "label": "Nursery", "order": 0},
            {"code": "pk-kg", "label": "KG / Prep", "order": 1},
            {"code": "pk-c1", "label": "Class 1", "order": 2},
            {"code": "pk-c2", "label": "Class 2", "order": 3},
            {"code": "pk-c3", "label": "Class 3", "order": 4},
            {"code": "pk-c4", "label": "Class 4", "order": 5},
            {"code": "pk-c5", "label": "Class 5", "order": 6},
            {"code": "pk-c6", "label": "Class 6", "order": 7},
            {"code": "pk-c7", "label": "Class 7", "order": 8},
            {"code": "pk-c8", "label": "Class 8", "order": 9},
            {"code": "pk-c9", "label": "Class 9 (Matric)", "order": 10},
            {"code": "pk-c10", "label": "Class 10 (Matric)", "order": 11},
            {"code": "pk-c11", "label": "First Year (FSc/FA)", "order": 12},
            {"code": "pk-c12", "label": "Second Year (FSc/FA)", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / Ustaad",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Result Card",
            "grade_level": "Class",
        },
    },
    "BD": {
        "calendar_system": {
            "code": "bd-2-term",
            "label": "2 Terms (Half-Yearly / Annual)",
            "term_count": 2,
            "term_names": ["Half-Yearly", "Annual"],
            "has_half_terms": False,
            "week_start": 0,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "kindergarten", "label": "Kindergarten", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "secondary", "label": "Secondary (SSC)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "11-16"},
            {"code": "higher-secondary", "label": "Higher Secondary (HSC)", "glyph": "\U0001F3DB️", "primary_sector": "post_secondary", "typical_ages": "16-18"},
            {"code": "university", "label": "University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "bd-c1", "label": "Class 1", "order": 0},
            {"code": "bd-c2", "label": "Class 2", "order": 1},
            {"code": "bd-c3", "label": "Class 3", "order": 2},
            {"code": "bd-c4", "label": "Class 4", "order": 3},
            {"code": "bd-c5", "label": "Class 5 (PSC)", "order": 4},
            {"code": "bd-c6", "label": "Class 6", "order": 5},
            {"code": "bd-c7", "label": "Class 7", "order": 6},
            {"code": "bd-c8", "label": "Class 8 (JSC)", "order": 7},
            {"code": "bd-c9", "label": "Class 9", "order": 8},
            {"code": "bd-c10", "label": "Class 10 (SSC)", "order": 9},
            {"code": "bd-c11", "label": "Class 11", "order": 10},
            {"code": "bd-c12", "label": "Class 12 (HSC)", "order": 11},
        ],
        "terminology": {
            "teacher": "Shikkhok / Teacher",
            "principal": "Principal / Prodhan Shikkhok",
            "term": "Term",
            "report_card": "Report Card",
            "grade_level": "Class",
        },
    },
    "ID": {
        "calendar_system": {
            "code": "id-2-semester",
            "label": "2 Semester",
            "term_count": 2,
            "term_names": ["Semester Ganjil", "Semester Genap"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 7,
        },
        "school_types": [
            {"code": "paud", "label": "PAUD / TK", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "sd", "label": "Sekolah Dasar (SD)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "smp", "label": "Sekolah Menengah Pertama (SMP)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "sma", "label": "Sekolah Menengah Atas (SMA)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "universitas", "label": "Universitas / Perguruan Tinggi", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "id-sd1", "label": "SD Kelas 1", "order": 0},
            {"code": "id-sd2", "label": "SD Kelas 2", "order": 1},
            {"code": "id-sd3", "label": "SD Kelas 3", "order": 2},
            {"code": "id-sd4", "label": "SD Kelas 4", "order": 3},
            {"code": "id-sd5", "label": "SD Kelas 5", "order": 4},
            {"code": "id-sd6", "label": "SD Kelas 6", "order": 5},
            {"code": "id-smp1", "label": "SMP Kelas 7", "order": 6},
            {"code": "id-smp2", "label": "SMP Kelas 8", "order": 7},
            {"code": "id-smp3", "label": "SMP Kelas 9", "order": 8},
            {"code": "id-sma1", "label": "SMA Kelas 10", "order": 9},
            {"code": "id-sma2", "label": "SMA Kelas 11", "order": 10},
            {"code": "id-sma3", "label": "SMA Kelas 12", "order": 11},
        ],
        "terminology": {
            "teacher": "Guru",
            "principal": "Kepala Sekolah",
            "term": "Semester",
            "report_card": "Rapor",
            "grade_level": "Kelas",
        },
    },
    "PH": {
        "calendar_system": {
            "code": "ph-4-quarter",
            "label": "4 Quarters (K-12)",
            "term_count": 4,
            "term_names": ["First Quarter", "Second Quarter", "Third Quarter", "Fourth Quarter"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Kinder", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-5"},
            {"code": "elementary", "label": "Elementary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "junior-high", "label": "Junior High School", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-16"},
            {"code": "senior-high", "label": "Senior High School", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "16-18"},
            {"code": "college", "label": "College / University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ph-k", "label": "Kindergarten", "order": 0},
            {"code": "ph-g1", "label": "Grade 1", "order": 1},
            {"code": "ph-g2", "label": "Grade 2", "order": 2},
            {"code": "ph-g3", "label": "Grade 3", "order": 3},
            {"code": "ph-g4", "label": "Grade 4", "order": 4},
            {"code": "ph-g5", "label": "Grade 5", "order": 5},
            {"code": "ph-g6", "label": "Grade 6", "order": 6},
            {"code": "ph-g7", "label": "Grade 7", "order": 7},
            {"code": "ph-g8", "label": "Grade 8", "order": 8},
            {"code": "ph-g9", "label": "Grade 9", "order": 9},
            {"code": "ph-g10", "label": "Grade 10", "order": 10},
            {"code": "ph-g11", "label": "Grade 11 (SHS)", "order": 11},
            {"code": "ph-g12", "label": "Grade 12 (SHS)", "order": 12},
        ],
        "terminology": {
            "teacher": "Teacher / Guro",
            "principal": "Principal / Punong-Guro",
            "term": "Quarter",
            "report_card": "Report Card (Form 138)",
            "grade_level": "Grade",
        },
    },
    "VN": {
        "calendar_system": {
            "code": "vn-2-semester",
            "label": "2 Học kỳ",
            "term_count": 2,
            "term_names": ["Học kỳ I", "Học kỳ II"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "mam-non", "label": "Mầm non", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "tieu-hoc", "label": "Tiểu học", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-11"},
            {"code": "thcs", "label": "Trung học Cơ sở (THCS)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "11-15"},
            {"code": "thpt", "label": "Trung học Phổ thông (THPT)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "dai-hoc", "label": "Đại học", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "vn-l1", "label": "Lớp 1", "order": 0},
            {"code": "vn-l2", "label": "Lớp 2", "order": 1},
            {"code": "vn-l3", "label": "Lớp 3", "order": 2},
            {"code": "vn-l4", "label": "Lớp 4", "order": 3},
            {"code": "vn-l5", "label": "Lớp 5", "order": 4},
            {"code": "vn-l6", "label": "Lớp 6", "order": 5},
            {"code": "vn-l7", "label": "Lớp 7", "order": 6},
            {"code": "vn-l8", "label": "Lớp 8", "order": 7},
            {"code": "vn-l9", "label": "Lớp 9", "order": 8},
            {"code": "vn-l10", "label": "Lớp 10", "order": 9},
            {"code": "vn-l11", "label": "Lớp 11", "order": 10},
            {"code": "vn-l12", "label": "Lớp 12 (Tốt nghiệp)", "order": 11},
        ],
        "terminology": {
            "teacher": "Giáo viên",
            "principal": "Hiệu trưởng",
            "term": "Học kỳ",
            "report_card": "Học bạ",
            "grade_level": "Lớp",
        },
    },
    "TH": {
        "calendar_system": {
            "code": "th-2-semester",
            "label": "2 ภาคเรียน (Phak Rian)",
            "term_count": 2,
            "term_names": ["ภาคเรียนที่ 1", "ภาคเรียนที่ 2"],
            "has_half_terms": False,
            "week_start": 1,
            "academic_year_starts_month": 5,
        },
        "school_types": [
            {"code": "anuban", "label": "อนุบาล (Anuban)", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "prathom", "label": "ประถมศึกษา (Prathom)", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "6-12"},
            {"code": "matthayom-ton", "label": "มัธยมศึกษาตอนต้น (M.1-3)", "glyph": "\U0001F4DA", "primary_sector": "middle", "typical_ages": "12-15"},
            {"code": "matthayom-plai", "label": "มัธยมศึกษาตอนปลาย (M.4-6)", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "15-18"},
            {"code": "mahawitthayalai", "label": "มหาวิทยาลัย (University)", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "th-p1", "label": "ป.1", "order": 0},
            {"code": "th-p2", "label": "ป.2", "order": 1},
            {"code": "th-p3", "label": "ป.3", "order": 2},
            {"code": "th-p4", "label": "ป.4", "order": 3},
            {"code": "th-p5", "label": "ป.5", "order": 4},
            {"code": "th-p6", "label": "ป.6", "order": 5},
            {"code": "th-m1", "label": "ม.1", "order": 6},
            {"code": "th-m2", "label": "ม.2", "order": 7},
            {"code": "th-m3", "label": "ม.3", "order": 8},
            {"code": "th-m4", "label": "ม.4", "order": 9},
            {"code": "th-m5", "label": "ม.5", "order": 10},
            {"code": "th-m6", "label": "ม.6", "order": 11},
        ],
        "terminology": {
            "teacher": "ครู (Khru)",
            "principal": "ผู้อำนวยการ (Phu Amnuaykarn)",
            "term": "ภาคเรียน (Phak Rian)",
            "report_card": "สมุดพก (Samut Phok)",
            "grade_level": "ระดับชั้น (Radap Chan)",
        },
    },
    "MY": {
        "calendar_system": {
            "code": "my-2-semester",
            "label": "2 Penggal Persekolahan",
            "term_count": 2,
            "term_names": ["Penggal 1", "Penggal 2"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "tadika", "label": "Tadika / Kindergarten", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "rendah", "label": "Sekolah Rendah", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "7-12"},
            {"code": "menengah", "label": "Sekolah Menengah", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "13-17"},
            {"code": "form-six", "label": "Tingkatan 6 / Pre-U", "glyph": "\U0001F4DA", "primary_sector": "post_secondary", "typical_ages": "18-19"},
            {"code": "universiti", "label": "Universiti / IPT", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "my-d1", "label": "Darjah 1", "order": 0},
            {"code": "my-d2", "label": "Darjah 2", "order": 1},
            {"code": "my-d3", "label": "Darjah 3", "order": 2},
            {"code": "my-d4", "label": "Darjah 4", "order": 3},
            {"code": "my-d5", "label": "Darjah 5", "order": 4},
            {"code": "my-d6", "label": "Darjah 6 (UPSR)", "order": 5},
            {"code": "my-t1", "label": "Tingkatan 1", "order": 6},
            {"code": "my-t2", "label": "Tingkatan 2", "order": 7},
            {"code": "my-t3", "label": "Tingkatan 3 (PT3)", "order": 8},
            {"code": "my-t4", "label": "Tingkatan 4", "order": 9},
            {"code": "my-t5", "label": "Tingkatan 5 (SPM)", "order": 10},
            {"code": "my-t6", "label": "Tingkatan 6 (STPM)", "order": 11},
        ],
        "terminology": {
            "teacher": "Guru / Cikgu",
            "principal": "Pengetua / Guru Besar",
            "term": "Penggal",
            "report_card": "Kad Laporan",
            "grade_level": "Darjah / Tingkatan",
        },
    },
    "SG": {
        "calendar_system": {
            "code": "sg-4-term",
            "label": "4 Terms (Singapore)",
            "term_count": 4,
            "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "has_half_terms": True,
            "week_start": 1,
            "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Preschool / Kindergarten", "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary", "label": "Primary School", "glyph": "\U0001F3EB", "primary_sector": "primary", "typical_ages": "7-12"},
            {"code": "secondary", "label": "Secondary School", "glyph": "\U0001F3DB️", "primary_sector": "secondary", "typical_ages": "13-17"},
            {"code": "jc", "label": "Junior College / Poly", "glyph": "\U0001F4DA", "primary_sector": "post_secondary", "typical_ages": "17-19"},
            {"code": "university", "label": "University", "glyph": "\U0001F393", "primary_sector": "higher_ed", "typical_ages": "19+"},
        ],
        "education_levels": [
            {"code": "sg-p1", "label": "Primary 1", "order": 0},
            {"code": "sg-p2", "label": "Primary 2", "order": 1},
            {"code": "sg-p3", "label": "Primary 3", "order": 2},
            {"code": "sg-p4", "label": "Primary 4", "order": 3},
            {"code": "sg-p5", "label": "Primary 5", "order": 4},
            {"code": "sg-p6", "label": "Primary 6 (PSLE)", "order": 5},
            {"code": "sg-s1", "label": "Secondary 1", "order": 6},
            {"code": "sg-s2", "label": "Secondary 2", "order": 7},
            {"code": "sg-s3", "label": "Secondary 3", "order": 8},
            {"code": "sg-s4", "label": "Secondary 4 (O-Level)", "order": 9},
            {"code": "sg-jc1", "label": "JC 1", "order": 10},
            {"code": "sg-jc2", "label": "JC 2 (A-Level)", "order": 11},
        ],
        "terminology": {
            "teacher": "Teacher / Cikgu",
            "principal": "Principal",
            "term": "Term",
            "report_card": "Report Book",
            "grade_level": "Level",
        },
    },
}


# ---------------------------------------------------------------------------
# Africa + LATAM + Middle East Tier 1 additions (load-bearing for the
# regional-default routing below). Hand-curated to match each country's
# actual K-12 system.
# ---------------------------------------------------------------------------

COUNTRY_LOCALIZATION.update({
    # Nigeria — Nursery / Primary / JSS / SSS / Tertiary.
    "NG": {
        "calendar_system": {
            "code": "ng-3-term", "label": "3 Terms (Nigerian)",
            "term_count": 3, "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1, "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery",   "label": "Nursery / Crèche",       "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "primary",   "label": "Primary School",         "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-11"},
            {"code": "jss",       "label": "Junior Secondary (JSS)", "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "sss",       "label": "Senior Secondary (SSS)", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "all-through","label": "All-Through (Nursery-SSS)","glyph": "\U0001F3EB", "primary_sector": "k12",          "typical_ages": "3-18"},
            {"code": "tertiary",  "label": "Tertiary / University",  "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ng-pre1", "label": "Pre-Nursery 1", "order": 0},
            {"code": "ng-p1",   "label": "Primary 1",     "order": 2},
            {"code": "ng-jss1", "label": "JSS 1",         "order": 8},
            {"code": "ng-ss3",  "label": "SS 3",          "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher", "principal": "Principal", "term": "Term",
            "report_card": "Report Sheet", "grade_level": "Class",
        },
    },
    # Kenya — ECDE / Primary / JSS / SSS (CBC).
    "KE": {
        "calendar_system": {
            "code": "ke-3-term", "label": "3 Terms (Kenyan)",
            "term_count": 3, "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 1, "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "ecde",       "label": "ECDE (Pre-school)",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primary",    "label": "Primary School",     "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "jss",        "label": "Junior Secondary",   "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "sss",        "label": "Senior Secondary",   "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "all-through","label": "All-Through",        "glyph": "\U0001F3EB", "primary_sector": "k12",             "typical_ages": "3-18"},
            {"code": "tvet",       "label": "TVET / Polytechnic", "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "university", "label": "University",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ke-pp1", "label": "PP1",      "order": 0},
            {"code": "ke-g1",  "label": "Grade 1",  "order": 2},
            {"code": "ke-g7",  "label": "Grade 7",  "order": 8},
            {"code": "ke-g12", "label": "Grade 12", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher", "principal": "Principal", "term": "Term",
            "report_card": "Report Form", "grade_level": "Grade",
        },
    },
    # Ghana — Crèche / KG / Primary / JHS / SHS.
    "GH": {
        "calendar_system": {
            "code": "gh-3-term", "label": "3 Terms (Ghanaian)",
            "term_count": 3, "term_names": ["First Term", "Second Term", "Third Term"],
            "week_start": 1, "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "creche",  "label": "Crèche / Nursery",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-4"},
            {"code": "kg",      "label": "Kindergarten",             "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "primary", "label": "Primary School",           "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "jhs",     "label": "Junior High School (JHS)", "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "shs",     "label": "Senior High School (SHS)", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "university","label": "University",             "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "gh-kg1",  "label": "KG 1",     "order": 0},
            {"code": "gh-b1",   "label": "Basic 1",  "order": 2},
            {"code": "gh-jhs1", "label": "JHS 1",    "order": 8},
            {"code": "gh-shs3", "label": "SHS 3",    "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher", "principal": "Headmaster/mistress", "term": "Term",
            "report_card": "Terminal Report", "grade_level": "Class",
        },
    },
    # South Africa — 4-term, Grade R -> Grade 12 (Matric).
    "ZA": {
        "calendar_system": {
            "code": "za-4-term", "label": "4 Terms (South African)",
            "term_count": 4, "term_names": ["Term 1", "Term 2", "Term 3", "Term 4"],
            "week_start": 1, "academic_year_starts_month": 1,
        },
        "school_types": [
            {"code": "preschool", "label": "Pre-school / Crèche",  "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "primary",   "label": "Primary School",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "5-13"},
            {"code": "high",      "label": "High School",           "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "13-18"},
            {"code": "combined",  "label": "Combined School",       "glyph": "\U0001F3EB", "primary_sector": "k12",             "typical_ages": "5-18"},
            {"code": "tvet",      "label": "TVET College",          "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "16+"},
            {"code": "university","label": "University",            "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "za-grr", "label": "Grade R",  "order": 0},
            {"code": "za-g1",  "label": "Grade 1",  "order": 1},
            {"code": "za-g7",  "label": "Grade 7",  "order": 7},
            {"code": "za-g12", "label": "Grade 12 (Matric)", "order": 12},
        ],
        "terminology": {
            "teacher": "Educator", "principal": "Principal", "term": "Term",
            "report_card": "Report", "grade_level": "Grade",
        },
    },
    # Brazil — Educação Infantil / Fundamental I+II / Médio / Superior.
    "BR": {
        "calendar_system": {
            "code": "br-4-bimester", "label": "4 Bimestres",
            "term_count": 4, "term_names": ["1º Bimestre", "2º Bimestre", "3º Bimestre", "4º Bimestre"],
            "week_start": 0, "academic_year_starts_month": 2,
        },
        "school_types": [
            {"code": "infantil", "label": "Educação Infantil",         "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-5"},
            {"code": "fund-1",   "label": "Fundamental Anos Iniciais", "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-10"},
            {"code": "fund-2",   "label": "Fundamental Anos Finais",   "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "medio",    "label": "Ensino Médio",              "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-17"},
            {"code": "tecnico",  "label": "Ensino Técnico",            "glyph": "\U0001F527", "primary_sector": "vocational",      "typical_ages": "15+"},
            {"code": "superior", "label": "Ensino Superior",           "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "br-bercario","label": "Berçário",  "order": 0},
            {"code": "br-f1",      "label": "1º Ano EF", "order": 4},
            {"code": "br-f9",      "label": "9º Ano EF", "order": 12},
            {"code": "br-em3",     "label": "3º Ano EM", "order": 15},
        ],
        "terminology": {
            "teacher": "Professor/a", "principal": "Diretor/a", "term": "Bimestre",
            "report_card": "Boletim", "grade_level": "Ano / Série",
        },
    },
    # Mexico — Preescolar / Primaria / Secundaria / Preparatoria / Universidad.
    "MX": {
        "calendar_system": {
            "code": "mx-3-trimester", "label": "3 Trimestres",
            "term_count": 3, "term_names": ["Primer Trimestre", "Segundo Trimestre", "Tercer Trimestre"],
            "week_start": 1, "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "preescolar",  "label": "Preescolar",                 "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "3-6"},
            {"code": "primaria",    "label": "Primaria",                    "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-12"},
            {"code": "secundaria",  "label": "Secundaria",                  "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "12-15"},
            {"code": "preparatoria","label": "Preparatoria / Bachillerato", "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "15-18"},
            {"code": "universidad", "label": "Universidad",                 "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "mx-pre1", "label": "1º Preescolar",  "order": 0},
            {"code": "mx-p1",   "label": "1º Primaria",    "order": 3},
            {"code": "mx-s3",   "label": "3º Secundaria",  "order": 11},
            {"code": "mx-prep3","label": "3º Bachillerato","order": 14},
        ],
        "terminology": {
            "teacher": "Maestro/a", "principal": "Director/a", "term": "Trimestre",
            "report_card": "Boleta de Calificaciones", "grade_level": "Grado",
        },
    },
    # United Arab Emirates — 3-term, bilingual EN/AR.
    "AE": {
        "calendar_system": {
            "code": "ae-3-term", "label": "3 Terms (UAE)",
            "term_count": 3, "term_names": ["Term 1", "Term 2", "Term 3"],
            "week_start": 0, "academic_year_starts_month": 9,
        },
        "school_types": [
            {"code": "nursery",   "label": "Nursery / حضانة",          "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "0-4"},
            {"code": "kg",        "label": "KG / روضة",                "glyph": "\U0001F9F8", "primary_sector": "early_childhood", "typical_ages": "4-6"},
            {"code": "primary",   "label": "Primary / ابتدائي",        "glyph": "\U0001F3EB", "primary_sector": "primary",         "typical_ages": "6-11"},
            {"code": "middle",    "label": "Preparatory / إعدادي",      "glyph": "\U0001F3EB", "primary_sector": "middle",          "typical_ages": "11-14"},
            {"code": "secondary", "label": "Secondary / ثانوي",         "glyph": "\U0001F393", "primary_sector": "secondary",       "typical_ages": "14-18"},
            {"code": "k12",       "label": "K-12 Combined",             "glyph": "\U0001F3EB", "primary_sector": "k12",             "typical_ages": "3-18"},
            {"code": "university","label": "University / جامعة",         "glyph": "\U0001F3DB", "primary_sector": "higher_ed",       "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "ae-kg1", "label": "KG 1",     "order": 0},
            {"code": "ae-g1",  "label": "Grade 1",  "order": 2},
            {"code": "ae-g6",  "label": "Grade 6",  "order": 7},
            {"code": "ae-g12", "label": "Grade 12", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / معلم", "principal": "Principal / مدير", "term": "Term / فصل",
            "report_card": "Report Card / كشف", "grade_level": "Grade / صف",
        },
    },
    # Saudi Arabia — 3-term (MOE 2021+).
    "SA": {
        "calendar_system": {
            "code": "sa-3-term", "label": "3 Terms (Saudi MOE)",
            "term_count": 3, "term_names": ["الفصل الأول", "الفصل الثاني", "الفصل الثالث"],
            "week_start": 0, "academic_year_starts_month": 8,
        },
        "school_types": [
            {"code": "rawda",     "label": "Rawda / روضة",        "glyph": "\U0001F9F8", "primary_sector": "early_childhood","typical_ages": "3-6"},
            {"code": "ibtidaiya", "label": "Primary / ابتدائية",  "glyph": "\U0001F3EB", "primary_sector": "primary",       "typical_ages": "6-12"},
            {"code": "mutawasita","label": "Intermediate / متوسطة","glyph": "\U0001F3EB", "primary_sector": "middle",        "typical_ages": "12-15"},
            {"code": "thanawiya", "label": "Secondary / ثانوية",   "glyph": "\U0001F393", "primary_sector": "secondary",     "typical_ages": "15-18"},
            {"code": "jamia",     "label": "University / جامعة",   "glyph": "\U0001F3DB", "primary_sector": "higher_ed",     "typical_ages": "18+"},
        ],
        "education_levels": [
            {"code": "sa-r1",  "label": "Rawda 1",  "order": 0},
            {"code": "sa-g1",  "label": "Grade 1",  "order": 2},
            {"code": "sa-g12", "label": "Grade 12", "order": 13},
        ],
        "terminology": {
            "teacher": "Teacher / معلم", "principal": "Principal / مدير", "term": "Term / فصل",
            "report_card": "Report Card / شهادة", "grade_level": "Grade / صف",
        },
    },
})


# ---------------------------------------------------------------------------
# Regional defaults — for any country not in COUNTRY_LOCALIZATION above,
# COUNTRY_REGIONAL_DEFAULT routes it to one of these packs. Each value is
# a reference to one of the Tier 1 country packs above.
# ---------------------------------------------------------------------------

REGIONAL_DEFAULTS = {
    "africa-anglophone":  COUNTRY_LOCALIZATION["NG"],
    "africa-francophone": COUNTRY_LOCALIZATION["FR"],
    "africa-arabic":      COUNTRY_LOCALIZATION["AE"],
    "europe-continental": COUNTRY_LOCALIZATION["DE"],
    "europe-nordic":      COUNTRY_LOCALIZATION["DE"],
    "europe-romance":     COUNTRY_LOCALIZATION["ES"],
    "europe-eastern":     COUNTRY_LOCALIZATION["DE"],
    "latam-spanish":      COUNTRY_LOCALIZATION["MX"],
    "latam-portuguese":   COUNTRY_LOCALIZATION["BR"],
    "east-asia":          COUNTRY_LOCALIZATION["JP"],
    "south-asia":         COUNTRY_LOCALIZATION["IN"],
    "southeast-asia":     COUNTRY_LOCALIZATION["IN"],
    "middle-east":        COUNTRY_LOCALIZATION["AE"],
    "oceania":            COUNTRY_LOCALIZATION["AU"],
    "caribbean":          COUNTRY_LOCALIZATION["GB"],
    "generic":            COUNTRY_LOCALIZATION["US"],
}


# ---------------------------------------------------------------------------
# COUNTRY_REGIONAL_DEFAULT — alpha-2 -> region key for every UN member NOT
# in COUNTRY_LOCALIZATION. Anything missing falls through to the
# generic-fallback in country_localization_service.
# ---------------------------------------------------------------------------

COUNTRY_REGIONAL_DEFAULT = {
    # Africa — Anglophone (British colonial heritage; 3-term + JSS/SSS-ish)
    "BW": "africa-anglophone",  "GM": "africa-anglophone",  "LR": "africa-anglophone",
    "MW": "africa-anglophone",  "MU": "africa-anglophone",  "NA": "africa-anglophone",
    "RW": "africa-anglophone",  "SC": "africa-anglophone",  "SL": "africa-anglophone",
    "SS": "africa-anglophone",  "SZ": "africa-anglophone",  "TZ": "africa-anglophone",
    "UG": "africa-anglophone",  "ZM": "africa-anglophone",  "ZW": "africa-anglophone",
    "LS": "africa-anglophone",  "ER": "africa-anglophone",
    # Africa — Francophone
    "BJ": "africa-francophone", "BF": "africa-francophone", "BI": "africa-francophone",
    "CM": "africa-francophone", "CF": "africa-francophone", "TD": "africa-francophone",
    "KM": "africa-francophone", "CG": "africa-francophone", "CD": "africa-francophone",
    "CI": "africa-francophone", "DJ": "africa-francophone", "GQ": "africa-francophone",
    "GA": "africa-francophone", "GN": "africa-francophone", "ML": "africa-francophone",
    "NE": "africa-francophone", "SN": "africa-francophone", "TG": "africa-francophone",
    "MG": "africa-francophone",
    # Africa — Lusophone / Arabic
    "AO": "latam-portuguese",   "CV": "latam-portuguese",   "GW": "latam-portuguese",
    "MZ": "latam-portuguese",   "ST": "latam-portuguese",
    "DZ": "africa-arabic",      "SD": "africa-arabic",      "LY": "africa-arabic",
    "MR": "africa-arabic",      "SO": "africa-arabic",      "TN": "africa-arabic",
    # Europe — Continental + Romance + Nordic + Eastern
    "AD": "europe-romance",     "AT": "europe-continental", "BG": "europe-eastern",
    "HR": "europe-eastern",     "CY": "europe-romance",     "CZ": "europe-eastern",
    "DK": "europe-nordic",      "EE": "europe-eastern",     "FI": "europe-nordic",
    "GR": "europe-romance",     "HU": "europe-eastern",     "IS": "europe-nordic",
    "LV": "europe-eastern",     "LI": "europe-continental", "LT": "europe-eastern",
    "LU": "europe-continental", "MT": "europe-romance",     "MD": "europe-eastern",
    "MC": "europe-romance",     "ME": "europe-eastern",     "MK": "europe-eastern",
    "NO": "europe-nordic",      "PL": "europe-eastern",     "PT": "europe-romance",
    "RO": "europe-eastern",     "SM": "europe-romance",     "RS": "europe-eastern",
    "SK": "europe-eastern",     "SI": "europe-eastern",     "SE": "europe-nordic",
    "CH": "europe-continental", "UA": "europe-eastern",     "BY": "europe-eastern",
    "BA": "europe-eastern",     "AL": "europe-eastern",     "RU": "europe-eastern",
    "VA": "europe-romance",     "XK": "europe-eastern",
    # Latin America — Spanish (default to Mexico)
    "AR": "latam-spanish", "BO": "latam-spanish", "CL": "latam-spanish",
    "CO": "latam-spanish", "CR": "latam-spanish", "CU": "latam-spanish",
    "DO": "latam-spanish", "EC": "latam-spanish", "SV": "latam-spanish",
    "GT": "latam-spanish", "HN": "latam-spanish", "NI": "latam-spanish",
    "PA": "latam-spanish", "PY": "latam-spanish", "PE": "latam-spanish",
    "UY": "latam-spanish", "VE": "latam-spanish",
    # Caribbean — Anglophone defaults
    "AG": "caribbean", "BS": "caribbean", "BB": "caribbean", "BZ": "caribbean",
    "DM": "caribbean", "GD": "caribbean", "GY": "caribbean",
    "HT": "africa-francophone", "JM": "caribbean", "KN": "caribbean",
    "LC": "caribbean", "VC": "caribbean", "TT": "caribbean",
    "SR": "europe-continental",
    # Middle East (non-AE/SA already Tier 1)
    "BH": "middle-east", "IR": "middle-east", "IQ": "middle-east",
    "IL": "middle-east", "JO": "middle-east", "KW": "middle-east",
    "LB": "middle-east", "OM": "middle-east", "PS": "middle-east",
    "QA": "middle-east", "SY": "middle-east", "TR": "middle-east",
    "YE": "middle-east",
    # South Asia (non-IN already Tier 1)
    "AF": "south-asia", "BD": "south-asia", "BT": "south-asia",
    "MV": "south-asia", "NP": "south-asia", "PK": "south-asia",
    "LK": "south-asia",
    # East Asia (non-JP already Tier 1)
    "KP": "east-asia", "MN": "east-asia", "TW": "east-asia",
    "HK": "east-asia", "MO": "east-asia",
    # Southeast Asia
    "BN": "southeast-asia", "KH": "southeast-asia", "LA": "southeast-asia",
    "MM": "southeast-asia", "TL": "southeast-asia",
    # Oceania
    "FJ": "oceania", "KI": "oceania", "MH": "oceania", "FM": "oceania",
    "NR": "oceania", "PW": "oceania", "PG": "oceania", "WS": "oceania",
    "SB": "oceania", "TO": "oceania", "TV": "oceania", "VU": "oceania",
    # Central Asia / Caucasus
    "AM": "europe-eastern", "AZ": "middle-east", "GE": "europe-eastern",
    "KZ": "east-asia", "KG": "east-asia", "TJ": "south-asia",
    "TM": "east-asia", "UZ": "east-asia",
}

