# Generated by Django 5.2.10 on 2026-03-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0034_remove_biometricdevice_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('step_group', models.CharField(blank=True, db_index=True, help_text='e.g. institution_basics, plan_choice, blueprint, branding, starter_stack, data_path', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('completed_keys', models.JSONField(blank=True, default=list, help_text='List of step keys marked done.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to='schools.school')),
            ],
            options={
                'verbose_name': 'Setup progress',
                'verbose_name_plural': 'Setup progress',
                'unique_together': {('school',)},
            },
        ),
    ]
