# Generated by Django 5.2.10 on 2026-01-22 11:15

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_student_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_student_year_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_status_due_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_profile_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pmt_invoice_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pay_invoice_paid_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pay_receipt_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pay_ext_ref_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentreminder",
            name="finance_reminder_active_send_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhooklog",
            name="finance_webhook_provider_ref_idx",
        ),
        migrations.RemoveIndex(
            model_name="webhooklog",
            name="finance_webhook_ip_time_idx",
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp - set instead of deleting",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded this payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp - set instead of deleting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF or image attachment for this invoice (max 5MB).",
                null=True,
                upload_to="finance/invoices/",
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[".pdf", ".doc", ".docx", ".xls", ".xlsx"],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        message="Only document files (PDF, Word, Excel) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                help_text="Optional uploaded receipt or slip (PDF/image, max 2MB).",
                null=True,
                upload_to="finance/receipts/",
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[".pdf", ".jpg", ".jpeg", ".png"],
                        allowed_types=[
                            "application/pdf",
                            "image/jpeg",
                            "image/png",
                            "image/jpg",
                        ],
                        message="Only PDF or image files are allowed for receipts.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=2),
                ],
            ),
        ),
    ]
