# Generated by Django 5.2.10 on 2026-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_payment_reconciliation_and_more'),
        ('finance', '0022_merge_20260127_1930'),
    ]

    operations = [
    ]
