# Generated by Django 5.2.10 on 2026-01-28 20:02

import apps.accounts.validators
from django.db import migrations, models, connection


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist in the database."""
    db_table = 'finance_payment'
    indexes_to_remove = [
        'finance_pay_status_05a375_idx',
        'finance_pay_student_237141_idx',
        'finance_pay_region__83483d_idx',
    ]
    
    with connection.cursor() as cursor:
        for index_name in indexes_to_remove:
            # Check if index exists
            cursor.execute("""
                SELECT indexname 
                FROM pg_indexes 
                WHERE tablename=%s AND indexname=%s
            """, [db_table, index_name])
            if cursor.fetchone():
                cursor.execute(f'DROP INDEX IF EXISTS {index_name}')


def reverse_remove_indexes(apps, schema_editor):
    """Reverse operation - no-op since we're removing indexes."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_merge_20260128_1423'),
    ]

    operations = [
        migrations.RunPython(remove_indexes_if_exist, reverse_remove_indexes),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Optional uploaded receipt or slip (PDF/image, max 2MB).', null=True, upload_to='finance/receipts/', validators=[apps.accounts.validators.FileTypeValidator(allowed_extensions=['.pdf', '.jpg', '.jpeg', '.png'], allowed_types=['application/pdf', 'image/jpeg', 'image/png', 'image/jpg'], message='Only PDF or image files are allowed for receipts.'), apps.accounts.validators.FileSizeValidator(max_size_mb=2)]),
        ),
    ]
