# Generated by Django 5.2.10 on 2026-01-28 20:02

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_merge_20260128_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_status_05a375_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_student_237141_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_region__83483d_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_status_05a375_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_student_237141_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_region__83483d_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Optional uploaded receipt or slip (PDF/image, max 2MB).', null=True, upload_to='finance/receipts/', validators=[apps.accounts.validators.FileTypeValidator(allowed_extensions=['.pdf', '.jpg', '.jpeg', '.png'], allowed_types=['application/pdf', 'image/jpeg', 'image/png', 'image/jpg'], message='Only PDF or image files are allowed for receipts.'), apps.accounts.validators.FileSizeValidator(max_size_mb=2)]),
        ),
    ]
