# Generated by Django 5.2.10 on 2026-01-28 20:44

from django.db import migrations, connection


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist (already handled conditionally in 0024, but Django state needs update)."""
    db_table = 'finance_payment'
    indexes_to_remove = [
        'finance_pay_status_05a375_idx',
        'finance_pay_student_237141_idx',
        'finance_pay_region__83483d_idx',
    ]
    
    with connection.cursor() as cursor:
        for index_name in indexes_to_remove:
            cursor.execute("""
                SELECT indexname 
                FROM pg_indexes 
                WHERE tablename=%s AND indexname=%s
            """, [db_table, index_name])
            if cursor.fetchone():
                cursor.execute(f'DROP INDEX IF EXISTS {index_name}')


def reverse_remove_indexes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_indexes_if_exist, reverse_remove_indexes),
    ]
