# Generated by Django 5.2.10
# Idempotent: safe to run when column/index already exist from a previous partial run.

import uuid
from django.db import migrations, models


def apply_payment_code_idempotent(apps, schema_editor):
    """Add column and indexes only if they do not exist; then backfill."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # 1. Add column if not exists (PostgreSQL 9.5+)
        cursor.execute("""
            ALTER TABLE finance_invoice
            ADD COLUMN IF NOT EXISTS payment_code VARCHAR(32) NULL;
        """)
        # 2. Create btree index only if not exists (avoid duplicate index error)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS finance_invoice_payment_code_btree_idx
            ON finance_invoice (payment_code);
        """)
        # 3. Create varchar_pattern_ops index only if not exists (Django's _like index)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS finance_invoice_payment_code_df7a7e77_like
            ON finance_invoice (payment_code varchar_pattern_ops);
        """)

    # 4. Backfill
    Invoice = apps.get_model("finance", "Invoice")
    for inv in Invoice.objects.filter(payment_code__isnull=True) | Invoice.objects.filter(payment_code=""):
        short = uuid.uuid4().hex[:8].upper()
        inv.payment_code = f"INV-{inv.id}-{short}"
        inv.save(update_fields=["payment_code"])

    with connection.cursor() as cursor:
        # 5. Set NOT NULL only if column is still nullable
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'finance_invoice'
                      AND column_name = 'payment_code'
                      AND is_nullable = 'YES'
                ) THEN
                    ALTER TABLE finance_invoice
                    ALTER COLUMN payment_code SET NOT NULL;
                END IF;
            END $$;
        """)
        # 6. Add unique constraint only if not exists
        cursor.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'finance_invoice_payment_code_key'
                ) THEN
                    ALTER TABLE finance_invoice
                    ADD CONSTRAINT finance_invoice_payment_code_key UNIQUE (payment_code);
                END IF;
            END $$;
        """)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_remove_payment_finance_pay_status_05a375_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="invoice",
                    name="payment_code",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique code for parent to quote when paying (e.g. MoMo). Auto-generated if blank.",
                        max_length=32,
                        null=True,
                        unique=False,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_payment_code_idempotent, noop_reverse),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="invoice",
                    name="payment_code",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique code for parent to quote when paying (e.g. MoMo). Auto-generated if blank.",
                        max_length=32,
                        null=False,
                        unique=True,
                    ),
                ),
            ],
            database_operations=[],  # Already applied in apply_payment_code_idempotent
        ),
    ]
