# Generated by Django 5.2.10

import uuid
from django.db import migrations, models


def backfill_payment_codes(apps, schema_editor):
    Invoice = apps.get_model("finance", "Invoice")
    for inv in Invoice.objects.filter(payment_code__isnull=True) | Invoice.objects.filter(payment_code=""):
        short = uuid.uuid4().hex[:8].upper()
        inv.payment_code = f"INV-{inv.id}-{short}"
        inv.save(update_fields=["payment_code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_remove_payment_finance_pay_status_05a375_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique code for parent to quote when paying (e.g. MoMo). Auto-generated if blank.",
                max_length=32,
                null=True,
                unique=False,
            ),
        ),
        migrations.RunPython(backfill_payment_codes, noop_reverse),
        migrations.AlterField(
            model_name="invoice",
            name="payment_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique code for parent to quote when paying (e.g. MoMo). Auto-generated if blank.",
                max_length=32,
                null=False,
                unique=True,
            ),
        ),
    ]
