# Generated by Django 5.2.10 on 2026-02-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_paymentproofupload_last_verification_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentproofupload",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Client key to prevent duplicate uploads on retry.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="paymentproofupload",
            name="reassign_to_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Set to another invoice (e.g. same student) and save to reassign this receipt.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="paymentproofupload",
            name="verification_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for manual approve/reject (required when overriding auto-verification).",
            ),
        ),
    ]
