# Generated by Django 5.2.10 on 2026-02-06 22:36

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0032_add_invoice_void_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("TUITION", "Tuition"),
                    ("PTA", "PTA Levy"),
                    ("WORKSHOP", "Workshop Fee"),
                    ("ACTIVITY", "Activity"),
                    ("TRANSPORT", "Transport / Bus"),
                    ("CUSTOM", "Custom"),
                ],
                default="TUITION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF or image attachment for this invoice (max 5MB).",
                null=True,
                upload_to="finance/invoices/",
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(
                blank=True,
                help_text="External transaction ID (provider, bank, receipt). Use for matching and idempotency. See docs/DATA_PAYMENT_REFERENCE.md.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Human-readable or internal reference; may mirror external_reference. See docs/DATA_PAYMENT_REFERENCE.md.",
                max_length=80,
            ),
        ),
    ]
