# Generated by Django 5.2.10 on 2026-03-06 17:12

import apps.accounts.validators
from django.db import migrations, models


def _tenant_upload_to(subpath):
    """Return an upload_to callable that prefixes path with tenants/{school_id}/.

    Inlined from ``apps.siteconfig.models._tenant_upload_to`` for migration
    historical-state safety.
    """

    def upload_to(instance, filename):
        school_id = getattr(instance, "school_id", None)
        if school_id is None and getattr(instance, "school", None):
            school_id = getattr(instance.school, "pk", None)
        if school_id is None:
            return f"tenant_uploads/{subpath}/{filename}"
        return f"tenants/{school_id}/{subpath}/{filename}"

    return upload_to


def _invoice_attachment_upload_to(instance, filename):
    """Tenant-scoped path for Invoice attachments (Section 25.3, media_tenant_scope.md).

    Inlined from ``apps.finance.models._invoice_attachment_upload_to`` for
    migration historical-state safety.
    """
    return _tenant_upload_to("finance/invoices")(instance, filename)


def _invoice_payment_proof_upload_to(instance, filename):
    """Tenant-scoped path for Invoice payment proofs (Section 25.3, media_tenant_scope.md).

    Inlined from ``apps.finance.models._invoice_payment_proof_upload_to`` for
    migration historical-state safety.
    """
    return _tenant_upload_to("finance/payment_proofs")(instance, filename)


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0047_rls_policy_default_deny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF or image attachment for this invoice (max 5MB).",
                null=True,
                upload_to=_invoice_attachment_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload proof of payment (receipt, screenshot, etc.) - max 2MB",
                null=True,
                upload_to=_invoice_payment_proof_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[".pdf", ".jpg", ".jpeg", ".png"],
                        allowed_types=[
                            "application/pdf",
                            "image/jpeg",
                            "image/png",
                            "image/jpg",
                        ],
                        message="Only PDF or image files are allowed for receipts.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=2),
                ],
            ),
        ),
    ]
