# Generated by Django 5.2.10 on 2026-03-07 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_invoice_tenant_upload_to'),
        ('siteconfig', '0136_form_draft_26_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED_REFUND', 'Resolved (refund issued)'), ('RESOLVED_NO_REFUND', 'Resolved (no refund)'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=24)),
                ('reason', models.CharField(choices=[('DUPLICATE', 'Duplicate charge'), ('NOT_RECEIVED', 'Service not received'), ('INCORRECT_AMOUNT', 'Incorrect amount'), ('FRAUD', 'Suspected fraud'), ('OTHER', 'Other')], max_length=24)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='finance.payment')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_disputes', to='siteconfig.regionconfig')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment dispute',
                'verbose_name_plural': 'Payment disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
