# Generated by Django 5.2.10 on 2026-03-09 11:46

from django.conf import settings
from django.db import migrations, models


def _default_currency():
    """Platform default currency (no hardcoded XAF). See config.PLATFORM_DEFAULT_CURRENCY.

    Inlined from ``_default_currency`` for migration
    historical-state safety.
    """
    return getattr(settings, "PLATFORM_DEFAULT_CURRENCY", "USD")


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0049_add_payment_dispute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                default=_default_currency,
                help_text="Currency code (ISO 4217, e.g. USD, XAF, EUR)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="complianceprofile",
            name="currency_code",
            field=models.CharField(
                default=_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="complianceprofile",
            name="currency_symbol",
            field=models.CharField(
                default=_default_currency, max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="parentwallet",
            name="currency_code",
            field=models.CharField(
                default=_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="suspensepayment",
            name="currency",
            field=models.CharField(
                default=_default_currency, max_length=3
            ),
        ),
    ]
