# Generated by Django 5.2.10 on 2026-03-09 11:46

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0049_add_payment_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default=apps.finance.models._default_currency, help_text='Currency code (ISO 4217, e.g. USD, XAF, EUR)', max_length=3),
        ),
        migrations.AlterField(
            model_name='complianceprofile',
            name='currency_code',
            field=models.CharField(default=apps.finance.models._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='complianceprofile',
            name='currency_symbol',
            field=models.CharField(default=apps.finance.models._default_currency, max_length=8),
        ),
        migrations.AlterField(
            model_name='parentwallet',
            name='currency_code',
            field=models.CharField(default=apps.finance.models._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='suspensepayment',
            name='currency',
            field=models.CharField(default=apps.finance.models._default_currency, max_length=3),
        ),
    ]
