# Generated by Django 5.2.10 on 2026-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_alter_webhooklog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreminder',
            name='reminder_channels',
            field=models.JSONField(default=list, help_text="Channels to use: ['email'], ['whatsapp'], ['email', 'sms'], etc. Falls back to platform default if empty."),
        ),
    ]
