# Generated by Django 5.2.10 on 2026-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0055_webhooklog_idempotency_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreminder',
            name='reminder_days_before',
            field=models.JSONField(default=list, help_text='List of days before due date to send reminders, e.g., [7, 3, 1]. Falls back to platform tenant site settings default if empty.'),
        ),
    ]
