# Generated by Django 5.2.10 on 2026-05-02 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0057_offline_global_ops'),
        ('schools', '0047_alter_marketingfunnelevent_event_type_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail_code', models.CharField(db_index=True, max_length=40)),
                ('provider_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('degraded', 'Degraded'), ('missing_credentials', 'Missing credentials'), ('external_required', 'External PSP setup required'), ('unknown', 'Unknown')], db_index=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('action_required', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_health_snapshots', to='schools.school')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['school', '-checked_at'], name='finance_pay_school__4fab6f_idx')],
            },
        ),
    ]
