# Generated by Django 5.2.14 on 2026-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0069_offlinepaymentintent_dedup_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsource',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='When True, funds may only be spent on the declared restricted_purpose.'),
        ),
        migrations.AddField(
            model_name='awardsource',
            name='restricted_purpose',
            field=models.CharField(blank=True, help_text='Program/purpose this fund is restricted to (e.g. scholarship, feeding-program, building-project). Enforced against Scholarship.purpose at disbursement when is_restricted is True.', max_length=120),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='purpose',
            field=models.CharField(blank=True, help_text='Program/purpose served; must match a restricted AwardSource.restricted_purpose to disburse from it.', max_length=120),
        ),
    ]
