# Generated by Django 5.2.10 on 2026-06-23 08:48

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0072_ensure_finance_notification_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceprofile',
            name='currency_symbol',
            field=models.CharField(default=apps.finance.models._default_currency_symbol, max_length=8),
        ),
    ]
