# Generated by Django 5.2.10 on 2026-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0073_alter_complianceprofile_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreminder',
            name='message_template_email',
            field=models.TextField(default='Dear {guardian}, please pay {currency}{amount} for {invoice} by {due_date}.', help_text="Email message template. {currency} is the school's currency symbol."),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='message_template_sms',
            field=models.TextField(blank=True, default='Reminder: Pay {currency}{amount} for {invoice} by {due_date}.', help_text="SMS message template. {currency} is the school's currency symbol."),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='message_template_whatsapp',
            field=models.TextField(blank=True, default='Hi {guardian}! 👋 Please pay *{currency}{amount}* for invoice *{invoice}* by *{due_date}*.', help_text="WhatsApp message template. {currency} is the school's currency symbol."),
        ),
    ]
