# Generated by Django 5.2.10 on 2026-06-26 15:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0074_reminder_default_currency_placeholder'),
        ('people', '0060_ensure_studentnote_table'),
        ('schools', '0076_alter_school_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractionalPaymentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('running_paid_total', models.DecimalField(decimal_places=2, help_text='Cumulative paid on invoice after this row posts.', max_digits=12)),
                ('invoice_balance_after', models.DecimalField(decimal_places=2, help_text='Remaining invoice balance after this row.', max_digits=12)),
                ('source', models.CharField(choices=[('cash_counter', 'Cash over counter'), ('gateway', 'Payment gateway'), ('wallet', 'Parent wallet'), ('adjustment', 'Manual adjustment')], default='cash_counter', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('enrollment_clearance_met', models.BooleanField(default=False, help_text='True when cumulative paid meets tenant enrollment clearance threshold.')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractional_ledger_rows', to='finance.invoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractional_payment_ledger_rows', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fractional_ledger_rows', to='people.studentprofile')),
            ],
            options={
                'ordering': ['posted_at', 'created_at'],
                'indexes': [models.Index(fields=['school', 'invoice', '-posted_at'], name='finance_fra_school__466b8e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('school', 'idempotency_key'), name='uniq_fractional_ledger_school_idempotency')],
            },
        ),
    ]
