# Generated by Django 5.2.14 on 2026-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0077_ensure_school_fk_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(blank=True, default='', help_text="ISO 4217. Left blank on create, save() resolves it from the invoice / compliance profile / school before falling back to the platform default — a hardcoded 'USD' default silently mis-stamped every payment recorded without an explicit currency.", max_length=3),
        ),
    ]
