# Generated by Django 5.2.14 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0080_expand_local_payment_method_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_offline_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_offline_id", ""), _negated=True),
                fields=("school", "client_offline_id"),
                name="uniq_invoice_school_offline_id",
            ),
        ),
    ]
