# Generated by Django 5.2.10 on 2026-03-06 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_scope_grant_and_billing_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('suspended', 'Suspended')], db_index=True, default='unverified', max_length=20)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('payout_email', models.EmailField(blank=True, max_length=254)),
                ('payout_processor_code', models.CharField(blank=True, max_length=32)),
                ('payout_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher organization',
                'verbose_name_plural': 'Publisher organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=24)),
                ('security_review_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('changes_required', 'Changes required'), ('rejected', 'Rejected')], db_index=True, default='not_required', max_length=24)),
                ('certification_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('changes_required', 'Changes required'), ('rejected', 'Rejected')], db_index=True, default='not_required', max_length=24)),
                ('revenue_share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kill_switch_active', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='marketplace.marketplaceapp')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.publisherorganization')),
            ],
            options={
                'verbose_name': 'Marketplace listing',
                'verbose_name_plural': 'Marketplace listings',
                'ordering': ['app__name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('listing', 'Listing review'), ('security', 'Security review'), ('certification', 'Certification review'), ('version', 'Version review')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('changes_required', 'Changes required'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=24)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('findings_json', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.marketplacelisting')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace review',
                'verbose_name_plural': 'Marketplace reviews',
                'ordering': ['status', '-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='marketplaceapp',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='marketplace.publisherorganization'),
        ),
    ]
