# Generated by Django 5.2.10 on 2026-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0004_phase11_app_types_capability_compat_lifecycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceapp",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_party", "First-party"),
                    ("third_party", "Third-party"),
                    ("premium", "Premium"),
                    ("tenant_private", "Tenant-private"),
                    ("connector", "Connector"),
                ],
                default="first_party",
                max_length=20,
            ),
        ),
    ]
