# Generated by Django 5.2.10 on 2026-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0006_marketplacelisting_preview_screenshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacelisting",
            name="compatibility",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional: countries (list), blueprint_families (list), plan_tiers (list), workflow_families (list), recommended_sectors (list of wedge 14–22 sector codes e.g. PUBLIC, NGO).",
            ),
        ),
    ]
