# Generated by Django 5.2.10 on 2026-04-30 10:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_stripeplanprice_plan_code'),
        ('marketplace', '0008_developer_platform_app_catalog'),
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceapp',
            name='billing_interval',
            field=models.CharField(choices=[('none', 'Not applicable'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='marketplaceapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='List price in the tenant billing account currency (subscription or usage floor).', max_digits=12),
        ),
        migrations.AddField(
            model_name='marketplaceapp',
            name='pricing_model',
            field=models.CharField(choices=[('free', 'Free'), ('subscription', 'Subscription'), ('usage', 'Usage')], db_index=True, default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformMarketplaceEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('install', 'Install / activation'), ('usage', 'Usage billing'), ('payment', 'Payment processor settlement')], default='install', max_length=16)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('publisher_pool_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross minus platform fee (remainder before publisher revenue-share).', max_digits=14)),
                ('publisher_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount accruing to the listing publisher per revenue_share_percent.', max_digits=14)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_earnings', to='marketplace.marketplaceapp')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_earnings', to='marketplace.appinstallation')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_earnings', to='marketplace.marketplacelisting')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_platform_earnings', to='schools.school')),
            ],
            options={
                'verbose_name': 'Platform marketplace earning',
                'verbose_name_plural': 'Platform marketplace earnings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMarketplaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(db_index=True, max_length=20)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_interval', models.CharField(default='none', max_length=16)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='marketplace.marketplaceapp')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_app_subscriptions', to='billing.billingaccount')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_subscription', to='marketplace.appinstallation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_app_subscriptions', to='schools.school')),
            ],
            options={
                'verbose_name': 'Tenant marketplace subscription',
                'verbose_name_plural': 'Tenant marketplace subscriptions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
