# Generated by Django — marketplace catalog free-intent flag

from django.db import migrations, models


def forwards_ack_existing_free(apps, schema_editor):
    MarketplaceApp = apps.get_model("marketplace", "MarketplaceApp")
    MarketplaceApp.objects.filter(pricing_model="free").update(is_intentionally_free=True)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_monetization_billing_hooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceapp",
            name="is_intentionally_free",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When pricing is Free, check this to confirm a deliberate $0 catalog offer (not a missing price).",
            ),
        ),
        migrations.RunPython(forwards_ack_existing_free, migrations.RunPython.noop),
    ]
