# Generated by Django 5.2.10 on 2026-05-02 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_marketplaceapp_is_intentionally_free'),
        ('schools', '0047_alter_marketingfunnelevent_event_type_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceMonetizationLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_key', models.CharField(db_index=True, default='', max_length=80)),
                ('event_type', models.CharField(choices=[('install', 'Install'), ('uninstall', 'Uninstall'), ('subscription_started', 'Subscription started'), ('usage_recorded', 'Usage recorded'), ('invoice_created', 'Invoice created'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('platform_fee_recorded', 'Platform fee recorded'), ('settlement_pending', 'Settlement pending'), ('settlement_completed', 'Settlement completed'), ('settlement_external_blocked', 'Settlement blocked (external)'), ('settlement_pending_external', 'Settlement pending (external PSP)')], db_index=True, max_length=40)),
                ('quantity', models.BigIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('pending', 'Pending'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='posted', max_length=16)),
                ('settlement_dependency', models.CharField(choices=[('internal', 'Internal metering'), ('external_psp', 'External PSP'), ('manual', 'Manual / offline')], db_index=True, default='external_psp', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=190)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monetization_ledger_entries', to='marketplace.marketplaceapp')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monetization_ledger_entries', to='marketplace.appinstallation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_monetization_ledger', to='schools.school')),
            ],
            options={
                'verbose_name': 'Marketplace monetization ledger entry',
                'verbose_name_plural': 'Marketplace monetization ledger entries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'idempotency_key'), name='marketplace_mon_led_unique_school_idempotency')],
            },
        ),
    ]
