# Generated by Django 5.2.10 on 2026-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_marketplace_monetization_ledger_entry_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacemonetizationledgerentry',
            name='event_type',
            field=models.CharField(choices=[('install', 'Install'), ('uninstall', 'Uninstall'), ('subscription_started', 'Subscription started'), ('usage_recorded', 'Usage recorded'), ('invoice_created', 'Invoice created'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('platform_fee_recorded', 'Platform fee recorded'), ('settlement_pending', 'Settlement pending'), ('settlement_ready', 'Settlement ready (awaiting PSP payout)'), ('settlement_completed', 'Settlement completed'), ('settlement_failed', 'Settlement failed'), ('settlement_reconciled', 'Settlement reconciled (manual)'), ('settlement_external_blocked', 'Settlement blocked (external)'), ('settlement_pending_external', 'Settlement pending (external PSP)')], db_index=True, max_length=40),
        ),
    ]
