# Generated by Django 5.2.10 on 2026-05-18 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_settlement_truth_event_types'),
        ('schools', '0051_add_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherorganization',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='publisherorganization',
            name='verified_contact_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Operator/owner email used to link platform user accounts to this publisher.', max_length=254),
        ),
        migrations.AddField(
            model_name='publisherorganization',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PublisherSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('intent', models.TextField(blank=True, help_text='Why the applicant wants to publish; what they intend to build.')),
                ('email_verify_token', models.CharField(help_text='One-time token sent to contact_email.', max_length=64, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('email_pending', 'Email verification pending'), ('email_verified', 'Email verified, awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='email_pending', max_length=24)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.ForeignKey(blank=True, help_text='Created PublisherOrganization once the request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='marketplace.publisherorganization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Authenticated user who submitted, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publisher signup request',
                'verbose_name_plural': 'Publisher signup requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('secret', models.CharField(help_text='HMAC-SHA256 secret; sent as X-RMC-Signature header.', max_length=128)),
                ('topics', models.JSONField(blank=True, default=list, help_text="Subscribed event topics, e.g. ['install', 'uninstall', 'scope_granted'].")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='marketplace.marketplaceapp')),
            ],
            options={
                'verbose_name': 'Webhook endpoint',
                'verbose_name_plural': 'Webhook endpoints',
                'ordering': ['app', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(db_index=True)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('verified_install', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('flagged', 'Flagged')], db_index=True, default='published', max_length=16)),
                ('publisher_reply', models.TextField(blank=True)),
                ('publisher_replied_at', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='marketplace.marketplaceapp')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_app_ratings', to='schools.school')),
            ],
            options={
                'verbose_name': 'App rating',
                'verbose_name_plural': 'App ratings',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='mkt_rating_stars_1_5')],
                'unique_together': {('app', 'school')},
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text='Semantic version, e.g. 1.4.2 or 2.0.0-beta.1.', max_length=32)),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('alpha', 'Alpha'), ('deprecated', 'Deprecated')], db_index=True, default='stable', max_length=16)),
                ('manifest_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen copy of the app manifest at the moment this version was published.')),
                ('changelog', models.TextField(blank=True, help_text='Markdown release notes for this version.')),
                ('migration_ref', models.CharField(blank=True, help_text='Optional schema migration id required to run this version.', max_length=120)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_yanked', models.BooleanField(db_index=True, default=False, help_text='True if this version was yanked post-publish (security/bug).')),
                ('yanked_reason', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketplace.marketplaceapp')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App version',
                'verbose_name_plural': 'App versions',
                'ordering': ['app', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['app', 'channel', 'is_published'], name='mkt_ver_app_ch_pub_idx')],
                'unique_together': {('app', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, max_length=190)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('succeeded', 'Succeeded'), ('failed', 'Failed (will retry)'), ('abandoned', 'Abandoned (max attempts)')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=6)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body_snippet', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='marketplace.marketplaceapp')),
                ('school', models.ForeignKey(blank=True, help_text='Originating tenant, if event was tenant-scoped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_webhook_deliveries', to='schools.school')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='marketplace.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook delivery',
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='mkt_wh_dlv_status_next_idx')],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'idempotency_key'), name='mkt_webhook_delivery_unique_endpoint_idempotency')],
            },
        ),
    ]
