# Generated by Django 5.2.10 on 2026-01-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="allows_third_term",
            field=models.BooleanField(
                default=True,
                help_text="Disable to block third-term activities (e.g., Form 5/Upper Sixth).",
            ),
        ),
    ]
