# Generated by Django 5.2.10 on 2026-01-18 20:10

from django.db import migrations


def add_academic_year_column(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "academics_classroom"
    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(
                cursor, table_name
            )
        }
    if "academic_year_id" not in existing_columns:
        if connection.vendor == "postgresql":
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" ADD COLUMN academic_year_id bigint'
            )
        elif connection.vendor == "mysql":
            schema_editor.execute(
                f"ALTER TABLE `{table_name}` ADD COLUMN academic_year_id bigint"
            )
        else:
            schema_editor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN academic_year_id integer"
            )

    AcademicYear = apps.get_model("academics", "AcademicYear")
    Classroom = apps.get_model("academics", "Classroom")

    active_year = (
        AcademicYear.objects.filter(is_active=True).order_by("-start_date").first()
    )
    if not active_year:
        active_year = AcademicYear.objects.order_by("-start_date").first()
    if not active_year:
        return

    Classroom.objects.filter(academic_year__isnull=True).update(
        academic_year=active_year
    )


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_classroom_allows_third_term"),
    ]

    operations = [
        migrations.RunPython(add_academic_year_column, migrations.RunPython.noop),
    ]
