# Generated by Django 5.2.10 on 2026-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0010_schedulingconstraint_room_schedule_timeslot_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scheduleentry",
            name="academics_s_room_id_73cb9b_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduleentry",
            name="academics_s_teacher_8df5c8_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduleentry",
            name="academics_s_schedul_9cffc7_idx",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="room",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="term",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="replacement_teacher",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="scheduleentry",
            name="time_slot",
        ),
        migrations.DeleteModel(
            name="SchedulingConstraint",
        ),
        migrations.AlterUniqueTogether(
            name="teacheravailability",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="teacheravailability",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="teacheravailability",
            name="time_slot",
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="ScheduleEntry",
        ),
        migrations.DeleteModel(
            name="TeacherAvailability",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
