# Generated by Django 5.2.10 on 2026-01-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_academicyear_enable_gce_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcandidate',
            name='official_cin',
            field=models.CharField(blank=True, help_text='Official CIN generated by the board e-registration software.', max_length=20),
        ),
        migrations.AddField(
            model_name='certificationcandidate',
            name='payment_amount_fcfa',
            field=models.PositiveIntegerField(default=0, help_text='Amount paid (FCFA).'),
        ),
        migrations.AddField(
            model_name='certificationcandidate',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='MTN Mobile Money transaction/payment ID used for validation.', max_length=120),
        ),
        migrations.AddField(
            model_name='certificationcandidate',
            name='unique_identifier',
            field=models.CharField(blank=True, help_text='MINESEC/MINEDUB Unique Identifier (matricule) for internal candidates.', max_length=80),
        ),
        migrations.AddField(
            model_name='certificationcandidate',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationexamsession',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='certificationexamsession',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='certificationexamsession',
            name='exam_centre_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificationexamsession',
            name='exam_centre_number',
            field=models.CharField(blank=True, help_text='Official centre number used by the board portal.', max_length=40),
        ),
    ]
