# Generated by Django 5.2.10 on 2026-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_certificationdocumentchecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationexamsession',
            name='admin_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Admin override records for deadline bypasses (audit trail).'),
        ),
    ]
