# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_certificationexamsession_admin_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='deadline_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Optional grading deadline for this subject/term/classroom.',
                null=True,
            ),
        ),
    ]
