# Generated by Django 5.2.10 on 2026-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0018_classroompromotionmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectassignment",
            name="grading_deadline_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for completing grades for this assignment (term/class/subject).",
                null=True,
            ),
        ),
    ]
