# Generated by Django 5.2.10 on 2026-02-09 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0021_schedulingconstraint_alter_subject_category_room_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSyllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending approval"),
                            ("NEEDS_REVISION", "Needs revision"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "builder_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data from the syllabus builder (e.g. CBA sections).",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional uploaded PDF/Word instead of or in addition to builder data.",
                        null=True,
                        upload_to="syllabi/%Y/%m/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_syllabi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_syllabi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_syllabus",
                        to="academics.subjectassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course syllabus",
                "verbose_name_plural": "Course syllabi",
                "ordering": ["-updated_at"],
            },
        ),
    ]
