# Generated by Django 5.2.10 on 2026-02-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0026_attendance_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "country_code",
                    models.CharField(
                        blank=True, help_text="e.g. CM, US, GB", max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="e.g. PHY-F5-U2-L3", max_length=80),
                ),
                ("title", models.CharField(max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("unit", "Unit"),
                            ("chapter", "Chapter"),
                            ("topic", "Topic"),
                        ],
                        default="topic",
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="academics.curriculumnode",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="academics.curriculumstandard",
                    ),
                ),
            ],
            options={
                "ordering": ["standard", "order", "code"],
                "unique_together": {("standard", "code")},
            },
        ),
    ]
