# Generated by Django 5.2.10 on 2026-02-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0029_enable_rls_postgresql"),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='academics_subject_school_name_uniq'),
        ),
    ]
