# Generated by Django 5.2.10 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_graduatemilestone_committee_member_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeprogram',
            name='transcript_track',
            field=models.CharField(choices=[('ACADEMIC', 'Academic (degree)'), ('VOCATIONAL', 'Vocational (certificate)')], default='ACADEMIC', help_text='Used for dual transcript: export by track (academic vs vocational).', max_length=20),
        ),
    ]
