# Generated by Django 5.2.10 on 2026-03-06 17:31

from django.db import migrations, models


def _syllabus_upload_to(instance, filename):
    """Tenant-scoped path for CourseSyllabus.uploaded_file (Section 25.3). School from subject_assignment.academic_year.

    Inlined from ``apps.academics.models._syllabus_upload_to`` for migration
    historical-state safety — migrations must not depend on live model code.
    """
    sa = getattr(instance, "subject_assignment", None)
    ay = getattr(sa, "academic_year", None) if sa else None
    school_id = getattr(ay, "school_id", None) if ay else None
    if school_id is None:
        return f"tenant_uploads/academics/syllabi/{filename}"
    return f"tenants/{school_id}/academics/syllabi/{filename}"


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0038_rls_policy_default_deny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesyllabus",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="Optional uploaded PDF/Word instead of or in addition to builder data.",
                null=True,
                upload_to=_syllabus_upload_to,
            ),
        ),
    ]
