# Generated by Django 5.2.10 on 2026-03-09 11:46

from django.conf import settings
from django.db import migrations, models


def _default_currency():
    """Platform default currency (no hardcoded XAF). See config.PLATFORM_DEFAULT_CURRENCY.

    Inlined from ``apps.academics.models._default_currency`` for migration
    historical-state safety.
    """
    return getattr(settings, "PLATFORM_DEFAULT_CURRENCY", "USD")


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0039_syllabus_tenant_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationfeetemplate",
            name="currency",
            field=models.CharField(
                default=_default_currency, max_length=10
            ),
        ),
    ]
