# Generated by Django 5.2.10 on 2026-03-09 11:46

import apps.academics.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0039_syllabus_tenant_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationfeetemplate",
            name="currency",
            field=models.CharField(
                default=apps.academics.models._default_currency, max_length=10
            ),
        ),
    ]
