# Generated by Django 5.2.10 on 2026-05-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_ensure_classroom_academic_year_column'),
        ('academics', '0016_subjectassignment_deadline_at'),
        ('academics', '0045_lms_assignment_submission'),
    ]

    operations = [
    ]
