# Generated by Django 5.2.10 on 2026-05-14 20:16

from django.db import migrations, models


def _lms_tenant_upload_to(subpath):
    """Tenant-prefixed upload_to.

    Inlined from ``apps.academics.models_lms._lms_tenant_upload_to`` for
    migration historical-state safety.
    """

    def upload_to(instance, filename):
        school_id = getattr(instance, "school_id", None)
        if school_id is None:
            assignment = getattr(instance, "assignment", None)
            school_id = getattr(assignment, "school_id", None)
        bucket = f"tenant-{school_id or 'unscoped'}"
        return f"{bucket}/{subpath}/{filename}"

    return upload_to


def lms_assignment_attachment_upload_to(instance, filename):
    return _lms_tenant_upload_to("lms_assignment_attachments")(instance, filename)


def lms_submission_attachment_upload_to(instance, filename):
    return _lms_tenant_upload_to("lms_submission_attachments")(instance, filename)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_merge_20260511_1554'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lmsassignment',
            new_name='academics_l_school__c5344d_idx',
            old_name='lms_assign_scs_idx',
        ),
        migrations.RenameIndex(
            model_name='lmsassignment',
            new_name='academics_l_teacher_ce3c6e_idx',
            old_name='lms_assign_teacher_due_idx',
        ),
        migrations.RenameIndex(
            model_name='lmssubmission',
            new_name='academics_l_school__c8a955_idx',
            old_name='lms_sub_sas_idx',
        ),
        migrations.RenameIndex(
            model_name='lmssubmission',
            new_name='academics_l_student_9b91ac_idx',
            old_name='lms_sub_student_sub_idx',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='deadline_at',
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=lms_assignment_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='late_penalty_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage docked per day late (0 disables).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='points_possible',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Max points; ignored if the school uses a non-numeric grading scale.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Multiplier applied when feeding the submission grade into the term composite.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=lms_submission_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='content',
            field=models.TextField(blank=True, help_text='Text body of the submission.'),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
