# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.academics.models
import apps.academics.models_lms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0048_classroom_settings_lexicon_k1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationfeetemplate',
            name='currency',
            field=models.CharField(default=apps.academics.models._default_currency, max_length=10),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Optional uploaded PDF/Word instead of or in addition to builder data.', null=True, upload_to=apps.academics.models._syllabus_upload_to),
        ),
        migrations.AlterField(
            model_name='lmsassignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.academics.models_lms.lms_assignment_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.academics.models_lms.lms_submission_attachment_upload_to),
        ),
    ]
