# Generated by Django 5.2.10 on 2026-05-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_global_academic_structure_and_shift'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academicstructurenode',
            new_name='academics_a_school__4b6953_idx',
            old_name='academics_a_school__a8f2c1_idx',
        ),
    ]
