# Generated by Django 5.2.10 on 2026-06-05 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0055_scheduleentry_db_conflict_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='uniq_schedentry_teacher_slot_shift',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='uniq_schedentry_room_slot_shift',
        ),
        migrations.RenameIndex(
            model_name='scheduleentry',
            new_name='academics_s_term_id_c719e5_idx',
            old_name='academics_s_term_id_6f2a91_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleentry',
            new_name='academics_s_term_id_2abeb6_idx',
            old_name='academics_s_term_id_8c4e12_idx',
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False), models.Q(('instruction_shift__isnull', True), _negated=True)), fields=('term', 'teacher', 'time_slot', 'instruction_shift'), name='uniq_schedentry_teacher_slot_shift'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False), models.Q(('instruction_shift__isnull', True), _negated=True)), fields=('term', 'room', 'time_slot', 'instruction_shift'), name='uniq_schedentry_room_slot_shift'),
        ),
    ]
