# Generated by Django 5.2.10 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0057_ensure_academics_school_id_columns'),
        ('schools', '0073_school_currency_alter_advancementgift_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='term_position_range_1_4_or_null',
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('position__isnull', True), models.Q(('position__gte', 1), ('position__lte', 12)), _connector='OR'), name='term_position_range_1_12_or_null'),
        ),
    ]
