# Generated by Django 5.2.10 on 2026-07-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_discipline_rls_postgresql'),
        ('schoolops', '0033_inventory_movement_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bookable_resource',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional link to the schoolops BookableResource this room maps to. When set, publishing a timetable cross-checks scheduled classes against confirmed ad-hoc bookings of the resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_rooms', to='schoolops.bookableresource'),
        ),
    ]
