# Generated by Django 5.2.10 on 2026-07-19 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_incident_resolved_at_incident_resolved_by'),
        ('schoolops', '0035_resource_booking_partial_capacity_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bookable_resource',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional link to the schoolops BookableResource this room maps to. When set, timetable generation AND publish cross-check scheduled classes against confirmed ad-hoc bookings of the resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_rooms', to='schoolops.bookableresource'),
        ),
    ]
