# Generated by Django 5.2.10 on 2026-07-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0068_alter_room_bookable_resource"),
        ("schoolops", "0036_substitute_market_shift"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "ordering": ["name"],
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
            },
        ),
        migrations.AlterField(
            model_name="room",
            name="bookable_resource",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text=(
                    "Link to the schoolops BookableResource this room maps to. "
                    "Auto-created on timetable generate/publish unless the school opts out; "
                    "when set, scheduled classes cross-check against confirmed ad-hoc bookings."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academics_rooms",
                to="schoolops.bookableresource",
            ),
        ),
    ]
