# Generated by Django 5.2.10 on 2026-07-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0069_alter_specialty_options_alter_room_bookable_resource'),
        ('schoolops', '0036_substitute_market_shift'),
        ('schools', '0081_rls_backfill_unenumerated_tenant_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1, help_text='Lessons per week of the cycle. 5 = Maths every weekday.')),
                ('block_length', models.PositiveSmallIntegerField(default=1, help_text='Consecutive periods per teaching block. 2 = double period (e.g. a laboratory session).')),
                ('cycle_length', models.PositiveSmallIntegerField(default=1, help_text='Weeks before the timetable repeats. 1 = ordinary weekly timetable; 2 = week A / week B rotation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum allocation',
                'verbose_name_plural': 'Curriculum allocations',
                'ordering': ['classroom__name', 'subject__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='uniq_schedentry_teacher_slot_in_plan',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='uniq_schedentry_room_slot_in_plan',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_rooms', to='schools.school'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='cycle_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_time_slots', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['school', 'is_available'], name='academics_r_school__25ba0d_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['school', 'is_active'], name='academics_t_school__ef606e_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='academics_room_school_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('schedule', 'teacher', 'time_slot', 'cycle_week'), name='uniq_schedentry_teacher_slot_in_plan'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('schedule', 'room', 'time_slot', 'cycle_week'), name='uniq_schedentry_room_slot_in_plan'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('school', 'day_of_week', 'start_time', 'end_time'), name='academics_timeslot_school_period_uniq'),
        ),
        migrations.AddField(
            model_name='curriculumallocation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_allocations', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='curriculumallocation',
            name='classroom',
            field=models.ForeignKey(help_text='The class / section this allocation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_allocations', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='curriculumallocation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_allocations', to='schools.school'),
        ),
        migrations.AddField(
            model_name='curriculumallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_allocations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='curriculumallocation',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Leave empty to apply to every term of the year.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_allocations', to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='curriculumallocation',
            index=models.Index(fields=['academic_year', 'term', 'classroom'], name='academics_c_academi_573430_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', False)), fields=('academic_year', 'term', 'classroom', 'subject'), name='academics_curralloc_term_scoped_uniq'),
        ),
        migrations.AddConstraint(
            model_name='curriculumallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', True)), fields=('academic_year', 'classroom', 'subject'), name='academics_curralloc_year_scoped_uniq'),
        ),
        migrations.AddConstraint(
            model_name='curriculumallocation',
            constraint=models.CheckConstraint(condition=models.Q(('periods_per_week__gte', 1)), name='academics_curralloc_ppw_min_1'),
        ),
        migrations.AddConstraint(
            model_name='curriculumallocation',
            constraint=models.CheckConstraint(condition=models.Q(('block_length__gte', 1)), name='academics_curralloc_block_min_1'),
        ),
        migrations.AddConstraint(
            model_name='curriculumallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_length__gte', 1)), name='academics_curralloc_cycle_min_1'),
        ),
    ]
