# Generated by Django 5.2.10 on 2026-07-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0072_enable_rls_curriculum_room_timeslot'),
        ('people', '0071_backfill_enrollment_from_student_row'),
        ('schools', '0083_force_rls_late_enabled_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='classroom',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_attendance_school_offline_id'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_classroom_school_offline_id'),
        ),
    ]
