# Generated by Django 5.2.10 on 2026-08-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0076_department_code_per_school_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional national/country-standard subject code (e.g. a GCE board code). Auto-derived from the country subject-code scheme on seed and fully admin-editable; blank is allowed.', max_length=30),
        ),
    ]
