# Generated by Django 5.2.10 on 2026-08-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0079_enable_rls_specialtysubject'),
        ('schools', '0083_force_rls_late_enabled_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='specialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='specialtysubject',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='specialtysubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_specialty_school_offline_id'),
        ),
        migrations.AddConstraint(
            model_name='specialtysubject',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_specialtysubject_school_offline_id'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_subject_school_offline_id'),
        ),
    ]
