# Generated by Django 5.2.14 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0080_edge_sync_anchor_catalogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectassignment",
            name="client_offline_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="subjectassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_offline_id", ""), _negated=True),
                fields=("school", "client_offline_id"),
                name="uniq_subjectassignment_school_offline_id",
            ),
        ),
    ]
