from django.urls import path
from .views import (
    studio_ai_cleanup,
    studio_audit_api,
    studio_automation_conflict_detection,
    studio_automation_dependency_graph,
    studio_automation_workflow_health,
    studio_control_impact,
    studio_experience_compare,
    studio_experience_recommendations,
    studio_experience_communication_style_packs,
    studio_experience_dashboard_visual_packs,
    studio_experience_packs,
    studio_experience_portal_shell_layouts,
    studio_experience_school_website_blocks,
    studio_experience_theme_tokens,
    studio_global_search,
    studio_output_branding_inheritance,
    studio_output_dependency_graph,
    studio_preview,
    studio_publish_api,
    studio_recommendations_api,
    studio_rollback,
    studio_save_draft_api,
    studio_shell,
    studio_version_history_api,
)

app_name = "studio_os"

urlpatterns = [
    path("", studio_shell, name="shell"),
    path("experience/", studio_shell, {"mode": "experience"}, name="experience"),
    path("experience/recommendations/", studio_experience_recommendations, name="experience_recommendations"),
    path("experience/compare/", studio_experience_compare, name="experience_compare"),
    path("experience/theme-tokens/", studio_experience_theme_tokens, name="experience_theme_tokens"),
    path("experience/portal-shell-layouts/", studio_experience_portal_shell_layouts, name="experience_portal_shell_layouts"),
    path("experience/dashboard-visual-packs/", studio_experience_dashboard_visual_packs, name="experience_dashboard_visual_packs"),
    path("experience/school-website-blocks/", studio_experience_school_website_blocks, name="experience_school_website_blocks"),
    path("experience/communication-style-packs/", studio_experience_communication_style_packs, name="experience_communication_style_packs"),
    path("experience/experience-packs/", studio_experience_packs, name="experience_packs"),
    path("automation/", studio_shell, {"mode": "automation"}, name="automation"),
    path("automation/conflict-detection/", studio_automation_conflict_detection, name="automation_conflict_detection"),
    path("automation/dependency-graph/", studio_automation_dependency_graph, name="automation_dependency_graph"),
    path("automation/workflow-health/", studio_automation_workflow_health, name="automation_workflow_health"),
    path("output/", studio_shell, {"mode": "output"}, name="output"),
    path("output/dependency-graph/", studio_output_dependency_graph, name="output_dependency_graph"),
    path("output/branding-inheritance/", studio_output_branding_inheritance, name="output_branding_inheritance"),
    path("launch/", studio_shell, {"mode": "launch"}, name="launch"),
    path("control/", studio_shell, {"mode": "control"}, name="control"),
    path("preview/", studio_preview, name="preview"),
    path("publish/", studio_publish_api, name="publish"),
    path("save-draft/", studio_save_draft_api, name="save_draft"),
    path("version-history/", studio_version_history_api, name="version_history"),
    path("search/", studio_global_search, name="global_search"),
    path("recommendations/", studio_recommendations_api, name="recommendations"),
    path("control/impact/", studio_control_impact, name="control_impact"),
    path("control/ai-cleanup/", studio_ai_cleanup, name="ai_cleanup"),
    path("audit/", studio_audit_api, name="audit"),
    path("rollback/", studio_rollback, name="rollback"),
]
