# Generated by Django 5.2.10 on 2026-03-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_add_quote_model'),
        ('siteconfig', '0147_sitesettings_compliance_profile_pointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Billing account',
                'verbose_name_plural': 'Billing accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billingaccount',),
        ),
        migrations.CreateModel(
            name='BillingProcessorSyncEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Billing processor sync event',
                'verbose_name_plural': 'Billing processor sync events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billingprocessorsyncevent',),
        ),
        migrations.CreateModel(
            name='CountryMultiplier',
            fields=[
            ],
            options={
                'verbose_name': 'Country price multiplier',
                'verbose_name_plural': 'Country price multipliers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.countrymultiplier',),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.plan',),
        ),
        migrations.CreateModel(
            name='PlanAddon',
            fields=[
            ],
            options={
                'verbose_name': 'Plan add-on',
                'verbose_name_plural': 'Plan add-ons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.planaddon',),
        ),
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Platform ledger entry',
                'verbose_name_plural': 'Platform ledger entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.platformledgerentry',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.quote',),
        ),
        migrations.CreateModel(
            name='RevenueSharePayout',
            fields=[
            ],
            options={
                'verbose_name': 'Revenue share payout',
                'verbose_name_plural': 'Revenue share payouts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.revenuesharepayout',),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant subscription',
                'verbose_name_plural': 'Tenant subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.tenantsubscription',),
        ),
        migrations.CreateModel(
            name='UsageMeter',
            fields=[
            ],
            options={
                'verbose_name': 'Usage meter',
                'verbose_name_plural': 'Usage meters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.usagemeter',),
        ),
    ]
