# Generated by Codex for the plans-entitlements owner proxy.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_entitlement"),
        ("plans_entitlements", "0001_proxy_owner_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entitlement",
            fields=[],
            options={
                "verbose_name": "Entitlement",
                "verbose_name_plural": "Entitlements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.entitlement",),
        ),
    ]
