# Generated by Django 5.2.10 on 2026-03-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registries", "0003_add_document_fee_grade_registry_and_country_fields"),
        ("schools", "0038_advancement_donor_gift"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAttendanceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=16)),
                ("label", models.CharField(max_length=160)),
                ("counts_as_present", models.BooleanField(default=False)),
                ("is_excused_absence", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_attendance_codes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant attendance code",
                "verbose_name_plural": "Tenant attendance codes",
                "ordering": ["sort_order", "code"],
                "unique_together": {("school", "code")},
            },
        ),
        migrations.CreateModel(
            name="TenantFeeTypeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_fee_entries",
                        to="registries.feecategoryregistry",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_fee_type_entries",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant fee type entry",
                "verbose_name_plural": "Tenant fee type entries",
                "ordering": ["sort_order", "code"],
                "unique_together": {("school", "code")},
            },
        ),
    ]
