# Generated by Django 5.2.10 on 2026-05-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0005_country_cockpit_override_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryregistry',
            name='cockpit_override_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Operator-edited overlay applied on top of the in-memory country seed pack at the service hot path (Wave 8 v3.62.8). Shape mirrors the country pack: calendar_systems / school_types / education_levels / terminology / languages. Lists override wholesale; dicts merge one level deep. Empty dict = no override.'),
        ),
    ]
