# Generated by Django 5.2.10 on 2026-08-13 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0012_seed_localization_registries'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevelregistry',
            name='isced_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='UNESCO ISCED 2011 level 0-8.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='educationlevelregistry',
            name='tier',
            field=models.CharField(blank=True, choices=[('EARLY_CHILDHOOD', 'Early childhood'), ('K12', 'K-12'), ('TERTIARY', 'Tertiary')], default='', help_text='Coarse educational-level tier used to drive tier-specific behaviour.', max_length=24),
        ),
    ]
