# Generated by Django 5.2.10 on 2026-03-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0034_remove_biometricdevice_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, max_length=120)),
                ('version', models.CharField(max_length=80)),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('action', models.CharField(choices=[('apply', 'Apply'), ('rollback', 'Rollback')], default='apply', max_length=20)),
                ('rollback_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Change Log',
                'verbose_name_plural': 'Package Change Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, max_length=120)),
                ('version', models.CharField(max_length=80)),
                ('compatibility', models.JSONField(blank=True, default=dict, help_text='Platform/region constraints.')),
                ('payload_sections', models.JSONField(blank=True, default=dict, help_text='Blueprint/workflow/dashboard/policy/theme payloads.')),
                ('changelog_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Version',
                'verbose_name_plural': 'Package Versions',
                'ordering': ['package_id', '-created_at'],
                'unique_together': {('package_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InstalledPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, help_text='Stable package identifier.', max_length=120)),
                ('package_type', models.CharField(choices=[('blueprint', 'Blueprint Pack'), ('workflow', 'Workflow Pack'), ('dashboard', 'Dashboard Pack'), ('policy', 'Policy Bundle'), ('theme', 'Theme Pack')], default='blueprint', max_length=40)),
                ('version', models.CharField(help_text='Installed version string.', max_length=80)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('region', 'Region'), ('blueprint', 'Blueprint'), ('plan', 'Plan'), ('tenant', 'Tenant'), ('sandbox', 'Sandbox')], default='tenant', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by_id', models.IntegerField(blank=True, null=True)),
                ('rollback_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, help_text='Null = platform/global install.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'Installed Package',
                'verbose_name_plural': 'Installed Packages',
                'ordering': ['-applied_at'],
                'unique_together': {('package_id', 'version', 'school')},
            },
        ),
    ]
