# Generated by Django 5.2.10 on 2026-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="installedpackage",
            name="apply_stage",
            field=models.CharField(
                choices=[
                    ("sandbox", "Sandbox"),
                    ("test", "Test"),
                    ("production", "Production"),
                    ("rollback", "Rollback"),
                    ("promoted", "Promoted"),
                ],
                default="production",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="installedpackage",
            name="dependency_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="installedpackage",
            name="impact_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="installedpackage",
            name="promoted_from_mode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="installedpackage",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("reconciled", "Reconciled"),
                    ("rolled_back", "Rolled Back"),
                    ("promoted", "Promoted"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="packagechangelog",
            name="dependency_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="packagechangelog",
            name="impact_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="packagechangelog",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("reconciled", "Reconciled"),
                    ("rolled_back", "Rolled Back"),
                    ("promoted", "Promoted"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="dependencies",
            field=models.JSONField(
                blank=True, default=list, help_text="Package dependencies."
            ),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="impact_summary",
            field=models.JSONField(
                blank=True, default=dict, help_text="Computed impact preview snapshot."
            ),
        ),
        migrations.AlterField(
            model_name="packagechangelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("apply", "Apply"),
                    ("rollback", "Rollback"),
                    ("promote", "Promote"),
                ],
                default="apply",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packagechangelog",
            name="mode",
            field=models.CharField(
                choices=[
                    ("sandbox", "Sandbox"),
                    ("test", "Test"),
                    ("production", "Production"),
                ],
                default="production",
                max_length=20,
            ),
        ),
    ]
