"""Curated workflow templates for operator gallery (descriptive — not live customer claims)."""

from __future__ import annotations

from typing import Any

WORKFLOW_TEMPLATE_GALLERY: list[dict[str, Any]] = [
    {
        "id": "missing_attendance_reminder",
        "title": "Missing attendance reminder",
        "trigger": "School day started + period window open",
        "condition": "Expected register row absent for class",
        "action": "Notify homeroom teacher + escalate to academic lead after N hours",
        "owner": "Academic operations",
        "expected_outcome": "Registers complete before reporting cutoff",
        "setup_effort": "Low — uses standard notification channel",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "missing_attendance_reminder",
    },
    {
        "id": "marks_missing_followup",
        "title": "Marks missing follow-up",
        "trigger": "Marking period closing window",
        "condition": "Required assessment cells empty for class",
        "action": "Stage reminders to teachers + leadership digest",
        "owner": "Registrar",
        "expected_outcome": "Gradebook complete before report batch",
        "setup_effort": "Medium — map assessments to workflow fields",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "marks_missing_followup",
    },
    {
        "id": "report_card_ready",
        "title": "Report card ready notification",
        "trigger": "Report batch job succeeded",
        "condition": "Parent portal feature enabled for tenant",
        "action": "Notify guardians with controlled link + audit log entry",
        "owner": "Communications",
        "expected_outcome": "Guardians retrieve reports without help-desk load",
        "setup_effort": "Low",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "report_card_ready",
    },
    {
        "id": "payment_overdue_escalation",
        "title": "Payment overdue escalation",
        "trigger": "Invoice past due date",
        "condition": "Balance > 0 and reminders enabled",
        "action": "Tiered reminders + leadership rollup (no live PSP guarantee)",
        "owner": "Finance office",
        "expected_outcome": "Faster settlement or structured follow-up",
        "setup_effort": "Medium — align to your PSP readiness",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "payment_overdue_escalation",
    },
    {
        "id": "parent_onboarding_reminder",
        "title": "Parent onboarding reminder",
        "trigger": "Student enrolled + guardian invite sent",
        "condition": "Guardian account not activated in N days",
        "action": "Reminder sequence + front-office task",
        "owner": "Admissions",
        "expected_outcome": "Higher portal activation before term start",
        "setup_effort": "Low",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "parent_onboarding_reminder",
    },
    {
        "id": "offline_conflict_followup",
        "title": "Offline conflict follow-up",
        "trigger": "Offline queue processed",
        "condition": "Conflict row requires human decision",
        "action": "Assign to school IT + SLA timer",
        "owner": "School IT",
        "expected_outcome": "Conflicts cleared without data loss",
        "setup_effort": "Low",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "offline_conflict_followup",
    },
    {
        "id": "at_risk_student",
        "title": "At-risk student intervention",
        "trigger": "Composite risk signal (attendance + marks trend)",
        "condition": "Signal crosses tenant policy threshold",
        "action": "Notify counselor + create structured follow-up task",
        "owner": "Student services",
        "expected_outcome": "Earlier intervention with audit trail",
        "setup_effort": "High — policy tuning required",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "at_risk_student",
    },
    {
        "id": "expansion_ready_outreach",
        "title": "Expansion-ready school outreach",
        "trigger": "Lifecycle state expansion-ready",
        "condition": "Pilot core loop completed honestly",
        "action": "Internal CS task + optional reference request (permissioned)",
        "owner": "Customer success",
        "expected_outcome": "Structured upsell without fabricated references",
        "setup_effort": "Low",
        "simulate_url_name": "automation:outcomes_console",
        "designer_url_name": "automation:visual_workflow_designer",
        "gallery_hint": "expansion_ready_outreach",
    },
]

REQUIRED_TEMPLATE_IDS = frozenset(t["id"] for t in WORKFLOW_TEMPLATE_GALLERY)

# Trigger keys for one-click dry-run (published workflow) or synthetic sample fallback.
GALLERY_TEMPLATE_DRY_RUN_TRIGGER: dict[str, str] = {
    "missing_attendance_reminder": "attendance_saved",
    "marks_missing_followup": "marks_submitted",
    "report_card_ready": "report_generated",
    "payment_overdue_escalation": "payment_failed",
    "parent_onboarding_reminder": "app_installed",
    "offline_conflict_followup": "offline_action_conflict",
    "at_risk_student": "student_risk_detected",
    "expansion_ready_outreach": "payment_success",
}
