# Generated by Django 5.2.10 on 2026-03-05 23:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('availability', 'Availability'), ('performance', 'Performance'), ('security', 'Security'), ('data', 'Data integrity'), ('integration', 'Integration'), ('billing', 'Billing'), ('deployment', 'Deployment'), ('support', 'Support escalation'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source_system', models.CharField(blank=True, max_length=128)),
                ('affected_schema_name', models.CharField(blank=True, db_index=True, max_length=63)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_incidents_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('affected_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_incidents', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_incidents_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_incidents_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'severity', 'detected_at'], name='observabili_status_12c4bb_idx'), models.Index(fields=['incident_type', 'detected_at'], name='observabili_inciden_224378_idx')],
            },
        ),
    ]
