# Generated by Django 5.2.10 on 2026-05-15 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0002_platformincident'),
        ('schools', '0048_force_rls_on_all_enabled_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrictionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(db_index=True, help_text='Django URL-conf name, route template, or stable JS view-id.', max_length=200)),
                ('kind', models.CharField(choices=[('validation_retry', 'Form submitted with errors ≥3 times'), ('form_abandon', 'Started a form, navigated away without submit'), ('dwell_excess', 'Lingered on a step far beyond normal'), ('repeat_error', 'Same client-side error fired 3× in a session')], db_index=True, max_length=32)),
                ('utc_day', models.DateField(db_index=True, help_text='UTC day the rollup covers.')),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_payload', models.JSONField(blank=True, default=dict, help_text='Most recent client-side context (field names, error code, dwell ms).')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set when an operator acknowledges or auto-resolution fires.', null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friction_events', to='schools.school')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated actor if available; null for anonymous.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friction event',
                'verbose_name_plural': 'Friction events',
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['school', 'kind', 'utc_day'], name='observabili_school__ee6957_idx'), models.Index(fields=['resolved_at'], name='observabili_resolve_ac31bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'school', 'view_name', 'kind', 'utc_day'), name='uniq_friction_actor_view_kind_day')],
            },
        ),
    ]
