# Generated by Django 5.2.10 on 2026-05-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0004_platformstatusincident'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformstatusincident',
            new_name='observabili_is_publ_01dce4_idx',
            old_name='observabili_is_publ_4a8f2a_idx',
        ),
    ]
