# Generated by Django 5.2.10 on 2026-07-02 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0005_rename_observabili_is_publ_4a8f2a_idx_observabili_is_publ_01dce4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('update', 'Update'), ('status_change', 'Status change'), ('postmortem', 'Postmortem'), ('action_item', 'Action item')], db_index=True, default='update', max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='observability.platformincident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', 'created_at'], name='observabili_inciden_24d1f6_idx')],
            },
        ),
    ]
