# Generated by Django 5.2.10 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observability", "0006_incident_update_timeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frictionevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("validation_retry", "Form submitted with errors ≥3 times"),
                    ("form_abandon", "Started a form, navigated away without submit"),
                    ("dwell_excess", "Lingered on a step far beyond normal"),
                    ("repeat_error", "Same client-side error fired 3× in a session"),
                    ("layout_overflow", "Responsive layout root overflow detected"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
