# Generated by Django 5.2.10 on 2026-07-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0067_incident_resolved_at_incident_resolved_by'),
        ('athletics', '0003_rls_policy_default_deny'),
        ('people', '0068_studentguardian_is_active_and_more'),
        ('schools', '0077_schoolmembership_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('arts', 'Arts & culture'), ('service', 'Service / community'), ('stem', 'STEM'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('meeting_day', models.CharField(blank=True, max_length=48)),
                ('meeting_location', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='forming', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletics_clubs', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletics_clubs', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubAdvisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead advisor'), ('assistant', 'Assistant advisor')], default='lead', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletics_club_advisor_assignments', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='athletics.club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletics_club_advisor_assignments', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waitlist', 'Waitlist'), ('left', 'Left')], default='active', max_length=16)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='athletics.club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletics_club_memberships', to='schools.school')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='athletics_club_memberships', to='people.studentprofile')),
            ],
            options={
                'ordering': ['club', 'student_id'],
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['school', 'status'], name='athletics_c_school__3bfce1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('school', 'slug')},
        ),
        migrations.AddIndex(
            model_name='clubadvisorassignment',
            index=models.Index(fields=['school', 'advisor', 'is_active'], name='athletics_c_school__002cf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubadvisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('club', 'advisor'), name='uniq_active_advisor_per_club'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['school', 'status'], name='athletics_c_school__95f6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['club', 'status'], name='athletics_c_club_id_585f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'waitlist'))), fields=('club', 'student'), name='uniq_active_membership_per_club'),
        ),
    ]
