# Generated by Django 5.2.10 on 2026-03-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0005_alter_policybundle_policy_snapshot'),
        ('siteconfig', '0147_sitesettings_compliance_profile_pointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintCompatibilityRule',
            fields=[
            ],
            options={
                'verbose_name': 'Blueprint compatibility rule',
                'verbose_name_plural': 'Blueprint compatibility rules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policies.blueprintcompatibilityrule',),
        ),
        migrations.CreateModel(
            name='BlueprintPack',
            fields=[
            ],
            options={
                'verbose_name': 'Blueprint pack',
                'verbose_name_plural': 'Blueprint packs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policies.blueprintpack',),
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
            ],
            options={
                'verbose_name': 'dashboard layout',
                'verbose_name_plural': 'dashboard layouts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboardlayout',),
        ),
        migrations.CreateModel(
            name='DashboardPack',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Pack',
                'verbose_name_plural': 'Dashboard Packs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboardpack',),
        ),
        migrations.CreateModel(
            name='DashboardPackAssignment',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard pack assignment',
                'verbose_name_plural': 'Dashboard pack assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboardpackassignment',),
        ),
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Template',
                'verbose_name_plural': 'Dashboard Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboardtemplate',),
        ),
        migrations.CreateModel(
            name='DashboardUserPreference',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard User Preference',
                'verbose_name_plural': 'Dashboard User Preferences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboarduserpreference',),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.dashboardwidget',),
        ),
        migrations.CreateModel(
            name='FormDraft',
            fields=[
            ],
            options={
                'verbose_name': 'Form draft',
                'verbose_name_plural': 'Form drafts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.formdraft',),
        ),
        migrations.CreateModel(
            name='OfficialReportTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'official report template',
                'verbose_name_plural': 'official report templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.officialreporttemplate',),
        ),
        migrations.CreateModel(
            name='ReportCardStyle',
            fields=[
            ],
            options={
                'verbose_name': 'report card style',
                'verbose_name_plural': 'report card styles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.reportcardstyle',),
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'report template',
                'verbose_name_plural': 'report templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.reporttemplate',),
        ),
        migrations.CreateModel(
            name='SuperAdminDashboardPreference',
            fields=[
            ],
            options={
                'verbose_name': 'Super Admin dashboard preference',
                'verbose_name_plural': 'Super Admin dashboard preferences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.superadmindashboardpreference',),
        ),
        migrations.CreateModel(
            name='TenantBlueprint',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant blueprint',
                'verbose_name_plural': 'Tenant blueprints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policies.tenantblueprint',),
        ),
        migrations.CreateModel(
            name='TenantLayoutAssignment',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant Layout Assignment',
                'verbose_name_plural': 'Tenant Layout Assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.tenantlayoutassignment',),
        ),
        migrations.CreateModel(
            name='TenantWorkflow',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant Workflow',
                'verbose_name_plural': 'Tenant Workflows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.tenantworkflow',),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.userpreference',),
        ),
        migrations.CreateModel(
            name='WorkflowPack',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow Pack',
                'verbose_name_plural': 'Workflow Packs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.workflowpack',),
        ),
        migrations.CreateModel(
            name='WorkflowPackAssignment',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow pack assignment',
                'verbose_name_plural': 'Workflow pack assignments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.workflowpackassignment',),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.workflowtemplate',),
        ),
    ]
