# Generated by Django 5.2.10 on 2026-01-22 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteconfig', '0015_add_internationalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rule_type', models.CharField(choices=[('data_retention', 'Data Retention'), ('certificate_format', 'Certificate Format'), ('student_id_format', 'Student ID Format'), ('document_validation', 'Document Validation'), ('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('data_agreement', 'Data Processing Agreement')], max_length=50)),
                ('description', models.TextField()),
                ('applies_globally', models.BooleanField(default=False, help_text='If True, applies to all regions')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must be enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('data_agreement', 'Data Processing Agreement'), ('parental_consent', 'Parental Consent Form'), ('user_agreement', 'User Agreement')], max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('pid', 'Pidgin'), ('ha', 'Hausa')], default='en', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Full HTML/text content of the legal document')),
                ('version', models.IntegerField(default=1, help_text='Document version number')),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_documents', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='siteconfig.regionconfig')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['region', 'document_type', 'language', '-version'],
                'unique_together': {('region', 'document_type', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RegionalComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_override', models.TextField(blank=True, help_text='Override default rule description for this region')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, help_text='Region-specific parameters (e.g., data retention months, ID format pattern)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('implemented', 'Implemented'), ('active', 'Active'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('implementation_date', models.DateField(blank=True, null=True)),
                ('enforcement_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Compliance deadline for this region', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirements', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='siteconfig.regionconfig')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_requirements', to='compliance.compliancerule')),
            ],
            options={
                'verbose_name': 'Regional Compliance Requirement',
                'verbose_name_plural': 'Regional Compliance Requirements',
                'ordering': ['region', 'rule__rule_type'],
                'unique_together': {('region', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('data_validation', 'Data Validation'), ('document_audit', 'Document Audit'), ('format_validation', 'Format Validation'), ('policy_review', 'Policy Review'), ('scheduled_review', 'Scheduled Review')], default='scheduled_review', max_length=50)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('pending', 'Pending')], max_length=20)),
                ('findings', models.TextField(help_text='Detailed findings from the compliance check')),
                ('issues_found', models.IntegerField(default=0, help_text='Number of compliance issues found')),
                ('issues_resolved', models.IntegerField(default=0, help_text='Number of issues already resolved')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('next_check_date', models.DateField(blank=True, null=True)),
                ('remediation_required', models.BooleanField(default=False)),
                ('remediation_deadline', models.DateField(blank=True, null=True)),
                ('remediation_notes', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='siteconfig.regionconfig')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.regionalcompliancerequirement')),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentIDFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_pattern', models.CharField(help_text='Pattern: region prefix, YY (year), nnn (sequential), other identifiers', max_length=100)),
                ('prefix', models.CharField(help_text='Regional prefix for student IDs', max_length=5)),
                ('min_length', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)])),
                ('max_length', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(50)])),
                ('allow_letters', models.BooleanField(default=True)),
                ('allow_numbers', models.BooleanField(default=True)),
                ('allow_special_chars', models.BooleanField(default=False)),
                ('example_id', models.CharField(help_text='Example of valid ID format', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_student_id_format', to='siteconfig.regionconfig')),
            ],
            options={
                'verbose_name': 'Student ID Format',
                'verbose_name_plural': 'Student ID Formats',
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('letter', 'Letter'), ('A3', 'A3')], default='A4', max_length=50)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=20)),
                ('requires_school_seal', models.BooleanField(default=True)),
                ('requires_principal_signature', models.BooleanField(default=True)),
                ('requires_official_stamp', models.BooleanField(default=True)),
                ('requires_issue_date', models.BooleanField(default=True)),
                ('requires_validity_date', models.BooleanField(default=False)),
                ('template_html', models.TextField(help_text='HTML template with placeholders')),
                ('css_styling', models.TextField(blank=True, help_text='CSS for styling')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='siteconfig.regionconfig')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['region', 'name', '-version'],
                'unique_together': {('region', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('check_performed', 'Compliance Check Performed'), ('requirement_created', 'Requirement Created'), ('requirement_updated', 'Requirement Updated'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('document_accessed', 'Document Accessed'), ('policy_enforced', 'Policy Enforced'), ('remediation_assigned', 'Remediation Assigned'), ('remediation_completed', 'Remediation Completed'), ('escalation', 'Issue Escalated')], max_length=50)),
                ('description', models.TextField(help_text='Details of the action performed')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional JSON data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='siteconfig.regionconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='compliance.legaldocument')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='compliance.regionalcompliancerequirement')),
            ],
            options={
                'verbose_name': 'Compliance Audit Log',
                'verbose_name_plural': 'Compliance Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['region', '-timestamp'], name='compliance__region__4ed5f3_idx'), models.Index(fields=['action_type', '-timestamp'], name='compliance__action__5178f0_idx'), models.Index(fields=['severity', '-timestamp'], name='compliance__severit_3d66ac_idx')],
            },
        ),
    ]
