# Generated by Django 5.2.10 on 2026-01-22 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_legaldocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'Web View'), ('API', 'API Call'), ('DOWNLOAD', 'File Download'), ('REPORT', 'Report Generation')], max_length=20)),
                ('resource', models.CharField(help_text='URL path or API endpoint', max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FORBIDDEN', 'Access Denied'), ('NOT_FOUND', 'Not Found'), ('ERROR', 'Error')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='If status != SUCCESS')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='compliance__user_id_aba0d1_idx'), models.Index(fields=['resource', '-timestamp'], name='compliance__resourc_d20b61_idx'), models.Index(fields=['status', '-timestamp'], name='compliance__status_ff39c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VIEW', 'Record Viewed'), ('EXPORT', 'Data Exported'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PERM_GRANT', 'Permission Granted'), ('PERM_REVOKE', 'Permission Revoked'), ('PUBLISH', 'Content Published'), ('APPROVE', 'Action Approved'), ('REJECT', 'Action Rejected')], max_length=20)),
                ('model_name', models.CharField(help_text="e.g., 'Invoice', 'Evaluation'", max_length=100)),
                ('object_id', models.CharField(help_text='Primary key of affected object', max_length=200)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of object', max_length=500)),
                ('sensitivity', models.CharField(choices=[('LOW', 'Public'), ('MEDIUM', 'Restricted'), ('HIGH', 'Confidential'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Data sensitivity classification', max_length=20)),
                ('old_values', models.JSONField(blank=True, help_text='Pre-change state (for UPDATE/DELETE)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Post-change state (for CREATE/UPDATE)', null=True)),
                ('changed_fields', models.JSONField(blank=True, help_text='List of field names that changed', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('reason', models.CharField(blank=True, help_text="Reason/comment for the action (e.g., 'Bulk import', 'Correction')", max_length=255)),
                ('related_audit_logs', models.ManyToManyField(blank=True, help_text='Reference to related audit entries', related_name='related_to', to='compliance.auditlog')),
                ('user', models.ForeignKey(help_text='User who performed the action (null if system-initiated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='compliance__user_id_71a297_idx'), models.Index(fields=['model_name', 'object_id'], name='compliance__model_n_d2788f_idx'), models.Index(fields=['action', '-timestamp'], name='compliance__action_26c18c_idx'), models.Index(fields=['sensitivity', '-timestamp'], name='compliance__sensiti_c84e72_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('AUDIT_TRAIL', 'Audit Trail'), ('DATA_ACCESS', 'Data Access Report'), ('PERM_SUMMARY', 'Permission Summary'), ('INTEGRITY', 'Data Integrity Check'), ('ANOMALY', 'Anomaly Detection')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(help_text='Report period start')),
                ('end_date', models.DateField(help_text='Report period end')),
                ('summary', models.JSONField(help_text='High-level metrics and findings')),
                ('details', models.JSONField(help_text='Detailed findings, grouped by category')),
                ('issues', models.JSONField(default=list, help_text='List of detected issues/anomalies')),
                ('export_formats', models.JSONField(default=list, help_text="Available export formats: ['pdf', 'csv', 'json']")),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='compliance__report__3ae4e7_idx'), models.Index(fields=['start_date', 'end_date'], name='compliance__start_d_7013a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flag if unusual activity detected')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_timestamp'],
                'indexes': [models.Index(fields=['user', '-login_timestamp'], name='compliance__user_id_8d6177_idx'), models.Index(fields=['is_suspicious'], name='compliance__is_susp_cd79ff_idx')],
            },
        ),
    ]
