# Generated by Django 5.2.10 on 2026-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0006_countryaccessrule_ipaccessrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("AUDIT", "Audit Event"),
                            ("THREAT", "Threat Finding"),
                            ("ACCESS", "Access Control"),
                            ("SYSTEM", "System Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source module or function",
                        max_length=100,
                    ),
                ),
                ("related_model", models.CharField(blank=True, max_length=100)),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Alert Digest",
                "verbose_name_plural": "Alert Digests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_sent", "created_at"],
                        name="compliance__is_sent_63db77_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "severity"],
                        name="compliance__alert_t_5ef55e_idx",
                    ),
                ],
            },
        ),
    ]
