# Generated by Django 5.2.10 on 2026-05-14 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_exportjob_eraserequest_sla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ferpadisclosure',
            new_name='compliance__school__c87190_idx',
            old_name='ferpa_disc_school_at_idx',
        ),
        migrations.RenameIndex(
            model_name='ferpadisclosure',
            new_name='compliance__student_dcb320_idx',
            old_name='ferpa_disc_student_at_idx',
        ),
        migrations.RenameIndex(
            model_name='ferpadisclosure',
            new_name='compliance__purpose_afeb8a_idx',
            old_name='ferpa_disc_purpose_idx',
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='disclosed_by',
            field=models.ForeignKey(blank=True, help_text='School official who recorded this disclosure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferpa_disclosures_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='parent_consent_obtained',
            field=models.BooleanField(default=False, help_text='True only when written consent is on file before disclosure.'),
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='recipient_name',
            field=models.CharField(help_text='Person who received the records (full name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='recipient_org',
            field=models.CharField(blank=True, help_text='Organization or agency, when applicable.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ferpadisclosure',
            name='record_types_disclosed',
            field=models.JSONField(blank=True, default=list, help_text='List of record categories released (transcripts, attendance, disciplinary, …).'),
        ),
    ]
