# Generated by Django 5.2.10 on 2026-06-07 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_rename_ferpa_disc_school_at_idx_compliance__school__c87190_idx_and_more'),
        ('schools', '0066_tenantinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspector_email', models.EmailField(blank=True, max_length=254)),
                ('inspector_label', models.CharField(blank=True, help_text="e.g. 'Ofsted Lead Inspector'", max_length=120)),
                ('scope', models.JSONField(blank=True, default=list, help_text='e.g. ["students:read"] (read-only scopes).')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_grants_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_grants', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditorAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='compliance.auditoraccessgrant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditoraccessgrant',
            index=models.Index(fields=['school', '-created_at'], name='compliance__school__df2288_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoraccesslog',
            index=models.Index(fields=['grant', '-occurred_at'], name='compliance__grant_i_26a7a0_idx'),
        ),
    ]
