# Generated by Django 5.2.10 on 2026-06-07 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_auditoraccessgrant_auditoraccesslog_and_more'),
        ('schools', '0066_tenantinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRepudiationLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='Per-school monotonic chain index.')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=80)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('webauthn_presence', models.CharField(blank=True, max_length=255)),
                ('prev_hash', models.CharField(max_length=64)),
                ('integrity_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_repudiation_entries', to='schools.school')),
            ],
            options={
                'ordering': ['school_id', 'sequence'],
                'indexes': [models.Index(fields=['school', 'sequence'], name='compliance__school__c06128_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'sequence'), name='uniq_nonrepudiation_school_sequence')],
            },
        ),
    ]
