# Generated by Django 5.2.14 on 2026-06-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_nonrepudiationlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoraccessgrant',
            name='ip_allowlist',
            field=models.JSONField(blank=True, default=list, help_text='Optional geo-fence: list of IPs/CIDRs the inspector may connect from (e.g. ["203.0.113.0/24", "198.51.100.7"]). Empty = no IP restriction.'),
        ),
        migrations.AddField(
            model_name='auditoraccesslog',
            name='allowed',
            field=models.BooleanField(default=True, help_text='False when the geo-fence IP allowlist denied this access.'),
        ),
        migrations.AddField(
            model_name='auditoraccesslog',
            name='denied_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
