# Generated by Django 5.2.10 on 2026-01-19 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('messaging', 'Messaging'), ('forums', 'Forums'), ('video', 'Video'), ('documents', 'Documents')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_feature_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Feature Item',
                'verbose_name_plural': 'Portal Feature Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
