# Generated by Django 5.2.10 on 2026-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_pendingguardianinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalfeatureitem",
            name="feature",
            field=models.CharField(
                choices=[
                    ("messaging", "Messaging"),
                    ("forums", "Forums"),
                    ("video", "Video"),
                    ("documents", "Documents"),
                    ("syllabus", "Syllabus"),
                ],
                max_length=20,
            ),
        ),
    ]
