# Generated by Django 5.2.10 on 2026-01-22 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_portalfeatureitem_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fa-question-circle')", max_length=50, verbose_name='Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(help_text='Brief description for listings', max_length=500, verbose_name='Summary')),
                ('content', models.TextField(help_text='Detailed article content', verbose_name='Content')),
                ('content_html', models.TextField(blank=True, verbose_name='Content (HTML)')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20, verbose_name='Difficulty Level')),
                ('estimated_read_time', models.PositiveIntegerField(default=5, verbose_name='Estimated Read Time (minutes)')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('PUBLISHED', 'Published'), ('UPDATED', 'Updated - Pending Review'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Count')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='Unhelpful Count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Comment Count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('contributors', models.ManyToManyField(blank=True, related_name='kb_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributors')),
                ('related_articles', models.ManyToManyField(blank=True, to='portal.kbarticle', verbose_name='Related Articles')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'KB Article',
                'verbose_name_plural': 'KB Articles',
                'ordering': ['-is_featured', 'display_order', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='KBArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', models.FileField(upload_to='kb/attachments/%Y/%m/', verbose_name='File')),
                ('file_type', models.CharField(blank=True, help_text='e.g., image/png, application/pdf', max_length=50, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_screenshot', models.BooleanField(default=True, verbose_name='Is Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.kbarticle', verbose_name='Article')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'KB Attachment',
                'verbose_name_plural': 'KB Attachments',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='portal.kbcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'KB Category',
                'verbose_name_plural': 'KB Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='kbarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portal.kbcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='KBComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('is_helpful', models.BooleanField(default=False, help_text='Marked by moderators as particularly helpful', verbose_name='Is Helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portal.kbarticle', verbose_name='Article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.kbcomment', verbose_name='Parent Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'KB Comment',
                'verbose_name_plural': 'KB Comments',
                'ordering': ['-is_helpful', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('FAQ_SUBMIT', 'FAQ Submitted'), ('FAQ_APPROVE', 'FAQ Approved'), ('ARTICLE_SUBMIT', 'Article Submitted'), ('ARTICLE_APPROVE', 'Article Approved'), ('COMMENT', 'Comment Posted'), ('HELPFUL_VOTE', 'Helpful Vote'), ('EDIT', 'Edit/Update')], max_length=20, verbose_name='Contribution Type')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_contributions_log', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Contribution',
                'verbose_name_plural': 'User Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_html', models.TextField(blank=True, help_text='Rich text answer format', verbose_name='Answer (HTML)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500, verbose_name='Tags')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Count')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='Unhelpful Count')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured FAQs appear first', verbose_name='Is Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_faqs', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_faqs', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='portal.faqcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-is_featured', 'display_order', '-view_count'],
                'indexes': [models.Index(fields=['status', 'category'], name='portal_faq_status_731485_idx'), models.Index(fields=['is_featured', '-view_count'], name='portal_faq_is_feat_fc5b80_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['status', 'category'], name='portal_kbar_status_b9a195_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['is_featured', '-view_count'], name='portal_kbar_is_feat_0a8edc_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['-published_at'], name='portal_kbar_publish_3cf12c_idx'),
        ),
    ]
