# Generated by Django 5.2.10 on 2026-01-28 23:21

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_studentprofile_user'),
        ('portal', '0009_delete_guardianlinkinvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Signature'), ('SIGNED', 'Signed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_user_agent', models.CharField(blank=True, max_length=500)),
                ('signature_data', models.TextField(blank=True, help_text='Base64-encoded signature image or signature hash')),
                ('signature_hash', models.CharField(blank=True, help_text='SHA-256 hash of signature for verification', max_length=256)),
                ('signed_pdf', models.FileField(blank=True, help_text='Final signed PDF document', null=True, upload_to='portal/signed_forms/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or comments')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this signature request expires', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Signature',
                'verbose_name_plural': 'Form Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='document_type',
            field=models.CharField(choices=[('GENERAL', 'General Document'), ('FORM', 'Form (Requires Signature)'), ('POLICY', 'Policy Document'), ('HANDBOOK', 'Handbook'), ('TIMETABLE', 'Timetable'), ('ANNOUNCEMENT', 'Announcement'), ('OTHER', 'Other')], default='GENERAL', help_text='Type of document (forms require signature)', max_length=20),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a document file (PDF, Word, Excel) - max 10MB', null=True, upload_to='portal/documents/%Y/%m/', validators=[apps.accounts.validators.FileTypeValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.xls', '.xlsx'], allowed_types=['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], message='Only document files (PDF, Word, Excel) are allowed.'), apps.accounts.validators.FileSizeValidator(max_size_mb=10)]),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='requires_signature',
            field=models.BooleanField(default=False, help_text='If checked, this form requires electronic signature from parents/students'),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='visible_to_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of roles that can see this document (empty = all authenticated users)'),
        ),
        migrations.AlterField(
            model_name='portalfeatureitem',
            name='link',
            field=models.URLField(blank=True, help_text='External link (if document is hosted elsewhere)'),
        ),
        migrations.AddIndex(
            model_name='portalfeatureitem',
            index=models.Index(fields=['feature', 'is_active'], name='portal_port_feature_17bfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='portalfeatureitem',
            index=models.Index(fields=['document_type', 'requires_signature'], name='portal_port_documen_097a93_idx'),
        ),
        migrations.AddField(
            model_name='formsignature',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this signature request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signature_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsignature',
            name='form_document',
            field=models.ForeignKey(help_text='The form that requires signature', limit_choices_to={'document_type': 'FORM', 'requires_signature': True}, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='portal.portalfeatureitem'),
        ),
        migrations.AddField(
            model_name='formsignature',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent/guardian signing the form', limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsignature',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student this form is for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_signatures', to='people.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='formsignature',
            index=models.Index(fields=['form_document', 'status'], name='portal_form_form_do_1c8f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='formsignature',
            index=models.Index(fields=['student', 'status'], name='portal_form_student_b5b494_idx'),
        ),
        migrations.AddIndex(
            model_name='formsignature',
            index=models.Index(fields=['parent', 'status'], name='portal_form_parent__d5dc66_idx'),
        ),
        migrations.AddIndex(
            model_name='formsignature',
            index=models.Index(fields=['expires_at', 'status'], name='portal_form_expires_96999a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formsignature',
            unique_together={('form_document', 'student', 'parent')},
        ),
    ]
