# Generated by Django 5.2.10 on 2026-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_restore_portal_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guardianlinkinvitation',
            new_name='portal_guar_token_0dc710_idx',
            old_name='portal_guardianlinkinvitation_token_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianlinkinvitation',
            new_name='portal_guar_parent__02d620_idx',
            old_name='portal_guardianlinkinvitation_parent_email_idx',
        ),
        migrations.RenameIndex(
            model_name='guardianlinkinvitation',
            new_name='portal_guar_student_78e7bf_idx',
            old_name='portal_guardianlinkinvitation_student_id_idx',
        ),
        migrations.RenameIndex(
            model_name='parentmessage',
            new_name='portal_pare_recipie_4c957a_idx',
            old_name='portal_parentmessage_recipient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parentstudentlink',
            new_name='portal_pare_parent__68693d_idx',
            old_name='portal_parentstudentlink_parent_student_idx',
        ),
        migrations.RenameIndex(
            model_name='parentstudentlink',
            new_name='portal_pare_parent__5018d4_idx',
            old_name='portal_parentstudentlink_parent_id_idx',
        ),
        migrations.RenameIndex(
            model_name='portalauditlog',
            new_name='portal_port_parent__d7d722_idx',
            old_name='portal_portalauditlog_parent_action_idx',
        ),
        migrations.RenameIndex(
            model_name='portalauditlog',
            new_name='portal_port_timesta_fafa57_idx',
            old_name='portal_portalauditlog_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portal_port_parent__95567c_idx',
            old_name='portal_portalnotification_parent_read_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portal_port_student_fe7347_idx',
            old_name='portal_portalnotification_student_id_idx',
        ),
        migrations.RenameIndex(
            model_name='portalsession',
            new_name='portal_port_parent__0abaeb_idx',
            old_name='portal_portalsession_parent_active_idx',
        ),
        migrations.RenameIndex(
            model_name='portalsession',
            new_name='portal_port_session_296777_idx',
            old_name='portal_portalsession_session_token_idx',
        ),
        migrations.AlterField(
            model_name='guardianlinkinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('read', 'Read'), ('archived', 'Archived')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentstudentlink',
            name='access_level',
            field=models.CharField(choices=[('full', 'Full Access'), ('limited', 'Limited Access'), ('read_only', 'Read Only')], default='limited', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentstudentlink',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('foster_parent', 'Foster Parent'), ('relative', 'Relative')], default='parent', max_length=20),
        ),
        migrations.AlterField(
            model_name='portalauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_grades', 'View Grades'), ('download_report', 'Download Report'), ('send_message', 'Send Message'), ('update_preferences', 'Update Preferences')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portalfeatureaccess',
            name='feature',
            field=models.CharField(choices=[('view_grades', 'View Grades'), ('view_attendance', 'View Attendance'), ('view_fees', 'View Fees'), ('download_reports', 'Download Reports'), ('message_teacher', 'Message Teachers'), ('register_events', 'Register for Events'), ('update_profile', 'Update Profile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='notification_type',
            field=models.CharField(choices=[('grade', 'Grade Update'), ('attendance', 'Attendance Alert'), ('fee', 'Fee Due'), ('behavior', 'Behavior Report'), ('announcement', 'Announcement'), ('event', 'Event Notice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portalpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20),
        ),
    ]
