# Generated by Django 5.2.10 on 2026-02-11 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_attendance_timestamps'),
        ('people', '0023_add_badge_scan_event'),
        ('portal', '0017_add_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierDeTexteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Date of the lesson')),
                ('lesson_topic_code', models.CharField(blank=True, help_text='Topic code from syllabus or national progression', max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('objectives', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_summary', models.TextField(blank=True)),
                ('practical_application', models.BooleanField(default=False)),
                ('integration_activity', models.BooleanField(default=False)),
                ('attendance_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VISED', 'Vised'), ('REVISIONS_REQUESTED', 'Revisions requested')], default='DRAFT', max_length=24)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_assignment', models.ForeignKey(blank=True, help_text='Class and subject (from schedule).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cahier_entries', to='academics.subjectassignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_entries', to='people.teacherprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vised_cahier_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cahier de Texte entry',
                'verbose_name_plural': 'Cahier de Texte entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', '-entry_date'], name='portal_cahi_teacher_40a01b_idx'), models.Index(fields=['status'], name='portal_cahi_status_58d852_idx')],
            },
        ),
    ]
