# Generated by Django 5.2.10 on 2026-03-01 20:34
# Idempotent for tenant migrations (PostgreSQL duplicate_column).

from django.conf import settings
from django.db import migrations, models


def add_kb_columns_if_missing(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        table = "portal_kbarticle"
        if connection.vendor == "postgresql":
            for col, typ in [
                ("country_code", "varchar(2) NOT NULL DEFAULT ''"),
                ("education_type", "varchar(80) NOT NULL DEFAULT ''"),
                ("plan_tier", "varchar(40) NOT NULL DEFAULT ''"),
            ]:
                cursor.execute(f"""
                    DO $$
                    BEGIN
                        ALTER TABLE {table} ADD COLUMN {col} {typ};
                    EXCEPTION WHEN duplicate_column THEN NULL;
                    END $$;
                """)
            cursor.execute("CREATE INDEX IF NOT EXISTS portal_kbar_country_10552f_idx ON portal_kbarticle (country_code)")
        else:
            cursor.execute(f"PRAGMA table_info({table})")
            cols = [row[1] for row in cursor.fetchall()]
            if "country_code" not in cols:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN country_code varchar(2) NOT NULL DEFAULT ''")
            if "education_type" not in cols:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN education_type varchar(80) NOT NULL DEFAULT ''")
            if "plan_tier" not in cols:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN plan_tier varchar(40) NOT NULL DEFAULT ''")
            cursor.execute("CREATE INDEX IF NOT EXISTS portal_kbar_country_10552f_idx ON portal_kbarticle (country_code)")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_add_lesson_plan_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='kbarticle',
                    name='country_code',
                    field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 (e.g. CM, CA). Blank = global.', max_length=2, verbose_name='Country code'),
                ),
                migrations.AddField(
                    model_name='kbarticle',
                    name='education_type',
                    field=models.CharField(blank=True, help_text='E.g. CAMEROON_K12, CANADA_K12 for region-aware filtering.', max_length=80, verbose_name='Education type'),
                ),
                migrations.AddField(
                    model_name='kbarticle',
                    name='plan_tier',
                    field=models.CharField(blank=True, help_text='Optional: restrict to plan slug (e.g. powerhouse).', max_length=40, verbose_name='Plan tier'),
                ),
                migrations.AddIndex(
                    model_name='kbarticle',
                    index=models.Index(fields=['country_code'], name='portal_kbar_country_10552f_idx'),
                ),
            ],
            database_operations=[migrations.RunPython(add_kb_columns_if_missing, noop)],
        ),
    ]
