# Generated by Django 5.2.10 on 2026-03-06 17:19

import apps.accounts.validators
from django.db import migrations, models


def _portal_upload_to(instance, filename, subpath, school_id):
    """Build tenant-prefixed path for portal uploads (Section 25.3).

    Inlined from ``apps.portal.models._portal_upload_to`` for migration
    historical-state safety.
    """
    if school_id is None:
        return f"tenant_uploads/portal/{subpath}/{filename}"
    return f"tenants/{school_id}/portal/{subpath}/{filename}"


def _justification_upload_to(instance, filename):
    """Inlined from apps.portal.models._justification_upload_to."""
    school_id = getattr(getattr(instance, "student", None), "school_id", None)
    return _portal_upload_to(instance, filename, "justifications", school_id)


def _form_signature_upload_to(instance, filename):
    """Inlined from apps.portal.models._form_signature_upload_to."""
    school_id = getattr(getattr(instance, "student", None), "school_id", None)
    return _portal_upload_to(instance, filename, "signed_forms", school_id)


def _lesson_plan_upload_to(instance, filename):
    """Inlined from apps.portal.models._lesson_plan_upload_to."""
    school_id = getattr(getattr(instance, "teacher", None), "school_id", None)
    return _portal_upload_to(instance, filename, "lesson_notes", school_id)


def _lesson_plan_attachment_upload_to(instance, filename):
    """Inlined from apps.portal.models._lesson_plan_attachment_upload_to."""
    lp = getattr(instance, "lesson_plan", None)
    school_id = getattr(getattr(lp, "teacher", None), "school_id", None) if lp else None
    return _portal_upload_to(instance, filename, "lesson_notes/resources", school_id)


def _photo_upload_token_upload_to(instance, filename):
    """Inlined from apps.portal.models._photo_upload_token_upload_to."""
    school_id = getattr(
        getattr(instance, "student", None), "school_id", None
    ) or getattr(getattr(instance, "teacher", None), "school_id", None)
    return _portal_upload_to(instance, filename, "photo_upload", school_id)


def _training_entry_upload_to(instance, filename):
    """Inlined from apps.portal.models._training_entry_upload_to."""
    school_id = getattr(getattr(instance, "teacher", None), "school_id", None)
    return _portal_upload_to(instance, filename, "training", school_id)


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0021_kb_regional_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancejustification",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=_justification_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formsignature",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                help_text="Final signed PDF document",
                null=True,
                upload_to=_form_signature_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="file",
            field=models.FileField(
                upload_to=_lesson_plan_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lessonplanattachment",
            name="file",
            field=models.FileField(
                upload_to=_lesson_plan_attachment_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="photouploadtoken",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=_photo_upload_token_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="teachertrainingentry",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=_training_entry_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".xls",
                            ".xlsx",
                            ".odt",
                            ".ods",
                        ],
                        allowed_types=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/vnd.oasis.opendocument.text",
                            "application/vnd.oasis.opendocument.spreadsheet",
                        ],
                        message="Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=10),
                ],
            ),
        ),
    ]
