# Generated by Django 5.2.10 on 2026-03-06 18:30
# Made idempotent for tenant migrations: add school_id only if missing (PostgreSQL duplicate_column).

import apps.accounts.validators
import apps.portal.models
import django.db.models.deletion
from django.db import migrations, models


def add_school_id_if_missing(apps, schema_editor):
    """Add school_id to portal_portalfeatureitem; no-op if already exists."""
    from django.db import connection

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute("""
                DO $$
                BEGIN
                    ALTER TABLE portal_portalfeatureitem
                    ADD COLUMN school_id uuid NULL REFERENCES schools_school(id) ON DELETE CASCADE;
                EXCEPTION WHEN duplicate_column THEN NULL;
                END $$;
            """)
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS portal_portalfeatureitem_school_id_idx ON portal_portalfeatureitem (school_id)"
            )
        else:
            cursor.execute("PRAGMA table_info(portal_portalfeatureitem)")
            cols = [row[1] for row in cursor.fetchall()]
            if "school_id" not in cols:
                cursor.execute(
                    "ALTER TABLE portal_portalfeatureitem ADD COLUMN school_id integer NULL REFERENCES schools_school(id) ON DELETE CASCADE"
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_tenant_upload_to_lesson_training_justification_photo_signature'),
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='portalfeatureitem',
                    name='school',
                    field=models.ForeignKey(blank=True, help_text='Tenant scope for document library (Section 25.3); set from request.school on save.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_feature_items', to='schools.school'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_school_id_if_missing, noop_reverse),
            ],
        ),
        migrations.AlterField(
            model_name='portalfeatureitem',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, Word, Excel, or LibreOffice ODT/ODS) - max 10MB', null=True, upload_to=apps.portal.models._portal_feature_item_file_upload_to, validators=[apps.accounts.validators.FileTypeValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.odt', '.ods'], allowed_types=['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet'], message='Only document files (PDF, Word, Excel, or LibreOffice ODT/ODS) are allowed.'), apps.accounts.validators.FileSizeValidator(max_size_mb=10)]),
        ),
    ]
