# Generated by Django 5.2.10
# Idempotent: add target_roles to KBCategory only if missing (fixes seed_kb_articles NOT NULL on Render).

from django.db import migrations, models


def add_target_roles_if_missing(apps, schema_editor):
    """Add target_roles to portal_kbcategory; no-op if column already exists."""
    from django.db import connection

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute("""
                DO $$
                BEGIN
                    ALTER TABLE portal_kbcategory
                    ADD COLUMN target_roles JSONB NOT NULL DEFAULT '[]'::jsonb;
                EXCEPTION WHEN duplicate_column THEN NULL;
                END $$;
            """)
        else:
            # SQLite: add if not exists via table_info check
            cursor.execute("PRAGMA table_info(portal_kbcategory)")
            cols = [row[1] for row in cursor.fetchall()]
            if "target_roles" not in cols:
                cursor.execute(
                    "ALTER TABLE portal_kbcategory ADD COLUMN target_roles TEXT NOT NULL DEFAULT '[]'"
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0023_portal_feature_item_school_tenant_upload"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="kbcategory",
                    name="target_roles",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of role codes that can see this category (empty = all).",
                        verbose_name="Target roles",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_target_roles_if_missing, noop_reverse),
            ],
        ),
    ]
