# Generated by Django 5.2.10 on 2026-03-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_document_library_metadata(apps, schema_editor):
    PortalFeatureItem = apps.get_model("portal", "PortalFeatureItem")

    for document in PortalFeatureItem.objects.all().iterator():
        if getattr(document, "feature", "") != "documents":
            continue
        lifecycle_state = "approved" if bool(document.is_active and (document.file or document.link)) else "draft"
        values = [
            getattr(document, "title", ""),
            getattr(document, "description", ""),
            getattr(document, "document_type", ""),
            lifecycle_state,
            getattr(document, "file", ""),
            getattr(document, "link", ""),
        ]
        document.lifecycle_state = lifecycle_state
        document.search_index = " ".join(str(value).strip() for value in values if str(value).strip()).lower()
        if lifecycle_state == "approved" and document.published_at is None:
            document.published_at = document.created_at
        document.save(update_fields=["lifecycle_state", "search_index", "published_at"])


def noop(_apps, _schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_documentpack'),
        ('portal', '0025_kbarticle_target_roles'),
        ('schools', '0034_remove_biometricdevice_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalfeatureitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='document_pack',
            field=models.ForeignKey(blank=True, help_text='Optional document pack that governs lifecycle states and retention rules.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='packages.documentpack'),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='lifecycle_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('archived', 'Archived'), ('retracted', 'Retracted')], db_index=True, default='draft', help_text='Document lifecycle state (draft, review, approved, archived, retracted).', max_length=20),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='retention_review_at',
            field=models.DateField(blank=True, help_text='Next retention review date derived from the document pack rule, when configured.', null=True),
        ),
        migrations.AddField(
            model_name='portalfeatureitem',
            name='search_index',
            field=models.TextField(blank=True, default='', help_text='Precomputed search text for title, description, category, lifecycle, and pack metadata.'),
        ),
        migrations.AddIndex(
            model_name='portalfeatureitem',
            index=models.Index(fields=['lifecycle_state', 'document_pack'], name='portal_port_lifecyc_1037f0_idx'),
        ),
        migrations.RunPython(backfill_document_library_metadata, noop),
    ]
