# Generated by Django 5.2.10 on 2026-03-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_hosted_office_document'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faq',
            new_name='portal_faq_help_au_f3a67d_idx',
            old_name='portal_faq_help_audience_status_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='portal_faq_country_419d77_idx',
            old_name='portal_faq_country_code_idx',
        ),
        migrations.RenameIndex(
            model_name='hostedofficedocument',
            new_name='portal_host_help_au_8e5277_idx',
            old_name='portal_host_help_aud_0f446f_idx',
        ),
        migrations.RenameIndex(
            model_name='hostedofficedocument',
            new_name='portal_host_school__155f02_idx',
            old_name='portal_host_school_i_86558e_idx',
        ),
        migrations.RenameIndex(
            model_name='kbarticle',
            new_name='portal_kbar_help_au_5bf672_idx',
            old_name='portal_kbarticle_help_audience_status_idx',
        ),
    ]
