# Generated by Django 5.2.10 on 2026-05-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_kb_target_roles'),
        ('portal', '0029_rename_portal_faq_help_audience_status_idx_portal_faq_help_au_f3a67d_idx_and_more'),
    ]

    operations = [
    ]
