# Generated by Django 5.2.10 on 2026-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_merge_20260511_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarticle',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of role codes that can see this article (empty = all).', verbose_name='Target roles'),
        ),
        migrations.AlterField(
            model_name='kbcategory',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of role codes that can see this category (empty = all).', verbose_name='Target roles'),
        ),
    ]
