# Generated by Django 5.2.10 on 2026-05-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_kbarticle_school_global_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kbarticle',
            new_name='portal_kbar_school__4fc3ce_idx',
            old_name='portal_kbar_school_glob_stat_idx',
        ),
    ]
