# Generated by Django 5.2.10 on 2026-05-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_kbarticle_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbarticle',
            name='locale_group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared UUID linking translated article variants (batch 1350).', max_length=36, verbose_name='Locale group'),
        ),
        migrations.AddField(
            model_name='kbarticle',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='portal.kbarticle', verbose_name='Translation of'),
        ),
    ]
