# Generated by Django 5.2.10 on 2026-05-20 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_help_center_wave2_1346_1353'),
        ('schools', '0051_add_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_categories', to='schools.school')),
            ],
            options={
                'verbose_name': 'Forum category',
                'verbose_name_plural': 'Forum categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics_authored', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='portal.communityforumcategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to='schools.school')),
            ],
            options={
                'verbose_name': 'Forum topic',
                'verbose_name_plural': 'Forum topics',
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_staff_answer', models.BooleanField(default=False, help_text='Marked when posted by school staff (moderator highlight).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_replies_authored', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.communityforumtopic')),
            ],
            options={
                'verbose_name': 'Forum reply',
                'verbose_name_plural': 'Forum replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communityforumcategory',
            index=models.Index(fields=['school', 'is_active', 'display_order'], name='portal_comm_school__c55489_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityforumcategory',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='uniq_forum_category_per_school'),
        ),
        migrations.AddIndex(
            model_name='communityforumtopic',
            index=models.Index(fields=['school', 'last_activity_at'], name='portal_comm_school__4a90d5_idx'),
        ),
        migrations.AddIndex(
            model_name='communityforumtopic',
            index=models.Index(fields=['school', 'category', 'last_activity_at'], name='portal_comm_school__4588d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityforumtopic',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='uniq_forum_topic_slug_per_school'),
        ),
        migrations.AddIndex(
            model_name='communityforumreply',
            index=models.Index(fields=['topic', 'created_at'], name='portal_comm_topic_i_38a6e3_idx'),
        ),
    ]
