# Generated by Django 5.2.10 on 2026-05-15 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('problem_statement', models.TextField()),
                ('proposed_solution', models.TextField(blank=True)),
                ('current_workaround', models.TextField(blank=True)),
                ('affected_roles', models.JSONField(blank=True, default=list)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('school_type', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, db_index=True, max_length=80)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('blocking', 'Blocking adoption')], default='medium', max_length=20)),
                ('urgency', models.CharField(choices=[('someday', 'Someday'), ('soon', 'Soon'), ('this_term', 'This term'), ('immediate', 'Immediate')], default='soon', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triaging', 'Triaging'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_discovery', 'In discovery'), ('in_development', 'In development'), ('in_pilot', 'In pilot'), ('released', 'Released'), ('declined', 'Declined'), ('duplicate', 'Duplicate'), ('needs_more_info', 'Needs more info'), ('external_blocked', 'External blocked')], db_index=True, default='submitted', max_length=32)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('roadmap_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('pilot_interest', models.BooleanField(default=False)),
                ('external_blocker', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feedback.featurerequest')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='schools.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weighted_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, max_length=32)),
                ('category', models.CharField(choices=[('general', 'General feedback'), ('bug', 'Bug report'), ('feature', 'Feature request'), ('workflow', 'Workflow pain point'), ('accessibility', 'Accessibility issue'), ('training', 'Training/support request'), ('billing', 'Billing/payment issue'), ('data_import', 'Data/import issue'), ('mobile', 'Mobile usability issue'), ('offline_sync', 'Offline sync issue'), ('communication', 'Communication issue'), ('login', 'Login issue'), ('suggestion', 'Suggestion')], db_index=True, default='general', max_length=32)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('route', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('blocked', 'Blocked')], default='neutral', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('needs_info', 'Needs info'), ('accepted', 'Accepted'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('released', 'Released'), ('closed', 'Closed'), ('declined', 'Declined'), ('duplicate', 'Duplicate'), ('external_blocked', 'External blocked')], db_index=True, default='new', max_length=32)),
                ('privacy_level', models.CharField(choices=[('school_private', 'Private to school'), ('rmc_private', 'Visible to RunMyCampus only'), ('anon_product', 'Share anonymously with product team'), ('public_candidate', 'Public roadmap candidate')], db_index=True, default='school_private', max_length=32)),
                ('contact_preference', models.CharField(blank=True, max_length=80)),
                ('browser_context', models.JSONField(blank=True, default=dict)),
                ('device_context', models.JSONField(blank=True, default=dict)),
                ('current_action_context', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('moderation_required', models.BooleanField(default=False)),
                ('visible_to_school', models.BooleanField(default=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feedback.feedbacksubmission')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.featurerequest')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbacksubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback/')),
                ('description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbacksubmission')),
            ],
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='source_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_feature_requests', to='feedback.feedbacksubmission'),
        ),
        migrations.CreateModel(
            name='FeedbackTriageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_events', to='feedback.featurerequest')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_events', to='feedback.feedbacksubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.featurerequest')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('problem', models.TextField()),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('pilot', 'Pilot'), ('released', 'Released'), ('declined', 'Declined'), ('external_blocked', 'External Blocked')], db_index=True, default='under_review', max_length=32)),
                ('target_module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('affected_roles', models.JSONField(blank=True, default=list)),
                ('source_feedback_count', models.PositiveIntegerField(default=0)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('public_visibility', models.BooleanField(db_index=True, default=False)),
                ('tenant_visibility', models.BooleanField(db_index=True, default=True)),
                ('release_target', models.CharField(blank=True, max_length=80)),
                ('expected_value', models.TextField(blank=True)),
                ('external_blocker', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_requests', models.ManyToManyField(blank=True, related_name='roadmap_items', to='feedback.featurerequest')),
                ('pilot_schools', models.ManyToManyField(blank=True, related_name='roadmap_pilots', to='schools.school')),
            ],
            options={
                'ordering': ['status', '-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('notify_submitters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_requests', models.ManyToManyField(blank=True, related_name='release_notes', to='feedback.featurerequest')),
                ('roadmap_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_notes', to='feedback.roadmapitem')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, max_length=32)),
                ('survey_type', models.CharField(choices=[('csat', 'CSAT'), ('nps', 'NPS'), ('ces', 'Customer Effort Score'), ('workflow', 'Workflow pulse')], db_index=True, max_length=20)),
                ('workflow', models.CharField(blank=True, db_index=True, max_length=80)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('browser_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['school', 'status', '-created_at'], name='feedback_fe_school__1f7fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['role', 'category', 'severity'], name='feedback_fe_role_99fbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['school', 'status', '-created_at'], name='feedback_fe_school__e775f1_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['module', 'status'], name='feedback_fe_module_982683_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvote',
            unique_together={('feature_request', 'user')},
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['school', 'survey_type', '-created_at'], name='feedback_su_school__bb0eb4_idx'),
        ),
    ]
