# Generated by Django 5.2.10 on 2026-05-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('portal', '0032_alter_attendancejustification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksubmission',
            name='related_contact_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='related_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to='portal.faq'),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='related_kb_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to='portal.kbarticle'),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='related_support_ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='source_channel',
            field=models.CharField(choices=[('in_app', 'In-app feedback center'), ('contextual', 'Contextual page widget'), ('help_center', 'Help center'), ('kb_article', 'Knowledge base article'), ('faq', 'FAQ'), ('contact_us', 'Contact us'), ('support_ticket', 'Support ticket')], db_index=True, default='in_app', max_length=32),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='support_escalated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
