# Generated by Django 5.2.10 on 2026-05-20 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_support_ai_review_note'),
        ('portal', '0037_help_center_wave2_1346_1353'),
        ('schools', '0051_add_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportaiinteractionreview',
            name='kb_draft_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitl_reviews', to='portal.kbarticle'),
        ),
        migrations.CreateModel(
            name='SupportAISessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('task_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('thumbs', models.CharField(blank=True, max_length=8)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_url', models.CharField(blank=True, max_length=500)),
                ('is_operator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_ai_session_ratings', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ai_session_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
