# Generated by Django 5.2.10 on 2026-03-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationapprovalqueue',
            name='schema_name',
            field=models.CharField(blank=True, db_index=True, max_length=63),
        ),
        migrations.AddField(
            model_name='automationapprovalqueue',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_approval_queue', to='schools.school'),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='schema_name',
            field=models.CharField(blank=True, db_index=True, max_length=63),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_execution_logs', to='schools.school'),
        ),
    ]
