# Generated by Django 5.2.10 on 2026-03-18 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_rename_automation_quarantine_school_domain_status_idx_automation__school__f101f6_idx_and_more'),
        ('schools', '0039_rename_schools_te_school_created_idx_schools_ten_school__c5fe28_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='exception_ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='exception_ack_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_exception_acks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='exception_ack_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='exception_ack_status',
            field=models.CharField(choices=[('NA', 'N/A'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='NA', max_length=16),
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['exception_ack_status', '-started_at'], name='automation__excepti_bb5d43_idx'),
        ),
    ]
