# Generated by Django 5.2.10 on 2026-04-30 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_backfill_migrationrun_exception_ack'),
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(choices=[('attendance_marked', 'Attendance marked'), ('payment_received', 'Payment received'), ('student_created', 'Student added'), ('report_generated', 'Report generated')], db_index=True, max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_workflows', to='schools.school')),
            ],
            options={
                'verbose_name': 'Visual workflow',
                'verbose_name_plural': 'Visual workflows',
                'ordering': ['school_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Stable client id from the visual builder.', max_length=64)),
                ('kind', models.CharField(choices=[('trigger', 'Trigger'), ('condition', 'Condition'), ('action', 'Action'), ('delay', 'Delay')], db_index=True, max_length=16)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Kind-specific payload (conditions, action params, delay seconds).')),
                ('position', models.JSONField(blank=True, default=dict, help_text='Optional {x,y} for canvas persistence.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow')),
            ],
            options={
                'ordering': ['workflow_id', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.workflow')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='automation.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='automation.workflownode')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(blank=True, max_length=48)),
                ('conditions_passed', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('actions_run', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='success', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='automation.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['school', 'trigger_event', 'status'], name='automation__school__dae5b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflownode',
            constraint=models.UniqueConstraint(fields=('workflow', 'external_id'), name='automation_workflownode_unique_external'),
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['workflow', 'source'], name='automation__workflo_d849dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['workflow', 'target'], name='automation__workflo_1fb2aa_idx'),
        ),
    ]
