# Generated by Django — attendance_saved visual workflow trigger (platform loop).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0014_visual_workflow_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("attendance_marked", "Attendance marked"),
                    ("attendance_saved", "Attendance saved (platform)"),
                    ("payment_received", "Payment received"),
                    ("student_created", "Student added"),
                    ("report_generated", "Report generated"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
    ]
