# Generated by Django 5.2.10 on 2026-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_workflow_triggers_expanded_and_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='trigger_event',
            field=models.CharField(choices=[('attendance_marked', 'Attendance marked'), ('attendance_saved', 'Attendance saved (platform)'), ('marks_submitted', 'Marks submitted'), ('payment_received', 'Payment received'), ('payment_success', 'Payment succeeded'), ('payment_failed', 'Payment failed'), ('student_created', 'Student added'), ('report_generated', 'Report generated'), ('student_risk_detected', 'Student risk detected'), ('app_installed', 'Marketplace app installed')], db_index=True, max_length=48),
        ),
    ]
