# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0017_alter_workflow_trigger_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("attendance_marked", "Attendance marked"),
                    ("attendance_saved", "Attendance saved (platform)"),
                    ("marks_submitted", "Marks submitted"),
                    ("payment_received", "Payment received"),
                    ("payment_success", "Payment succeeded"),
                    ("payment_failed", "Payment failed"),
                    ("student_created", "Student added"),
                    ("report_generated", "Report generated"),
                    ("student_risk_detected", "Student risk detected"),
                    ("app_installed", "Marketplace app installed"),
                    ("offline_action_conflict", "Offline sync action conflict"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
    ]
