# Generated by Django 5.2.10 on 2026-05-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_workflow_trigger_offline_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('graph_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen {nodes: [...], edges: [...]} payload at publish time.')),
                ('trigger_event', models.CharField(blank=True, max_length=48)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='automation.workflow')),
            ],
            options={
                'ordering': ['workflow', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='workflowrunlog',
            name='workflow_version',
            field=models.ForeignKey(blank=True, help_text='Move 2: pin run to the version that was current at trigger time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_logs', to='automation.workflowversion'),
        ),
        migrations.CreateModel(
            name='WorkflowStepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('condition_evaluated', 'Condition evaluated'), ('action_started', 'Action started'), ('action_succeeded', 'Action succeeded'), ('action_failed', 'Action failed'), ('delay_scheduled', 'Delay scheduled'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, max_length=24)),
                ('node_external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.workflowrunlog')),
            ],
            options={
                'ordering': ['run', 'sequence_number'],
                'indexes': [models.Index(fields=['run', 'event_type'], name='auto_wfe_run_type_idx')],
                'unique_together': {('run', 'sequence_number')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'is_current'], name='auto_wfv_wf_cur_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version_number')},
        ),
    ]
