# Generated by Django 5.2.10 on 2026-03-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0005_alter_marketplaceapp_kind'),
        ('siteconfig', '0147_sitesettings_compliance_profile_pointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAuditLog',
            fields=[
            ],
            options={
                'verbose_name': 'App Audit Log',
                'verbose_name_plural': 'App Audit Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.appauditlog',),
        ),
        migrations.CreateModel(
            name='AppBillingLedger',
            fields=[
            ],
            options={
                'verbose_name': 'App Billing Ledger',
                'verbose_name_plural': 'App Billing Ledger',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.appbillingledger',),
        ),
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
            ],
            options={
                'verbose_name': 'App Installation',
                'verbose_name_plural': 'App Installations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.appinstallation',),
        ),
        migrations.CreateModel(
            name='AppScope',
            fields=[
            ],
            options={
                'verbose_name': 'App Scope',
                'verbose_name_plural': 'App Scopes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.appscope',),
        ),
        migrations.CreateModel(
            name='AppVersionCompat',
            fields=[
            ],
            options={
                'verbose_name': 'App Version Compatibility',
                'verbose_name_plural': 'App Version Compatibility',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.appversioncompat',),
        ),
        migrations.CreateModel(
            name='CapabilityRegistry',
            fields=[
            ],
            options={
                'verbose_name': 'Capability (registry)',
                'verbose_name_plural': 'Capabilities (registry)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.capabilityregistry',),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
            ],
            options={
                'verbose_name': 'integration',
                'verbose_name_plural': 'integrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.integration',),
        ),
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace App',
                'verbose_name_plural': 'Marketplace Apps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.marketplaceapp',),
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace listing',
                'verbose_name_plural': 'Marketplace listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.marketplacelisting',),
        ),
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace review',
                'verbose_name_plural': 'Marketplace reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.marketplacereview',),
        ),
        migrations.CreateModel(
            name='PublisherOrganization',
            fields=[
            ],
            options={
                'verbose_name': 'Publisher organization',
                'verbose_name_plural': 'Publisher organizations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.publisherorganization',),
        ),
        migrations.CreateModel(
            name='ScopeGrant',
            fields=[
            ],
            options={
                'verbose_name': 'Scope Grant',
                'verbose_name_plural': 'Scope Grants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.scopegrant',),
        ),
        migrations.CreateModel(
            name='ServiceIntegration',
            fields=[
            ],
            options={
                'verbose_name': 'Service integration',
                'verbose_name_plural': 'Service integrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('siteconfig.serviceintegration',),
        ),
    ]
