# Generated by Django 5.2.10 on 2026-05-29 15:32

import apps.accounts.legacy_hashes.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_marketplace', '0001_proxy_owner_models'),
        ('schools', '0062_school_institution_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSConnectorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('canvas', 'Canvas LMS'), ('moodle', 'Moodle'), ('google_classroom', 'Google Classroom')], db_index=True, max_length=24)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', apps.accounts.legacy_hashes.encryption.EncryptedCharField(blank=True, default='', max_length=2048)),
                ('refresh_token', apps.accounts.legacy_hashes.encryption.EncryptedCharField(blank=True, default='', max_length=2048)),
                ('scope', models.CharField(blank=True, default='', max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_connector_tokens', to='schools.school')),
            ],
            options={
                'verbose_name': 'LMS connector token',
                'verbose_name_plural': 'LMS connector tokens',
                'ordering': ('school_id', 'provider'),
                'unique_together': {('school', 'provider')},
            },
        ),
    ]
