# Generated by Django 5.2.10 on 2026-05-29 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_marketplace', '0002_lms_connector_token'),
        ('schools', '0062_school_institution_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSPushGradeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=24)),
                ('course_id', models.CharField(max_length=128)),
                ('assignment_id', models.CharField(max_length=128)),
                ('user_hash', models.CharField(db_index=True, help_text='SHA-256[:16] of the LMS user_id (PII-free).', max_length=32)),
                ('score_text', models.CharField(blank=True, default='', max_length=16)),
                ('ok', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(default=0)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('actor_user_id', models.CharField(blank=True, default='', help_text='Operator user pk who triggered the push (string for UUID/int compatibility).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_push_grade_audits', to='schools.school')),
            ],
            options={
                'verbose_name': 'LMS push-grade audit',
                'verbose_name_plural': 'LMS push-grade audits',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', 'provider'], name='integration_school__e61228_idx'), models.Index(fields=['ok', 'created_at'], name='integration_ok_325f25_idx')],
            },
        ),
    ]
