# Generated by Django 5.2.10 on 2026-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_marketplace', '0004_lms_diag_action_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payload_b64', models.TextField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_reason', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('replayed', 'replayed'), ('expired', 'expired'), ('discarded', 'discarded')], db_index=True, default='pending', max_length=20)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, default='', help_text='Cross-tenant safety marker — replay endpoint refuses cross-schema replay.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Dead Letter',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', 'created_at'], name='dlq_psc_idx'), models.Index(fields=['status', 'expires_at'], name='dlq_se_idx')],
            },
        ),
    ]
