# Generated by Django 5.2.10 on 2026-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_marketplace', '0005_webhookdeadletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRetentionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=64)),
                ('target_table', models.CharField(choices=[('lms_diag_action_audit', 'LMSDiagActionAudit'), ('lms_push_grade_audit', 'LMSPushGradeAudit'), ('lms_token_rotation_chain', 'LMSTokenRotationChain'), ('webhook_dead_letter', 'WebhookDeadLetter')], db_index=True, max_length=64)),
                ('retention_years', models.PositiveIntegerField(help_text='0 = retain forever. Otherwise rows older than this are eligible for sweep.')),
                ('reason', models.CharField(blank=True, default='', help_text='Why this override exists (e.g. state law cite).', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by_actor_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Tenant Retention Override',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'target_table'], name='rto_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_schema', 'target_table'), name='uniq_retention_override_per_tenant_table')],
            },
        ),
    ]
