# Generated by Django 5.2.10 on 2026-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0003_substitutecover'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='substitutecover',
            new_name='schools_sub_school__c81209_idx',
            old_name='schools_sub_school_i_7f8a9b_idx',
        ),
        migrations.AlterField(
            model_name='substitutecover',
            name='period_label',
            field=models.CharField(blank=True, help_text='e.g. Period 3, Full day', max_length=80),
        ),
    ]
