# Generated by Django 5.2.10 on 2026-03-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0005_visitorcheckin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitorcheckin',
            new_name='schools_vis_school__6167ff_idx',
            old_name='schools_vis_school_i_idx',
        ),
        migrations.AlterField(
            model_name='visitorcheckin',
            name='host_contact',
            field=models.CharField(blank=True, help_text='Person or office being visited', max_length=255),
        ),
    ]
