# Generated by Django 5.2.10 on 2026-03-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0007_maintenancerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenancerequest',
            new_name='schools_mai_school__7c78a2_idx',
            old_name='schools_mai_school_i_idx',
        ),
    ]
