# Generated by Django 5.2.10 on 2026-05-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0018_micro_friction_persistence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='substitutehandoverpacketrecord',
            new_name='schoolops_s_school__e39c44_idx',
            old_name='schoolops_su_school__a1b2c3_idx',
        ),
    ]
