# Generated by Django 5.2.10 on 2026-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0019_rename_micro_friction_handover_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_hash', models.CharField(db_index=True, help_text='sha256(recipient_email.lower())[:12] — never the raw address.', max_length=12, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('unsubscribe', 'Marketing unsubscribe'), ('manual', 'Manual operator block')], default='hard_bounce', help_text='Why this recipient is suppressed.', max_length=24)),
                ('source', models.CharField(blank=True, default='', help_text="Coarse origin: 'webhook' | 'send_time' | 'unsubscribe' | 'operator'.", max_length=48)),
                ('detail', models.CharField(blank=True, default='', help_text='Optional non-PII detail (e.g. provider bounce label, vendor code).', max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='True = suppress sends. False = lifted (re-subscribe / operator clear).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suppressed email recipient',
                'verbose_name_plural': 'Suppressed email recipients',
                'db_table': 'schoolops_email_suppressed_recipient',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['active', 'reason'], name='schoolops_e_active_5f2997_idx')],
            },
        ),
    ]
