# Generated by Django 5.2.10 on 2026-06-03 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0020_suppressedrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildeliveryevent',
            name='message_id_prefix',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Local-part of the outbound Message-ID header (sha-ish token before '@', angle-brackets stripped). Correlation key for provider bounce webhooks. NEVER contains PII.", max_length=64),
        ),
        migrations.CreateModel(
            name='EmailDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUIDv4 primary key.', primary_key=True, serialize=False)),
                ('to_hash', models.CharField(db_index=True, help_text='sha256(recipient_email.lower())[:12] — never the raw address.', max_length=12)),
                ('subject_prefix', models.CharField(blank=True, default='', help_text='Redacted 64-char subject snapshot (display only).', max_length=64)),
                ('priority', models.CharField(default='transactional', help_text='Send priority class carried over from the original send.', max_length=24)),
                ('payload_encrypted', models.TextField(help_text='Fernet-encrypted JSON of the full resend payload (subject, body, html_body, recipients, reply_to, from_email, headers, school_id). Decrypted ONLY transiently inside the redrive worker.')),
                ('error_kind', models.CharField(blank=True, default='', help_text='Coarse error_kind from the failing send that parked this row.', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='SMTP attempts the original send made before being parked.')),
                ('status', models.CharField(choices=[('pending', 'Pending redrive'), ('redriven', 'Redriven (delivered)'), ('exhausted', 'Redrive attempts exhausted'), ('abandoned', 'Abandoned by operator')], db_index=True, default='pending', help_text='Lifecycle: pending → redriven | exhausted | abandoned.', max_length=16)),
                ('redrive_count', models.PositiveSmallIntegerField(default=0, help_text='Number of redrive attempts made by the worker so far.')),
                ('last_error_kind', models.CharField(blank=True, default='', help_text='error_kind from the most recent redrive attempt.', max_length=64)),
                ('delivery_event_id', models.CharField(blank=True, default='', help_text='UUID of the EmailDeliveryEvent row for the original failure.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redriven_at', models.DateTimeField(blank=True, help_text='Set when the row reached a terminal redriven/exhausted state.', null=True)),
            ],
            options={
                'verbose_name': 'Email dead letter',
                'verbose_name_plural': 'Email dead letters',
                'db_table': 'schoolops_email_dead_letter',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='schoolops_e_status_745df2_idx')],
            },
        ),
    ]
