# Generated by Django 5.2.10 on 2026-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0021_emaildeliveryevent_message_id_prefix_emaildeadletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcheckin',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
