# Generated by Django 5.2.10 on 2026-06-04 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0022_visitorcheckin_client_offline_id'),
        ('schools', '0065_school_tenant_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visitorcheckin',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_visitorcheckin_school_offline_id'),
        ),
    ]
