# Generated by Django 5.2.10 on 2026-06-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0057_applicant_client_offline_id_and_more'),
        ('schoolops', '0023_visitorcheckin_uniq_visitorcheckin_school_offline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='possaleline',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-supplied key; a repeated key returns the prior sale (no double-charge).', max_length=128),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Student charged (cashless campus POS); null for anonymous cash sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_lines', to='people.studentprofile'),
        ),
    ]
