# Generated by Django 5.2.10 on 2026-06-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0057_applicant_client_offline_id_and_more'),
        ('schoolops', '0024_possaleline_idempotency_key_possaleline_student'),
        ('schools', '0066_tenantinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusBoardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('board', 'Boarded'), ('alight', 'Alighted')], default='board', max_length=8)),
                ('capture_method', models.CharField(default='rfid', help_text='rfid / nfc / qr / manual', max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('parent_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_events', to='schoolops.bus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_events', to='schoolops.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_boarding_events', to='schools.school')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_boarding_events', to='people.studentprofile')),
            ],
            options={
                'db_table': 'schoolops_busboardingevent',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['school', 'occurred_at'], name='schoolops_b_school__bb0a86_idx')],
            },
        ),
    ]
