# Generated by Django 5.2.10 on 2026-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0025_busboardingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude; enables offline route optimisation.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude; enables offline route optimisation.', max_digits=9, null=True),
        ),
    ]
