# Generated by Django 5.2.10 on 2026-06-26 14:46

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


def _add_booking_exclude_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    ResourceBooking = apps.get_model("schoolops", "ResourceBooking")
    constraint = django.contrib.postgres.constraints.ExclusionConstraint(
        name="exclude_overlapping_resource_bookings",
        expressions=[
            (models.F("school_id"), "="),
            (models.F("resource_id"), "="),
            (models.F("time_range"), "&&"),
        ],
        condition=models.Q(status="confirmed"),
    )
    schema_editor.add_constraint(ResourceBooking, constraint)


def _drop_booking_exclude_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    ResourceBooking = apps.get_model("schoolops", "ResourceBooking")
    constraint = django.contrib.postgres.constraints.ExclusionConstraint(
        name="exclude_overlapping_resource_bookings",
        expressions=[
            (models.F("school_id"), "="),
            (models.F("resource_id"), "="),
            (models.F("time_range"), "&&"),
        ],
        condition=models.Q(status="confirmed"),
    )
    schema_editor.remove_constraint(ResourceBooking, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0028_ensure_micro_friction_tables'),
        ('schools', '0076_alter_school_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='BookableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('room', 'Room'), ('lab', 'Lab'), ('hall', 'Hall'), ('asset', 'Asset')], default='room', max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Concurrent bookings allowed; capacity=1 uses DB exclusion.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookable_resources', to='schoolops.hostelroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookable_resources', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_bookings_created', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schoolops.bookableresource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookableresource',
            index=models.Index(fields=['school', 'is_active'], name='schoolops_b_school__61bd71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookableresource',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['school', 'resource', 'status'], name='schoolops_r_school__aa2314_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=_add_booking_exclude_constraint,
                    reverse_code=_drop_booking_exclude_constraint,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='resourcebooking',
                    constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(('status', 'confirmed')),
                        expressions=[
                            (models.F('school_id'), '='),
                            (models.F('resource_id'), '='),
                            (models.F('time_range'), '&&'),
                        ],
                        name='exclude_overlapping_resource_bookings',
                    ),
                ),
            ],
        ),
    ]
