# Generated by Django 5.2.10 on 2026-06-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0031_rls_policy_default_deny'),
        ('schools', '0076_alter_school_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('checkout', 'Checkout'), ('return', 'Return'), ('consume', 'Consume'), ('transfer', 'Transfer'), ('loss', 'Loss'), ('adjust', 'Adjustment')], default='adjust', max_length=16)),
                ('quantity_delta', models.IntegerField(help_text='Signed change applied to item.quantity.')),
                ('quantity_after', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='schoolops.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'item', '-created_at'], name='schoolops_i_school__acab66_idx')],
            },
        ),
    ]
