# Generated by Django 5.2.10 on 2026-08-13 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0071_backfill_enrollment_from_student_row'),
        ('schoolops', '0036_substitute_market_shift'),
        ('schools', '0083_force_rls_late_enabled_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(help_text='Vaccine code/name (stored normalized: strip + upper).', max_length=64)),
                ('dose_number', models.PositiveSmallIntegerField(default=1)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('exemption_type', models.CharField(blank=True, help_text='Non-empty marks the vaccine exempt for the student (e.g. medical, religious).', max_length=16)),
                ('exemption_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_records', to='schools.school')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='immunization_records', to='people.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_immunization_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schools_immunizationrecord',
                'ordering': ['-date_administered', '-created_at'],
                'indexes': [models.Index(fields=['school', 'student'], name='schools_imm_school__681765_idx'), models.Index(fields=['school', 'vaccine'], name='schools_imm_school__11190b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VaccineRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(help_text='Required vaccine code/name (stored normalized: strip + upper).', max_length=64)),
                ('doses_required', models.PositiveSmallIntegerField(default=1)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, help_text='Advisory age hint (not enforced by the increment-1 sweep).', null=True)),
                ('max_age_years', models.PositiveSmallIntegerField(blank=True, help_text='Advisory age hint (not enforced by the increment-1 sweep).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_requirements', to='schools.school')),
            ],
            options={
                'db_table': 'schools_vaccinerequirement',
                'ordering': ['vaccine'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='schools_vac_school__724940_idx')],
                'unique_together': {('school', 'vaccine')},
            },
        ),
    ]
