# Generated by Django 5.2.10 on 2026-08-20 16:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0084_academicyear_calendar_invariants'),
        ('schoolops', '0038_immunization_vaccine_rls'),
        ('schools', '0084_alter_marketing_funnel_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_certified', models.BooleanField(default=False, help_text='Vetted supplier. Shown to operators; does not restrict ordering.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='USD', help_text='ISO-4217 code the vendor prices in.', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_vendors', to='schools.school')),
            ],
            options={
                'db_table': 'schoolops_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('source', models.CharField(choices=[('CLASS_CONFIG', 'Auto-generated from class configuration'), ('MANUAL', 'Created by hand')], default='MANUAL', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Resolved at generation time via apps.billing.tax_engine.', max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='schools.school')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='schoolops.vendor')),
            ],
            options={
                'db_table': 'schoolops_purchaseorder',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='each', help_text='each / box / pack / litre …', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_products', to='schools.school')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='schoolops.vendor')),
            ],
            options={
                'db_table': 'schoolops_vendorproduct',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_student', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Units of this product each enrolled student needs.', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requirements', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requirements', to='academics.subject')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_requirements', to='schoolops.vendorproduct')),
            ],
            options={
                'db_table': 'schoolops_supplyrequirement',
                'ordering': ['subject__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='schoolops.purchaseorder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='schools.school')),
                ('subject_assignment', models.ForeignKey(blank=True, help_text='The class configuration this quantity was derived from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='academics.subjectassignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='schoolops.vendorproduct')),
            ],
            options={
                'db_table': 'schoolops_purchaseorderline',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_vendor_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['school', 'status'], name='idx_po_school_status'),
        ),
        migrations.AddConstraint(
            model_name='vendorproduct',
            constraint=models.UniqueConstraint(fields=('vendor', 'sku'), name='uniq_product_sku_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='supplyrequirement',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'product'), name='uniq_requirement_per_subject_product'),
        ),
    ]
