# Generated by Django 5.2.10 on 2026-03-24 12:36

from django.db import migrations, models


def seed_phase_b_domain_snapshots(apps, schema_editor):
    # Use historical snapshot model only: live sync_phase_b_domain_snapshots_from_site
    # touches payload_key_count / checksum fields added in 0026–0027 and fails here.
    from apps.platform_runtime.phase_b_domain_snapshots import (
        PHASE_B_SNAPSHOT_DOMAINS,
        snapshot_payload_for_domain,
    )

    Snapshot = apps.get_model("platform_runtime", "PlatformPhaseBDomainSnapshot")
    SiteSettings = apps.get_model("siteconfig", "SiteSettings")
    site = SiteSettings.objects.order_by("pk").first()
    if not site:
        return
    for domain in PHASE_B_SNAPSHOT_DOMAINS:
        payload = snapshot_payload_for_domain(site, domain)
        Snapshot.objects.update_or_create(
            domain=domain,
            defaults={"payload": payload},
        )


def unseed_phase_b_domain_snapshots(apps, schema_editor):
    PlatformPhaseBDomainSnapshot = apps.get_model(
        "platform_runtime", "PlatformPhaseBDomainSnapshot"
    )
    PlatformPhaseBDomainSnapshot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_runtime", "0006_platformeventlog"),
        # After slim SiteSettings + RuntimeDefaults seed (0162); snapshots use owned_payload.
        ("siteconfig", "0162_phase_b_slim_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPhaseBDomainSnapshot",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phase B domain snapshot",
                "verbose_name_plural": "Phase B domain snapshots",
                "db_table": "platform_runtime_phase_b_domain_snapshot",
            },
        ),
        migrations.RunPython(seed_phase_b_domain_snapshots, unseed_phase_b_domain_snapshots),
    ]
