# Generated by Django 5.2.10 on 2026-03-24 12:36

from django.db import migrations, models


def seed_phase_b_domain_snapshots(apps, schema_editor):
    from apps.siteconfig.models import SiteSettings
    from apps.platform_runtime.phase_b_domain_snapshots import (
        sync_phase_b_domain_snapshots_from_site,
    )

    site = SiteSettings.objects.order_by("pk").first()
    if site:
        sync_phase_b_domain_snapshots_from_site(site)


def unseed_phase_b_domain_snapshots(apps, schema_editor):
    PlatformPhaseBDomainSnapshot = apps.get_model(
        "platform_runtime", "PlatformPhaseBDomainSnapshot"
    )
    PlatformPhaseBDomainSnapshot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_runtime", "0006_platformeventlog"),
        # After slim SiteSettings + RuntimeDefaults seed (0162); snapshots use owned_payload.
        ("siteconfig", "0162_phase_b_slim_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPhaseBDomainSnapshot",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phase B domain snapshot",
                "verbose_name_plural": "Phase B domain snapshots",
                "db_table": "platform_runtime_phase_b_domain_snapshot",
            },
        ),
        migrations.RunPython(seed_phase_b_domain_snapshots, unseed_phase_b_domain_snapshots),
    ]
