# Generated by Django 5.2 — FleetGovernedChange (WHATS_LEFT §2.1 thin slice)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform_runtime", "0007_platform_phase_b_domain_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetGovernedChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "change_type",
                    models.CharField(
                        db_index=True,
                        help_text="Logical class of change, e.g. PACKAGE_ROLLOUT, FEATURE_FLAG.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("SCHEDULED", "Scheduled"),
                            ("APPLYING", "Applying"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Target scope (tenant ids, segments, school keys, etc.).",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Apply hints / parameters for the operator completing work downstream.",
                    ),
                ),
                (
                    "apply_surface_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Named URL path or absolute link to the apply UI (staged activation, rollout, …).",
                        max_length=512,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_governed_changes_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_governed_changes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet governed change",
                "verbose_name_plural": "Fleet governed changes",
                "ordering": ["-created_at"],
            },
        ),
    ]
