# Generated by Django 5.2.10 on 2026-03-25 21:50

from django.db import migrations, models

# Keep in sync with apps.platform_runtime.runtime_defaults_first_class (migration-safe copy).
_RUNTIME_DEFAULTS_FIRST_CLASS_KEYS = (
    "cache_rankings_interval_minutes",
    "preview_mode_enabled",
    "preview_note",
    "skip_theme_publish_guard",
    "sms_provider",
    "sms_sender_id",
    "email_from_address",
    "whatsapp_support_number",
    "whatsapp_admissions_number",
    "enable_whatsapp_parent_portal",
    "enable_whatsapp_staff_portal",
    "marksheet_ocr_command",
)


def _backfill_first_class_from_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    obj = RuntimeDefaults.objects.filter(pk=1).first()
    if not obj:
        return
    pl = dict(obj.payload or {})
    updates = {}
    for key in _RUNTIME_DEFAULTS_FIRST_CLASS_KEYS:
        if key not in pl:
            continue
        updates[key] = pl.pop(key)
    if not updates and pl == dict(obj.payload or {}):
        return
    for k, v in updates.items():
        setattr(obj, k, v)
    obj.payload = pl
    obj.save(update_fields=list(updates.keys()) + ["payload"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0008_fleetgovernedchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimedefaults',
            name='email_from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='enable_whatsapp_parent_portal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='enable_whatsapp_staff_portal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='marksheet_ocr_command',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='preview_mode_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='preview_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='skip_theme_publish_guard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='sms_provider',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='whatsapp_admissions_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='runtimedefaults',
            name='whatsapp_support_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='runtimedefaults',
            name='cache_rankings_interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='When set, resolver uses this instead of payload/SiteSettings.', null=True),
        ),
        migrations.RunPython(_backfill_first_class_from_payload, _noop_reverse),
    ]
