# Generated by Django 5.2 — marketplace_integrations secret split (§11.4).

from django.db import migrations, models


def forwards_move_sms_api_key_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("sms_api_key", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.sms_api_key = s[:512]
        else:
            row.sms_api_key = None
        row.payload = payload
        row.save(update_fields=["payload", "sms_api_key", "updated_at"])


def backwards_restore_sms_api_key_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "sms_api_key", None) or ""
        if str(key).strip():
            payload["sms_api_key"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0028_runtimedefaults_report_downloads_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="sms_api_key",
            field=models.CharField(
                blank=True,
                help_text="SMS provider API key (marketplace_integrations). Stored as a typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_sms_api_key_to_column,
            backwards_restore_sms_api_key_to_payload,
        ),
    ]
