# Generated by Django 5.2 — marketplace_integrations AI secret split (§11.4).

from django.db import migrations, models


def forwards_move_ai_provider_api_key_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("ai_provider_api_key", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.ai_provider_api_key = s[:512]
        else:
            row.ai_provider_api_key = None
        row.payload = payload
        row.save(update_fields=["payload", "ai_provider_api_key", "updated_at"])


def backwards_restore_ai_provider_api_key_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "ai_provider_api_key", None) or ""
        if str(key).strip():
            payload["ai_provider_api_key"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0029_runtimedefaults_sms_api_key_first_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="ai_provider_api_key",
            field=models.CharField(
                blank=True,
                help_text="AI / LLM provider API key (marketplace_integrations). Typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_ai_provider_api_key_to_column,
            backwards_restore_ai_provider_api_key_to_payload,
        ),
    ]
