# Generated by Django 5.2 — marketplace_integrations WhatsApp secret split (§11.4).

from django.db import migrations, models


def forwards_move_whatsapp_api_token_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("whatsapp_api_token", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.whatsapp_api_token = s[:512]
        else:
            row.whatsapp_api_token = None
        row.payload = payload
        row.save(update_fields=["payload", "whatsapp_api_token", "updated_at"])


def backwards_restore_whatsapp_api_token_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "whatsapp_api_token", None) or ""
        if str(key).strip():
            payload["whatsapp_api_token"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0030_runtimedefaults_ai_provider_api_key_first_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="whatsapp_api_token",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp Business / Cloud API access token (marketplace_integrations). Typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_whatsapp_api_token_to_column,
            backwards_restore_whatsapp_api_token_to_payload,
        ),
    ]
