# Generated by Django 5.2 — marketplace_integrations SMTP secret split (§11.4).

from django.db import migrations, models


def forwards_move_smtp_password_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("smtp_password", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.smtp_password = s[:512]
        else:
            row.smtp_password = None
        row.payload = payload
        row.save(update_fields=["payload", "smtp_password", "updated_at"])


def backwards_restore_smtp_password_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "smtp_password", None) or ""
        if str(key).strip():
            payload["smtp_password"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0032_runtimedefaults_marksheet_ocr_api_key_first_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="SMTP / transactional email password (marketplace_integrations). Typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_smtp_password_to_column,
            backwards_restore_smtp_password_to_payload,
        ),
    ]
