# Generated by Django 5.2 — marketplace_integrations outbound webhook signing secret (§11.4).

from django.db import migrations, models


def forwards_move_webhook_signing_secret_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("webhook_signing_secret", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.webhook_signing_secret = s[:512]
        else:
            row.webhook_signing_secret = None
        row.payload = payload
        row.save(update_fields=["payload", "webhook_signing_secret", "updated_at"])


def backwards_restore_webhook_signing_secret_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "webhook_signing_secret", None) or ""
        if str(key).strip():
            payload["webhook_signing_secret"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0033_runtimedefaults_smtp_password_first_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="webhook_signing_secret",
            field=models.CharField(
                blank=True,
                help_text="Shared secret for signing or verifying integration webhooks (marketplace_integrations). Typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_webhook_signing_secret_to_column,
            backwards_restore_webhook_signing_secret_to_payload,
        ),
    ]
