# Generated by Django 5.2 — plans_entitlements operator default report SKU bundle (Phase B typed slice).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_runtime", "0035_platform_integration_webhook_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformReportPlatformSkuDefault",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                (
                    "default_bundle_slug",
                    models.CharField(
                        blank=True,
                        help_text="e.g. reports-standard or reports-advanced (see billing_sku_registry).",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report platform SKU default",
                "verbose_name_plural": "Report platform SKU defaults",
                "db_table": "platform_runtime_reportplatformskudefault",
            },
        ),
    ]
