# Generated by Django 5.2 — marketplace_integrations partner OAuth client secret (§11.4).

from django.db import migrations, models


def forwards_move_marketplace_partner_client_secret_to_column(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        raw = payload.pop("marketplace_partner_client_secret", None)
        if raw is None:
            row.payload = payload
            row.save(update_fields=["payload", "updated_at"])
            continue
        s = str(raw).strip()
        if s:
            row.marketplace_partner_client_secret = s[:512]
        else:
            row.marketplace_partner_client_secret = None
        row.payload = payload
        row.save(
            update_fields=[
                "payload",
                "marketplace_partner_client_secret",
                "updated_at",
            ]
        )


def backwards_restore_marketplace_partner_client_secret_to_payload(apps, schema_editor):
    RuntimeDefaults = apps.get_model("platform_runtime", "RuntimeDefaults")
    for row in RuntimeDefaults.objects.all():
        payload = dict(row.payload or {})
        key = getattr(row, "marketplace_partner_client_secret", None) or ""
        if str(key).strip():
            payload["marketplace_partner_client_secret"] = str(key)[:512]
        row.payload = payload
        row.save(update_fields=["payload", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0036_platform_report_platform_sku_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimedefaults",
            name="marketplace_partner_client_secret",
            field=models.CharField(
                blank=True,
                help_text="OAuth-style client secret for marketplace / integration partners (marketplace_integrations). Typed column, not in JSON payload.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.RunPython(
            forwards_move_marketplace_partner_client_secret_to_column,
            backwards_restore_marketplace_partner_client_secret_to_payload,
        ),
    ]
