# Generated by Django 5.2 — typed operator playbook / runbook deep links (Batch 14+).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0037_runtimedefaults_marketplace_partner_client_secret_first_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformOperatorPlaybookLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "href",
                    models.CharField(
                        help_text="Relative path (e.g. /super/workflow-simulator/) or absolute URL.",
                        max_length=512,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="playbook",
                        help_text="e.g. playbook, admin, runbook",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Operator playbook link",
                "verbose_name_plural": "Operator playbook links",
                "db_table": "platform_runtime_operatorplaybooklink",
                "ordering": ("sort_order", "slug"),
            },
        ),
    ]
