# Generated by Django 5.2.10 on 2026-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_runtime", "0050_platform_operator_migration_cloud_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtimedefaults",
            name="cache_rankings_interval_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="When set, resolver uses this instead of JSON payload / tenant settings singleton.",
                null=True,
            ),
        ),
    ]

