# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
        ("platform_runtime", "0051_alter_runtimedefaults_cache_rankings_interval_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolOnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of step keys marked complete (operator acknowledgment).",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "last_step",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress_record",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School onboarding progress",
                "verbose_name_plural": "School onboarding progress",
                "db_table": "platform_runtime_schoolonboardingprogress",
            },
        ),
    ]
