# Generated by Django 5.2.10 on 2026-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0053_clicktrackevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grading', 'Grading'), ('payment_receipt', 'Payment / receipt capture'), ('notes_report', 'Notes / report capture')], db_index=True, max_length=32),
        ),
    ]
