# Generated by Django 5.2.10 on 2026-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0055_event_bus_webhook_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventwebhookdelivery',
            new_name='platform_ru_status_cb3141_idx',
            old_name='platform_ru_status_64f0ee_idx',
        ),
        migrations.RenameIndex(
            model_name='eventwebhookdelivery',
            new_name='platform_ru_platfor_b4202c_idx',
            old_name='platform_ru_platfor_8e8c2e_idx',
        ),
        migrations.AlterField(
            model_name='eventwebhooksubscription',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eventwebhooksubscription',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
