# Generated by Django 5.2.10 on 2026-05-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0057_eventwebhookdelivery_operator_remediation'),
        ('schools', '0047_alter_marketingfunnelevent_event_type_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLifecycleSchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenants_scanned', models.PositiveIntegerField(default=0)),
                ('actions_created', models.PositiveIntegerField(default=0)),
                ('audits_written', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_runtime_tenantlifecycleschedulerrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRetentionPlaybookAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_code', models.CharField(db_index=True, max_length=64)),
                ('trigger', models.CharField(blank=True, default='', max_length=128)),
                ('condition_summary', models.CharField(blank=True, default='', max_length=256)),
                ('action_kind', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=24)),
                ('schedule', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduler_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_actions', to='platform_runtime.tenantlifecycleschedulerrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_playbook_actions', to='schools.school')),
            ],
            options={
                'db_table': 'platform_runtime_tenantretentionplaybookaction',
                'indexes': [models.Index(fields=['school', 'playbook_code', 'status'], name='platform_ru_school__05b016_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantRetentionPlaybookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_code', models.CharField(db_index=True, max_length=64)),
                ('trigger', models.CharField(blank=True, default='', max_length=128)),
                ('outcome', models.CharField(db_index=True, max_length=32)),
                ('detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduler_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_audits', to='platform_runtime.tenantlifecycleschedulerrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_playbook_audits', to='schools.school')),
            ],
            options={
                'db_table': 'platform_runtime_tenantretentionplaybookauditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'playbook_code', 'created_at'], name='platform_ru_school__937acf_idx')],
            },
        ),
    ]
