# Generated by Django 5.2.10 on 2026-05-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_runtime", "0061_packinstallation"),
        ("schools", "0047_alter_marketingfunnelevent_event_type_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintinstallation",
            name="available_version",
            field=models.CharField(default="1.0.0", max_length=80),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="installed_version",
            field=models.CharField(default="1.0.0", max_length=80),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="previous_version",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="upgrade_available",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="upgrade_impact_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="upgrade_preview_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="blueprintinstallation",
            name="upgrade_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="available_version",
            field=models.CharField(default="1.0.0", max_length=80),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="installed_version",
            field=models.CharField(default="1.0.0", max_length=80),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="previous_version",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="upgrade_available",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="upgrade_impact_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="upgrade_preview_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="packinstallation",
            name="upgrade_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.CreateModel(
            name="ConfigurationChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_type", models.CharField(choices=[("blueprint_apply", "Blueprint apply"), ("blueprint_rollback", "Blueprint rollback"), ("pack_apply", "Pack apply"), ("pack_rollback", "Pack rollback"), ("pack_deactivate", "Pack deactivate"), ("pack_upgrade", "Pack upgrade")], db_index=True, max_length=40)),
                ("target_key", models.CharField(db_index=True, max_length=160)),
                ("target_type", models.CharField(db_index=True, max_length=60)),
                ("target_version", models.CharField(blank=True, default="", max_length=80)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("requested", "Requested"), ("pending_approval", "Pending approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("scheduled", "Scheduled"), ("applied", "Applied"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("rolled_back", "Rolled back")], db_index=True, default="draft", max_length=32)),
                ("risk_level", models.CharField(blank=True, default="", max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("preview_snapshot", models.JSONField(blank=True, default=dict)),
                ("simulation_snapshot", models.JSONField(blank=True, default=dict)),
                ("impact_snapshot", models.JSONField(blank=True, default=dict)),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                ("external_blockers", models.JSONField(blank=True, default=list)),
                ("approval_notes", models.TextField(blank=True, default="")),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("schedule_status", models.CharField(blank=True, default="", max_length=32)),
                ("execution_window", models.CharField(blank=True, default="", max_length=120)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("audit_ref", models.CharField(blank=True, default="", max_length=128)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, default="", max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("scheduled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="configuration_change_requests", to="schools.school")),
            ],
            options={
                "db_table": "platform_runtime_configurationchangerequest",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["school", "status", "request_type"], name="platform_ru_school__e69fca_idx"),
                    models.Index(fields=["target_type", "target_key", "target_version"], name="platform_ru_target__5f9eed_idx"),
                ],
            },
        ),
    ]
