# Generated by Django 5.2.10 on 2026-05-23 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0069_dashboard_topology_surface_tier'),
        ('schools', '0057_school_primary_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offlineaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('school', 'idempotency_key'), name='uniq_offline_action_idempotency_per_school'),
        ),
    ]
