# Generated by Django 5.2.10 on 2026-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0070_sodp_offline_waves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grading', 'Grading'), ('payment_receipt', 'Payment / receipt capture'), ('notes_report', 'Notes / report capture'), ('notify.parent', 'Notify parent'), ('notify.staff', 'Notify staff')], db_index=True, max_length=32),
        ),
    ]
