# Generated by Django 5.2.10 on 2026-06-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0082_agentic_audit_phase3_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grading', 'Grading'), ('payment_receipt', 'Payment / receipt capture'), ('notes_report', 'Notes / report capture'), ('homework_submission', 'Homework submission'), ('notify.parent', 'Notify parent'), ('notify.staff', 'Notify staff'), ('support_ticket', 'Support ticket'), ('provision.signup', 'Provisional device signup')], db_index=True, max_length=32),
        ),
    ]
