# Generated by Django 5.2.10 on 2026-06-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0083_alter_offlineaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimedefaults',
            name='enable_student_portal',
            field=models.BooleanField(blank=True, help_text='Default student portal enabled toggle.', null=True),
        ),
    ]
