# Generated by Django 5.2.10 on 2026-06-16 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0087_operator_tenant_assignment'),
        ('schools', '0066_tenantinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformoperatorinvite',
            name='tier',
            field=models.CharField(choices=[('observer', 'Observer'), ('support', 'Support'), ('tenant_support', 'Tenant Support'), ('fleet', 'Fleet'), ('billing', 'Billing'), ('security', 'Security'), ('principal', 'Principal'), ('break_glass', 'Break Glass')], default='support', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformoperatorprofile',
            name='tier',
            field=models.CharField(choices=[('observer', 'Observer'), ('support', 'Support'), ('tenant_support', 'Tenant Support'), ('fleet', 'Fleet'), ('billing', 'Billing'), ('security', 'Security'), ('principal', 'Principal'), ('break_glass', 'Break Glass')], default='support', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformoperatorpromotionrequest',
            name='requested_tier',
            field=models.CharField(choices=[('observer', 'Observer'), ('support', 'Support'), ('tenant_support', 'Tenant Support'), ('fleet', 'Fleet'), ('billing', 'Billing'), ('security', 'Security'), ('principal', 'Principal'), ('break_glass', 'Break Glass')], max_length=32),
        ),
        migrations.CreateModel(
            name='RemoteSupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiator', models.CharField(choices=[('tenant', 'Tenant requested'), ('operator', 'Operator proposed')], default='tenant', max_length=16)),
                ('channel', models.CharField(choices=[('online', 'Online (near real-time)'), ('offline_async', 'Offline (queued, syncs on reconnect)')], default='online', max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('active', 'Active'), ('ended', 'Ended'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('support_ticket_ref', models.UUIDField(blank=True, null=True)),
                ('requires_consent', models.BooleanField(default=True)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('impersonation_used', models.BooleanField(default=False)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, help_text='End-of-session summary.')),
                ('ended_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('consent_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_support_consents', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, help_text='Assigned platform operator (or in-school support person).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='Tenant user who asked for help (null when operator-proposed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_support_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_support_sessions', to='schools.school')),
            ],
            options={
                'db_table': 'platform_runtime_remotesupportsession',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='platform_ru_school__532769_idx'), models.Index(fields=['operator', 'status'], name='platform_ru_operato_ad5b51_idx'), models.Index(fields=['status', '-created_at'], name='platform_ru_status_b57ebc_idx')],
            },
        ),
    ]
