# Generated by Django 5.2.10 on 2026-06-16 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0088_remote_support_session'),
        ('schools', '0066_tenantinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConnectivityHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('profile', models.CharField(blank=True, max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('pending_sync', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_heartbeat', to='schools.school')),
            ],
            options={
                'db_table': 'platform_runtime_tenantheartbeat',
            },
        ),
        migrations.CreateModel(
            name='OperatorIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('message', 'Message to tenant'), ('config_refresh', 'Tenant should re-pull config'), ('diagnostic_request', 'Tenant should upload diagnostics'), ('support_note', 'Support note')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered (tenant fetched)'), ('acknowledged', 'Acknowledged'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ack_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_intents_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_intents', to='schools.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_intents', to='platform_runtime.remotesupportsession')),
            ],
            options={
                'db_table': 'platform_runtime_operatorintent',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='platform_ru_school__80dade_idx'), models.Index(fields=['status', 'created_at'], name='platform_ru_status_7a480c_idx')],
            },
        ),
    ]
