# Generated by Django 5.2.14 on 2026-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0089_remote_support_reverse_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grading', 'Grading'), ('payment_receipt', 'Payment / receipt capture'), ('notes_report', 'Notes / report capture'), ('homework_submission', 'Homework submission'), ('notify.parent', 'Notify parent'), ('notify.staff', 'Notify staff'), ('support_ticket', 'Support ticket'), ('provision.signup', 'Provisional device signup'), ('donation.intake', 'Donation / pledge capture'), ('in_kind.intake', 'In-kind donation capture')], db_index=True, max_length=32),
        ),
    ]
