# Generated by Django 5.2.10 on 2026-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0090_alter_offlineaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimedefaults',
            name='ai_mode',
            field=models.CharField(blank=True, choices=[('auto', 'Auto (cloud when available, else on-device)'), ('cloud', 'Cloud (prefer remote AI gateway)'), ('local', 'Local (on-device only — data never leaves the box)')], help_text='Platform-default AI provider mode. Blank/None = auto. Tenants may override per-school via SiteSettings. Resolved by services.ai_deployment_posture.resolve_effective_ai_mode.', max_length=16, null=True),
        ),
    ]
