# Generated by Django 5.2.10 on 2026-06-21 11:04
#
# Idempotent create: the platform_runtime_scheduledjobheartbeat table can already
# exist in a database while this migration is NOT recorded as applied (a prior
# deploy created the table out-of-band / a partial migrate left state drift). A
# plain CreateModel then raises psycopg DuplicateTable ("relation already exists")
# and — under set -e in scripts/release/render_predeploy.sh — aborts EVERY deploy,
# freezing production at the last good commit. SeparateDatabaseAndState keeps the
# model in Django's migration state (so model history + makemigrations stay clean
# and dependents resolve) while the database step creates the table only when it
# is missing. This heals the shared schema, every tenant schema, and fresh DBs.

from django.db import migrations, models


def _create_table_if_missing(apps, schema_editor):
    model = apps.get_model("platform_runtime", "ScheduledJobHeartbeat")
    table = model._meta.db_table
    # introspection.table_names() honours the connection's current schema search
    # path, so under migrate_schemas this checks the schema being migrated.
    if table in schema_editor.connection.introspection.table_names():
        return
    schema_editor.create_model(model)


def _drop_table_if_present(apps, schema_editor):
    model = apps.get_model("platform_runtime", "ScheduledJobHeartbeat")
    if model._meta.db_table in schema_editor.connection.introspection.table_names():
        schema_editor.delete_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0091_runtimedefaults_ai_mode'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ScheduledJobHeartbeat',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('job_name', models.CharField(max_length=200, unique=True)),
                        ('expected_interval_seconds', models.PositiveIntegerField(default=0)),
                        ('last_started_at', models.DateTimeField(blank=True, null=True)),
                        ('last_success_at', models.DateTimeField(blank=True, null=True)),
                        ('last_status', models.CharField(blank=True, default='', max_length=32)),
                        ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                        ('last_error', models.TextField(blank=True, default='')),
                        ('consecutive_failures', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'scheduled job heartbeat',
                        'verbose_name_plural': 'scheduled job heartbeats',
                        'ordering': ('job_name',),
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_create_table_if_missing, _drop_table_if_present),
            ],
        ),
    ]
