# Generated by Django 5.2.10 on 2026-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0091_runtimedefaults_ai_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200, unique=True)),
                ('expected_interval_seconds', models.PositiveIntegerField(default=0)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'scheduled job heartbeat',
                'verbose_name_plural': 'scheduled job heartbeats',
                'ordering': ('job_name',),
            },
        ),
    ]
