# Generated by Django 5.2.10 on 2026-06-21 11:04
#
# Idempotent create. The platform_runtime_scheduledjobheartbeat table can already
# exist in a schema while this migration is NOT recorded as applied (out-of-band /
# partial-migrate drift). A plain CreateModel then raises psycopg DuplicateTable
# ("relation already exists") and — under set -e in render_predeploy.sh — aborts
# EVERY deploy, freezing production at the last good commit.
#
# SeparateDatabaseAndState keeps the model in Django's migration state (so model
# history + makemigrations stay clean and dependents resolve), while the database
# step delegates to tenant_schema_guard.ensure_models_tables, which creates the
# table only when missing and is a no-op when it already exists — healing the
# shared schema, every tenant schema, and fresh DBs alike.

from django.db import migrations, models


def _ensure_heartbeat_table(apps, schema_editor):
    # This migration INTRODUCES ScheduledJobHeartbeat, so the migration-state
    # ``apps`` (from-state) does not contain it yet — get_model on it raises
    # LookupError. Resolve the concrete model from the live registry instead;
    # safe because 0092 is the leaf migration for this model (no later schema
    # change), so the live definition equals this migration's state.
    from django.apps import apps as live_apps  # noqa: F811 — live registry, not the historical state

    from apps.schools.tenant_schema_guard import ensure_models_tables

    model = live_apps.get_model("platform_runtime", "ScheduledJobHeartbeat")
    ensure_models_tables(schema_editor, [model])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0091_runtimedefaults_ai_mode'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ScheduledJobHeartbeat',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('job_name', models.CharField(max_length=200, unique=True)),
                        ('expected_interval_seconds', models.PositiveIntegerField(default=0)),
                        ('last_started_at', models.DateTimeField(blank=True, null=True)),
                        ('last_success_at', models.DateTimeField(blank=True, null=True)),
                        ('last_status', models.CharField(blank=True, default='', max_length=32)),
                        ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                        ('last_error', models.TextField(blank=True, default='')),
                        ('consecutive_failures', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'scheduled job heartbeat',
                        'verbose_name_plural': 'scheduled job heartbeats',
                        'ordering': ('job_name',),
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_heartbeat_table, migrations.RunPython.noop),
            ],
        ),
    ]
