# Generated by Django 5.2.10 on 2026-07-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0099_heavy_work_outbox_and_one_active_provision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyworkoutbox',
            name='kind',
            field=models.CharField(choices=[('provision_school', 'Provision school'), ('heal_tenant_schema', 'Heal tenant schema drift'), ('run_tenant_migrations', 'Run tenant migrations'), ('mc_advance_bundle', 'Migration Cloud advance'), ('mc_apply_bundle', 'Migration Cloud apply')], db_index=True, max_length=48),
        ),
    ]
