# Generated by Django 5.2.10 on 2026-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0100_heavy_work_outbox_kind_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineaction',
            name='action_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grading', 'Grading'), ('payment_receipt', 'Payment / receipt capture'), ('notes_report', 'Notes / report capture'), ('homework_submission', 'Homework submission'), ('migration_cloud_upload', 'Migration Cloud file upload'), ('notify.parent', 'Notify parent'), ('notify.staff', 'Notify staff'), ('support_ticket', 'Support ticket'), ('provision.signup', 'Provisional device signup'), ('donation.intake', 'Donation / pledge capture'), ('in_kind.intake', 'In-kind donation capture'), ('report_batch.distribute', 'Report card batch distribute')], db_index=True, max_length=32),
        ),
    ]
