# Generated by Django 5.2.10 on 2026-03-11 17:02

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("siteconfig", "0147_sitesettings_compliance_profile_pointer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[],
            options={
                "verbose_name": "Brand profile",
                "verbose_name_plural": "Brand profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("siteconfig.brandprofile",),
        ),
        migrations.CreateModel(
            name="BrandSettings",
            fields=[],
            options={
                "verbose_name": "Brand settings",
                "verbose_name_plural": "Brand settings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("siteconfig.brandsettings",),
        ),
        migrations.CreateModel(
            name="DesignTemplate",
            fields=[],
            options={
                "verbose_name": "Design template",
                "verbose_name_plural": "Design templates",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("siteconfig.designtemplate",),
        ),
        migrations.CreateModel(
            name="GlobalBrandRegistry",
            fields=[],
            options={
                "verbose_name": "Global brand registry",
                "verbose_name_plural": "Global brand registry",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("siteconfig.globalbrandregistry",),
        ),
        migrations.CreateModel(
            name="ThemePack",
            fields=[],
            options={
                "verbose_name": "theme pack",
                "verbose_name_plural": "theme packs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("siteconfig.themepack",),
        ),
    ]
