# Generated by Django 5.2.10 on 2026-05-15 22:42

import apps.siteconfig.svg_sanitize
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_experience', '0002_platform_global_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformglobalbranding',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/bg/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
        migrations.AlterField(
            model_name='platformglobalbranding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for browser tabs. Shown across portal, backend, and admin.', null=True, upload_to='branding/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
        migrations.AlterField(
            model_name='platformglobalbranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
        migrations.AlterField(
            model_name='platformglobalbranding',
            name='sidebar_icon',
            field=models.ImageField(blank=True, help_text='Optional small icon shown when the nav sidebar is collapsed.', null=True, upload_to='branding/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
        migrations.AlterField(
            model_name='platformglobalbranding',
            name='svg_background',
            field=models.FileField(blank=True, help_text='Optional: SVG file for animated or vector background.', null=True, upload_to='branding/svg/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
    ]
