# Generated by Django 5.2.10 on 2026-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('payments', 'Payments'), ('analytics', 'Analytics'), ('other', 'Other')], default='other', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Gilead School System', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Knowledge • Technology • Excellence', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('accent_color', models.CharField(default='#198754', max_length=20)),
                ('use_dark_mode', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_teacher_portal', models.BooleanField(default=True)),
                ('enable_reports_pdf', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
