# Generated by Django 5.2.10 on 2026-01-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('siteconfig', '0002_sitesettings_deadline_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='compliance_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='finance.complianceprofile'),
        ),
    ]
