# Generated by Django 5.2.10 on 2026-01-19 01:07
# Updated: add FK only in tenant schemas (finance is TENANT_APPS; public schema has no finance_complianceprofile).

import django.db.models.deletion
from django.db import connection, migrations, models


def add_compliance_profile_if_tenant(apps, schema_editor):
    """Only add FK on tenant schemas; public schema has no finance_complianceprofile."""
    if getattr(connection, "schema_name", None) == "public":
        return
    SiteSettings = apps.get_model("siteconfig", "SiteSettings")
    ComplianceProfile = apps.get_model("finance", "ComplianceProfile")
    field = models.ForeignKey(
        ComplianceProfile,
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name="site_settings",
    )
    field.set_attributes_from_name("compliance_profile")
    schema_editor.add_field(SiteSettings, field)


def remove_compliance_profile_if_tenant(apps, schema_editor):
    if getattr(connection, "schema_name", None) == "public":
        return
    SiteSettings = apps.get_model("siteconfig", "SiteSettings")
    field = SiteSettings._meta.get_field("compliance_profile")
    schema_editor.remove_field(SiteSettings, field)


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("siteconfig", "0002_sitesettings_deadline_mode_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="sitesettings",
                    name="compliance_profile",
                    field=models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_settings",
                        to="finance.complianceprofile",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_compliance_profile_if_tenant, remove_compliance_profile_if_tenant),
            ],
        ),
    ]
