# Generated by Django 5.2.10 on 2026-01-21 21:54

from django.db import migrations, models


def default_social_links():
    """Inlined from ``apps.siteconfig.models.default_social_links`` for
    migration historical-state safety.
    """
    return [
        {"platform": "Facebook", "url": "", "icon": "bi bi-facebook", "enabled": False},
        {
            "platform": "Instagram",
            "url": "",
            "icon": "bi bi-instagram",
            "enabled": False,
        },
        {"platform": "YouTube", "url": "", "icon": "bi bi-youtube", "enabled": False},
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0012_userpreference_dashboard_widgets"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_links",
            field=models.JSONField(
                blank=True, default=default_social_links
            ),
        ),
    ]
