# Generated by Django 5.2.10 on 2026-01-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0013_sitesettings_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_tag_photos_from_exif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cache_rankings_interval_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_grading_scale',
            field=models.CharField(choices=[('numeric_0_20', 'Numeric 0–20 (Cameroon Francophone)'), ('letter_a_e', 'Letters A–E (Cameroon Anglophone)'), ('gpa_4_0', 'GPA 4.0 Scale'), ('percentage', 'Percentage 0–100')], default='numeric_0_20', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_region',
            field=models.CharField(choices=[('cameroon_anglophone', 'Cameroon Anglophone'), ('cameroon_francophone', 'Cameroon Francophone'), ('global', 'Global/Other')], default='cameroon_anglophone', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_address',
            field=models.EmailField(default='noreply@school.example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_concurrent_mark_uploads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_offline_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_practical_assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offline_sync_conflict_resolution',
            field=models.CharField(choices=[('show_both', 'Show Both Versions'), ('reject', 'Reject Offline Entry'), ('auto_merge', 'Auto-Merge Latest')], default='show_both', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('africastalking', 'AfricasTalking'), ('console', 'Console (Dev Only)')], default='console', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_sender_id',
            field=models.CharField(default='GILEAD', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='teacher_deadline_reminder_days',
            field=models.JSONField(default=list, help_text='Days before deadline: [7, 3, 1, 0.5]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='teacher_reminder_time_of_day',
            field=models.TimeField(default='08:00'),
        ),
    ]
