# Generated by Django 5.2.10 on 2026-01-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_classroom_academic_year_repair"),
        ("siteconfig", "0014_sitesettings_auto_tag_photos_from_exif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionConfig",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO country code (CMR, USA, GBR, KEN, NGA, etc.)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Country/Region name (Cameroon, United States, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="en",
                        help_text="Default language code (en, fr, pid, sw, ha)",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone name (Africa/Douala, America/New_York, Europe/London, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "decimal_separator",
                    models.CharField(
                        default=".",
                        help_text="Decimal separator (. or ,)",
                        max_length=1,
                    ),
                ),
                (
                    "thousands_separator",
                    models.CharField(
                        default=",",
                        help_text="Thousands separator (, or .)",
                        max_length=1,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD/MM/YYYY",
                        help_text="Date display format (DD/MM/YYYY, MM/DD/YYYY, YYYY-MM-DD)",
                        max_length=20,
                    ),
                ),
                (
                    "calendar_system",
                    models.CharField(
                        choices=[
                            ("gregorian", "Gregorian"),
                            ("islamic", "Islamic"),
                            ("buddhist", "Buddhist"),
                            ("hebrew", "Hebrew"),
                        ],
                        default="gregorian",
                        max_length=20,
                    ),
                ),
                (
                    "grading_scale",
                    models.CharField(
                        choices=[
                            ("0-20", "Cameroon (0-20)"),
                            ("0-100", "US/UK (0-100)"),
                            ("0-10", "European (0-10)"),
                            ("a-f", "Letter Grade (A-F)"),
                            ("gpa", "GPA (0-4.0)"),
                        ],
                        default="0-20",
                        max_length=20,
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="XAF",
                        help_text="ISO currency code (XAF, USD, EUR, GBP, KES, NGN, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "academic_year_start_month",
                    models.IntegerField(
                        default=9,
                        help_text="Month when academic year starts (1-12, usually 9=September)",
                    ),
                ),
                (
                    "term_count_per_year",
                    models.IntegerField(
                        choices=[(2, "2 terms"), (3, "3 terms"), (4, "4 terms")],
                        default=3,
                    ),
                ),
                (
                    "school_registration_number_format",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for school registration numbers",
                        max_length=100,
                    ),
                ),
                (
                    "student_id_format",
                    models.CharField(
                        blank=True,
                        help_text="Format for student IDs (e.g., 'nnnn' for 4 digits)",
                        max_length=100,
                    ),
                ),
                (
                    "certificate_template_name",
                    models.CharField(
                        default="standard",
                        help_text="Certificate template to use (standard, fancy, minimal, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "enable_online_admissions",
                    models.BooleanField(
                        default=True,
                        help_text="Allow online applications in this region",
                    ),
                ),
                (
                    "enable_parent_portal",
                    models.BooleanField(
                        default=True,
                        help_text="Enable parent/guardian access to student information",
                    ),
                ),
                (
                    "enable_student_portal",
                    models.BooleanField(
                        default=True, help_text="Enable student self-service portal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Region Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="timezone",
            field=models.CharField(default="Africa/Douala", max_length=64),
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., 'Christmas Break', 'Eid al-Fitr')",
                        max_length=200,
                    ),
                ),
                ("date_start", models.DateField(help_text="Holiday start date")),
                (
                    "date_end",
                    models.DateField(help_text="Holiday end date (inclusive)"),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("school_holiday", "School Holiday"),
                            ("public_holiday", "Public Holiday"),
                            ("exam_period", "Exam Period"),
                            ("religious", "Religious Holiday"),
                            ("special_event", "Special Event"),
                        ],
                        help_text="Type of holiday",
                        max_length=50,
                    ),
                ),
                (
                    "is_working_day",
                    models.BooleanField(
                        default=False,
                        help_text="Some regions work during certain holidays (e.g., religious holidays)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Holiday description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="Academic year for this holiday",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays_by_region",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Region this holiday applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="siteconfig.regionconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["date_start"],
                "unique_together": {("region", "academic_year", "name")},
            },
        ),
        migrations.CreateModel(
            name="GradingScaleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scale_type",
                    models.CharField(
                        help_text="Scale identifier (0-20, 0-100, 0-10, a-f, gpa)",
                        max_length=20,
                    ),
                ),
                ("min_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "display_format",
                    models.CharField(
                        help_text="Format string for display (e.g., '{score:.0f}/20', '{score:.1f}%')",
                        max_length=50,
                    ),
                ),
                ("grade_a_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_b_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_c_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_d_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_f_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Region this scale applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_scales",
                        to="siteconfig.regionconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["region", "scale_type"],
                "unique_together": {("region", "scale_type")},
            },
        ),
    ]
