# Generated by Django 5.2.10 on 2026-01-24 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0016_alter_userpreference_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("stats", "Statistics Card"),
                            ("chart", "Chart"),
                            ("list", "Recent Items"),
                            ("action", "Quick Action"),
                            ("alert", "Alert/Notification"),
                            ("feed", "Activity Feed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("PARENT", "Parent"),
                            ("ADMIN", "Administrator"),
                            ("ANY", "Any User"),
                        ],
                        default="ANY",
                        max_length=20,
                    ),
                ),
                (
                    "template_path",
                    models.CharField(
                        help_text="Path to widget template", max_length=255
                    ),
                ),
                (
                    "default_width",
                    models.IntegerField(
                        choices=[(1, "Full"), (2, "Half"), (3, "Third")], default=1
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=300, help_text="Seconds between refreshes"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DashboardUserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(
                        default=dict,
                        help_text="Widget positions and layout configuration",
                    ),
                ),
                (
                    "visible_widgets",
                    models.JSONField(
                        default=list,
                        help_text="List of visible widget IDs on dashboard",
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("auto", "System Default"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("es", "Español"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False, help_text="Enable high contrast mode"
                    ),
                ),
                (
                    "reduced_motion",
                    models.BooleanField(default=False, help_text="Reduce animations"),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("large", "Large"),
                            ("extra-large", "Extra Large"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "items_per_page",
                    models.IntegerField(
                        choices=[(10, "10"), (25, "25"), (50, "50")], default=10
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard User Preference",
                "verbose_name_plural": "Dashboard User Preferences",
            },
        ),
        migrations.CreateModel(
            name="WidgetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(help_text="Cached widget data")),
                ("cached_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_data",
                        to="siteconfig.dashboardwidget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Data Cache",
                "verbose_name_plural": "Widget Data Caches",
                "unique_together": {("widget", "user")},
            },
        ),
    ]
