# Generated by Django 5.2.10 on 2026-01-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0017_dashboardwidget_dashboarduserpreference_widgetdata'),
        ('siteconfig', '0018_sitesettings_admin_portal_stats_config'),
    ]

    operations = [
    ]
