# Generated by Django 5.2.10 on 2026-01-24 20:46

from django.db import migrations, models


def default_footer_badges():
    """Inlined from ``default_footer_badges``."""
    return [
        {"label": "Secure & Encrypted", "tone": "secure"},
        {"label": "2026 Standards Compliant", "tone": "compliant"},
    ]


def default_portal_announcements():
    """Inlined from ``default_portal_announcements``."""
    return [
        {"title": "New Homework Policy", "meta": "2 days ago", "roles": ["PARENT"], "enabled": True},
        {"title": "Sports Day Registration Open", "meta": "4 days ago", "roles": ["PARENT"], "enabled": True},
        {"title": "Library Hours Extended", "meta": "1 week ago", "roles": ["PARENT"], "enabled": True},
    ]


def default_portal_quick_actions():
    """Inlined from ``default_portal_quick_actions``."""
    return [
        {"label": "Message Teacher", "url": "#", "icon": "bi-chat-dots", "roles": ["PARENT"], "enabled": True},
        {"label": "View Report Card", "url": "#", "icon": "bi-file-earmark-text", "roles": ["PARENT"], "enabled": True},
        {"label": "Request Meeting", "url": "#", "icon": "bi-calendar-event", "roles": ["PARENT"], "enabled": True},
        {"label": "Download Documents", "url": "#", "icon": "bi-download", "roles": ["PARENT"], "enabled": True},
    ]


def default_portal_recent_grades():
    """Inlined from ``default_portal_recent_grades``."""
    return [
        {"label": "Mathematics", "grade": "A (92%)", "tone": "success", "roles": ["PARENT"], "enabled": True},
        {"label": "English", "grade": "A- (88%)", "tone": "success", "roles": ["PARENT"], "enabled": True},
        {"label": "Science", "grade": "B+ (85%)", "tone": "primary", "roles": ["PARENT"], "enabled": True},
        {"label": "History", "grade": "B (82%)", "tone": "warning", "roles": ["PARENT"], "enabled": True},
    ]


def default_portal_upcoming_assessments():
    """Inlined from ``default_portal_upcoming_assessments``."""
    return [
        {"title": "Physics Test", "when": "Tomorrow", "detail": "Chapter 5-7", "tone": "info", "roles": ["PARENT"], "enabled": True},
        {"title": "Math Quiz", "when": "Jan 28", "detail": "Algebra II", "tone": "secondary", "roles": ["PARENT"], "enabled": True},
        {"title": "English Essay", "when": "Feb 2", "detail": "Due by 5 PM", "tone": "secondary", "roles": ["PARENT"], "enabled": True},
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0019_merge_20260124_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_accreditation_subtext",
            field=models.CharField(
                blank=True,
                default="Certified for educational institutions worldwide | ISO 9001:2015 Quality Management",
                help_text="Footer accreditation subtext.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_accreditation_text",
            field=models.CharField(
                blank=True,
                default="Ministry of Education - Cameroon | UNESCO Standards 2026 Compliant",
                help_text="Footer accreditation text.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_badges",
            field=models.JSONField(
                blank=True,
                default=default_footer_badges,
                help_text="Footer badges list (JSON). Each item: label, tone.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_status_text",
            field=models.CharField(
                blank=True,
                default="All Systems Operational",
                help_text="Footer system status label.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_support_hours",
            field=models.CharField(
                blank=True,
                default="Mon-Fri: 8AM-6PM | Sat: 9AM-4PM",
                help_text="Footer support hours label.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp_url",
            field=models.URLField(
                blank=True,
                default="https://wa.me/237XXXXXXXXX?text=Hello%20School%20Management%20System%20Support",
                help_text="Footer WhatsApp support link.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_announcements",
            field=models.JSONField(
                blank=True,
                default=default_portal_announcements,
                help_text="Portal announcements list (JSON). Each item: title, meta, roles, enabled.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_quick_actions",
            field=models.JSONField(
                blank=True,
                default=default_portal_quick_actions,
                help_text="Portal quick actions list (JSON). Each item: label, url, icon, roles, enabled.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_recent_grades",
            field=models.JSONField(
                blank=True,
                default=default_portal_recent_grades,
                help_text="Portal recent grades list (JSON). Each item: label, grade, tone, roles, enabled.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_upcoming_assessments",
            field=models.JSONField(
                blank=True,
                default=default_portal_upcoming_assessments,
                help_text="Portal upcoming assessments list (JSON). Each item: title, when, detail, tone, roles, enabled.",
            ),
        ),
    ]
