# Generated by Django 5.2.10 on 2026-01-24 20:46

import apps.siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0019_merge_20260124_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_accreditation_subtext',
            field=models.CharField(blank=True, default='Certified for educational institutions worldwide | ISO 9001:2015 Quality Management', help_text='Footer accreditation subtext.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_accreditation_text',
            field=models.CharField(blank=True, default='Ministry of Education - Cameroon | UNESCO Standards 2026 Compliant', help_text='Footer accreditation text.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_badges',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_footer_badges, help_text='Footer badges list (JSON). Each item: label, tone.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_status_text',
            field=models.CharField(blank=True, default='All Systems Operational', help_text='Footer system status label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_support_hours',
            field=models.CharField(blank=True, default='Mon-Fri: 8AM-6PM | Sat: 9AM-4PM', help_text='Footer support hours label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/237XXXXXXXXX?text=Hello%20School%20Management%20System%20Support', help_text='Footer WhatsApp support link.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_announcements',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_portal_announcements, help_text='Portal announcements list (JSON). Each item: title, meta, roles, enabled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_quick_actions',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_portal_quick_actions, help_text='Portal quick actions list (JSON). Each item: label, url, icon, roles, enabled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_recent_grades',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_portal_recent_grades, help_text='Portal recent grades list (JSON). Each item: label, grade, tone, roles, enabled.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_upcoming_assessments',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_portal_upcoming_assessments, help_text='Portal upcoming assessments list (JSON). Each item: title, when, detail, tone, roles, enabled.'),
        ),
    ]
