# Generated by Codex on 2026-01-24

from django.db import migrations


def seed_dashboard_widgets(apps, schema_editor):
    DashboardWidget = apps.get_model("siteconfig", "DashboardWidget")
    widgets = [
        {
            "id": "attendance",
            "name": "Attendance",
            "description": "Attendance snapshot",
            "widget_type": "stats",
            "template_path": "widgets/attendance.html",
        },
        {
            "id": "performance",
            "name": "Performance",
            "description": "Performance overview",
            "widget_type": "chart",
            "template_path": "widgets/performance.html",
        },
        {
            "id": "finance",
            "name": "Finance",
            "description": "Financial summary",
            "widget_type": "stats",
            "template_path": "widgets/finance.html",
        },
        {
            "id": "events",
            "name": "Events",
            "description": "Events and alerts",
            "widget_type": "alert",
            "template_path": "widgets/events.html",
        },
        {
            "id": "tasks",
            "name": "Tasks",
            "description": "Task tracker",
            "widget_type": "list",
            "template_path": "widgets/tasks.html",
        },
        {
            "id": "communications",
            "name": "Communications",
            "description": "Communication center",
            "widget_type": "feed",
            "template_path": "widgets/communications.html",
        },
        {
            "id": "referral",
            "name": "Referrals",
            "description": "Referral health",
            "widget_type": "stats",
            "template_path": "widgets/referral.html",
        },
        {
            "id": "access",
            "name": "Access",
            "description": "Portal access",
            "widget_type": "stats",
            "template_path": "widgets/access.html",
        },
        {
            "id": "system_status",
            "name": "System Status",
            "description": "System status",
            "widget_type": "alert",
            "template_path": "widgets/system_status.html",
        },
        {
            "id": "completion",
            "name": "Completion",
            "description": "Completion drill",
            "widget_type": "stats",
            "template_path": "widgets/completion.html",
        },
        {
            "id": "analytics",
            "name": "Analytics",
            "description": "Analytics insights",
            "widget_type": "chart",
            "template_path": "widgets/analytics.html",
        },
        {
            "id": "upcoming",
            "name": "Upcoming",
            "description": "Upcoming classes",
            "widget_type": "list",
            "template_path": "widgets/upcoming.html",
        },
        {
            "id": "links",
            "name": "Quick Actions",
            "description": "Quick actions",
            "widget_type": "action",
            "template_path": "widgets/links.html",
        },
    ]

    for index, widget in enumerate(widgets, start=1):
        DashboardWidget.objects.get_or_create(
            id=widget["id"],
            defaults={
                "name": widget["name"],
                "description": widget["description"],
                "widget_type": widget["widget_type"],
                "required_role": "ANY",
                "template_path": widget["template_path"],
                "default_width": 1,
                "refresh_interval": 300,
                "order": index,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0020_sitesettings_footer_accreditation_subtext_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_dashboard_widgets, migrations.RunPython.noop),
    ]
