# Generated by Django 5.2.10 on 2026-01-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0024_regionalconfig_geoiplocation_ipwhitelist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoIPLocation',
        ),
        migrations.AlterUniqueTogether(
            name='regionalaccesspolicy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regionalaccesspolicy',
            name='region',
        ),
        migrations.DeleteModel(
            name='IPWhitelist',
        ),
        migrations.DeleteModel(
            name='RegionalAccessPolicy',
        ),
        migrations.DeleteModel(
            name='RegionalConfig',
        ),
    ]
