# Generated by Django 5.2.10 on 2026-01-25 16:43

import apps.siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0026_theme_brightness_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_links',
            field=models.JSONField(blank=True, default=apps.siteconfig.models.default_footer_links, help_text='Footer links list (JSON). Each item: label, url, roles, enabled.'),
        ),
    ]
