# Generated by Django 5.2.10 on 2026-01-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0035_add_preview_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='preview_banner_text',
            field=models.CharField(blank=True, default='Preview changes are staged and won’t go live until you clear the sandbox.', help_text='Banner text shown when preview mode is active or ready.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preview_toggle_enabled',
            field=models.BooleanField(default=True, help_text='Allow quick toggle of preview mode from the dashboards.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preview_toggle_label',
            field=models.CharField(default='Toggle preview', help_text='Label for the preview toggle button shown when preview mode is inactive.', max_length=60),
        ),
        migrations.CreateModel(
            name='DashboardLayoutAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('widget_meta', 'Widget meta change'), ('settings', 'Layout settings change')], max_length=32)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Layout Audit',
                'verbose_name_plural': 'Dashboard Layout Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
