# Generated by Django 5.2.10 on 2026-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0037_admin_theme_pack_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="report_preview_contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email shown on report card previews/header.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="report_preview_contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number shown on report previews/header.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="report_preview_footer_note",
            field=models.CharField(
                blank=True,
                default="Powered by Gilead Technical High School.",
                help_text="Footer note text shown on report previews.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_report_preview_type",
            field=models.CharField(
                choices=[("term", "Term"), ("annual", "Annual")],
                default="term",
                help_text="Template shown to admins when opening a report preview from the builder.",
                max_length=12,
            ),
        ),
    ]
