# Generated by Django 5.2.10 on 2026-01-26 17:22

from django.db import migrations, models


def default_grade_approval_roles():
    """Inlined from ``apps.siteconfig.models.default_grade_approval_roles`` for
    migration historical-state safety.
    """
    return ["DEAN", "HOD"]


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0040_marksheet_ocr_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="grade_approval_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Require staff approval before publishing teacher-submitted marks.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="grade_approval_roles",
            field=models.JSONField(
                blank=True,
                default=default_grade_approval_roles,
                help_text="List of role codes allowed to review/approve teacher grade submissions.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_report_preview_type",
            field=models.CharField(
                choices=[("term", "Term Report"), ("annual", "Annual Report")],
                default="term",
                help_text="Template shown to admins when opening a report preview from the builder.",
                max_length=12,
            ),
        ),
    ]
