# Generated by Django 5.2.10 on 2026-01-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0044_reportcardstyle_labels_and_layout_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_banner_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_toggle_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_toggle_label',
        ),
        migrations.AlterField(
            model_name='gradingscaleconfig',
            name='region',
            field=models.ForeignKey(help_text='Region this scale applies to', on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', related_query_name='gradingscaleconfig', to='siteconfig.regionconfig'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admission_number_pattern',
            field=models.CharField(blank=True, default='(\\\\d{2}[A-Z0-9]{2,10}\\\\d{4}[A-Z0-9]{2,6}[A-Z0-9]{1,4})|(\\\\d{2}-[A-Z0-9]{2,10}-\\\\d{4}-[A-Z0-9]{2,6}-[A-Z0-9]{1,4})', help_text='Regex used to validate admission numbers. Defaults to YY + SCHOOL + #### + SPEC + CLASS (no dashes) or the legacy dashed format.', max_length=255),
        ),
    ]
