# Generated by Django 5.2.10 on 2026-01-28 20:44

from django.db import migrations, connection


def remove_preview_fields_if_exist(apps, schema_editor):
    """Remove fields only if they exist (already handled conditionally in 0045, but Django state needs update)."""
    db_table = 'siteconfig_sitesettings'
    fields_to_remove = [
        'preview_banner_text',
        'preview_toggle_enabled',
        'preview_toggle_label',
    ]
    
    with connection.cursor() as cursor:
        for field_name in fields_to_remove:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name=%s
            """, [db_table, field_name])
            if cursor.fetchone():
                cursor.execute(f'ALTER TABLE siteconfig_sitesettings DROP COLUMN IF EXISTS {field_name}')


def reverse_remove_preview_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0045_remove_sitesettings_preview_banner_text_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_preview_fields_if_exist, reverse_remove_preview_fields),
    ]
