# Generated by Django 5.2.10 on 2026-01-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0045_alter_sitesettings_admission_number_pattern'),
        ('siteconfig', '0046_remove_sitesettings_preview_banner_text_and_more'),
    ]

    operations = [
    ]
