# Generated by Django 5.2.10 on 2026-01-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0047_merge_20260128_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_banner_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_toggle_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='preview_toggle_label',
        ),
    ]
