# Generated by Django 5.2.10 on 2026-01-29 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0045_alter_sitesettings_admission_number_pattern_and_more"),
        ("siteconfig", "0048_remove_sitesettings_preview_banner_text_and_more"),
    ]

    operations = []
