# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0049_merge_20260128_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="backend_console_theme",
            field=models.CharField(
                choices=[("dark", "Dark (grey)"), ("light", "Light")],
                default="dark",
                help_text="Theme for the Backend Console (Workflow Center, Entity Console). Dark = grey/dark sidebar and dashboard; Light = light background.",
                max_length=10,
            ),
        ),
    ]
