# Generated by Django - Theme Phases A–D (login, header, layout, sidebar, email, nav, typography)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0050_sitesettings_backend_console_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="login_hero_heading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional heading for the login hero (e.g. 'Welcome to Our School'). Leave blank to use site name.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="login_hero_subtext",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional subtext for the login hero. Leave blank to use tagline.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_header_search",
            field=models.BooleanField(default=True, help_text="Show search in the portal/backend header."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_header_notifications",
            field=models.BooleanField(default=True, help_text="Show notifications bell in the header."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_header_profile_menu",
            field=models.BooleanField(default=True, help_text="Show user profile / quick links in the header."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_header_theme_toggle",
            field=models.BooleanField(default=True, help_text="Show theme (light/dark) toggle in the header when applicable."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, help_text="Favicon for browser tabs. Shown across portal, backend, and admin.", null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="layout_style",
            field=models.CharField(
                choices=[("fluid", "Fluid (full width)"), ("boxed", "Boxed (max-width container)")],
                default="fluid",
                help_text="Page layout: fluid (full width) or boxed (centered max-width).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_sidebar_collapsed",
            field=models.BooleanField(
                default=False,
                help_text="When True, new users see the nav sidebar collapsed by default.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="branded_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display-only domain for login and emails (e.g. portal.school.edu). No DNS logic.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_sidebar_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional list of portal sidebar item IDs in display order. Empty = use template default.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sidebar_icon",
            field=models.ImageField(
                blank=True,
                help_text="Optional small icon shown when the nav sidebar is collapsed.",
                null=True,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="secondary_font",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional secondary font (e.g. for headings). Leave blank to use primary font.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="use_secondary_font_for_headings",
            field=models.BooleanField(
                default=False,
                help_text="When True, use secondary_font for headings (h1–h6).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="base_font_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=16,
                help_text="Base font size in pixels for rem-based typography. Null = use CSS default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_widgets_per_role",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional: role code -> list of widget IDs for default dashboard (e.g. {\"TEACHER\": [\"widget-a\", \"widget-b\"]}).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="admin_use_site_primary",
            field=models.BooleanField(
                default=False,
                help_text="When True, admin sidebar active/accent uses SiteSettings.primary_color.",
            ),
        ),
    ]
