# Generated by Django - Theme Phase D1: chart type per widget

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0051_theme_phases_a_d"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="chart_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="For chart widgets: preferred chart type (bar, pie, line). Empty = use template default.",
                max_length=16,
            ),
        ),
    ]
