# Generated by Django 5.2.10 on 2026-01-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0052_dashboardwidget_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_dashboard_view',
            field=models.CharField(choices=[('OVERVIEW', 'Overview'), ('WORKFLOW', 'Workflow Center'), ('FINANCE', 'Finances'), ('ACADEMICS', 'Academics'), ('ATTENDANCE', 'Attendance'), ('CERTIFICATION', 'Certification & Exams'), ('CUSTOM', 'Custom')], default='OVERVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='dashboard_view',
            field=models.CharField(choices=[('OVERVIEW', 'Overview'), ('WORKFLOW', 'Workflow Center'), ('FINANCE', 'Finances'), ('ACADEMICS', 'Academics'), ('ATTENDANCE', 'Attendance'), ('CERTIFICATION', 'Certification & Exams'), ('CUSTOM', 'Custom')], default='OVERVIEW', max_length=20),
        ),
    ]
