# Generated by Django 5.2.10 on 2026-02-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0058_logo_bg_mode_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='backend_console_theme',
            field=models.CharField(choices=[('dark', 'Dark (slate grey)'), ('light', 'Light (lavender tint)'), ('system', 'System (follows OS)'), ('black', 'Black (true black #000)'), ('ink', 'Ink (deep black #030712)'), ('onyx', 'Onyx (rich black #0c0c0c)'), ('charcoal', 'Charcoal (soft black)'), ('graphite', 'Graphite (zinc grey)'), ('midnight', 'Midnight (deep blue-black)'), ('ocean', 'Ocean (dark blue)'), ('steel', 'Steel (blue-grey)'), ('slate', 'Slate (medium grey)'), ('forest', 'Forest (dark green)'), ('indigo', 'Indigo (dark purple)'), ('amber', 'Amber (warm dark)'), ('sand', 'Sand (warm light)'), ('snow', 'Snow (cool light)'), ('cream', 'Cream (ivory light)'), ('lavender', 'Lavender (soft purple light)')], default='dark', help_text='Theme for the Backend Console (Workflow Center, Entity Console).', max_length=20),
        ),
    ]
