# Generated by Django 5.2.10 on 2026-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0060_restore_regionalconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeoIPLocation",
        ),
        migrations.AlterUniqueTogether(
            name="regionalaccesspolicy",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="regionalaccesspolicy",
            name="region",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_whatsapp_parent_portal",
            field=models.BooleanField(
                default=False,
                help_text="Allow WhatsApp contact buttons in the parent portal (support and, if set, admissions).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_whatsapp_staff_portal",
            field=models.BooleanField(
                default=False,
                help_text="Allow WhatsApp shortcuts for staff when contacting guardians.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_admissions_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional WhatsApp Business number for Admissions / Front office. Used for admissions-specific CTAs when configured.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_support_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Official WhatsApp Business number for general support (E.164 format, e.g. +2376XXXXXXX). If set, footer and portal can generate wa.me links.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="improvement_delta_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Minimum score improvement required between terms for a student to be flagged as 'improving' in analytics.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="pass_mark",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Default pass mark used by analytics and summary widgets when a more specific rule is not configured.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="top_students_default_limit",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="How many top students to show by default on analytics views (e.g. Top 10 students in a class or school).",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="use_promotion_rule_for_pass",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use the promotion rule configuration to decide pass/fail instead of this simple pass mark.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="weak_subject_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Score threshold below which a subject is highlighted as weak in analytics reports.",
                max_digits=5,
            ),
        ),
        migrations.DeleteModel(
            name="IPWhitelist",
        ),
        migrations.DeleteModel(
            name="RegionalAccessPolicy",
        ),
        migrations.DeleteModel(
            name="RegionalConfig",
        ),
    ]
