# Generated by Django 5.2.10 on 2026-02-03 15:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0064_sitesettings_finance_payment_instructions_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="finance_on_student_withdrawal",
            field=models.CharField(
                choices=[
                    ("stop_reminders_only", "Stop payment reminders only"),
                    (
                        "stop_and_mark",
                        "Stop reminders and mark invoices (no new payments)",
                    ),
                    ("no_auto_change", "No automatic change"),
                ],
                default="stop_reminders_only",
                help_text="When student is marked withdrawn/inactive.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_overpayment_handling",
            field=models.CharField(
                choices=[
                    ("reject", "Reject (strict)"),
                    ("allow_with_refund", "Allow and create refund request for excess"),
                    ("allow_as_credit", "Allow excess as credit for next invoice"),
                ],
                default="allow_with_refund",
                help_text="When receipt amount exceeds invoice balance.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_overpayment_tolerance_xaf",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Max overpayment to allow (XAF). Above this always flag for review.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_receipt_allowed_extensions",
            field=models.CharField(
                default="pdf,jpg,jpeg,png",
                help_text="Comma-separated: pdf,jpg,jpeg,png",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_receipt_idempotency_window_minutes",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Minutes within which duplicate receipt upload (same invoice+user+file) is ignored.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_receipt_max_size_mb",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Max receipt file size in MB (e.g. 5)."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_receipt_require_verification_reason",
            field=models.BooleanField(
                default=True,
                help_text="Require a reason when staff manually approve or reject a receipt.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_receipt_second_approval_threshold_xaf",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Receipts above this amount (XAF) require second approver (0 = disabled).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_reminder_max_retries",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="Max retries for failed reminder sends."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_reminder_no_contact_action",
            field=models.CharField(
                choices=[
                    ("skip", "Skip reminder only"),
                    ("warn_only", "Log warning only"),
                    ("create_task", "Create task for staff to contact guardian"),
                ],
                default="warn_only",
                help_text="When guardian has no email/phone for reminder.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_reminder_retry_failed_hours",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Retry failed reminders after this many hours (0 = no retry).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="finance_void_invoice_with_payments",
            field=models.CharField(
                choices=[
                    ("allow", "Allow void, stop reminders only"),
                    ("allow_credit_only", "Allow void, treat remaining as credit"),
                    ("block_void", "Block void if invoice has payments"),
                ],
                default="allow",
                help_text="When voiding an invoice that has payments.",
                max_length=30,
            ),
        ),
    ]
