# Generated by Django 5.2.10 on 2026-02-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0074_restore_geoip_regional_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoIPLocation',
        ),
        migrations.AlterUniqueTogether(
            name='regionalaccesspolicy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regionalaccesspolicy',
            name='region',
        ),
        migrations.AlterField(
            model_name='reportcardstyle',
            name='annual_template',
            field=models.CharField(choices=[('reports/annual_report.html', 'Standard annual template'), ('reports/annual_report_cameroon.html', 'Cameroon annual template'), ('reports/annual_report_cameroon_modern.html', 'Cameroon annual template (modern)')], default='reports/annual_report.html', max_length=120),
        ),
        migrations.AlterField(
            model_name='reportcardstyle',
            name='term_template',
            field=models.CharField(choices=[('reports/term_report.html', 'Standard term template'), ('reports/term_report_cameroon.html', 'Cameroon term template'), ('reports/term_report_cameroon_modern.html', 'Cameroon term template (modern)')], default='reports/term_report.html', max_length=120),
        ),
        migrations.DeleteModel(
            name='IPWhitelist',
        ),
        migrations.DeleteModel(
            name='RegionalAccessPolicy',
        ),
        migrations.DeleteModel(
            name='RegionalConfig',
        ),
    ]
