# Generated by Django 5.2.10 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0080_merge_0077_0079_siteconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarduserpreference",
            name="role_visual_presets",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Per-role visual style preferences for dashboards. "
                    'Example: {"PARENT": "soft-glass", "TEACHER": "crisp-professional"}.'
                ),
            ),
        ),
    ]
