# Generated by Django 5.2.10 on 2026-02-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_enable_rls_postgresql"),
        ("siteconfig", "0081_dashboarduserpreference_role_visual_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(blank=True, help_text="e.g. CMR", max_length=20),
                ),
                (
                    "sub_system",
                    models.CharField(
                        choices=[
                            ("FR", "French sub-system"),
                            ("EN", "English sub-system"),
                            ("INT", "International"),
                        ],
                        default="EN",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        help_text="HTML or Excel template for data injection",
                        null=True,
                        upload_to="report_templates/official/",
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_report_templates",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["region_code", "sub_system", "name"],
            },
        ),
    ]
