# Generated by Django 5.2.10 on 2026-02-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_weather_locations(apps, schema_editor):
    RegionConfig = apps.get_model("siteconfig", "RegionConfig")
    WeatherLocation = apps.get_model("siteconfig", "WeatherLocation")
    db_alias = schema_editor.connection.alias
    rows = [
        (
            "CMR",
            "Cameroon",
            "Buea",
            "Buea, Cameroon",
            4.1527,
            9.2410,
            "Africa/Douala",
            10,
        ),
        (
            "CMR",
            "Cameroon",
            "Douala",
            "Douala, Cameroon",
            4.0511,
            9.7679,
            "Africa/Douala",
            20,
        ),
        (
            "USA",
            "United States",
            "New York",
            "New York, United States",
            40.7128,
            -74.0060,
            "America/New_York",
            10,
        ),
        (
            "USA",
            "United States",
            "Los Angeles",
            "Los Angeles, United States",
            34.0522,
            -118.2437,
            "America/Los_Angeles",
            20,
        ),
        (
            "GBR",
            "United Kingdom",
            "London",
            "London, United Kingdom",
            51.5072,
            -0.1276,
            "Europe/London",
            10,
        ),
        (
            "NGA",
            "Nigeria",
            "Lagos",
            "Lagos, Nigeria",
            6.5244,
            3.3792,
            "Africa/Lagos",
            10,
        ),
        (
            "KEN",
            "Kenya",
            "Nairobi",
            "Nairobi, Kenya",
            -1.2864,
            36.8172,
            "Africa/Nairobi",
            10,
        ),
        (
            "FRA",
            "France",
            "Paris",
            "Paris, France",
            48.8566,
            2.3522,
            "Europe/Paris",
            10,
        ),
    ]

    for code, country_name, city, label, lat, lon, tz, sort_order in rows:
        region, _ = RegionConfig.objects.using(db_alias).get_or_create(
            code=code,
            defaults={
                "name": country_name,
                "default_language": "en",
                "timezone": tz,
                "date_format": "DD/MM/YYYY",
                "grading_scale": "0-100",
                "default_currency": "USD",
                "academic_year_start_month": 9,
                "term_count_per_year": 3,
            },
        )
        WeatherLocation.objects.using(db_alias).get_or_create(
            region=region,
            city=city,
            defaults={
                "label": label,
                "latitude": lat,
                "longitude": lon,
                "timezone": tz,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_enable_rls_postgresql"),
        ("siteconfig", "0087_themepack_backend_console_theme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureToggleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=80)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global only"),
                            ("school", "School override allowed"),
                        ],
                        default="school",
                        max_length=20,
                    ),
                ),
                ("default_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "label", "key"],
            },
        ),
        migrations.CreateModel(
            name="FeatureToggleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="siteconfig.featuretoggledefinition",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_toggle_states",
                        to="schools.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_toggle_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["definition__key", "school_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition", "school"),
                        name="siteconfig_toggle_state_unique_definition_school",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("label", models.CharField(blank=True, max_length=180)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_locations",
                        to="siteconfig.regionconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["region__name", "sort_order", "city"],
                "unique_together": {("region", "city")},
            },
        ),
        migrations.RunPython(seed_weather_locations, migrations.RunPython.noop),
    ]
