# Generated by Django 5.2.10 on 2026-02-21 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def _default_term_labels():
    return ["Term 1", "Term 2", "Term 3"]


def _default_subject_seed():
    return [
        {"name": "Mathematics", "category": "GENERAL"},
        {"name": "English", "category": "GENERAL"},
        {"name": "Science", "category": "GENERAL"},
    ]


def seed_education_profiles(apps, schema_editor):
    RegionConfig = apps.get_model("siteconfig", "RegionConfig")
    EducationSystemProfile = apps.get_model("siteconfig", "EducationSystemProfile")
    db_alias = schema_editor.connection.alias

    def ensure_region(
        code: str,
        *,
        name: str,
        timezone: str,
        language: str,
        grading_scale: str,
        currency: str,
        start_month: int,
        term_count: int,
    ):
        region, _ = RegionConfig.objects.using(db_alias).get_or_create(
            code=code,
            defaults={
                "name": name,
                "default_language": language,
                "timezone": timezone,
                "date_format": "DD/MM/YYYY",
                "grading_scale": grading_scale,
                "default_currency": currency,
                "academic_year_start_month": start_month,
                "term_count_per_year": term_count,
            },
        )
        return region

    region_map = {
        "CMR": ensure_region(
            "CMR",
            name="Cameroon",
            timezone="Africa/Douala",
            language="en",
            grading_scale="0-20",
            currency="XAF",
            start_month=9,
            term_count=3,
        ),
        "UGA": ensure_region(
            "UGA",
            name="Uganda",
            timezone="Africa/Kampala",
            language="en",
            grading_scale="0-100",
            currency="UGX",
            start_month=2,
            term_count=3,
        ),
        "NGA": ensure_region(
            "NGA",
            name="Nigeria",
            timezone="Africa/Lagos",
            language="en",
            grading_scale="0-100",
            currency="NGN",
            start_month=9,
            term_count=3,
        ),
        "KEN": ensure_region(
            "KEN",
            name="Kenya",
            timezone="Africa/Nairobi",
            language="sw",
            grading_scale="0-100",
            currency="KES",
            start_month=1,
            term_count=3,
        ),
        "USA": ensure_region(
            "USA",
            name="United States",
            timezone="America/New_York",
            language="en",
            grading_scale="0-100",
            currency="USD",
            start_month=8,
            term_count=2,
        ),
        "GBR": ensure_region(
            "GBR",
            name="United Kingdom",
            timezone="Europe/London",
            language="en",
            grading_scale="a-f",
            currency="GBP",
            start_month=9,
            term_count=3,
        ),
        "FRA": ensure_region(
            "FRA",
            name="France",
            timezone="Europe/Paris",
            language="fr",
            grading_scale="0-20",
            currency="EUR",
            start_month=9,
            term_count=3,
        ),
    }

    profiles = [
        {
            "code": "global-int-default",
            "name": "Global International Default",
            "region": None,
            "sub_system": "INT",
            "is_default": True,
            "academic_year_start_month": 9,
            "term_count_per_year": 3,
            "term_labels": ["Term 1", "Term 2", "Term 3"],
            "grading_scale": "0-100",
            "default_language": "en",
            "default_currency": "USD",
            "default_timezone": "UTC",
            "subject_seed": [
                {"name": "Mathematics", "category": "GENERAL"},
                {"name": "English", "category": "GENERAL"},
                {"name": "Science", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "percentage",
                "report_template_family": "global",
            },
        },
        {
            "code": "cmr-anglophone-default",
            "name": "Cameroon Anglophone Secondary",
            "region": "CMR",
            "sub_system": "EN",
            "is_default": True,
            "academic_year_start_month": 9,
            "term_count_per_year": 3,
            "term_labels": ["First Term", "Second Term", "Third Term"],
            "grading_scale": "0-20",
            "default_language": "en",
            "default_currency": "XAF",
            "default_timezone": "Africa/Douala",
            "subject_seed": [
                {"name": "Mathematics", "category": "GENERAL"},
                {"name": "English Language", "category": "GENERAL"},
                {"name": "Biology", "category": "GENERAL"},
                {"name": "Chemistry", "category": "GENERAL"},
                {"name": "Physics", "category": "GENERAL"},
                {"name": "History", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "numeric_0_20",
                "report_template_family": "cameroon",
            },
        },
        {
            "code": "cmr-francophone-default",
            "name": "Cameroon Francophone Secondary",
            "region": "CMR",
            "sub_system": "FR",
            "is_default": True,
            "academic_year_start_month": 9,
            "term_count_per_year": 3,
            "term_labels": ["Trimestre 1", "Trimestre 2", "Trimestre 3"],
            "grading_scale": "0-20",
            "default_language": "fr",
            "default_currency": "XAF",
            "default_timezone": "Africa/Douala",
            "subject_seed": [
                {"name": "Mathematiques", "category": "GENERAL"},
                {"name": "Francais", "category": "GENERAL"},
                {"name": "Anglais", "category": "GENERAL"},
                {"name": "Physique", "category": "GENERAL"},
                {"name": "Chimie", "category": "GENERAL"},
                {"name": "Histoire", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "numeric_0_20",
                "report_template_family": "cameroon",
            },
        },
        {
            "code": "uga-national-default",
            "name": "Uganda National Secondary",
            "region": "UGA",
            "sub_system": "EN",
            "is_default": True,
            "academic_year_start_month": 2,
            "term_count_per_year": 3,
            "term_labels": ["Term I", "Term II", "Term III"],
            "grading_scale": "0-100",
            "default_language": "en",
            "default_currency": "UGX",
            "default_timezone": "Africa/Kampala",
            "subject_seed": [
                {"name": "Mathematics", "category": "GENERAL"},
                {"name": "English", "category": "GENERAL"},
                {"name": "Biology", "category": "GENERAL"},
                {"name": "Chemistry", "category": "GENERAL"},
                {"name": "Physics", "category": "GENERAL"},
                {"name": "Geography", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "percentage",
                "report_template_family": "east_africa",
            },
        },
        {
            "code": "nga-national-default",
            "name": "Nigeria National Secondary",
            "region": "NGA",
            "sub_system": "EN",
            "is_default": True,
            "academic_year_start_month": 9,
            "term_count_per_year": 3,
            "term_labels": ["First Term", "Second Term", "Third Term"],
            "grading_scale": "0-100",
            "default_language": "en",
            "default_currency": "NGN",
            "default_timezone": "Africa/Lagos",
            "subject_seed": [
                {"name": "Mathematics", "category": "GENERAL"},
                {"name": "English", "category": "GENERAL"},
                {"name": "Basic Science", "category": "GENERAL"},
                {"name": "Civic Education", "category": "GENERAL"},
                {"name": "Agricultural Science", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "percentage",
                "report_template_family": "west_africa",
            },
        },
        {
            "code": "ken-national-default",
            "name": "Kenya National Secondary",
            "region": "KEN",
            "sub_system": "EN",
            "is_default": True,
            "academic_year_start_month": 1,
            "term_count_per_year": 3,
            "term_labels": ["Term 1", "Term 2", "Term 3"],
            "grading_scale": "0-100",
            "default_language": "sw",
            "default_currency": "KES",
            "default_timezone": "Africa/Nairobi",
            "subject_seed": [
                {"name": "Mathematics", "category": "GENERAL"},
                {"name": "English", "category": "GENERAL"},
                {"name": "Kiswahili", "category": "GENERAL"},
                {"name": "Biology", "category": "GENERAL"},
                {"name": "Chemistry", "category": "GENERAL"},
            ],
            "config": {
                "grading_logic": "percentage",
                "report_template_family": "east_africa",
            },
        },
    ]

    for row in profiles:
        defaults = dict(row)
        region_code = defaults.pop("region")
        defaults["region"] = region_map.get(region_code) if region_code else None
        code = defaults.pop("code")
        EducationSystemProfile.objects.using(db_alias).get_or_create(
            code=code,
            defaults=defaults,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0089_enable_rls_feature_toggle_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionconfig",
            name="term_count_per_year",
            field=models.IntegerField(
                default=3,
                help_text="Number of instructional periods in a school year (1-12).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.CreateModel(
            name="EducationSystemProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "sub_system",
                    models.CharField(
                        choices=[
                            ("ANY", "Any"),
                            ("FR", "French sub-system"),
                            ("EN", "English sub-system"),
                            ("INT", "International"),
                        ],
                        default="ANY",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year_start_month",
                    models.IntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "term_count_per_year",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "term_labels",
                    models.JSONField(
                        blank=True,
                        default=_default_term_labels,
                        help_text='Ordered labels for terms/semesters (e.g. ["Term 1", "Term 2", "Term 3"]).',
                    ),
                ),
                ("grading_scale", models.CharField(default="0-100", max_length=20)),
                ("default_language", models.CharField(default="en", max_length=10)),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("default_timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "subject_seed",
                    models.JSONField(
                        blank=True,
                        default=_default_subject_seed,
                        help_text="Default subjects to seed when onboarding a school.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional profile settings (grading logic, compliance tags, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_profiles",
                        to="siteconfig.regionconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.RunPython(seed_education_profiles, migrations.RunPython.noop),
    ]
