# Generated by Django 5.2.10 on 2026-02-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_school_is_frozen_frozen_reason'),
        ('siteconfig', '0103_regionconfig_grading_rule_global_and_plan_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Province/state code (e.g. NW, CA)', max_length=32)),
                ('name', models.CharField(help_text='Province/state name', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Province / State',
                'verbose_name_plural': 'Provinces / States',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text='Module/feature code (e.g. library, transport, workshop_management).', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System feature',
                'verbose_name_plural': 'System features',
                'ordering': ['system', 'feature_key'],
            },
        ),
        migrations.CreateModel(
            name='TenantSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant system assignment',
                'verbose_name_plural': 'Tenant system assignments',
                'ordering': ['school', 'system'],
            },
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='siteconfig__school__03cea2_idx',
            old_name='siteconfig_s_school__a0e0b4_idx',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='siteconfig__entity__a45c12_idx',
            old_name='siteconfig_s_entity__b1f1c5_idx',
        ),
        migrations.AlterField(
            model_name='customnuance',
            name='logic_data',
            field=models.JSONField(default=dict, help_text='JSON-Logic structure (e.g. {"and": [{">": [{"var": "gpa"}, 3.8]}, {"var": "sibling_count"}]}). Only allowed ops run.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Tier bands for TIERED model, e.g. [{"max": 500, "price": 200}, {"max": 2000, "price": 600}]'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(help_text='Country (region) this province belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='siteconfig.regionconfig'),
        ),
        migrations.AddField(
            model_name='educationsystemprofile',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Optional province/state for filtering systems by geography.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_profiles', to='siteconfig.province'),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_features', to='siteconfig.educationsystemprofile'),
        ),
        migrations.AddField(
            model_name='tenantsystem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_systems', to='schools.school'),
        ),
        migrations.AddField(
            model_name='tenantsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_schools', to='siteconfig.educationsystemprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('region', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='systemfeature',
            unique_together={('system', 'feature_key')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantsystem',
            unique_together={('school', 'system')},
        ),
    ]
