# Generated by Django 5.2.10 on 2026-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0106_add_regionconfig_is_rtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='simple_mode',
            field=models.BooleanField(default=False, help_text='Plan XIV: When True, show simplified UI (consumer-grade).'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='category',
            field=models.CharField(blank=True, choices=[('LMS', 'LMS'), ('PAYMENT', 'Payment'), ('ATTENDANCE', 'Attendance'), ('LIBRARY', 'Library'), ('AI', 'AI'), ('SIS', 'SIS'), ('MESSAGING', 'Messaging'), ('BADGES', 'Badges'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('payments', 'Payments'), ('analytics', 'Analytics'), ('whatsapp', 'WhatsApp Business'), ('push', 'Push Notifications'), ('stripe', 'Stripe'), ('badges', 'Digital Badges'), ('lms', 'LMS'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceintegration',
            name='service_type',
            field=models.CharField(choices=[('LTI', 'LTI 1.3'), ('OAUTH', 'OAuth 2.0 / OpenID'), ('WEBHOOK', 'Webhook outbound'), ('WHATSAPP', 'WhatsApp Business API'), ('PUSH', 'Push Notifications'), ('STRIPE', 'Stripe'), ('BADGES', 'Digital Badges / Open Badges'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
