# Generated by Django 5.1.1 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0113_seed_regional_pitch_cameroon_canada"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalBrandRegistry",
            fields=[
                (
                    "iso_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g. CM, CA, BR).",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_name", models.CharField(max_length=120)),
                (
                    "primary_language",
                    models.CharField(
                        default="en",
                        help_text="Primary language code for this country profile (e.g. en, fr, ar).",
                        max_length=16,
                    ),
                ),
                (
                    "academic_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ISCED levels, term structure, grading defaults, and education nuances.",
                    ),
                ),
                (
                    "labels_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Terminology map (student, teacher, principal, etc.) for UI hydration.",
                    ),
                ),
                (
                    "compliance_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data residency and privacy-law defaults for this country.",
                    ),
                ),
                (
                    "seo_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Marketing SEO defaults (headlines, summaries, proof points, metadata).",
                    ),
                ),
                (
                    "ui_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="UI defaults such as date format, number separators, RTL, and locale hints.",
                    ),
                ),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        default="global_catalog",
                        help_text="Data source name (e.g. global_catalog, unesco_uis, manual).",
                        max_length=64,
                    ),
                ),
                ("source_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global brand registry",
                "verbose_name_plural": "Global brand registry",
                "ordering": ["iso_code"],
            },
        ),
    ]
