# Generated by Django 5.2.10 on 2026-03-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0115_runmycampus_platform_neutral_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="report_preview_footer_note",
            field=models.CharField(
                blank=True,
                default="Powered by RunMyCampus.",
                help_text="Footer note text shown on report previews.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="School System", max_length=120),
        ),
    ]
