# Generated by Django 5.2.10 on 2026-03-04 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0116_alter_sitesettings_report_preview_footer_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code (e.g. subject-grade-topic).', max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='siteconfig.globalsyllabus')),
            ],
            options={
                'verbose_name': 'Global syllabus node',
                'verbose_name_plural': 'Global syllabus nodes',
                'ordering': ['country_code', 'sort_order', 'code'],
            },
        ),
    ]
