# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0121_add_ai_embedding_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalaiconfig',
            name='preferred_model_id',
            field=models.CharField(
                blank=True,
                help_text='Optional override: when set, used instead of registry/default (Super Admin can flip without touching LB).',
                max_length=128,
            ),
        ),
    ]
