# Generated by Django 5.2.10 on 2026-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0124_add_dashboard_template_and_tenant_layout_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admission_number_strategy',
            field=models.CharField(blank=True, choices=[('FULL', 'Full (YY+School+Seq+Spec+Class)'), ('YEAR_SEQ', 'Year + sequence only'), ('SEQ_ONLY', 'Sequence only')], default='FULL', help_text='Built-in generation strategy when no template is set.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admission_number_template',
            field=models.CharField(blank=True, default='', help_text='Optional template with placeholders: {year_2digit}, {school_code}, {seq_4digit}, {spec_code}, {class_segment}. Overrides strategy when set.', max_length=255),
        ),
    ]
