# Generated by Django 5.2.10 on 2026-03-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
        ('siteconfig', '0130_add_workflow_run_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, help_text='Primary tenant logo URL.')),
                ('logo_dark_url', models.URLField(blank=True, help_text='Optional dark-surface logo URL.')),
                ('favicon_url', models.URLField(blank=True, help_text='Optional tenant favicon URL.')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=20)),
                ('accent_color', models.CharField(default='#198754', max_length=20)),
                ('font_family', models.CharField(blank=True, max_length=160)),
                ('login_background_url', models.URLField(blank=True)),
                ('portal_visual', models.CharField(blank=True, max_length=120)),
                ('email_template', models.CharField(blank=True, max_length=120)),
                ('pdf_template', models.CharField(blank=True, max_length=120)),
                ('certificate_template', models.CharField(blank=True, max_length=120)),
                ('tokens', models.JSONField(blank=True, default=dict, help_text='Theme tokens used across login, portal, reports, and emails.')),
                ('templates', models.JSONField(blank=True, default=dict, help_text='Template and layout bindings for branded surfaces.')),
                ('assets', models.JSONField(blank=True, default=dict, help_text='Versioned asset references and brand media metadata.')),
                ('custom_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='schools.school')),
            ],
            options={
                'verbose_name': 'Brand profile',
                'verbose_name_plural': 'Brand profiles',
            },
        ),
    ]
