# Generated by Django 5.2.10 on 2026-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0132_section_22_tenant_admission_number_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtemplate",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Level 1: Locked global default (safety/legal)"),
                    (
                        2,
                        "Level 2: Configurable template (tenant chooses approved variants)",
                    ),
                    (
                        3,
                        "Level 3: Constrained custom (tenant customizes within safe boundaries)",
                    ),
                ],
                default=2,
                help_text="Section 5: 1=locked, 2=configurable template, 3=constrained custom.",
            ),
        ),
    ]
