# Generated by Django 5.2.10 on 2026-03-07 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_add_default_workflow_dashboard_slugs'),
        ('siteconfig', '0135_workflow_template_certified_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(db_index=True, help_text='Form identifier, e.g. backend_student_create, application_form.', max_length=80)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Serialized form field values (safe to rehydrate into form).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_drafts', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form draft',
                'verbose_name_plural': 'Form drafts',
                'ordering': ['-updated_at'],
                'unique_together': {('school', 'user', 'form_key')},
            },
        ),
    ]
