# Generated by Django 5.2.10 on 2026-03-13 18:18
# Alter EducationSystemProfile subject_seed/term_labels (help_text + default alignment).

from django.db import migrations, models


def _default_term_labels():
    return ["Term 1", "Term 2", "Term 3"]


def _default_subject_seed():
    return [
        {"name": "Mathematics", "category": "GENERAL"},
        {"name": "English", "category": "GENERAL"},
        {"name": "Science", "category": "GENERAL"},
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0155_normalize_gilead_residue_runmycampus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationsystemprofile",
            name="subject_seed",
            field=models.JSONField(
                blank=True,
                default=_default_subject_seed,
                help_text="Default subjects to seed when onboarding a school.",
            ),
        ),
        migrations.AlterField(
            model_name="educationsystemprofile",
            name="term_labels",
            field=models.JSONField(
                blank=True,
                default=_default_term_labels,
                help_text='Ordered labels for terms/semesters (e.g. ["Term 1", "Term 2", "Term 3"]).',
            ),
        ),
    ]
