# Generated by Django 5.2.10 on 2026-03-16 01:16

from decimal import Decimal
from django.db import migrations, models


def default_education_subject_seed():
    """Inlined from ``apps.siteconfig.models_platform_catalog.default_education_subject_seed``
    for migration historical-state safety.
    """
    return [
        {"name": "Mathematics", "category": "GENERAL"},
        {"name": "English", "category": "GENERAL"},
        {"name": "Science", "category": "GENERAL"},
    ]


def default_education_term_labels():
    """Inlined from ``apps.siteconfig.models_platform_catalog.default_education_term_labels``
    for migration historical-state safety.
    """
    return ["Term 1", "Term 2", "Term 3"]


class Migration(migrations.Migration):
    dependencies = [
        ("siteconfig", "0156_alter_educationsystemprofile_subject_seed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationsystemprofile",
            name="subject_seed",
            field=models.JSONField(
                blank=True,
                default=default_education_subject_seed,
                help_text="Default subjects to seed when onboarding a school.",
            ),
        ),
        migrations.AlterField(
            model_name="educationsystemprofile",
            name="term_labels",
            field=models.JSONField(
                blank=True,
                default=default_education_term_labels,
                help_text='Ordered labels for terms/semesters (e.g. ["Term 1", "Term 2", "Term 3"]).',
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="finance_bank_verification_amount_tolerance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Amount tolerance when matching by amount + date, in tenant's currency (default: 1.00).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="finance_receipt_amount_tolerance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Tolerance for amount matching in tenant's currency (e.g., 1.00 units difference allowed).",
                max_digits=10,
            ),
        ),
    ]
