# Generated by Django 5.2.10 on 2026-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0165_globalsupportticket_thread_csat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSupportTicketWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, default='', help_text='Optional HMAC secret (same contract as SUPPORT_TICKET_WEBHOOK_SECRET).', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global support ticket webhook endpoint',
                'verbose_name_plural': 'Global support ticket webhook endpoints',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
