# Generated by Django 5.2.10 on 2026-04-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
        ('siteconfig', '0168_remove_legacy_dynamicfield_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAutomationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('trigger', models.CharField(db_index=True, help_text='Domain trigger e.g. student_updated, payment_received.', max_length=80)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Conditions: [{"field": "...", "op": "eq", "value": ...}].')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Actions: [{"type": "notify", "params": {...}}].')),
                ('graph', models.JSONField(blank=True, default=dict, help_text='Visual builder graph: nodes/edges for drag-drop UI.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='When false, engine skips this workflow even if published.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_automation_workflows', to='schools.school')),
            ],
            options={
                'verbose_name': 'School automation workflow',
                'verbose_name_plural': 'School automation workflows',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolWorkflowCreatedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_created_records', to='schools.school')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='siteconfig.schoolautomationworkflow')),
            ],
            options={
                'verbose_name': 'School workflow created record',
                'verbose_name_plural': 'School workflow created records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolWorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions_passed', models.BooleanField(default=False)),
                ('actions_run', models.JSONField(default=list)),
                ('context_keys', models.JSONField(default=list)),
                ('run_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='siteconfig.schoolautomationworkflow')),
            ],
            options={
                'verbose_name': 'School workflow execution log',
                'verbose_name_plural': 'School workflow execution logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolautomationworkflow',
            index=models.Index(fields=['school', 'trigger', 'status'], name='siteconfig__school__830a4e_idx'),
        ),
    ]
