# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.siteconfig.models
import apps.siteconfig.models_platform_catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0172_regionconfig_neutral_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsystemprofile',
            name='subject_seed',
            field=models.JSONField(blank=True, default=apps.siteconfig.models_platform_catalog.default_education_subject_seed, help_text='Default subjects to seed when onboarding a school.'),
        ),
        migrations.AlterField(
            model_name='educationsystemprofile',
            name='term_labels',
            field=models.JSONField(blank=True, default=apps.siteconfig.models_platform_catalog.default_education_term_labels, help_text='Ordered labels for terms/semesters (e.g. ["Term 1", "Term 2", "Term 3"]).'),
        ),
        migrations.AlterField(
            model_name='waiverrequest',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Proof of NGO / non-profit status', upload_to=apps.siteconfig.models.tenant_upload_to_waiver_requests),
        ),
    ]
