# Generated by Django 5.2.10 on 2026-05-15 22:42

import apps.siteconfig.svg_sanitize
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0173_alter_educationsystemprofile_subject_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardstyle',
            name='watermark_logo',
            field=models.ImageField(blank=True, help_text="Optional custom watermark logo used when mode is 'Use style logo'.", null=True, upload_to='branding/reportcard/watermarks/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
        migrations.AlterField(
            model_name='themepack',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional: Logo for this theme pack.', null=True, upload_to='branding/themepack/logo/', validators=[apps.siteconfig.svg_sanitize.validate_svg_safe]),
        ),
    ]
