# Generated by Django 5.2.10 on 2026-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0176_tourstep_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourstep',
            name='code',
            field=models.CharField(db_index=True, help_text='Step id; should match a data-tour attribute when selector is blank.', max_length=80),
        ),
    ]
