# Generated by Django 5.2.10 on 2026-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolops', '0011_possaleline_tax'),
        ('schools', '0051_add_default_language'),
        ('siteconfig', '0177_alter_tourstep_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceintegration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='serviceintegration',
            constraint=models.UniqueConstraint(fields=('school', 'campus', 'service_name'), name='serviceintegration_school_campus_service_uniq'),
        ),
    ]
