# Generated by Django 5.2.10 on 2026-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0192_close_migration_drift_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnuance',
            name='hook_point',
            field=models.CharField(choices=[('tuition_calc', 'Tuition / fee calculation'), ('grade_weight', 'Grade weighting'), ('attendance_alert', 'Attendance alerts'), ('fee_discount', 'Fee discount eligibility'), ('report_card_avg', 'Report card weighted average'), ('generic', 'Generic (custom)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingnuance',
            name='hook_point',
            field=models.CharField(choices=[('tuition_calc', 'Tuition / fee calculation'), ('grade_weight', 'Grade weighting'), ('attendance_alert', 'Attendance alerts'), ('fee_discount', 'Fee discount eligibility'), ('report_card_avg', 'Report card weighted average'), ('generic', 'Generic (custom)')], max_length=50),
        ),
    ]
