# Generated by Django 5.2.10 on 2026-06-23 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0200_plan_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2/3 (matches CountryMultiplier)', max_length=3)),
                ('subdivision_code', models.CharField(help_text="Subdivision code within the country (e.g. 'CA', 'NY', 'ON').", max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Sales/consumption tax rate for this subdivision (e.g. 0.0725 for 7.25%).', max_digits=5)),
                ('tax_code', models.CharField(blank=True, help_text='Local tax code identifier (e.g. PST, HST, state sales tax); informational only.', max_length=32)),
                ('name', models.CharField(blank=True, help_text="Subdivision name (e.g. 'California').", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subdivision tax rate',
                'verbose_name_plural': 'Subdivision tax rates',
                'ordering': ['country_code', 'subdivision_code'],
                'unique_together': {('country_code', 'subdivision_code')},
            },
        ),
    ]
