# Generated by Django 5.2.10 on 2026-06-23 13:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0074_schoolmembership_is_school_owner'),
        ('siteconfig', '0201_subdivision_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='regional_sku_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-country price overrides keyed by ISO country code (B2), e.g. {"NG": "15000", "IN": "999"}. When a tenant\'s country has an override, that explicit amount is used as the localized subtotal instead of base_price x PPP multiplier — letting one market be repriced without changing the global pricing formula.'),
        ),
        migrations.CreateModel(
            name='HoldingCurrencyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of sub-school billing totals in this currency (no FX conversion).', max_digits=16)),
                ('source_school_count', models.PositiveIntegerField(default=0, help_text='How many sub-schools contributed to this currency bucket.')),
                ('as_of', models.DateTimeField(help_text='When this rollup was materialized.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_school', models.ForeignKey(help_text='The holding company (parent school) this rollup belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='currency_rollups', to='schools.school')),
            ],
            options={
                'verbose_name': 'Holding currency rollup',
                'verbose_name_plural': 'Holding currency rollups',
                'ordering': ['parent_school', 'currency_code'],
                'unique_together': {('parent_school', 'currency_code')},
            },
        ),
    ]
