# Generated by Django 5.2.10 on 2026-05-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_phase10_orchestration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinition',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProcessDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orchestration.processdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['definition', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='orchestrationrun',
            name='definition_version',
            field=models.ForeignKey(blank=True, help_text='Move 2: the exact version snapshot this run is bound to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='orchestration.processdefinitionversion'),
        ),
        migrations.CreateModel(
            name='OrchestrationSLOMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('runs_total', models.PositiveIntegerField(default=0)),
                ('runs_succeeded', models.PositiveIntegerField(default=0)),
                ('runs_failed', models.PositiveIntegerField(default=0)),
                ('runs_sla_breached', models.PositiveIntegerField(default=0)),
                ('p50_latency_ms', models.PositiveIntegerField(default=0)),
                ('p95_latency_ms', models.PositiveIntegerField(default=0)),
                ('p99_latency_ms', models.PositiveIntegerField(default=0)),
                ('queue_depth_max', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slo_metrics', to='orchestration.processdefinition')),
            ],
            options={
                'ordering': ['-window_start', 'definition'],
                'unique_together': {('definition', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='OrchestrationStepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Monotonic position within this run (1, 2, 3, ...).')),
                ('event_type', models.CharField(choices=[('run_created', 'Run created'), ('run_started', 'Run started'), ('step_started', 'Step started'), ('step_succeeded', 'Step succeeded'), ('step_failed', 'Step failed'), ('retry_scheduled', 'Retry scheduled'), ('run_completed', 'Run completed'), ('run_failed', 'Run failed'), ('run_cancelled', 'Run cancelled'), ('compensation_started', 'Compensation started'), ('compensation_completed', 'Compensation completed')], db_index=True, max_length=32)),
                ('step_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orchestration.orchestrationrun')),
            ],
            options={
                'ordering': ['run', 'sequence_number'],
                'indexes': [models.Index(fields=['run', 'event_type'], name='orch_evt_run_type_idx')],
                'unique_together': {('run', 'sequence_number')},
            },
        ),
        migrations.AddIndex(
            model_name='processdefinitionversion',
            index=models.Index(fields=['definition', 'is_current'], name='orch_pdv_def_cur_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processdefinitionversion',
            unique_together={('definition', 'version_number')},
        ),
    ]
