# Generated by Django 5.2.10 on 2026-08-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0083_force_rls_late_enabled_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncApplyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('local_pk', models.CharField(max_length=64)),
                ('applied_updated_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, default='', max_length=32)),
                ('applied_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_apply_ledger', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sync apply ledger entry',
                'verbose_name_plural': 'Sync apply ledger',
                'indexes': [models.Index(fields=['school', 'entity_type'], name='sync_engine_school__687d7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'entity_type', 'local_pk'), name='uq_syncapplyledger_row')],
            },
        ),
    ]
