# Generated by Django 5.2.10 on 2026-08-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0005_edgesyncrun_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgesyncrun',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SyncTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('local_pk', models.CharField(max_length=64)),
                ('client_offline_id', models.CharField(blank=True, default='', max_length=64)),
                ('deleted_at', models.DateTimeField(db_index=True)),
                ('origin', models.CharField(blank=True, default='', max_length=32)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tombstones', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sync tombstone',
                'verbose_name_plural': 'Sync tombstones',
                'ordering': ['deleted_at'],
                'indexes': [models.Index(fields=['school', 'deleted_at'], name='sync_engine_school__09c611_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'entity_type', 'local_pk'), name='uq_synctombstone_row')],
            },
        ),
    ]
