# Generated by Django 5.2.10 on 2026-08-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0006_synctombstone_and_deleted_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBundleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('direction', models.CharField(blank=True, default='', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_bundle_receipts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sync bundle receipt',
                'verbose_name_plural': 'Sync bundle receipts',
                'indexes': [models.Index(fields=['school', 'received_at'], name='sync_engine_school__1a9a39_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'nonce'), name='uq_syncbundlereceipt_school_nonce')],
            },
        ),
        migrations.CreateModel(
            name='SyncFileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=8)),
                ('relative_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('bytes_done', models.BigIntegerField(default=0)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'In progress'), ('DONE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('local_pk', models.CharField(blank=True, default='', max_length=64)),
                ('field_name', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_file_transfers', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sync file transfer',
                'verbose_name_plural': 'Sync file transfers',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['school', 'state'], name='sync_engine_school__f000e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'direction', 'relative_path'), name='uq_syncfiletransfer_target')],
            },
        ),
    ]
