# Generated by Django 5.2.14 on 2026-08-20 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0009_rls_policy_default_deny'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgePairingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_slug', models.CharField(blank=True, default='', max_length=100)),
                ('user_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('poll_secret_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved, awaiting collection'), ('redeemed', 'Credential collected'), ('denied', 'Denied'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('box_label', models.CharField(blank=True, default='', max_length=120)),
                ('box_hostname', models.CharField(blank=True, default='', max_length=253)),
                ('box_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('box_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('denied_reason', models.CharField(blank=True, default='', max_length=200)),
                ('credential_device_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('poll_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edge_pairing_requests', to='schools.school')),
            ],
            options={
                'verbose_name': 'Edge pairing request',
                'verbose_name_plural': 'Edge pairing requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='sync_engine_school__ea321e_idx'), models.Index(fields=['status', 'expires_at'], name='sync_engine_status_f92650_idx')],
            },
        ),
    ]
