# Generated by Django 5.2.14 on 2026-08-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0009_rls_policy_default_deny'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="What this rule is for, e.g. 'Term time' or 'Overnight catch-up'.", max_length=80)),
                ('is_enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('INTERVAL', 'Every N minutes, within a window'), ('AT_TIMES', 'At specific times')], default='INTERVAL', max_length=16)),
                ('days_of_week', models.CharField(blank=True, default='0,1,2,3,4,5,6', max_length=32)),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('at_times', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client_offline_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='schools.school')),
            ],
            options={
                'verbose_name': 'sync schedule rule',
                'verbose_name_plural': 'sync schedule rules',
                'ordering': ('school_id', 'id'),
                'indexes': [models.Index(fields=['school', 'is_enabled'], name='sync_engine_school__07e082_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_syncschedule_school_offline_id')],
            },
        ),
    ]
