# Generated by Django 5.2.14 on 2026-08-20 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0011_edgecloudbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPushConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.CharField(db_index=True, max_length=64)),
                ('high_water', models.CharField(blank=True, default='', max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('built_at', models.BigIntegerField(default=0)),
                ('failure', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_push_confirmations', to='schools.school')),
            ],
            options={
                'verbose_name': 'Pending push confirmation',
                'verbose_name_plural': 'Pending push confirmations',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'nonce'), name='uq_pendingpushconfirmation_nonce')],
            },
        ),
    ]
