# Generated by Django 5.2.14 on 2026-08-20 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0012_pendingpushconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeClaimTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('misuse_attempts', models.PositiveIntegerField(default=0)),
                ('last_misuse_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('redeemed_by_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sync_engine.edgepairingrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_claim_tickets', to='schools.school')),
            ],
            options={
                'verbose_name': 'Edge claim ticket',
                'verbose_name_plural': 'Edge claim tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'redeemed_at'], name='sync_engine_school__082fc4_idx')],
            },
        ),
    ]
