# Generated by Django 5.2.14 on 2026-08-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0014_merge_0011_syncschedule_rls_0013_edgeclaimticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_ceiling_minutes', models.PositiveIntegerField(default=60, help_text='Longest this box may go without checking in, even when no run is scheduled. The cloud cannot contact a box, so this is also how long an operator instruction can take to arrive.')),
                ('catch_up_missed', models.BooleanField(default=True, help_text='If the box was off or offline through a scheduled time, sync once as soon as it is back instead of waiting for the next scheduled time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client_offline_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_policy', to='schools.school')),
            ],
            options={
                'verbose_name': 'sync policy',
                'verbose_name_plural': 'sync policies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_syncpolicy_school_offline_id')],
            },
        ),
    ]
