# Generated by Django 5.2.14 on 2026-08-22 15:08

import apps.platform_runtime.append_only
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_engine', '0017_pairing_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeDeploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifest_hash', models.CharField(db_index=True, max_length=64)),
                ('previous_manifest_hash', models.CharField(blank=True, default='', max_length=64)),
                ('version_label', models.CharField(blank=True, default='', max_length=64)),
                ('channel', models.CharField(blank=True, default='stable', max_length=32)),
                ('engine_commit', models.CharField(blank=True, default='', max_length=64)),
                ('release_id', models.CharField(blank=True, default='', max_length=64)),
                ('release_path', models.CharField(blank=True, default='', max_length=500)),
                ('files_total', models.IntegerField(default=0)),
                ('files_verified', models.IntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('migrations_applied', models.JSONField(blank=True, default=list)),
                ('complete', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, default='', max_length=16)),
                ('activation', models.CharField(blank=True, default='', max_length=16)),
                ('state', models.CharField(choices=[('STAGED', 'Staged'), ('VERIFIED', 'Verified'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ROLLED_BACK', 'Rolled back'), ('FAILED', 'Failed')], db_index=True, default='STAGED', max_length=16)),
                ('health_ok', models.BooleanField(default=False)),
                ('health_seconds', models.FloatField(default=0.0)),
                ('health_detail', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('staged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Edge deployment history',
                'verbose_name_plural': 'Edge deployment history',
                'ordering': ['-staged_at'],
                'indexes': [models.Index(fields=['state', '-staged_at'], name='sync_engine_state_203b29_idx'), models.Index(fields=['manifest_hash', '-staged_at'], name='sync_engine_manifes_38d23d_idx')],
            },
            bases=(apps.platform_runtime.append_only.AppendOnlyModelMixin, models.Model),
        ),
    ]
