# Generated by Django 5.2.14 on 2026-08-22 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_alter_marketing_funnel_event_types'),
        ('sync_engine', '0020_rollout_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeFleetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_manifest_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reported_engine', models.CharField(blank=True, default='', max_length=64)),
                ('offered_manifest_hash', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_manifest_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_text', models.CharField(blank=True, default='', max_length=500)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edge_fleet_state', to='schools.school')),
            ],
            options={
                'verbose_name': 'Edge fleet state',
                'verbose_name_plural': 'Edge fleet state',
            },
        ),
    ]
