# Generated by Django 5.2.14 on 2026-08-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0087_alter_school_subdomain'),
        ('sync_engine', '0022_fleet_state_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('local_pk', models.CharField(max_length=64)),
                ('client_offline_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('origin', models.CharField(blank=True, default='', max_length=32)),
                ('attempts', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_dead_letters', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sync dead letter',
                'verbose_name_plural': 'Sync dead letters',
                'ordering': ['first_seen_at'],
                'indexes': [models.Index(fields=['school', 'resolved_at', 'first_seen_at'], name='sync_engine_school__5f8917_idx'), models.Index(fields=['resolved_at', 'first_seen_at'], name='sync_engine_resolve_ea1f50_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'entity_type', 'local_pk', 'reason'), name='uq_syncdeadletter_row')],
            },
        ),
    ]
