# Generated by Django 5.2.10 on 2026-04-30 10:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policybundle_policy_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintpack',
            name='is_premium_commercial',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, apply/upgrade may require commercial entitlement.'),
        ),
        migrations.AddField(
            model_name='blueprintpack',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commercial list price for premium blueprint packs (billing integration).', max_digits=12),
        ),
    ]
