"""
Platform bootstrap: Seed migration connector profiles so the Migration Cloud has
starter profiles (CSV/XLSX, student/finance/attendance/grades, generic SIS).
Idempotent (update_or_create by slug). Run: python manage.py seed_migration_profiles
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.automation.models import MigrationProfile


# Schema hints: source column names → canonical field (for auto-mapping).
# Keys are lowercase/alternate names often seen in exports.
POWERSCHOOL_STUDENT_HINTS = {
    "student_number": "admission_number",
    "student_id": "admission_number",
    "first_name": "first_name",
    "last_name": "last_name",
    "firstname": "first_name",
    "lastname": "last_name",
    "grade_level": "academic_year",
    "grade": "academic_year",
    "homeroom": "classroom",
    "class": "classroom",
    "status": "status",
}
BLACKBAUD_STUDENT_HINTS = {
    "student_id": "admission_number",
    "first_name": "first_name",
    "last_name": "last_name",
    "grade_level": "academic_year",
    "grade": "academic_year",
    "form": "academic_year",
    "year_group": "academic_year",
    "homeroom": "classroom",
    "advisor": "classroom",
    "status": "status",
}
VERACROSS_STUDENT_HINTS = {
    "person_id": "admission_number",
    "student_id": "admission_number",
    "first_name": "first_name",
    "last_name": "last_name",
    "grade": "academic_year",
    "form": "academic_year",
    "section": "classroom",
    "advisor": "classroom",
    "status": "status",
}
INFINITE_CAMPUS_STUDENT_HINTS = {
    "student_id": "admission_number",
    "student_number": "admission_number",
    "firstName": "first_name",
    "lastName": "last_name",
    "grade": "academic_year",
    "schoolYear": "academic_year",
    "homeroom": "classroom",
    "status": "status",
}
FACTS_STUDENT_HINTS = {
    # Pass 8.C: widened so a typical FACTS Mgr / FACTS SIS export crosses
    # the 0.8 auto-detect confidence floor without manual mapping.
    "student_id": "admission_number",
    "student_number": "admission_number",
    "student_dcid": "admission_number",
    "factsid": "admission_number",
    "facts_id": "admission_number",
    "first_name": "first_name",
    "preferred_first": "first_name",
    "first": "first_name",
    "last_name": "last_name",
    "last": "last_name",
    "grade_level": "academic_year",
    "grade": "academic_year",
    "school_year": "academic_year",
    "homeroom": "classroom",
    "homeroom_teacher": "classroom",
    "class_of": "specialty",
    "enrollment_status": "status",
    "status": "status",
}
SKYWARD_STUDENT_HINTS = {
    # Pass 8.C: widened with Skyward "Other ID", Family School, and Counselor
    # columns common in district exports.
    "student_number": "admission_number",
    "student_id": "admission_number",
    "other_id": "admission_number",
    "other id": "admission_number",
    "alpha_key": "admission_number",
    "first_name": "first_name",
    "first name": "first_name",
    "last_name": "last_name",
    "last name": "last_name",
    "grade_level": "academic_year",
    "grade": "academic_year",
    "grad_year": "specialty",
    "homeroom": "classroom",
    "homeroom_teacher": "classroom",
    "primary_teacher": "classroom",
    "primary teacher": "classroom",
    "counselor": "specialty",
    "status": "status",
    "enrollment_status": "status",
}
ALMA_STUDENT_HINTS = {
    # Pass 8.C: widened to cover Alma's roster CSV (Student ID + Section +
    # Advisor naming).
    "student_id": "admission_number",
    "student id": "admission_number",
    "alma_id": "admission_number",
    "first_name": "first_name",
    "first name": "first_name",
    "preferred_name": "first_name",
    "last_name": "last_name",
    "last name": "last_name",
    "grade_level": "academic_year",
    "grade level": "academic_year",
    "grade": "academic_year",
    "section": "classroom",
    "homeroom": "classroom",
    "advisor": "classroom",
    "house": "specialty",
    "status": "status",
    "enrollment_status": "status",
}

# Official starter migration profiles (audit pack + Phase A competitor adapters)
MIGRATION_PROFILES = [
    # Generic / Other (no source_system)
    {
        "slug": "students",
        "name": "Student import",
        "description": "Import students from CSV or XLSX (first_name, last_name, admission_number, classroom, etc.).",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": None,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
        },
        "sort_order": 10,
    },
    {
        "slug": "grades",
        "name": "Grades import",
        "description": "Import grades from CSV or XLSX (student_code, subject_assignment_id, term_id, scores).",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": None,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
        },
        "sort_order": 20,
    },
    {
        "slug": "finance_import",
        "name": "Fees / invoices import",
        "description": "Import fee structures or invoices from CSV or XLSX. (Persistence to the Invoice model lands in pass 8.B.)",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.FINANCE,
        "source_system": None,
        "config": {
            "label": "Fees / invoices",
            "migration_type": "fees",
            "target_fields": [
                "invoice_number",
                "student_code",
                "amount",
                "currency",
                "due_date",
                "status",
                "fee_type",
                "academic_year",
                "term_name",
            ],
            "required": ["student_code", "amount"],
        },
        "sort_order": 30,
    },
    {
        "slug": "payments_import",
        "name": "Payments import",
        "description": "Import payment records from CSV or XLSX. (Persistence to the Payment model lands in pass 8.B.)",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.FINANCE,
        "source_system": None,
        "config": {
            "label": "Payments",
            "migration_type": "payments",
            "target_fields": [
                "payment_reference",
                "student_code",
                "amount",
                "currency",
                "paid_at",
                "method",
                "invoice_number",
                "notes",
            ],
            "required": ["student_code", "amount", "paid_at"],
        },
        "sort_order": 31,
    },
    {
        "slug": "attendance_import",
        "name": "Attendance import",
        "description": "Import attendance records from CSV or XLSX. Status values: present, absent, late, excused.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.ATTENDANCE,
        "source_system": None,
        "config": {
            "label": "Attendance",
            "migration_type": "attendance",
            "target_fields": [
                "student_code",
                "date",
                "status",
                "session",
                "remarks",
                "recorded_by_username",
            ],
            "required": ["student_code", "date", "status"],
        },
        "sort_order": 40,
    },
    {
        "slug": "teachers_import",
        "name": "Teachers import",
        "description": "Import teacher staff records from CSV or XLSX; auto-creates User + TeacherProfile + SchoolMembership.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": None,
        "config": {
            "label": "Teachers",
            "migration_type": "teachers",
            "target_fields": [
                "username",
                "email",
                "first_name",
                "last_name",
                "phone",
                "subject_specialty",
                "employment_status",
            ],
            "required": ["email", "first_name", "last_name"],
        },
        "sort_order": 11,
    },
    {
        "slug": "guardians_import",
        "name": "Parents / Guardians import",
        "description": "Import parents and link them to existing students by student_code (comma-separated).",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": None,
        "config": {
            "label": "Parents / Guardians",
            "migration_type": "guardians",
            "target_fields": [
                "username",
                "email",
                "first_name",
                "last_name",
                "phone",
                "relationship",
                "student_codes",
            ],
            "required": ["email", "first_name", "last_name", "student_codes"],
        },
        "sort_order": 12,
    },
    {
        "slug": "roster_import",
        "name": "Roster import (classroom + subject + term)",
        "description": "Composite import: creates Classroom, Subject, and Term rows in one wizard step. SubjectAssignment links are deferred to pass 8.B.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": None,
        "config": {
            "label": "Roster",
            "migration_type": "roster",
            "target_fields": [
                "classroom_name",
                "subject_code",
                "subject_name",
                "term_name",
                "teacher_username",
                "academic_year",
            ],
            "required": ["classroom_name", "subject_code"],
        },
        "sort_order": 13,
    },
    {
        "slug": "generic_sis",
        "name": "Generic SIS profile",
        "description": "Generic SIS connector for mapping external student information system data.",
        "format": MigrationProfile.Format.GENERIC_SIS,
        "domain": MigrationProfile.Domain.GENERIC_SIS,
        "source_system": None,
        "config": {"label": "Generic SIS", "target_fields": [], "required": []},
        "sort_order": 50,
    },
    # Phase A: PowerSchool adapters
    {
        "slug": "students_from_powerschool",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Student import (from PowerSchool)",
        "description": "Import students from PowerSchool CSV export. Column names are auto-mapped.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.POWERSCHOOL,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": POWERSCHOOL_STUDENT_HINTS,
        },
        "sort_order": 61,
    },
    {
        "slug": "grades_from_powerschool",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Grades import (from PowerSchool)",
        "description": "Import grades from PowerSchool export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.POWERSCHOOL,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            "schema_hints": {
                "student_id": "student_code",
                "student_number": "student_code",
                "course_name": "subject_assignment_id",
                "term": "term_id",
            },
        },
        "sort_order": 62,
    },
    # Blackbaud adapters
    {
        "slug": "students_from_blackbaud",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Student import (from Blackbaud)",
        "description": "Import students from Blackbaud CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.BLACKBAUD,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": BLACKBAUD_STUDENT_HINTS,
        },
        "sort_order": 71,
    },
    {
        "slug": "grades_from_blackbaud",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Grades import (from Blackbaud)",
        "description": "Import grades from Blackbaud export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.BLACKBAUD,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            "schema_hints": {
                "student_id": "student_code",
                "course": "subject_assignment_id",
                "term": "term_id",
            },
        },
        "sort_order": 72,
    },
    # Veracross adapters
    {
        "slug": "students_from_veracross",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Student import (from Veracross)",
        "description": "Import students from Veracross CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.VERACROSS,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": VERACROSS_STUDENT_HINTS,
        },
        "sort_order": 81,
    },
    {
        "slug": "grades_from_veracross",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Grades import (from Veracross)",
        "description": "Import grades from Veracross export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.VERACROSS,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            "schema_hints": {
                "person_id": "student_code",
                "student_id": "student_code",
                "course_id": "subject_assignment_id",
                "term": "term_id",
            },
        },
        "sort_order": 82,
    },
    # Infinite Campus adapters
    {
        "slug": "students_from_infinite_campus",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Student import (from Infinite Campus)",
        "description": "Import students from Infinite Campus CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.INFINITE_CAMPUS,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": INFINITE_CAMPUS_STUDENT_HINTS,
        },
        "sort_order": 91,
    },
    {
        "slug": "grades_from_infinite_campus",
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "name": "Grades import (from Infinite Campus)",
        "description": "Import grades from Infinite Campus export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.INFINITE_CAMPUS,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            "schema_hints": {
                "student_id": "student_code",
                "section_id": "subject_assignment_id",
                "term": "term_id",
            },
        },
        "sort_order": 92,
    },
    # FACTS adapters
    {
        "slug": "students_from_facts",
        "name": "Student import (from FACTS)",
        "description": "Import students from FACTS CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.FACTS,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": FACTS_STUDENT_HINTS,
        },
        "sort_order": 101,
    },
    {
        "slug": "grades_from_facts",
        "name": "Grades import (from FACTS)",
        "description": "Import grades from FACTS export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.FACTS,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            # Pass 8.C: FACTS-flavored grade-book column names.
            "schema_hints": {
                "student_id": "student_code",
                "student_number": "student_code",
                "facts_id": "student_code",
                "course": "subject_assignment_id",
                "course_id": "subject_assignment_id",
                "section": "subject_assignment_id",
                "term": "term_id",
                "trimester": "term_id",
                "marking_period": "term_id",
                "teacher": "teacher_username",
                "instructor": "teacher_username",
            },
        },
        "sort_order": 102,
    },
    # Skyward adapters
    {
        "slug": "students_from_skyward",
        "name": "Student import (from Skyward)",
        "description": "Import students from Skyward CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.SKYWARD,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": SKYWARD_STUDENT_HINTS,
        },
        "sort_order": 111,
    },
    {
        "slug": "grades_from_skyward",
        "name": "Grades import (from Skyward)",
        "description": "Import grades from Skyward export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.SKYWARD,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            # Pass 8.C: Skyward-flavored grade-book column names.
            "schema_hints": {
                "student_id": "student_code",
                "student_number": "student_code",
                "other_id": "student_code",
                "course": "subject_assignment_id",
                "course_code": "subject_assignment_id",
                "section_code": "subject_assignment_id",
                "section": "subject_assignment_id",
                "marking_period": "term_id",
                "term": "term_id",
                "quarter": "term_id",
                "primary_teacher": "teacher_username",
                "teacher": "teacher_username",
            },
        },
        "sort_order": 112,
    },
    # Alma adapters
    {
        "slug": "students_from_alma",
        "name": "Student import (from Alma)",
        "description": "Import students from Alma CSV export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.ALMA,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Students",
            "target_fields": [
                "first_name",
                "last_name",
                "admission_number",
                "academic_year",
                "classroom",
                "specialty",
                "status",
            ],
            "required": ["first_name", "last_name"],
            "schema_hints": ALMA_STUDENT_HINTS,
        },
        "sort_order": 121,
    },
    {
        "slug": "grades_from_alma",
        "name": "Grades import (from Alma)",
        "description": "Import grades from Alma export.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.GRADES,
        "source_system": MigrationProfile.SourceSystem.ALMA,
        "profile_category": MigrationProfile.ProfileCategory.VENDOR,
        "config": {
            "label": "Grades",
            "target_fields": [
                "student_code",
                "subject_assignment_id",
                "term_id",
                "teacher_username",
                "seq1",
                "seq2",
                "exam",
                "mock",
                "practical",
                "test1",
                "test2",
                "remarks",
            ],
            "required": ["student_code", "subject_assignment_id", "term_id"],
            # Pass 8.C: Alma-flavored grade-book column names.
            "schema_hints": {
                "student_id": "student_code",
                "alma_id": "student_code",
                "course_id": "subject_assignment_id",
                "course": "subject_assignment_id",
                "section": "subject_assignment_id",
                "section_id": "subject_assignment_id",
                "term": "term_id",
                "quarter": "term_id",
                "marking_period": "term_id",
                "instructor": "teacher_username",
                "teacher": "teacher_username",
            },
        },
        "sort_order": 122,
    },
    # Generic strategy profile (non-competitor)
    {
        "slug": "phased_migration",
        "name": "Phased migration strategy",
        "description": "Run migrations in phases (e.g. students first, then grades, then finance) with validation between steps.",
        "format": MigrationProfile.Format.CSV,
        "domain": MigrationProfile.Domain.STUDENTS,
        "source_system": MigrationProfile.SourceSystem.OTHER,
        "profile_category": MigrationProfile.ProfileCategory.STRATEGY,
        "config": {
            "label": "Phased",
            "strategy": "phased",
            "target_fields": [],
            "required": [],
        },
        "sort_order": 200,
    },
]


class Command(BaseCommand):
    help = (
        "Seed migration connector profiles so Migration Cloud has starter profiles. "
        "Idempotent (update_or_create by slug)."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would be created/updated without writing.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        if dry_run:
            self.stdout.write("Dry run: no changes will be written.")

        created = 0
        for row in MIGRATION_PROFILES:
            slug = row["slug"]
            if dry_run:
                if not MigrationProfile.objects.filter(slug=slug).exists():
                    self.stdout.write(
                        f"Would create migration profile: {row['name']} ({slug})"
                    )
                    created += 1
                continue
            _, was_created = MigrationProfile.objects.update_or_create(
                slug=slug,
                defaults={
                    "name": row["name"],
                    "description": row.get("description", ""),
                    "format": row.get("format", MigrationProfile.Format.CSV),
                    "domain": row.get("domain", MigrationProfile.Domain.STUDENTS),
                    "source_system": row.get("source_system"),
                    "profile_category": row.get("profile_category"),
                    "config": row.get("config", {}),
                    "is_active": True,
                    "sort_order": row.get("sort_order", 0),
                },
            )
            if was_created:
                created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Migration profiles: {len(MIGRATION_PROFILES)} ensured ({created} created)."
            )
        )
