# Generated by Django 5.2.10 on 2026-01-25 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_remove_scheduleentry_room_and_more"),
        ("communication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("parents", "Parents"),
                            ("teachers", "Teachers"),
                            ("staff", "Staff"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="academics.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="communicati_created_778c6a_idx"
                    ),
                    models.Index(
                        fields=["audience", "is_active"],
                        name="communicati_audienc_9c0f6a_idx",
                    ),
                ],
            },
        ),
    ]
