# Generated by Django 5.2.10 on 2026-06-03 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_alter_announcement_expiry_date_and_more'),
        ('schools', '0064_school_schools_softdel_active_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push notification')], db_index=True, help_text='Messaging channel the decision applies to.', max_length=12)),
                ('identifier_hash', models.CharField(db_index=True, help_text='sha256(identifier.lower())[:12] — never the raw email/phone.', max_length=12)),
                ('action', models.CharField(choices=[('granted', 'Consent granted / opted in'), ('withdrawn', 'Consent withdrawn / opted out'), ('help_requested', 'Help requested')], help_text='granted | withdrawn | help_requested.', max_length=16)),
                ('reason', models.CharField(blank=True, default='', help_text="Coarse machine reason, e.g. the keyword ('stop'/'start').", max_length=64)),
                ('source', models.CharField(blank=True, default='', help_text="Origin surface: 'sms_webhook' | 'newsletter' | 'preference_centre'.", max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, help_text='Tenant context when known (platform-level events leave null).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_events', to='schools.school')),
            ],
            options={
                'verbose_name': 'Consent event',
                'verbose_name_plural': 'Consent events',
                'db_table': 'communication_consent_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'identifier_hash', 'created_at'], name='communicati_channel_63f59a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push notification')], db_index=True, max_length=12)),
                ('provider', models.CharField(blank=True, default='', help_text="Provider key: 'twilio' | 'africastalking' | 'meta_whatsapp'.", max_length=32)),
                ('provider_message_id', models.CharField(db_index=True, help_text="The provider's own message id (Twilio SID / Meta wamid).", max_length=128)),
                ('recipient_hash', models.CharField(blank=True, db_index=True, default='', help_text='sha256(recipient.lower())[:12] — never the raw phone/token.', max_length=12)),
                ('status', models.CharField(blank=True, default='', help_text='Verbatim provider status, lower-cased (queued/sent/delivered/…).', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', help_text='Provider error code on failure/undelivered (e.g. Twilio 30007).', max_length=32)),
                ('terminal', models.BooleanField(db_index=True, default=False, help_text='True once the status is delivered/failed/undelivered/read.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_delivery_receipts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Message delivery receipt',
                'verbose_name_plural': 'Message delivery receipts',
                'db_table': 'communication_message_delivery_receipt',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='communicati_channel_bc5549_idx'), models.Index(fields=['terminal', 'updated_at'], name='communicati_termina_454a89_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'provider_message_id'), name='comm_delivery_receipt_channel_msgid_uniq')],
            },
        ),
    ]
