# Generated by Django 5.2.10 on 2026-06-21 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_rename_communicati_user_id_6f0d8d_idx_communicati_user_id_bfeec3_idx'),
        ('schools', '0072_recurringdonationschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Set once the fan-out sender has dispatched it (idempotency guard so it sends once).', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Future publish time; null = immediate. A periodic sender fans it out when due (Phase 4).', null=True),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.message')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_categories', models.JSONField(blank=True, default=list, help_text='List of Category values the user muted.')),
                ('channel_overrides', models.JSONField(blank=True, default=dict, help_text='Optional {category: [channel, ...]}; empty = channel defaults.')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_cadence', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=16)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('recipient_hash', models.CharField(help_text='sha256 hex prefix of the E.164 number — never the raw phone.', max_length=64)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_hash', 'created_at'], name='communicati_recipie_f37096_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_sms_send_idempotency_key')],
            },
        ),
    ]
