# Generated by Django 5.2.10 on 2026-06-21 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0025_announcement_delivered_at_announcement_scheduled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='specific_recipients',
            field=models.ManyToManyField(blank=True, help_text="When audience='specific', the explicit set of recipient users. Resolution is still re-scoped to this announcement's school at fan-out time, so a stray cross-tenant pick can never be delivered.", related_name='targeted_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
