# Generated by Django 5.2.10 on 2026-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0026_announcement_specific_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
