# Generated by Django 5.2.10 on 2026-06-21 22:49
#
# Idempotent create. A thrash-cancelled deploy can partially create one of these
# three tables in a tenant schema while this migration is NOT recorded as applied
# (out-of-band / partial-migrate drift) — especially likely here because the
# migration creates THREE tables, so a mid-migration cancellation leaves some of
# them behind. A plain CreateModel then raises psycopg DuplicateTable ("relation
# already exists") and — under set -e in render_predeploy.sh — aborts EVERY deploy,
# freezing production at the last good commit (same failure as platform_runtime 0092).
#
# SeparateDatabaseAndState keeps the models in Django's migration state (so model
# history + makemigrations stay clean and dependents resolve), while the database
# step delegates to tenant_schema_guard.ensure_models_tables, which creates each
# table only when missing and is a no-op when it already exists.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _ensure_tables(apps, schema_editor):
    # These models are INTRODUCED by this migration, so the migration-state
    # ``apps`` (from-state) does not contain them yet — get_model would raise
    # LookupError. Resolve from the live registry instead; safe because this is
    # the leaf migration for each model, so the live definition equals the state.
    from django.apps import apps as live_apps  # noqa: F811 — live registry, not the historical state

    from apps.schools.tenant_schema_guard import ensure_models_tables

    ensure_models_tables(
        schema_editor,
        [
            live_apps.get_model("communication", "MessageBlock"),
            live_apps.get_model("communication", "ThreadMessageMention"),
            live_apps.get_model("communication", "ThreadMute"),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0028_threadmessageattachment'),
        ('schools', '0072_recurringdonationschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='MessageBlock',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks_received', to=settings.AUTH_USER_MODEL)),
                        ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks_made', to=settings.AUTH_USER_MODEL)),
                        ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks', to='schools.school')),
                    ],
                    options={
                        'indexes': [models.Index(fields=['blocked', 'blocker'], name='communicati_blocked_bf3687_idx')],
                        'unique_together': {('blocker', 'blocked')},
                    },
                ),
                migrations.CreateModel(
                    name='ThreadMessageMention',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='communication.threadmessage')),
                        ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_mentions', to='schools.school')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_mentions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'indexes': [models.Index(fields=['user', '-created_at'], name='communicati_user_id_9e198f_idx')],
                        'unique_together': {('message', 'user')},
                    },
                ),
                migrations.CreateModel(
                    name='ThreadMute',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_mutes', to='schools.school')),
                        ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='communication.messagethread')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_mutes', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'indexes': [models.Index(fields=['user', 'thread'], name='communicati_user_id_7f0a73_idx')],
                        'unique_together': {('thread', 'user')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_tables, migrations.RunPython.noop),
            ],
        ),
    ]
