# Generated by Django 5.2.10 on 2026-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0032_ensure_school_fk_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessagequeue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
