#!/usr/bin/env python3
"""
Phase 3/4 surface scan: template extends, data-page-archetype, operator_console_strip.

Run from repo root:
  python scripts/audit_phase3_phase4_surfaces.py
  python scripts/audit_phase3_phase4_surfaces.py --write docs/phase_audit/PHASE_3_4_SURFACE_SCAN.md

This is a mechanical inventory, not proof of zero dead-end paths.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "templates"

# Direct extends that pull in portal_base `page-wrap` default archetype block.
PORTAL_DEFAULT_ARCHETYPE_EXTENDS = frozenset(
    {
        "portal_base.html",
        "backend_base.html",
        "studio_os/shell.html",
    }
)
# Subset: direct portal/backend only (Studio shell child pages inherit shell canvas archetype).
PORTAL_PAGE_WRAP_DEFAULT_EXTENDS = frozenset(
    {
        "portal_base.html",
        "backend_base.html",
    }
)

EXTENDS_RE = re.compile(r"{%\s*extends\s+[\"']([^\"']+)[\"']\s*%}")
ARCHETYPE_RE = re.compile(r"data-page-archetype=[\"']([^\"']+)[\"']")
PAGE_ARCHETYPE_BLOCK_RE = re.compile(
    r"{%\s*block\s+page_archetype\s*%}([\s\S]*?){%\s*endblock\s*%}"
)
STRIP_RE = re.compile(r"operator_console_strip")


def scan_file(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8", errors="strict")
    except UnicodeDecodeError:
        text = path.read_text(encoding="utf-8", errors="replace")
    rel = path.relative_to(ROOT).as_posix()
    extends_m = EXTENDS_RE.search(text)
    archetypes = sorted(set(ARCHETYPE_RE.findall(text)))
    has_strip = bool(STRIP_RE.search(text))
    ext = extends_m.group(1) if extends_m else ""
    block_arch = PAGE_ARCHETYPE_BLOCK_RE.search(text)
    portal_default_archetype = bool(ext and ext in PORTAL_DEFAULT_ARCHETYPE_EXTENDS)
    return {
        "path": rel,
        "extends": ext,
        "archetypes": archetypes,
        "has_operator_strip": has_strip,
        "has_page_archetype_block": bool(block_arch),
        "portal_shell_default_archetype": portal_default_archetype,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write",
        metavar="PATH",
        help="Write markdown report relative to repo root",
    )
    args = ap.parse_args()

    rows: list[dict] = []
    if TEMPLATES.is_dir():
        for p in sorted(TEMPLATES.rglob("*.html")):
            if "node_modules" in p.parts:
                continue
            rows.append(scan_file(p))

    by_base: dict[str, list[str]] = defaultdict(list)
    no_archetype_portal: list[str] = []
    portal_without_explicit_or_block: list[str] = []
    for r in rows:
        ext = r["extends"]
        if ext:
            by_base[ext].append(r["path"])
        if "portal_base.html" in ext and not r["archetypes"]:
            no_archetype_portal.append(r["path"])
        if (
            r["extends"] in PORTAL_PAGE_WRAP_DEFAULT_EXTENDS
            and not (r["archetypes"] or r["has_page_archetype_block"])
        ):
            portal_without_explicit_or_block.append(r["path"])

    lines: list[str] = []
    lines.append("# Phase 3/4 template surface scan\n")
    lines.append("Generated by `scripts/audit_phase3_phase4_surfaces.py`.\n")
    lines.append("## Summary\n")
    lines.append(f"- HTML templates under `templates/`: **{len(rows)}**\n")
    lines.append(
        f"- Templates with direct `extends portal_base.html` and no `data-page-archetype` in file: **{len(no_archetype_portal)}** (shell default still applies via `page-wrap` on `portal_base`).\n"
    )
    lines.append(
        f"- Templates extending `portal_base` / `backend_base` with **no** inline archetype and **no** `{{% block page_archetype %}}`: **{len(portal_without_explicit_or_block)}** (effective default = `operational-workbench` on `page-wrap`; inner partials may still add a second archetype for sub-views).\n"
    )
    lines.append(
        "- Templates referencing `operator_console_strip`: see per-file column (portal shell also injects strip for eligible operators).\n"
    )
    lines.append("\n## Dead-end / link hygiene\n")
    lines.append(
        "- Mechanical URL pass: run `python scripts/audit_template_url_names.py` "
        "(writes `docs/phase_audit/PHASE_3_4_URL_NAME_AUDIT.md`).\n"
    )
    lines.append(
        "- Full click-graph proof requires crawling authenticated flows; use the URL audit plus "
        "manual Phase H passes for role-specific dead ends.\n"
    )
    lines.append("\n## Extends histogram (direct parent)\n")
    for base, paths in sorted(by_base.items(), key=lambda x: (-len(x[1]), x[0])):
        if len(paths) > 15:
            lines.append(f"- `{base}`: **{len(paths)}** files\n")
        else:
            lines.append(f"- `{base}`: {len(paths)} - {', '.join(paths)}\n")

    lines.append("\n## Direct `extends portal_base` without inline `data-page-archetype`\n")
    lines.append(
        "_Default archetype is still set on `portal_base` `page-wrap` "
        "(`operational-workbench` unless `{% block page_archetype %}` overrides)._\n\n"
    )
    if not no_archetype_portal:
        lines.append("_None._\n")
    else:
        for p in no_archetype_portal[:200]:
            lines.append(f"- `{p}`\n")
        if len(no_archetype_portal) > 200:
            lines.append(f"\n_…and {len(no_archetype_portal) - 200} more._\n")

    lines.append(
        "\n## Portal shell templates with no inline archetype and no `page_archetype` block\n"
    )
    if not portal_without_explicit_or_block:
        lines.append("_None._\n")
    else:
        for p in portal_without_explicit_or_block[:200]:
            lines.append(f"- `{p}`\n")
        if len(portal_without_explicit_or_block) > 200:
            lines.append(
                f"\n_...and {len(portal_without_explicit_or_block) - 200} more._\n"
            )

    lines.append("\n## Full inventory (extends | archetypes | strip)\n")
    lines.append(
        "| File | extends | archetype(s) | page_archetype block | strip |\n"
    )
    lines.append("|---|---|---|---|---|\n")
    for r in rows:
        arch = ", ".join(r["archetypes"]) or "—"
        strip = "yes" if r["has_operator_strip"] else ""
        ext = r["extends"] or "—"
        pb = "yes" if r["has_page_archetype_block"] else ""
        lines.append(f"| `{r['path']}` | `{ext}` | {arch} | {pb} | {strip} |\n")

    body = "".join(lines)
    print(body)
    if args.write:
        out = ROOT / args.write
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8")
        print(f"\nWrote {out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
