#!/usr/bin/env python3
"""Generate a MARKETING-scoped subset of static/css/rmc-class-grammar.css.

rmc-class-grammar.css is the platform-wide `.rmc-*` component grammar (~218KB,
1099 rules). It is loaded directly by every DASHBOARD shell (base / portal_base /
control_plane_skeleton / admin), but the public MARKETING surface pulled the
WHOLE file into its deferred `marketing-enhanced` bundle even though marketing
uses only ~10% of the rules. This script emits a subset containing only the
grammar rules the marketing surface actually references, which the bundle
manifest then uses in place of the full file. The FULL file is never modified —
dashboards keep loading it directly, so scan_undefined_css_classes stays green.

"Used" = every class token appearing in the MARKETING template universe
(base_marketing + everything that extends it + all transitive literal includes,
plus every template physically under templates/marketing/) UNION every
prefixed class token referenced in the JS actually loaded by base_marketing
(marketing JS + the shared js/rmc-*.js it links). A grammar rule is kept when
its selector has NO class token (element/attr/:root — safe, cheap) or shares at
least one class token with the used set; @media/@supports/@keyframes blocks are
kept whole when any inner rule qualifies (conservative — bias to KEEP).

Usage (repo root):
  python scripts/build_marketing_class_grammar_subset.py            # write subset
  python scripts/build_marketing_class_grammar_subset.py --check    # stale -> exit 1

Regenerate + re-check whenever rmc-class-grammar.css or the marketing templates
change (marketing-gates.yml enforces --check). A stale subset would silently
strip CSS from the PUBLIC site (scan_undefined_css_classes cannot catch it — the
full file still defines the class), so this gate is the real protector.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
FULL = REPO / "static" / "css" / "rmc-class-grammar.css"
OUT = REPO / "static" / "marketing" / "css" / "rmc-class-grammar-marketing-subset.css"
BASE_MARKETING = "marketing/base_marketing.html"

TEMPLATE_ROOTS = [REPO / "templates"] + sorted((REPO / "apps").glob("*/templates"))

_EXTENDS = re.compile(r'{%\s*extends\s+["\']([^"\']+)["\']')
_INCLUDE = re.compile(r'{%\s*include\s+["\']([^"\']+)["\']')
_CLASS_ATTR = re.compile(r'class\s*=\s*"([^"]*)"|class\s*=\s*\'([^\']*)\'')
_DJ_TAG = re.compile(r'{%.*?%}|{{.*?}}|{#.*?#}')
_SCRIPT_STATIC = re.compile(r'''src\s*=\s*["']?\{%\s*static\s+["']([^"']+\.js)["']''')
_CLASS_IN_SEL = re.compile(r'\.(-?[_a-zA-Z][_a-zA-Z0-9-]*)')
# prefixed tokens that could be classes toggled from JS
_JS_PREFIXED = re.compile(r'["\'`]([a-zA-Z0-9_\-]*(?:rmc|cp|mkt|portal|ccc)[a-zA-Z0-9_\-]*)["\'`]')

BANNER = (
    "/* GENERATED by scripts/build_marketing_class_grammar_subset.py — DO NOT EDIT.\n"
    "   Marketing-scoped subset of static/css/rmc-class-grammar.css (the full file\n"
    "   stays loaded on dashboard shells). Regenerate + re-check after editing the\n"
    "   full grammar or any marketing template. */\n"
)


def _rel(p: Path) -> str:
    return str(p.relative_to(REPO)).replace("\\", "/")


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _build_graph():
    name_to_file: dict[str, Path] = {}
    all_files: list[Path] = []
    for root in TEMPLATE_ROOTS:
        if not root.is_dir():
            continue
        for f in root.rglob("*.html"):
            all_files.append(f)
            name = str(f.relative_to(root)).replace("\\", "/")
            name_to_file.setdefault(name, f)
    parent_file: dict[Path, Path] = {}
    includes: dict[Path, set[str]] = {}
    for f in all_files:
        t = _read(f)
        m = _EXTENDS.search(t)
        if m:
            pf = name_to_file.get(m.group(1))
            if pf:
                parent_file[f] = pf
        includes[f] = set(_INCLUDE.findall(t))
    return name_to_file, all_files, parent_file, includes


def marketing_universe() -> tuple[set[Path], dict[str, Path]]:
    name_to_file, all_files, parent_file, includes = _build_graph()
    base_file = name_to_file.get(BASE_MARKETING)
    if not base_file:
        raise SystemExit(f"!! {BASE_MARKETING} not found under template roots")
    universe: set[Path] = {base_file}
    for f in all_files:
        cur, seen = f, set()
        while cur in parent_file and cur not in seen:
            seen.add(cur)
            cur = parent_file[cur]
            if cur == base_file:
                universe.add(f)
                break
    for f in all_files:
        if "/marketing/" in _rel(f):
            universe.add(f)
    # transitive literal includes
    frontier = list(universe)
    while frontier:
        f = frontier.pop()
        for child in includes.get(f, ()):  # literal include names only
            cf = name_to_file.get(child)
            if cf and cf not in universe:
                universe.add(cf)
                frontier.append(cf)
    return universe, name_to_file


def used_classes() -> set[str]:
    universe, _ = marketing_universe()
    used: set[str] = set()
    base_js: list[str] = []
    for f in universe:
        t = _read(f)
        for m in _CLASS_ATTR.finditer(t):
            raw = _DJ_TAG.sub(" ", m.group(1) or m.group(2) or "")
            used.update(tok for tok in raw.split() if tok)
        if _rel(f).endswith(BASE_MARKETING):
            base_js = _SCRIPT_STATIC.findall(t)
    # JS: all marketing JS + the shared js/*.js base_marketing actually loads
    js_files: list[Path] = list((REPO / "static" / "marketing" / "js").rglob("*.js"))
    for rel in base_js:
        p = REPO / "static" / rel
        if p.is_file():
            js_files.append(p)
    for p in js_files:
        for m in _JS_PREFIXED.finditer(_read(p)):
            used.add(m.group(1))
    return used


def _split_top_level(css: str) -> list[tuple[str, str, str]]:
    """Return (prelude, body, verbatim) for each top-level construct, verbatim-exact."""
    out: list[tuple[str, str, str]] = []
    i, n = 0, len(css)
    start = 0
    while i < n:
        c = css[i]
        if c == "{":
            prelude = css[start:i]
            depth, j = 1, i + 1
            while j < n and depth:
                if css[j] == "{":
                    depth += 1
                elif css[j] == "}":
                    depth -= 1
                j += 1
            body = css[i + 1 : j - 1]
            out.append((prelude.strip(), body, css[start:j]))
            i = j
            start = j
        else:
            i += 1
    return out


def _rule_kept(prelude: str, body: str, used: set[str]) -> bool:
    if prelude.startswith("@"):
        head = prelude.split("(")[0].split()[0].lower()
        if head in ("@keyframes", "@font-face", "@page", "@import", "@charset", "@layer"):
            return True
        if head in ("@media", "@supports", "@container"):
            for ip, ib, _ in _split_top_level(body):
                if _rule_kept(ip, ib, used):
                    return True
            return False
        return True
    sel_classes = set(_CLASS_IN_SEL.findall(prelude))
    return (not sel_classes) or bool(sel_classes & used)


def generate() -> str:
    used = used_classes()
    full = _read(FULL)
    kept = [verbatim for prelude, body, verbatim in _split_top_level(full) if _rule_kept(prelude, body, used)]
    return BANNER + "\n".join(v.strip() for v in kept) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed subset is stale")
    args = ap.parse_args()
    content = generate()
    if args.check:
        if not OUT.is_file() or _read(OUT) != content:
            print(
                f"{_rel(OUT)} stale — run: python scripts/build_marketing_class_grammar_subset.py",
                file=sys.stderr,
            )
            return 1
        print(f"marketing class-grammar subset fresh ({len(content.encode('utf-8'))} bytes)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    full_bytes = len(_read(FULL).encode("utf-8"))
    sub_bytes = len(content.encode("utf-8"))
    print(
        f"wrote {_rel(OUT)} ({sub_bytes} bytes) — subset of {_rel(FULL)} ({full_bytes} bytes); "
        f"raw reduction {full_bytes - sub_bytes} bytes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
