#!/usr/bin/env bash
# C4: Security and compliance scan (CI-ready).
# Runs: pip-audit, Bandit, optional Semgrep, Django check --deploy.
# Appends or writes summary to docs/security_baseline.md.
# Usage: from repo root, bash scripts/security_ci.sh

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="${1:-docs/security_baseline.md}"
mkdir -p "$(dirname "$OUT")"

run_check() {
    local name="$1"
    local cmd="$2"
    echo "--- $name ---"
    if eval "$cmd"; then
        echo "[PASS] $name"
        return 0
    else
        echo "[FAIL] $name"
        return 1
    fi
}

report() {
    local section="$1"
    local body="$2"
    if [[ -f "$OUT" ]]; then
        # Remove existing section if present
        sed -i.bak "/^## $section$/,/^## /{ /^## $section$/d; /^## /!d; }" "$OUT" 2>/dev/null || true
    fi
    {
        echo ""
        echo "## $section"
        echo ""
        echo "$body"
        echo ""
    } >> "$OUT"
}

echo "=== Security CI (C4) ==="

# 1) pip-audit (dependency vulnerabilities)
PIP_AUDIT_OUT=""
if command -v pip-audit &>/dev/null; then
    PIP_AUDIT_OUT=$(pip-audit 2>&1) || true
    run_check "pip-audit" "pip-audit 2>&1 | tee /dev/stderr" || true
else
    echo "pip-audit not installed. Install: pip install pip-audit"
fi

# 2) Bandit (Python security)
BANDIT_OUT=""
if command -v bandit &>/dev/null; then
    BANDIT_OUT=$(bandit -r apps/ config/ -ll --skip B101 2>&1) || true
    run_check "Bandit" "bandit -r apps/ config/ -ll --skip B101 2>&1 | tee /dev/stderr" || true
else
    echo "Bandit not installed. Install: pip install bandit"
fi

# 3) Django check --deploy
DJANGO_OUT=""
if [[ -n "${DJANGO_SETTINGS_MODULE:-}" ]] || [[ -f manage.py ]]; then
    DJANGO_OUT=$(python manage.py check --deploy 2>&1) || true
    run_check "Django check --deploy" "python manage.py check --deploy 2>&1 | tee /dev/stderr" || true
else
    echo "Django env not set; skipping check --deploy"
fi

# 4) Semgrep (optional)
if command -v semgrep &>/dev/null; then
    run_check "Semgrep (Django)" "semgrep scan --config=p/django apps/ config/ 2>&1 | head -100" || true
else
    echo "Semgrep not installed. Optional: pip install semgrep"
fi

# Write/update security_baseline.md
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
{
    echo "# Security baseline (C4)"
    echo ""
    echo "Last run: $TIMESTAMP. Generated by \`scripts/security_ci.sh\`."
    echo ""
    echo "## Checks"
    echo ""
    echo "| Check | Description |"
    echo "|-------|-------------|"
    echo "| pip-audit | Dependency vulnerabilities |"
    echo "| Bandit | Python static security (apps/, config/) |"
    echo "| Django check --deploy | Production settings, security middleware |"
    echo "| Semgrep | Optional; Django/auth rules |"
    echo ""
    echo "## Findings and patches"
    echo ""
    echo "- Run \`pip-audit\` and fix reported vulnerabilities with \`pip-audit --fix\` or version bumps."
    echo "- Run \`bandit -r apps/ config/ -ll --skip B101\` and address high/medium issues."
    echo "- Resolve \`manage.py check --deploy\` warnings (e.g. DEBUG=0, SECURE_* in production)."
    echo "- CSP: enable \`django-csp\` or set Content-Security-Policy headers; use report-only first."
} > "$OUT"

echo "Wrote $OUT"
exit 0
