apiVersion: v1
kind: Secret
metadata:
  name: collabora-env
  namespace: collabora
type: Opaque
stringData:
  username: "admin"
  password: "change-me"
  domain: "runmycampus.com|.*\.runmycampus\.com"
