# Generated by Django 5.2.10 on 2026-05-30 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistDockShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('target_url', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_short_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist dock short link',
                'verbose_name_plural': 'Assist dock short links',
                'indexes': [models.Index(fields=['created_by', 'expires_at'], name='ad_shortlink_user_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='info', max_length=16)),
                ('page_path', models.CharField(blank=True, default='', max_length=256)),
                ('cta_label', models.CharField(blank=True, default='', max_length=120)),
                ('cta_href', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist dock insight',
                'verbose_name_plural': 'Assist dock insights',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='ad_insight_user_exp_idx'), models.Index(fields=['user', 'page_path'], name='ad_insight_user_page_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'insight_id'), name='ad_uniq_user_insight_id')],
            },
        ),
    ]
