# Generated by Django 5.2.10 on 2026-05-31 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dock', '0002_assistdockshortlink_insightrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistDockShortLinkRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=320)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('send_status', models.CharField(default='queued', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='assist_dock.assistdockshortlink')),
            ],
            options={
                'verbose_name': 'Assist dock short link recipient',
                'verbose_name_plural': 'Assist dock short link recipients',
                'indexes': [models.Index(fields=['short_link', 'sent_at'], name='ad_shortlink_recip_idx')],
            },
        ),
        migrations.CreateModel(
            name='PresencePing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=256)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_presence_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist dock presence ping',
                'verbose_name_plural': 'Assist dock presence pings',
                'indexes': [models.Index(fields=['page_path', 'last_seen'], name='ad_presence_page_last_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'page_path'), name='ad_uniq_user_page')],
            },
        ),
    ]
