# Generated by Django 5.2.10 on 2026-05-31 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dock', '0003_assistdockshortlinkrecipient_presenceping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=280)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='requested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('approver', models.ForeignKey(blank=True, help_text='Operator who approved (must differ from grantor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_dock_impersonation_grants_approved', to=settings.AUTH_USER_MODEL)),
                ('grantor', models.ForeignKey(help_text='Operator who requested the grant.', on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_impersonation_grants_requested', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='User who will be impersonated when this grant is consumed.', on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_impersonation_grants_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist dock impersonation grant',
                'verbose_name_plural': 'Assist dock impersonation grants',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assist_dock.impersonationgrant')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_impersonation_sessions_run', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_dock_impersonation_sessions_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist dock impersonation session',
                'verbose_name_plural': 'Assist dock impersonation sessions',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('started', 'Started'), ('stopped', 'Stopped'), ('expired_at_start', 'Expired before start'), ('revoked', 'Revoked'), ('denied_by_rbac', 'Denied by RBAC')], max_length=24)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_dock_impersonation_audit_events', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='assist_dock.impersonationgrant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='assist_dock.impersonationsession')),
            ],
            options={
                'verbose_name': 'Assist dock impersonation audit event',
                'verbose_name_plural': 'Assist dock impersonation audit events',
            },
        ),
        migrations.AddIndex(
            model_name='impersonationgrant',
            index=models.Index(fields=['status', 'expires_at'], name='ad_imp_grant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationgrant',
            index=models.Index(fields=['grantor', 'created_at'], name='ad_imp_grant_grantor_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['operator', 'started_at'], name='ad_imp_sess_op_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['target', 'started_at'], name='ad_imp_sess_target_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationauditevent',
            index=models.Index(fields=['grant', 'created_at'], name='ad_imp_audit_grant_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationauditevent',
            index=models.Index(fields=['actor', 'created_at'], name='ad_imp_audit_actor_idx'),
        ),
    ]
