"""
Canonical list of full-page dashboard templates (Phase 7 marker gate + Phase 8 declarations).

Single source: scripts/verify_phase7_dashboard_markers.py imports this list.
"""

from __future__ import annotations

# Full-page dashboards (exclude fragments under admin/components/, widgets/, etc.)
PHASE7_DASHBOARD_TEMPLATES: tuple[str, ...] = (
    "accounts/backend_dashboard.html",
    "accounts/certification_home.html",
    "accounts/district_lms_interop.html",
    "accounts/entity_console.html",
    "accounts/import_hub.html",
    "accounts/migration_wizard.html",
    "accounts/rbac_dashboard.html",
    "accounts/security_trust_hub.html",
    "accounts/tenant_impersonation_audit.html",
    "accounts/workflow_center.html",
    "admin/admin_dashboard.html",
    "analytics/at_risk_dashboard.html",
    "analytics/dashboard.html",
    "analytics/executive_dashboard.html",
    "apicenter/dashboard.html",
    "compliance/dashboard.html",
    "customersuccess/super_dashboard.html",
    "emis/dashboard.html",
    "evals/compliance_dashboard.html",
    "finance/dashboard.html",
    "finance/invoices.html",
    "marketplace/app_catalog.html",
    "marketplace/governance_console.html",
    "marketplace/incident_dashboard.html",
    "marketplace/installation_health.html",
    "marketplace/package_rollout.html",
    "marketplace/sandbox_inspector.html",
    "metadata/lineage_graph.html",
    "observability/platform_incidents.html",
    "observability/slo_dashboard.html",
    "orchestration/operator_workbench.html",
    "parent/dashboard.html",
    "payroll/dashboard.html",
    "people/employer_dashboard.html",
    "platform_runtime/tenant_lifecycle_dashboard.html",
    "requests/dashboard.html",
    "schoolops/ops_library.html",
    "schools/billing_dashboard.html",
    "schools/marketing_funnel_dashboard.html",
    "schools/parent_tenant_dashboard.html",
    "schools/super_backlog_unlock_center.html",
    "schools/super_command_center.html",
    "schools/super_control_health.html",
    "schools/super_dashboard.html",
    "schools/super_dashboard_packs.html",
    "schools/super_he_pack.html",
    "schools/super_analytics_overview.html",
    "schools/super_metadata_catalog.html",
    "schools/super_migration_cloud.html",
    "schools/super_native_roster_connectors.html",
    "schools/super_phase_b_snapshot_diff.html",
    "schools/super_policy_diff.html",
    "schools/super_platform_operator_hub.html",
    "schools/super_playbook_operator_hub.html",
    "schools/super_pulse.html",
    "schools/super_usage.html",
    "schools/super_runtime_truth_hub.html",
    "schools/super_security_hub.html",
    "schools/super_support_dashboard.html",
    "schools/super_support_csat_dashboard.html",
    "schools/super_support_ticket_detail.html",
    "schools/super_tenant_360.html",
    "schools/super_trust_center.html",
    "schools/super_wedge_index.html",
    "schools/super_wedge_operator_detail.html",
    "siteconfig/console_domains_hub.html",
    "siteconfig/console_domains_hub_control_plane.html",
    "siteconfig/feature_control_panel.html",
    "siteconfig/dashboard_configuration_hub.html",
    "siteconfig/dashboard_hub.html",
    "siteconfig/tenant_runtime_configuration_hub.html",
    "student/learning_home.html",
    "studio_os/partials/subpages/experience_dashboard_visual_packs.html",
    "teacher/dashboard.html",
)
