# Generated by Django 5.2.10 on 2026-02-12 20:38

import apps.schools.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteconfig', '0081_dashboarduserpreference_role_visual_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL slug e.g. ghs-limbe', max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain for this school (e.g. ghs-limbe for ghs-limbe.yoursystem.com)', max_length=120, unique=True)),
                ('sub_system', models.CharField(choices=[('FR', 'French sub-system'), ('EN', 'English sub-system'), ('INT', 'International')], default='EN', help_text='Cameroon FR/EN or International', max_length=10)),
                ('timezone', models.CharField(default='Africa/Douala', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='School-level overrides: grading_logic, term_count, custom fields config, etc.')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Enabled modules: {"library": true, "transport": false}')),
                ('logo_url', models.URLField(blank=True, help_text='URL to school logo (e.g. from tenants/{id}/logo.png)')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('accent_color', models.CharField(default='#198754', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain e.g. portal.school.edu', max_length=255)),
                ('custom_domain_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_region', models.ForeignKey(blank=True, help_text='Region for currency, grading, timezone', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='siteconfig.regionconfig')),
                ('parent_school', models.ForeignKey(blank=True, help_text='Parent tenant e.g. Catholic Education Secretariat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schools', to='schools.school')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=apps.schools.models._get_role_choices, default='ADMIN', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='When user has multiple schools, which one is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School membership',
                'verbose_name_plural': 'School memberships',
                'ordering': ['-is_primary', 'school__name'],
                'unique_together': {('user', 'school')},
            },
        ),
    ]
