# Generated by Django 5.2.10 on 2026-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_signup_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='wallpaper_url',
            field=models.URLField(blank=True, help_text='URL to tenant login wallpaper (split-screen left panel image)'),
        ),
    ]
