# Generated by Django 5.2.10 on 2026-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_school_wallpaper_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='compliance_region',
            field=models.CharField(blank=True, choices=[('', 'None (default)'), ('EU', 'EU (GDPR)'), ('US', 'US (FERPA)'), ('NDPR', 'Nigeria (NDPR)')], default='', help_text='Compliance region for data privacy: EU (GDPR), US (FERPA), Nigeria (NDPR). Affects masking, retention, consent.', max_length=10),
        ),
    ]
