# Generated by Django 5.2.10 on 2026-02-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_inventory_transport'),
        ('siteconfig', '0108_tour_step_feature_usage_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bus',
            name='schools_bus_school_id_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='route',
            name='schools_route_school_name_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='stop',
            name='schools_stop_route_seq_uniq',
        ),
        migrations.AddField(
            model_name='school',
            name='theme_pack',
            field=models.ForeignKey(blank=True, help_text='Portal/login theme pack for this school. Leave blank to use global default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_using_theme', to='siteconfig.themepack'),
        ),
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('school', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'sequence')},
        ),
    ]
