# Generated by Django 5.2.10 on 2026-03-01 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_add_school_theme_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, help_text='Hostname e.g. school.runmycampus.com or portal.school.edu', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='True after TXT verification (custom) or when created from School.subdomain (subdomain).')),
                ('dns_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='TXT record runmycampus-verify=<token> for custom domain verification.', unique=True)),
                ('kind', models.CharField(choices=[('SUBDOMAIN', 'Subdomain'), ('CUSTOM', 'Custom domain')], default='CUSTOM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_entries', to='schools.school')),
            ],
            options={
                'verbose_name': 'School domain',
                'verbose_name_plural': 'School domains',
                'ordering': ['school', 'domain'],
                'indexes': [models.Index(fields=['domain'], name='schools_sch_domain_3bdbe8_idx'), models.Index(fields=['is_verified', 'domain'], name='schools_sch_is_veri_6109e2_idx')],
                'unique_together': {('school', 'domain')},
            },
        ),
    ]
