# Generated by Django 5.2.10 on 2026-03-04 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_world_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='impersonation_consent_granted_at',
            field=models.DateTimeField(blank=True, help_text='When set, principal/school admin has consented to RunMyCampus support impersonation (JIT).', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='impersonation_consent_granted_by',
            field=models.ForeignKey(blank=True, help_text='User (e.g. principal) who granted impersonation consent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
