# Generated by Django 5.2.10 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_world_engine_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, db_index=True, default='BASE_SCHOOL', help_text='School type from module manifest (BASE_SCHOOL, TECHNICAL_COLLEGE, STEM_ACADEMY). Determines required_apps and UI skin.', max_length=32),
        ),
    ]
