# Generated by Django 5.2.10 on 2026-03-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
        ('schools', '0026_rls_policy_default_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical ISO 3166-1 alpha-2 country code for onboarding and analytics.', max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='education_levels',
            field=models.ManyToManyField(blank=True, help_text='Canonical education levels served by this school.', related_name='schools', to='registries.educationlevelregistry'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_system_types',
            field=models.ManyToManyField(blank=True, help_text='Canonical education system types served by this school.', related_name='schools', to='registries.educationsystemtyperegistry'),
        ),
        migrations.AddField(
            model_name='school',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Canonical subdivision selection for this school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='registries.subdivisionregistry'),
        ),
    ]
