# Generated by Django 5.2.10 on 2026-03-05 23:34
# Made idempotent: columns/tables are added only if they don't exist (fixes deploy when column already exists).

import django.db.models.deletion
from django.db import migrations, models


def add_fields_if_missing(apps, schema_editor):
    """Add country_code, subdivision, and M2M through tables only if they don't exist (idempotent)."""
    from django.db import connection

    def _column_exists(cursor, table_name: str, column_name: str) -> bool:
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s
                """,
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
        if connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info('{table_name}')")
            return any(row[1] == column_name for row in cursor.fetchall())
        return column_name in {
            col.name for col in connection.introspection.get_table_description(cursor, table_name)
        }

    def _table_exists(cursor, table_name: str) -> bool:
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = current_schema() AND table_name = %s
                """,
                [table_name],
            )
            return cursor.fetchone() is not None
        if connection.vendor == "sqlite":
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
                [table_name],
            )
            return cursor.fetchone() is not None
        return table_name in connection.introspection.table_names(cursor)

    with connection.cursor() as cursor:
        # 1. country_code
        if not _column_exists(cursor, "schools_school", "country_code"):
            cursor.execute(
                "ALTER TABLE schools_school ADD COLUMN country_code varchar(2) NOT NULL DEFAULT ''"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_country_code_idx ON schools_school (country_code)"
            )

        # 2. subdivision_id (FK)
        if not _column_exists(cursor, "schools_school", "subdivision_id"):
            if connection.vendor == "postgresql":
                cursor.execute("""
                    ALTER TABLE schools_school ADD COLUMN subdivision_id integer NULL
                    REFERENCES public.registries_subdivisionregistry(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
                """)
            else:
                cursor.execute(
                    "ALTER TABLE schools_school ADD COLUMN subdivision_id bigint NULL "
                    "REFERENCES registries_subdivisionregistry(id) ON DELETE SET NULL"
                )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_subdivision_id_idx ON schools_school (subdivision_id)"
            )

        # 3. M2M through table: schools_school_education_levels
        if not _table_exists(cursor, "schools_school_education_levels"):
            if connection.vendor == "postgresql":
                cursor.execute("""
                    CREATE TABLE schools_school_education_levels (
                        id serial PRIMARY KEY,
                        school_id uuid NOT NULL REFERENCES schools_school(id) ON DELETE CASCADE,
                        educationlevelregistry_id varchar(32) NOT NULL REFERENCES public.registries_educationlevelregistry(code) ON DELETE CASCADE,
                        CONSTRAINT schools_school_education_levels_school_id_education_level_uniq UNIQUE (school_id, educationlevelregistry_id)
                    )
                """)
            else:
                cursor.execute("""
                    CREATE TABLE schools_school_education_levels (
                        id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        school_id char(32) NOT NULL REFERENCES schools_school(id) ON DELETE CASCADE,
                        educationlevelregistry_id varchar(32) NOT NULL REFERENCES registries_educationlevelregistry(code) ON DELETE CASCADE,
                        CONSTRAINT schools_school_education_levels_school_id_education_level_uniq UNIQUE (school_id, educationlevelregistry_id)
                    )
                """)
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_education_levels_school_id_idx ON schools_school_education_levels (school_id)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_education_levels_educationlevelregistry_id_idx ON schools_school_education_levels (educationlevelregistry_id)"
            )

        # 4. M2M through table: schools_school_education_system_types
        if not _table_exists(cursor, "schools_school_education_system_types"):
            if connection.vendor == "postgresql":
                cursor.execute("""
                    CREATE TABLE schools_school_education_system_types (
                        id serial PRIMARY KEY,
                        school_id uuid NOT NULL REFERENCES schools_school(id) ON DELETE CASCADE,
                        educationsystemtyperegistry_id varchar(48) NOT NULL REFERENCES public.registries_educationsystemtyperegistry(code) ON DELETE CASCADE,
                        CONSTRAINT schools_school_education_system_types_school_id_type_uniq UNIQUE (school_id, educationsystemtyperegistry_id)
                    )
                """)
            else:
                cursor.execute("""
                    CREATE TABLE schools_school_education_system_types (
                        id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        school_id char(32) NOT NULL REFERENCES schools_school(id) ON DELETE CASCADE,
                        educationsystemtyperegistry_id varchar(48) NOT NULL REFERENCES registries_educationsystemtyperegistry(code) ON DELETE CASCADE,
                        CONSTRAINT schools_school_education_system_types_school_id_type_uniq UNIQUE (school_id, educationsystemtyperegistry_id)
                    )
                """)
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_education_system_types_school_id_idx ON schools_school_education_system_types (school_id)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS schools_school_education_system_types_educationsystemtyperegistry_id_idx ON schools_school_education_system_types (educationsystemtyperegistry_id)"
            )


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op for idempotent forward (cannot safely remove if others depend on it)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
        ('schools', '0026_rls_policy_default_deny'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='school',
                    name='country_code',
                    field=models.CharField(blank=True, db_index=True, help_text='Canonical ISO 3166-1 alpha-2 country code for onboarding and analytics.', max_length=2),
                ),
                migrations.AddField(
                    model_name='school',
                    name='education_levels',
                    field=models.ManyToManyField(blank=True, help_text='Canonical education levels served by this school.', related_name='schools', to='registries.educationlevelregistry'),
                ),
                migrations.AddField(
                    model_name='school',
                    name='education_system_types',
                    field=models.ManyToManyField(blank=True, help_text='Canonical education system types served by this school.', related_name='schools', to='registries.educationsystemtyperegistry'),
                ),
                migrations.AddField(
                    model_name='school',
                    name='subdivision',
                    field=models.ForeignKey(blank=True, help_text='Canonical subdivision selection for this school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='registries.subdivisionregistry'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_fields_if_missing, noop_reverse),
            ],
        ),
    ]
