# Generated by Django 5.2.10 on 2026-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_school_country_code_school_education_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='default_dashboard_slug',
            field=models.CharField(blank=True, help_text='Default dashboard preset slug for this school (e.g. from dashboard registry).', max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='default_workflow_slug',
            field=models.CharField(blank=True, help_text='Default workflow preset slug for this school (e.g. from TenantWorkflow registry).', max_length=80),
        ),
    ]
