# Generated by Django 5.2.10 on 2026-03-06 19:58
# Made idempotent for tenant migrations: add columns only if missing (PostgreSQL duplicate_column).

from django.db import migrations, models


def add_columns_if_missing(apps, schema_editor):
    """Add default_dashboard_slug and default_workflow_slug to schools_school; no-op if already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute("""
                DO $$
                BEGIN
                    ALTER TABLE schools_school ADD COLUMN default_dashboard_slug varchar(80) NOT NULL DEFAULT '';
                EXCEPTION WHEN duplicate_column THEN NULL;
                END $$;
            """)
            cursor.execute("""
                DO $$
                BEGIN
                    ALTER TABLE schools_school ADD COLUMN default_workflow_slug varchar(80) NOT NULL DEFAULT '';
                EXCEPTION WHEN duplicate_column THEN NULL;
                END $$;
            """)
        else:
            cursor.execute("PRAGMA table_info(schools_school)")
            cols = [row[1] for row in cursor.fetchall()]
            if "default_dashboard_slug" not in cols:
                cursor.execute(
                    "ALTER TABLE schools_school ADD COLUMN default_dashboard_slug varchar(80) NOT NULL DEFAULT ''"
                )
            if "default_workflow_slug" not in cols:
                cursor.execute(
                    "ALTER TABLE schools_school ADD COLUMN default_workflow_slug varchar(80) NOT NULL DEFAULT ''"
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0027_school_country_code_school_education_levels_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="school",
                    name="default_dashboard_slug",
                    field=models.CharField(
                        blank=True,
                        help_text="Default dashboard preset slug for this school (e.g. from dashboard registry).",
                        max_length=80,
                    ),
                ),
                migrations.AddField(
                    model_name="school",
                    name="default_workflow_slug",
                    field=models.CharField(
                        blank=True,
                        help_text="Default workflow preset slug for this school (e.g. from TenantWorkflow registry).",
                        max_length=80,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_if_missing, noop_reverse),
            ],
        ),
    ]
