# Generated by Django 5.2.10 on 2026-03-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0030_add_library_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingFunnelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("visit", "Visit (landing)"),
                            ("discovery", "Discovery (find school / discover)"),
                            ("signup", "Signup (trial/school signup)"),
                            ("activation", "Activation (onboard complete / first use)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Marketing funnel event",
                "verbose_name_plural": "Marketing funnel events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="schools_mar_event_t_ddd58a_idx",
                    )
                ],
            },
        ),
    ]
