# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0031_add_marketing_funnel_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="MarketingFunnelEvent",
            name="utm_source",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="MarketingFunnelEvent",
            name="utm_medium",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
