# Generated by Django 5.2.10 on 2026-03-09 11:46

from django.conf import settings
from django.db import migrations, models


def _default_timezone():
    """Platform default timezone (no hardcoded Africa/Douala). See config.PLATFORM_DEFAULT_TIMEZONE.

    Inlined from ``apps.schools.models._default_timezone`` for migration
    historical-state safety.
    """
    return getattr(settings, "PLATFORM_DEFAULT_TIMEZONE", "UTC")


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0032_marketing_funnel_event_utm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="timezone",
            field=models.CharField(
                default=_default_timezone, max_length=50
            ),
        ),
    ]
