# Generated by Django 5.2.10 on 2026-03-09 11:46

import apps.schools.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0032_marketing_funnel_event_utm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="timezone",
            field=models.CharField(
                default=apps.schools.models._default_timezone, max_length=50
            ),
        ),
    ]
