# Generated by Django 5.2.10 on 2026-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_school_report_platform_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='report_platform_bundle_slug',
            field=models.CharField(blank=True, default='', help_text='Optional reports-standard or reports-advanced: overrides platform operator default for granular report SKU floor when plan/addons/features include coarse reports. Empty = operator default only (see billing_sku_registry).', max_length=64),
        ),
    ]
