# Generated by Django 5.2.10 on 2026-04-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_alter_school_report_platform_bundle_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingfunnelevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketingfunnelevent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_funnel_events', to='schools.school'),
        ),
        migrations.AddField(
            model_name='marketingfunnelevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_funnel_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketingfunnelevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit (landing)'), ('discovery', 'Discovery (find school / discover)'), ('signup', 'Signup (form submitted)'), ('activation', 'Activation (school verified / live)'), ('demo_started', 'Demo started (book-demo submitted)'), ('signup_completed', 'Signup completed (email verified, school active)'), ('first_dashboard_view', 'First authenticated dashboard view'), ('first_action', 'First substantive POST / action'), ('first_result', 'First operational outcome (e.g. payment recorded)'), ('subscription_started', 'Platform subscription row created (billing)')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='schoolprovisioningevent',
            name='event_type',
            field=models.CharField(choices=[('REQUEST_RECEIVED', 'Request Received'), ('QUEUED', 'Queued'), ('STARTED', 'Started'), ('PROFILE_APPLIED', 'Profile Applied'), ('ACADEMIC_YEAR_READY', 'Academic Year Ready'), ('SUBJECTS_READY', 'Subjects Ready'), ('BLUEPRINT_TEMPLATE_RECORDED', 'Blueprint Template Recorded'), ('SAMPLE_DATA_READY', 'Sample Data Ready'), ('DOMAIN_PENDING', 'Domain Pending'), ('DOMAIN_VERIFIED', 'Domain Verified'), ('DOMAIN_UNVERIFIED', 'Domain Unverified'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='marketingfunnelevent',
            index=models.Index(fields=['school', 'event_type', 'created_at'], name='schools_mar_school__cee9f0_idx'),
        ),
    ]
