# Generated by Django 5.2.10 on 2026-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0044_provisioning_event_types_blueprint_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingfunnelevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit (landing)'), ('discovery', 'Discovery (find school / discover)'), ('signup', 'Signup (form submitted)'), ('activation', 'Activation (school verified / live)'), ('onboarding_start', 'Public onboarding wizard opened (step 1)'), ('onboarding_complete', 'Public onboarding wizard finished (review / signup)'), ('demo_started', 'Demo started (book-demo submitted)'), ('signup_completed', 'Signup completed (email verified, school active)'), ('first_dashboard_view', 'First authenticated dashboard view'), ('first_action', 'First substantive POST / action'), ('first_result', 'First operational outcome (e.g. payment recorded)'), ('subscription_started', 'Platform subscription row created (billing)')], db_index=True, max_length=40),
        ),
    ]
