# Generated by Django 5.2.10 on 2026-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0048_force_rls_on_all_enabled_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='data_region',
            field=models.CharField(blank=True, db_index=True, help_text="Regulatory data residency region (e.g. 'eu_central', 'us_east', 'apac_southeast'). Defaults from country_code via apps.schools.data_residency.derive_default_region; explicit override wins.", max_length=32),
        ),
    ]
