# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0049_school_data_region_g4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='timezone',
            field=models.CharField(default=apps.schools.models._default_timezone, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=apps.schools.models._get_role_choices, default='ADMIN', max_length=20),
        ),
    ]
