# Generated by Django 5.2.10 on 2026-05-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0050_alter_school_timezone_alter_schoolmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='default_language',
            field=models.CharField(blank=True, default='', help_text="Tenant default language code (mirrors settings.LANGUAGES). When set, anonymous visitors to this tenant's marketing surface get this language before Accept-Language is consulted. Empty = platform default 'en'.", max_length=16),
        ),
    ]
