# Generated by Django 5.2.10 on 2026-05-22 22:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0054_school_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='school',
            managers=[
                ('live_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
