# Generated by Django 5.2.10 on 2026-05-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0055_school_live_objects_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
    ]
