# Generated by Django 5.2.10 on 2026-05-29 13:18

import apps.schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0060_school_governance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='governance_operating_mode',
            field=models.CharField(choices=apps.schools.models._get_governance_operating_mode_choices, db_index=True, default='standalone', help_text='standalone | group_member | group_member_sovereign (default standalone).', max_length=32),
        ),
        migrations.AlterField(
            model_name='school',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='School-level overrides: grading_logic, term_count, custom fields config, etc. Optional governance_inherit map (domain → inherit|local|hybrid) for group-member schools.'),
        ),
    ]
