# Generated by Django 5.2.10 on 2026-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0062_school_institution_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprovisioningevent',
            name='event_type',
            field=models.CharField(choices=[('REQUEST_RECEIVED', 'Request Received'), ('QUEUED', 'Queued'), ('STARTED', 'Started'), ('PROFILE_APPLIED', 'Profile Applied'), ('ACADEMIC_YEAR_READY', 'Academic Year Ready'), ('ACADEMIC_STRUCTURE_READY', 'Academic Structure Ready'), ('SUBJECTS_READY', 'Subjects Ready'), ('BLUEPRINT_TEMPLATE_RECORDED', 'Blueprint Template Recorded'), ('SAMPLE_DATA_READY', 'Sample Data Ready'), ('DOMAIN_PENDING', 'Domain Pending'), ('DOMAIN_VERIFIED', 'Domain Verified'), ('DOMAIN_UNVERIFIED', 'Domain Unverified'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('OFFBOARDING_EXPORT', 'Offboarding Export'), ('OFFBOARDING_DEACTIVATED', 'Offboarding Deactivated'), ('OFFBOARDING_PURGE_REQUESTED', 'Offboarding Purge Requested'), ('OFFBOARDING_PURGE_COMPLETED', 'Offboarding Purge Completed'), ('OFFBOARDING_SELF_SERVICE_REQUESTED', 'Offboarding Self-Service Requested'), ('OFFBOARDING_SELF_SERVICE_CANCELLED', 'Offboarding Self-Service Cancelled'), ('OFFBOARDING_AUTO_PURGE_SCHEDULED', 'Offboarding Auto Purge Scheduled'), ('OFFBOARDING_AUTO_PURGE_EXECUTED', 'Offboarding Auto Purge Executed')], max_length=40),
        ),
    ]
