# Generated by Django 5.2.10 on 2026-06-04 13:06

import hashlib

from django.db import migrations, models


def _backfill_tenant_hash(apps, schema_editor):
    School = apps.get_model("schools", "School")
    to_update = []
    for school in School.objects.all().only("id", "tenant_hash").iterator():
        digest = hashlib.sha256(str(school.id).encode("utf-8")).hexdigest()[:12]
        if school.tenant_hash != digest:
            school.tenant_hash = digest
            to_update.append(school)
        if len(to_update) >= 500:
            School.objects.bulk_update(to_update, ["tenant_hash"])
            to_update = []
    if to_update:
        School.objects.bulk_update(to_update, ["tenant_hash"])


def _noop_reverse(apps, schema_editor):
    # The column is dropped by the AddField reversal; nothing to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0064_school_schools_softdel_active_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tenant_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Derived sha256(id)[:12] for fast WAL tenant resolution.', max_length=12),
        ),
        migrations.RunPython(_backfill_tenant_hash, _noop_reverse),
    ]
