# Generated by Django 5.2.10 on 2026-06-06 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0065_school_tenant_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Bound to the created school once the invite is accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invites', to='schools.school')),
            ],
            options={
                'verbose_name': 'Tenant invite',
                'verbose_name_plural': 'Tenant invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'accepted_at'], name='schools_ten_email_18b9be_idx')],
            },
        ),
    ]
