# Generated by Django 5.2.14 on 2026-06-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0070_awardsource_is_restricted_and_more'),
        ('schoolops', '0028_ensure_micro_friction_tables'),
        ('schools', '0066_tenantinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancementgift',
            name='award_source',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional restricted/scholarship fund this gift credits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advancement_gifts', to='finance.awardsource'),
        ),
        migrations.AddField(
            model_name='advancementgift',
            name='credited_to_fund_at',
            field=models.DateTimeField(blank=True, help_text='Set once this gift has been applied to its award_source fund (idempotency guard).', null=True),
        ),
        migrations.CreateModel(
            name='InKindDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('books', 'Books / learning materials'), ('equipment', 'Equipment'), ('food', 'Food / supplies'), ('uniforms', 'Uniforms'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('service', 'Service / volunteer time'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, help_text='e.g. boxes, units, hours', max_length=40)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('condition', models.CharField(blank=True, help_text='e.g. new, good, fair, poor', max_length=40)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('acknowledgment_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, help_text='Optional; blank for anonymous in-kind gifts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_kind_donations', to='schools.advancementdonor')),
                ('inventory_item', models.ForeignKey(blank=True, db_constraint=False, help_text='Inventory line created/incremented when this donation is accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_kind_donations', to='schoolops.inventoryitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_kind_donations', to='schools.school')),
            ],
            options={
                'verbose_name': 'In-kind donation',
                'verbose_name_plural': 'In-kind donations',
                'ordering': ['-received_at', '-pk'],
                'indexes': [models.Index(fields=['school', 'status'], name='schools_ink_school__22c8cd_idx')],
            },
        ),
    ]
