# Generated by Django 5.2.14 on 2026-06-19 15:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0070_awardsource_is_restricted_and_more'),
        ('schools', '0067_advancementgift_award_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorGiftAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='schools.advancementdonor')),
            ],
            options={
                'verbose_name': 'Donor gift access link',
                'verbose_name_plural': 'Donor gift access links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundraisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=12)),
                ('is_public', models.BooleanField(default=False, help_text='Show this campaign on the donor portal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_source', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional fund that gifts to this campaign credit by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraising_campaigns', to='finance.awardsource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraising_campaigns', to='schools.school')),
            ],
            options={
                'verbose_name': 'Fundraising campaign',
                'verbose_name_plural': 'Fundraising campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='advancementgift',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional structured campaign this gift counts toward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='schools.fundraisingcampaign'),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional structured campaign this donation counts toward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_kind_donations', to='schools.fundraisingcampaign'),
        ),
        migrations.AddIndex(
            model_name='fundraisingcampaign',
            index=models.Index(fields=['school', 'status'], name='schools_fun_school__e57da9_idx'),
        ),
        migrations.AddIndex(
            model_name='fundraisingcampaign',
            index=models.Index(fields=['school', 'is_public'], name='schools_fun_school__8206ad_idx'),
        ),
    ]
