# Generated by Django 5.2.14 on 2026-06-19 16:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0068_donorgiftaccesslink_fundraisingcampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('partial', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pledged', max_length=12)),
                ('fulfilled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.PositiveIntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='schools.fundraisingcampaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='schools.advancementdonor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_pledges', to='schools.school')),
            ],
            options={
                'verbose_name': 'Donation pledge',
                'verbose_name_plural': 'Donation pledges',
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='schools_don_school__a28bb0_idx'), models.Index(fields=['school', 'due_date'], name='schools_don_school__9c6d4d_idx')],
            },
        ),
    ]
