# Generated by Django 5.2.10 on 2026-06-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0070_awardsource_is_restricted_and_more'),
        ('schoolops', '0028_ensure_micro_friction_tables'),
        ('schools', '0069_donationpledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancementgift',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client-generated offline idempotency key; dedupes replayed offline donation captures so one captured gift can never credit a fund twice.', max_length=64),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='client_offline_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client-generated offline idempotency key; dedupes replayed offline in-kind captures so one capture can never create two donation records.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='advancementgift',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('donor', 'client_offline_id'), name='uniq_advancementgift_donor_client_offline_id'),
        ),
        migrations.AddConstraint(
            model_name='inkinddonation',
            constraint=models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_inkinddonation_school_client_offline_id'),
        ),
    ]
