# Generated by Django 5.2.10 on 2026-06-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0070_awardsource_is_restricted_and_more'),
        ('schools', '0070_advancementgift_client_offline_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_name', models.CharField(max_length=200)),
                ('program', models.CharField(blank=True, help_text='Programme or purpose the grant funds.', max_length=200)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('awarded', 'Awarded'), ('declined', 'Declined'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('narrative', models.TextField(blank=True, help_text='Application narrative (may be AI-drafted, then edited).')),
                ('credited_to_fund_at', models.DateTimeField(blank=True, help_text='Idempotency stamp: set once the award has credited its fund.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Submission deadline.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_source', models.ForeignKey(blank=True, help_text='Fund credited when the grant is awarded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='finance.awardsource')),
                ('renewed_from', models.ForeignKey(blank=True, help_text='Prior grant this application renews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='schools.grantapplication')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grant application',
                'verbose_name_plural': 'Grant applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('waived', 'Waived')], default='pending', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='schools.grantapplication')),
            ],
            options={
                'verbose_name': 'Grant milestone',
                'verbose_name_plural': 'Grant milestones',
                'ordering': ['order', 'due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrantReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('narrative', 'Narrative'), ('financial', 'Financial')], default='narrative', max_length=12)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted')], default='draft', max_length=12)),
                ('content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.grantapplication')),
            ],
            options={
                'verbose_name': 'Grant report',
                'verbose_name_plural': 'Grant reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grantapplication',
            index=models.Index(fields=['school', 'status'], name='schools_gra_school__fbeab1_idx'),
        ),
        migrations.AddIndex(
            model_name='grantapplication',
            index=models.Index(fields=['school', 'due_date'], name='schools_gra_school__be0a4e_idx'),
        ),
    ]
