# Generated by Django 5.2.10 on 2026-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0072_recurringdonationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='currency',
            field=models.CharField(blank=True, default='', help_text="Tenant default currency (ISO 4217, e.g. NGN / XAF / GBP / USD). Empty = derive local-first via resolve_currency(): default_region → country pack → platform default. Set explicitly to override (e.g. an international school billing in a currency other than its country's default).", max_length=3),
        ),
        migrations.AlterField(
            model_name='advancementgift',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='donationpledge',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='fundraisingcampaign',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringdonationschedule',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
