# Generated by Django 5.2.10 on 2026-06-23 10:33

from django.conf import settings
from django.db import migrations, models


def backfill_owners(apps, schema_editor):
    """Seed one founding owner per existing school so nothing is left ownerless.

    Heuristic (conservative single-owner backfill — multi-owner is opt-in via the
    grant/transfer endpoints going forward): the earliest-created ADMIN membership
    is the closest proxy for "the user who created the school"; if a school somehow
    has no ADMIN, fall back to its earliest membership of any role so the school
    always retains at least one owner.
    """
    SchoolMembership = apps.get_model("schools", "SchoolMembership")
    db = schema_editor.connection.alias
    school_ids = (
        SchoolMembership.objects.using(db)
        .values_list("school_id", flat=True)
        .distinct()
    )
    for school_id in list(school_ids):
        base = SchoolMembership.objects.using(db).filter(school_id=school_id)
        founder = (
            base.filter(role="ADMIN").order_by("created_at", "pk").first()
            or base.order_by("created_at", "pk").first()
        )
        if founder is not None:
            base.filter(pk=founder.pk).update(is_school_owner=True)


def unset_owners(apps, schema_editor):
    SchoolMembership = apps.get_model("schools", "SchoolMembership")
    db = schema_editor.connection.alias
    SchoolMembership.objects.using(db).update(is_school_owner=False)


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0073_school_currency_alter_advancementgift_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='is_school_owner',
            field=models.BooleanField(default=False, help_text="Per-school OWNER (the tenant's 'super admin'). The user who created the school is the owner by default; ownership is transferable and a school may have multiple owners. Distinct from is_primary (a per-user default-school pointer with no authority) and from User.role=SUPERADMIN (a control-plane/operator role that is redirected off tenant hosts). Owners are admin-like; granting ownership ensures the ADMIN role."),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['school', 'is_school_owner'], name='schoolmember_owner_idx'),
        ),
        migrations.RunPython(backfill_owners, unset_owners),
    ]
