# Generated by Django 5.2.10 on 2026-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0075_backfill_school_default_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='currency',
            field=models.CharField(blank=True, default='', help_text="Tenant default currency (ISO 4217, e.g. NGN / XAF / GBP / USD). Empty = derive local-first via resolve_currency(): country pack -> default_region -> platform default. Set explicitly to override (e.g. an international school billing in a currency other than its country's default).", max_length=3),
        ),
    ]
