# Generated by Django 5.2.10 on 2026-01-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_gradeimportjob"),
        ("people", "0012_alter_studentprofile_joined_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_score", models.FloatField(default=0)),
                ("total_evaluations", models.IntegerField(default=0)),
                ("pass_rate", models.FloatField(default=0)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("IMPROVING", "Improving"),
                            ("DECLINING", "Declining"),
                            ("STABLE", "Stable"),
                        ],
                        default="STABLE",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="people.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Metrics",
                "verbose_name_plural": "Performance Metrics",
            },
        ),
    ]
