# Generated by Django 5.2.10 on 2026-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_performancemetrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceMetrics',
        ),
    ]
