# Generated by Django 5.2.10 on 2026-01-24 13:40

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_delete_performancemetrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeimportjob",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="grade_imports/%Y/%m/%d/",
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[".csv", ".xls", ".xlsx"],
                        allowed_types=[
                            "text/csv",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        message="Only CSV or Excel files are allowed for imports.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=5),
                ],
            ),
        ),
    ]
