# Generated by Django 5.2.10 on 2026-01-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_merge_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceMetrics',
        ),
    ]
