# Generated by Django 5.2.10 on 2026-02-27 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0011_student_signals"),
        ("schools", "0015_add_school_wallpaper_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interventionlog",
            name="dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionlog",
            name="dismissed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dismissed_interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interventionlog",
            name="draft_email_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interventionlog",
            name="draft_email_subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interventionlog",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("RESOLVED", "Resolved"),
                    ("DISMISSED", "Dismissed"),
                ],
                default="ONGOING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RiskThresholds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amber_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Score >= this → Amber band",
                        max_digits=5,
                    ),
                ),
                (
                    "red_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=80,
                        help_text="Score >= this → Red band",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_thresholds",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk thresholds",
                "verbose_name_plural": "Risk thresholds",
            },
        ),
    ]
