# Generated by Django 5.2.10 on 2026-03-06 17:31

import apps.accounts.validators
from django.db import migrations, models


def grade_import_job_upload_to(instance, filename):
    """Tenant-scoped path for GradeImportJob.uploaded_file (Section 25.3). School from academic_year.

    Inlined from ``apps.analytics.models.grade_import_job_upload_to`` for
    migration historical-state safety.
    """
    ay = getattr(instance, "academic_year", None)
    school_id = getattr(ay, "school_id", None) if ay else None
    if school_id is None:
        return f"tenant_uploads/analytics/grade_imports/{filename}"
    return f"tenants/{school_id}/analytics/grade_imports/{filename}"


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0012_risk_thresholds_intervention_action_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeimportjob",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=grade_import_job_upload_to,
                validators=[
                    apps.accounts.validators.FileTypeValidator(
                        allowed_extensions=[".csv", ".xls", ".xlsx"],
                        allowed_types=[
                            "text/csv",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        message="Only CSV or Excel files are allowed for imports.",
                    ),
                    apps.accounts.validators.FileSizeValidator(max_size_mb=5),
                ],
            ),
        ),
    ]
