# Generated by Django 5.2.10 on 2026-03-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_grade_import_tenant_upload_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactor',
            name='model_version',
            field=models.CharField(blank=True, help_text='ML model name@version used for this score (Phase 9 registry).', max_length=80),
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('version', models.CharField(db_index=True, max_length=40)),
                ('model_type', models.CharField(choices=[('risk', 'Risk scoring'), ('forecast', 'Enrollment/forecast'), ('other', 'Other')], default='risk', max_length=20)),
                ('artifact_path', models.CharField(blank=True, help_text='Path or blob reference to serialized model (e.g. S3 key, file path).', max_length=500)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Config for loading/running (e.g. threshold, feature list).')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='Expected input keys/types for inference.')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='Output keys (e.g. score, label).')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active per (name, model_type) should be True.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML model',
                'verbose_name_plural': 'ML models',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='analytics_m_model_t_0ffda9_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
