# Generated by Django 5.2.10 on 2026-03-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0014_add_ml_model_and_risk_model_version"),
        ("schools", "0038_advancement_donor_gift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAtRiskSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Higher = more at-risk (0–100 scale)."
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. attendance_pct, grade_trend, flags.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_intervention", "In intervention"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="at_risk_signals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="at_risk_signals",
                        to="schools.school",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="at_risk_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student at-risk signal (EWS)",
                "verbose_name_plural": "Student at-risk signals (EWS)",
                "ordering": ["-score", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status", "-score"],
                        name="analytics_s_school__427205_idx",
                    )
                ],
            },
        ),
    ]
