# Generated by Django 5.2.10 on 2026-05-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_rename_gsr_index_short'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governedsavedreport',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Governed saved report', 'verbose_name_plural': 'Governed saved reports'},
        ),
        migrations.AlterField(
            model_name='governedsavedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governed_saved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governedsavedreport',
            name='definition',
            field=models.JSONField(default=dict, help_text='Allowed keys: dataset_id, fields, filters, group_by, aggregate, limit.'),
        ),
    ]
