# Generated by Django 5.2.10 on 2026-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_at_risk_outcome_label_o4'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atriskoutcomelabel',
            new_name='analytics_a_school__c339f1_idx',
            old_name='analytics_a_school__b66ad6_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskoutcomelabel',
            new_name='analytics_a_label_f479ad_idx',
            old_name='analytics_a_label_e07e35_idx',
        ),
        migrations.AlterField(
            model_name='atriskoutcomelabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
