# Generated by Django 5.2.10 on 2026-05-17 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_risk_digest_recipient'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atriskinferencerun',
            new_name='analytics_a_school__1a48fe_idx',
            old_name='analytics_a_school__1f5b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskinferencerun',
            new_name='analytics_a_artifac_c685ab_idx',
            old_name='analytics_a_artifac_3c9e8d_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskmodelartifact',
            new_name='analytics_a_status_5e78d7_idx',
            old_name='analytics_a_status_8a4f12_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskmodelartifact',
            new_name='analytics_a_model_v_b3df8a_idx',
            old_name='analytics_a_model_v_1d2e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskshadowcomparison',
            new_name='analytics_a_run_id_e2a17d_idx',
            old_name='analytics_a_run_id_4a2c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskshadowcomparison',
            new_name='analytics_a_run_id_bc2a73_idx',
            old_name='analytics_a_run_id_band_7d5f10_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskshadowrun',
            new_name='analytics_a_school__2d8219_idx',
            old_name='analytics_a_school__3e7a91_idx',
        ),
        migrations.RenameIndex(
            model_name='atriskshadowrun',
            new_name='analytics_a_candida_70e798_idx',
            old_name='analytics_a_candida_5b1f44_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeprediction',
            new_name='analytics_g_school__a5c27b_idx',
            old_name='analytics_g_school__c2a8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeprediction',
            new_name='analytics_g_academi_1810c0_idx',
            old_name='analytics_g_academ__9e7f54_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepredictionlabel',
            new_name='analytics_g_school__d48fb1_idx',
            old_name='analytics_g_school__7d1e22_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepredictionlabel',
            new_name='analytics_g_student_a560a6_idx',
            old_name='analytics_g_student_4a8c93_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepredictionmodelartifact',
            new_name='analytics_g_status_646004_idx',
            old_name='analytics_g_status_b9f4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepredictionshadowcomparison',
            new_name='analytics_g_run_id_fc522b_idx',
            old_name='analytics_g_run_id__8e2c91_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepredictionshadowrun',
            new_name='analytics_g_school__fe3418_idx',
            old_name='analytics_g_school__d3a8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='riskdigestrecipient',
            new_name='analytics_r_school__db7929_idx',
            old_name='analytics_r_school__1c3b8d_idx',
        ),
        migrations.AlterField(
            model_name='atriskinferencerun',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text="Null when run ran on heuristic fallback or a path-pinned artifact that hasn't been registered.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='analytics.atriskmodelartifact'),
        ),
        migrations.AlterField(
            model_name='atriskinferencerun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atriskinferencerun',
            name='model_version_snapshot',
            field=models.CharField(blank=True, help_text='Resolved model_version at run time (denormalised so the row stays meaningful if the artifact row is later renamed).', max_length=120),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='artifact_path',
            field=models.CharField(help_text='Filesystem path of the joblib bundle this row represents.', max_length=512),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='feature_order',
            field=models.JSONField(default=list, help_text='Snapshot of the feature list at training time. Loader compares to current feature contract to catch silent drift.'),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='metric_ece',
            field=models.FloatField(blank=True, help_text='Expected Calibration Error from check_at_risk_calibration.', null=True),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='model_version',
            field=models.CharField(help_text="Stable identifier — e.g. 'at_risk_v2_2026_q1' or commit-tagged.", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='trained_at',
            field=models.DateTimeField(help_text='Wall-clock time the trainer wrote the joblib bundle.'),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='training_dataset_hash',
            field=models.CharField(blank=True, help_text="SHA-256 of the CSV used to train; lets us spot 'same data, different artifact' situations.", max_length=64),
        ),
        migrations.AlterField(
            model_name='atriskmodelartifact',
            name='training_row_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of labelled rows the trainer consumed.'),
        ),
        migrations.AlterField(
            model_name='atriskshadowcomparison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atriskshadowcomparison',
            name='score_delta',
            field=models.FloatField(help_text='candidate_score - production_score (signed).'),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='agreement_pct',
            field=models.FloatField(blank=True, help_text='Share of students with identical bands across both models, [0.0, 1.0].', null=True),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='band_changes',
            field=models.PositiveIntegerField(default=0, help_text='Number of students whose risk band differs between production and candidate.'),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='demotions',
            field=models.PositiveIntegerField(default=0, help_text='Candidate moved student to a LOWER risk band.'),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='promotions',
            field=models.PositiveIntegerField(default=0, help_text='Candidate moved student to a HIGHER risk band (green→amber, amber→red).'),
        ),
        migrations.AlterField(
            model_name='atriskshadowrun',
            name='psi_score_distribution',
            field=models.FloatField(blank=True, help_text='PSI between production and candidate score distributions (10 bins).', null=True),
        ),
        migrations.AlterField(
            model_name='gradeprediction',
            name='confidence_high',
            field=models.FloatField(blank=True, help_text='Upper 90% confidence bound.', null=True),
        ),
        migrations.AlterField(
            model_name='gradeprediction',
            name='confidence_low',
            field=models.FloatField(blank=True, help_text='Lower 90% confidence bound (heuristic ± 1 SD).', null=True),
        ),
        migrations.AlterField(
            model_name='gradeprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradeprediction',
            name='predicted_grade',
            field=models.FloatField(help_text='Predicted end-of-term grade, scale 0-100.'),
        ),
        migrations.AlterField(
            model_name='gradepredictionlabel',
            name='actual_grade',
            field=models.FloatField(help_text='End-of-term grade, scale 0-100 normalised.'),
        ),
        migrations.AlterField(
            model_name='gradepredictionlabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradepredictionmodelartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradepredictionmodelartifact',
            name='metric_mae',
            field=models.FloatField(blank=True, help_text='Mean Absolute Error on holdout (regression metric).', null=True),
        ),
        migrations.AlterField(
            model_name='gradepredictionmodelartifact',
            name='metric_r2',
            field=models.FloatField(blank=True, help_text='Coefficient of determination R² on holdout, [-∞, 1.0].', null=True),
        ),
        migrations.AlterField(
            model_name='gradepredictionmodelartifact',
            name='metric_rmse',
            field=models.FloatField(blank=True, help_text='Root Mean Squared Error on holdout.', null=True),
        ),
        migrations.AlterField(
            model_name='gradepredictionshadowcomparison',
            name='grade_delta',
            field=models.FloatField(help_text='candidate_grade - production_grade'),
        ),
        migrations.AlterField(
            model_name='gradepredictionshadowcomparison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradepredictionshadowrun',
            name='bias',
            field=models.FloatField(blank=True, help_text='mean(candidate - production); persistent positive = candidate is more optimistic.', null=True),
        ),
        migrations.AlterField(
            model_name='gradepredictionshadowrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskdigestrecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskdigestrecipient',
            name='label',
            field=models.CharField(blank=True, help_text="Operator-facing name (e.g. 'principal', '#success-team').", max_length=120),
        ),
        migrations.AlterField(
            model_name='riskdigestrecipient',
            name='target',
            field=models.CharField(help_text='Email address for channel=email; webhook URL for channel=slack_webhook.', max_length=512),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='feature_contributions',
            field=models.JSONField(blank=True, default=list, help_text='Wave 3: top-K feature attributions, list of {name, value, importance, direction}. Empty when heuristic path served.'),
        ),
    ]
