# Generated by Django 5.2.10 on 2026-01-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_classroom_allows_third_term"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion_average",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "demotion_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_rules",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_rules",
                        to="academics.classroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("academic_year", "classroom")},
            },
        ),
    ]
