# Generated by Django on behalf of compatibility changes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportcard_language_reportcard_region_code'),
    ]

    operations = []

