# Generated by Django 5.2.10 on 2026-02-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_promotionrule_use_technical_promotion_rule"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="schools.school",
            ),
        ),
    ]
