# Generated by Django 5.2.10 on 2026-03-06 17:24

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_rls_policy_default_deny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.reports.models.reportcard_pdf_upload_to),
        ),
    ]
