# Generated by Django 5.2.10 on 2026-03-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0039_syllabus_tenant_upload_to"),
        ("reports", "0014_add_adhoc_report_definition"),
        ("schools", "0029_add_hostel_canteen_health_biometric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EMISSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT", "Enrollment"),
                            ("ATTENDANCE", "Attendance"),
                            ("FINANCE", "Finance"),
                            ("STAFF", "Staff"),
                            ("MOE_PRESET", "MoE preset (regulatory)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        help_text="e.g. 2024-Q1, 2024/2025 Term 1", max_length=80
                    ),
                ),
                (
                    "preset_id",
                    models.CharField(
                        blank=True,
                        help_text="MoE preset id when report_type=MOE_PRESET",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREPARED", "Prepared"),
                            ("SUBMITTED", "Submitted"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Generated report file (PDF/CSV)",
                        max_length=500,
                    ),
                ),
                (
                    "submission_url",
                    models.URLField(
                        blank=True,
                        help_text="Ministry/district submission URL if applicable",
                        max_length=500,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference from ministry/district",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emis_submissions",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emis_submissions",
                        to="schools.school",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emis_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emis_submissions",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "EMIS submission",
                "verbose_name_plural": "EMIS submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "report_type", "period_label"],
                        name="reports_emi_school__4f22c0_idx",
                    ),
                    models.Index(
                        fields=["school", "status"],
                        name="reports_emi_school__a7359c_idx",
                    ),
                ],
            },
        ),
    ]
