# Generated by Django 5.2.10 on 2026-03-11 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_add_emis_submission'),
        ('runtime_blueprints', '0001_proxy_owner_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dependency_schema', models.JSONField(blank=True, default=dict, help_text='Fields, policies, templates dependencies.')),
                ('sample_data_config', models.JSONField(blank=True, default=dict, help_text='Seeded sample data for preview.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Pack',
                'verbose_name_plural': 'Report Packs',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='dashboardwidgetplacement',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtime_blueprints.dashboardwidget'),
        ),
        migrations.AlterField(
            model_name='userdashboard',
            name='widgets',
            field=models.ManyToManyField(through='reports.DashboardWidgetPlacement', to='runtime_blueprints.dashboardwidget'),
        ),
    ]
