# Generated by Django 5.2.10 on 2026-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reportpack_alter_dashboardwidgetplacement_widget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocreportdefinition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adhocreportdefinition',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidgetplacement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetplacement',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetplacement',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='userdashboard',
            name='widgets',
        ),
        migrations.DeleteModel(
            name='MaterializedReportCache',
        ),
        migrations.RemoveField(
            model_name='reportdefinition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='report_definition',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='report_definition',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdashboard',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdHocReportDefinition',
        ),
        migrations.DeleteModel(
            name='AdHocReportExecution',
        ),
        migrations.DeleteModel(
            name='DashboardWidgetPlacement',
        ),
        migrations.DeleteModel(
            name='ReportDefinition',
        ),
        migrations.DeleteModel(
            name='ReportExecution',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
        migrations.DeleteModel(
            name='UserDashboard',
        ),
    ]
