# Generated by Django 5.2.10 on 2026-03-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_remove_adhocreportdefinition_created_by_and_more'),
        ('schools', '0041_school_impersonation_dual_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_key', models.SlugField(default='summary', help_text='Stable key for report type / template wiring.', max_length=80)),
                ('schedule_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('schedule_time', models.TimeField()),
                ('recipients', models.JSONField(default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='schools.school')),
            ],
            options={
                'ordering': ['next_run'],
                'indexes': [models.Index(fields=['school', 'is_active', 'next_run'], name='reports_ten_school__1c8d09_idx')],
            },
        ),
    ]
