# Generated by Django 5.2.10 on 2026-03-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_tenant_report_schedule_rls_postgresql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantreportschedule',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
