# Generated by Django 5.2.10 on 2026-05-15 21:55

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_restore_adhoc_report_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.reports.models.reportcard_pdf_upload_to),
        ),
    ]
