# Generated by Django 5.2.10 on 2026-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_backfill_report_card_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrule',
            name='conditional_promotion_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. A student whose average falls between this value (inclusive) and the promotion average advances with the outcome CONDITIONALLY_PROMOTED. Leave empty to disable conditional promotion for this scope.', max_digits=5, null=True),
        ),
    ]
