# Generated by Django 5.2.10 on 2026-08-06 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0073_attendance_classroom_client_offline_id'),
        ('reports', '0025_enrollment_first_class'),
        ('schools', '0083_force_rls_late_enabled_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATE', 'Generate'), ('PRINT', 'Print'), ('SHARE', 'Share')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued (offline)'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('group_mode', models.CharField(blank=True, max_length=16)),
                ('group_ref_id', models.IntegerField(blank=True, null=True)),
                ('group_label', models.CharField(blank=True, max_length=160)),
                ('included_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_batches', to='academics.academicyear')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_batches', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_batches', to='schools.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_batches', to='academics.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['academic_year', 'term', 'created_at'], name='reports_rcbatch_ayt_idx')],
            },
        ),
    ]
