# Generated by Django 5.2.10 on 2026-05-26 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_rename_payroll_pay_code_is_a_idx_payroll_pay_code_f28230_idx_and_more'),
        ('schools', '0057_school_primary_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollOfflineCaptureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(db_index=True, max_length=64)),
                ('client_offline_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('PENDING_REVIEW', 'Pending review'), ('FAILED', 'Failed')], db_index=True, default='APPLIED', max_length=20)),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=12)),
                ('fields_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_offline_captures_created', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_captures', to='payroll.payrollrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_offline_captures', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'workflow', 'created_at'], name='payroll_pay_school__3bcf7b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_offline_id', ''), _negated=True), fields=('school', 'client_offline_id'), name='uniq_payroll_offline_capture_client_id')],
            },
        ),
    ]
