# Generated by Django 5.2.14 on 2026-08-22 15:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_ensure_offline_capture_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='details',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
