# Generated by Django 5.2.10 on 2026-05-22 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0053_schoolprovisioningevent_offboarding_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLifecycleStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROVISIONED', 'Provisioned'), ('ONBOARDING_STARTED', 'Onboarding started'), ('ONBOARDING_LAUNCH_READY', 'Launch ready'), ('OPERATING', 'Operating'), ('MIGRATING', 'Migrating'), ('MIGRATION_COMPLETE', 'Migration complete'), ('OFFBOARDING_REQUESTED', 'Offboarding requested'), ('OFFBOARDING_EXPORTED', 'Export complete'), ('OFFBOARDING_GRACE', 'In grace period'), ('OFFBOARDING_CANCELLED', 'Offboarding cancelled'), ('OFFBOARDING_PURGED', 'Purged'), ('FAILED', 'Failed')], db_index=True, max_length=40)),
                ('actor_hash', models.CharField(blank=True, default='', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_stages', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', '-created_at'], name='lifecycle_s_school__55bfd4_idx'), models.Index(fields=['stage', '-created_at'], name='lifecycle_s_stage_2aa703_idx')],
            },
        ),
    ]
