# Generated by Django 5.2.10 on 2026-06-16 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.CharField(db_index=True, max_length=64)),
                ('school_slug', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('completed_phases', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('row_total', models.PositiveIntegerField(default=0)),
                ('schema_dropped', models.BooleanField(default=False)),
                ('sessions_revoked', models.PositiveIntegerField(default=0)),
                ('manifest_path', models.CharField(blank=True, max_length=512)),
                ('certificate', models.JSONField(blank=True, null=True)),
                ('certificate_signature', models.CharField(blank=True, max_length=128)),
                ('certificate_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purge_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lifecycle_purgeoperation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'status'], name='lifecycle_p_school__92271a_idx'), models.Index(fields=['status', '-created_at'], name='lifecycle_p_status_f7fd64_idx')],
            },
        ),
    ]
