# Generated by Django 5.2.10 on 2026-06-26 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0002_purge_operation'),
        ('schools', '0076_alter_school_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantImmutableSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('primary_uri', models.CharField(max_length=512)),
                ('secondary_uri', models.CharField(blank=True, default='', max_length=512)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('signature_hex', models.CharField(max_length=128)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immutable_snapshots', to='schools.school')),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'snapshot_date'), name='uniq_tenant_immutable_snapshot_day')],
            },
        ),
    ]
