server {
  listen 443 ssl http2;
  server_name collabora.runmycampus.com;

  # ssl_certificate /etc/letsencrypt/live/collabora.runmycampus.com/fullchain.pem;
  # ssl_certificate_key /etc/letsencrypt/live/collabora.runmycampus.com/privkey.pem;

  proxy_read_timeout 3600s;
  proxy_send_timeout 3600s;
  client_max_body_size 64m;

  location / {
    proxy_pass http://127.0.0.1:9980;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
