"""The cloud half of the OTA rail: what changed, and the bytes of what changed.

TWO ENDPOINTS, ON THE LANE THE BOX ALREADY USES. No new port, no second hostname, no SSH,
no object-store URL. A school's firewall has already approved exactly one thing — HTTPS to
the operator base, with a bearer edge credential — and these routes sit on that same mount
next to ``sync/bundle/`` and ``sync/files/``. That is not a stylistic preference: a remote
school's network is not ours to reconfigure, and an upgrade channel that needs a firewall
change is an upgrade channel that never runs.

  * ``GET upgrade/manifest/?since=<hash>`` — the target manifest's identity plus the exact
    delta from the caller's declared hash. Cheap: two JSON loads and a dict subtraction.
  * ``GET upgrade/chunk/?path=…&offset=…`` — one byte range of one file, so a link that
    drops at 80% resumes at 80%.

AUTHORISATION IS THE MANIFEST, NOT THE FILESYSTEM. ``path`` is a caller-supplied string
used to read a file, which is a directory-traversal hole unless something constrains it.
Sanitising the string is the weak answer. The strong answer, used here and mirroring
``file_manifest.servable_paths``, is that a path is servable only if it is a KEY in the
deployment's own ``system_manifest.json``. That set is generated by a crawl the operator
ran, contains no absolute paths and no parent references, and cannot be argued into
``../../.env`` or into another tenant's media — because it contains only shippable source.
The resolved path is additionally re-checked against the manifest root, so a symlink
planted inside the tree cannot widen the set either.

WHY THE BOX IS NOT TRUSTED TO ASK FOR THE RIGHT THING. The response stamps the sha256 the
manifest declares for every chunk served. The box re-hashes the whole file after the last
chunk and refuses to promote a tree that disagrees. A partial or corrupted transfer
therefore cannot reach a running deployment even if every HTTP status along the way was
200 — which is the specific failure this pipeline exists to survive.
"""
from __future__ import annotations

import os
from pathlib import Path

from django.conf import settings
from django.http import HttpResponse
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.api.edge_auth import EdgeCredentialAuthentication
from apps.schools.tenant_api_guards import user_may_operate_on_school
from apps.sync_engine import upgrade_delta, upgrade_lock
from apps.sync_engine.system_manifest import (
    ASSET_CATEGORIES,
    load_manifest,
    manifest_path,
)

# Response headers, mirroring the X-RMC-* convention the bundle + file rails already use.
UPGRADE_MANIFEST_HEADER = "X-RMC-Upgrade-Manifest"
UPGRADE_SHA256_HEADER = "X-RMC-Upgrade-Sha256"
UPGRADE_OFFSET_HEADER = "X-RMC-Upgrade-Offset"
UPGRADE_SIZE_HEADER = "X-RMC-Upgrade-Size"
UPGRADE_COMPLETE_HEADER = "X-RMC-Upgrade-Complete"

_DEFAULT_CHUNK_BYTES = 1024 * 1024  # magic-number-allow: 1 MiB default chunk
_MAX_CHUNK_BYTES = 8 * 1024 * 1024  # magic-number-allow: 8 MiB hard ceiling per request


def ota_enabled() -> bool:
    """Master switch. Off => both routes answer 409 and nothing is served.

    Defaults ON for the CLOUD half deliberately: serving a manifest is read-only and
    costs nothing until a box asks. The half that changes a running system — the box's
    apply — is the one that defaults off (``RMC_OTA_AUTO_APPLY``).
    """
    return bool(getattr(settings, "RMC_OTA_ENABLED", True))


def _manifest_root() -> Path:
    """Directory the manifest's relative paths are resolved against."""
    override = str(getattr(settings, "RMC_OTA_MANIFEST_ROOT", "") or "").strip()
    return Path(override) if override else Path(str(getattr(settings, "BASE_DIR", ".")))


def resolve_servable(relative_path: str, manifest: dict) -> Path | None:
    """Absolute path for a manifest key, or ``None`` when the caller may not have it.

    Three independent conditions, all required: the path is a key in the manifest; the
    resolved location is inside the manifest root; and it is a regular file. The first
    alone would already be sufficient against traversal — the second exists because a
    symlink inside the tree is not something the crawl can see.
    """
    key = str(relative_path or "").strip().replace("\\", "/").lstrip("/")
    if not key or key not in (manifest.get("files") or {}):
        return None
    root = _manifest_root().resolve()
    try:
        candidate = (root / key).resolve()
    except OSError:
        return None
    try:
        candidate.relative_to(root)
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


class _EdgeUpgradeView(APIView):
    authentication_classes = [EdgeCredentialAuthentication]
    permission_classes = [IsAuthenticated]

    def _guard(self, request):
        """``(school, manifest, refusal)`` — refusal is a Response or None."""
        school = getattr(request, "school", None)
        if school is None:
            return None, None, Response({"ok": False, "error": "school_required"}, status=403)
        if not user_may_operate_on_school(request, school):
            return None, None, Response({"ok": False, "error": "forbidden"}, status=403)
        if not ota_enabled():
            return None, None, Response({"ok": False, "error": "ota_disabled"}, status=409)
        manifest = load_manifest()
        if not manifest.get("files"):
            # An operator that never ran ``generate_system_manifest`` has nothing to
            # offer. Saying so plainly beats serving an empty delta that a box would
            # read as "you are up to date".
            return None, None, Response(
                {
                    "ok": False,
                    "error": "no_manifest",
                    "detail": (
                        f"no system manifest at {manifest_path()} — run "
                        "`manage.py generate_system_manifest` on the operator deployment"
                    ),
                },
                status=503,
            )

        # ROLLOUT RING. The handshake already declines to ADVERTISE a manifest this
        # school is not released to; this is the enforcement half, because a box can ask
        # directly and the advice header is advisory. Refused with 409 rather than 403:
        # nothing is wrong with the box or its credentials, the release simply has not
        # reached its ring yet, and an operator reading a 403 would go looking for a
        # permissions bug that does not exist.
        from apps.sync_engine.models_rollout import may_receive

        allowed, reason = may_receive(school, str(manifest.get("manifest_hash") or ""))
        if not allowed:
            return None, None, Response(
                {"ok": False, "error": "not_released", "detail": reason},
                status=409,
            )
        return school, manifest, None


@extend_schema_view(
    get=extend_schema(
        tags=["Offline Sync"],
        summary="Target system manifest and the delta from a declared hash",
        description=(
            "Returns the operator deployment's manifest identity plus the exact set of "
            "files the caller must fetch to reach it. `since` is the caller's own "
            "manifest hash; omit it to receive the whole manifest as a delta. "
            "`categories=UI_TEMPLATE,STATIC_ASSET` restricts the delta to files that can "
            "be swapped without reloading the interpreter."
        ),
        responses={200: dict, 403: dict, 409: dict, 503: dict},
    ),
)
class SyncUpgradeManifestView(_EdgeUpgradeView):
    def get(self, request):
        school, manifest, refusal = self._guard(request)
        if refusal is not None:
            return refusal

        since = str(request.query_params.get("since") or "").strip()
        raw_categories = str(request.query_params.get("categories") or "").strip()
        if raw_categories.lower() in ("assets", "asset"):
            categories = set(ASSET_CATEGORIES)
        elif raw_categories:
            categories = {c.strip().upper() for c in raw_categories.split(",") if c.strip()}
        else:
            categories = None

        target_hash = str(manifest.get("manifest_hash") or "")
        up_to_date = bool(since) and since == target_hash

        # The BASE is the caller's manifest, which the cloud does not hold. It holds only
        # the hash. So the delta is computed against an empty base whenever the hashes
        # differ, and the box narrows it locally against its own manifest before fetching
        # — see local_upgrade.plan(). Reporting the full target here is what lets a box
        # with a corrupted or absent manifest recover completely rather than fetching a
        # difference from a state it does not actually have.
        delta = upgrade_delta.compute_delta({}, manifest, categories=categories)

        if up_to_date:
            upgrade_lock.release(school)
        else:
            upgrade_lock.hold(
                school,
                target_hash=target_hash,
                current_hash=since,
                reason="manifest mismatch at upgrade/manifest",
            )

        return Response(
            {
                "ok": True,
                "up_to_date": up_to_date,
                "manifest_hash": target_hash,
                "version_label": manifest.get("version_label") or "",
                "channel": manifest.get("channel") or "stable",
                "engine_commit": manifest.get("engine_commit") or "",
                "generated_at": manifest.get("generated_at") or "",
                "file_count": manifest.get("file_count") or 0,
                "total_bytes": manifest.get("total_bytes") or 0,
                "migration_heads": manifest.get("migration_heads") or {},
                "sync_state": upgrade_lock.state(school).get("state"),
                # The full target file map. A box subtracts its own manifest from this
                # locally, so the cloud never needs to store per-box state to answer.
                "files": manifest.get("files") or {},
                "delta": delta,
            },
            headers={UPGRADE_MANIFEST_HEADER: target_hash},
        )


@extend_schema_view(
    get=extend_schema(
        tags=["Offline Sync"],
        summary="Download one byte range of one manifest file (resumable)",
        responses={200: bytes, 403: dict, 404: dict, 409: dict, 416: dict},
    ),
)
class SyncUpgradeChunkView(_EdgeUpgradeView):
    def get(self, request):
        _school, manifest, refusal = self._guard(request)
        if refusal is not None:
            return refusal

        relative = request.query_params.get("path") or ""
        target = resolve_servable(relative, manifest)
        if target is None:
            # Deliberately identical for "not in the manifest" and "outside the root":
            # distinguishing them would confirm the existence of paths to a caller who
            # is, by construction, not entitled to know.
            return Response({"ok": False, "error": "not_servable"}, status=404)

        entry = (manifest.get("files") or {}).get(str(relative).replace("\\", "/").lstrip("/")) or {}
        declared_sha = str(entry.get("sha256") or "")

        try:
            offset = max(0, int(request.query_params.get("offset") or 0))
        except (TypeError, ValueError):
            offset = 0
        try:
            length = int(request.query_params.get("length") or _DEFAULT_CHUNK_BYTES)
        except (TypeError, ValueError):
            length = _DEFAULT_CHUNK_BYTES
        length = max(1, min(length, _MAX_CHUNK_BYTES))

        size = os.path.getsize(target)
        if offset > size:
            # Past the end is a client bug, not an empty file. 416 says so precisely; a
            # 200 with zero bytes would let a box believe a truncated file was complete.
            return Response(
                {"ok": False, "error": "offset_beyond_eof", "size": size}, status=416
            )

        with open(target, "rb") as handle:
            handle.seek(offset)
            payload = handle.read(length)

        served_to = offset + len(payload)
        response = HttpResponse(payload, content_type="application/octet-stream")
        response[UPGRADE_MANIFEST_HEADER] = str(manifest.get("manifest_hash") or "")
        response[UPGRADE_SHA256_HEADER] = declared_sha
        response[UPGRADE_OFFSET_HEADER] = str(offset)
        response[UPGRADE_SIZE_HEADER] = str(size)
        response[UPGRADE_COMPLETE_HEADER] = "1" if served_to >= size else "0"
        return response


__all__ = [
    "UPGRADE_MANIFEST_HEADER",
    "UPGRADE_SHA256_HEADER",
    "UPGRADE_OFFSET_HEADER",
    "UPGRADE_SIZE_HEADER",
    "UPGRADE_COMPLETE_HEADER",
    "ota_enabled",
    "resolve_servable",
    "SyncUpgradeManifestView",
    "SyncUpgradeChunkView",
]
